### PR TITLE
Fix discussions issues after room deletion and translation actions not being shown

### LINKED ISSUE #13689: Discussion Deletion
1.0.0-develop-beta.1

1. Create Discussion

2. Delete Discussion. 
- Discussion still appears in channel/Discussion. 
- 'No replies' shows under original comment. 
- Clicking No Replies shows 'Not Allowed'

3. Cannot appear to rename discussion after creation

Related:
https://github.com/RocketChat/Rocket.Chat/issues/13664
https://github.com/RocketChat/Rocket.Chat/pull/13541

### LINKED ISSUE #13965: Auto Translate/Translate not working in discussions when first join
### Description:

If you attempt to translate a message using the translation action item in a discussion nothing happens.  Verified still works in DM's

### Steps to reproduce:

1. Ask someone nicely to start a discussion
2. Ask them to write something in another language
3. Join the discussion
3. Click the Toggle Original/Translated option from the message actions

### Expected behavior:

Translate like this:

image

### Actual behavior:

Nothing seems to happen.

### Server Setup Information:

- Version of Rocket.Chat Server: current develop
- Operating System: debian stretch
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.x
- MongoDB Version: 4.x

### Relevant logs:

No exceptions in log that I could find

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #13689
Closes #13965

### CODE REVIEW

File: server/startup/migrations/v140.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { Migrations } from '../../../app/migrations/server';
+
+import { Messages, Rooms } from '../../../app/models/server';
+
+Migrations.add({
+	version: 140,
+	up() {
+		Messages.find({ drid: { $exists: 1 } }, { fields: { drid: 1 } }).forEach(({ _id, drid }) => Rooms.findOne({ _id: drid }) || Messages.update({ _id }, {
```
Comment (sampaiodiego) [inline server/startup/migrations/v140.js]:
```suggestion
		Messages.find({ drid: { $exists: 1 } }, { fields: { drid: 1 } }).forEach(({ _id, drid }) => !Rooms.findOne({ _id: drid }) || Messages.update({ _id }, {
```

if I get this right, you're trying to see if the room of the discussion was already removed right? in this case, my suggestion applies

File: app/ui-message/client/message.html [hunk 2]
```diff
@@ -32,7 +32,7 @@
 			<span class="time" title='{{date}} {{time}}'>{{time}}</span>
 			{{#if showTranslated}}
 				<span class="translated">
-					<i class="icon-language {{#if autoTranslateFetching}}loading{{/if}}" aria-label="{{_ "Translated"}}"></i>
+					<i class="icon-language {{#if msg.autoTranslateFetching}}loading{{/if}}" aria-label="{{_ "Translated"}}"></i>
```
Comment (sampaiodiego) [inline app/ui-message/client/message.html]: is `msg.autoTranslateFetching` already available in this branch?

Comment (ggazzo) [reply app/ui-message/client/message.html]: ops

File: app/autotranslate/client/lib/actionButton.js [hunk 3]
```diff
@@ -24,11 +24,9 @@ Meteor.startup(function() {
 						AutoTranslate.messageIdsToWait[message._id] = true;
 						Messages.update({ _id: message._id }, { $set: { autoTranslateFetching: true } });
```
Comment (sampaiodiego) [inline app/autotranslate/client/lib/actionButton.js]: I guess this needs to be removed, otherwise it will be called twice

File: app/autotranslate/client/lib/autotranslate.js [hunk 4]
```diff
@@ -61,7 +61,7 @@ export const AutoTranslate = {
 						if (!message.translations) {
 							message.translations = {};
 						}
-						if (subscription && subscription.autoTranslate !== message.autoTranslateShowInverse) {
+						if (!!(subscription && subscription.autoTranslate) !== !!message.autoTranslateShowInverse) {
```
Comment (sampaiodiego) [inline app/autotranslate/client/lib/autotranslate.js]: this is confusing, what is the motivation here?

if the code cannot be made clear, please add a comment describing what it is doing.

File: app/ui-message/client/message.js [hunk 5]
```diff
@@ -197,18 +197,11 @@ Template.message.helpers({
...
-				'u._id': Meteor.userId(),
-			}, {
-				fields: {
-					autoTranslate: 1,
-					autoTranslateLanguage: 1,
-				},
-			});
-			const language = AutoTranslate.getLanguage(this.rid);
-			return this.autoTranslateFetching || (subscription && subscription.autoTranslate !== this.autoTranslateShowInverse && this.translations && this.translations[language]);
+		const { msg, subscription, settings } = this;
```
Comment (sampaiodiego) [inline app/ui-message/client/message.js]: I guess this is not supposed to be in this PR as well, there is no such properties in `this` object.
