### PR TITLE
Regression: LDAP Issues

### LINKED ISSUE #23296: LDAP authentication failing in spite of successful connection
### Description:

In spite of LDAP configuration being correct (using and LDAP service account for BINDs) and tests being successful, manual synchronization and user authentication is failing with the following error:
```
{"level":50,"time":"2021-09-27T14:00:08.797Z","pid":1,"hostname":"2af473c901d9","name":"LDAP","err":{"type":"","message":"000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000","stack":"OperationsError: 000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000\n    at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1218:45)\n    at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:886:14)\n    at Parser.emit (events.js:314:20)\n    at Parser.EventEmitter.emit (domain.js:483:12)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:107:8)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:144:15\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","lde_message":"000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000","lde_dn":null},"msg":"000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000"}
```

### Steps to reproduce:

1. Update to `4.0.0-develop` (commit `70a7b94c`)
2. Attempt to log in with an LDAP user.
3. Will get `User not found or incorrect password` error.
4. Log in to administration. Attempt to test the LDAP configuration. It tests successfuly.
5. Attempt to Sync.
6. Will get a `Not Authorized` error.

### Expected behavior:

Users should be authenticated, and manual synchronization should work, given there have been no changes to the LDAP configuration or environment.

### Actual behavior:

LDAP errors occur, preventing both authentication and synchronization.
image
image
image

### Server Setup Information:

- Version of Rocket.Chat Server: `4.0.0-develop` (commit `70a7b94c`)
- Operating System: Ubuntu 20.04.3 (docker)
- Deployment Method: docker 
- Number of Running Instances:  1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.16 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop: 3.5, Browser: Firefox 92.0.1
- Operating System: Windows 10 21H1

### PR DESCRIPTION
**Pull request by pierre-lehnen-rc**
- [X] Fixed documentation URL
- [X] Fixed admin authentication (closes #23296)

Also added a new button to the admin screen to run a test search on the ldap server.

### CODE REVIEW

File: client/views/admin/settings/groups/LDAPGroupPage.tsx [hunk 1]
```diff
@@ -45,28 +49,70 @@ function LDAPGroupPage({ _id, ...group }: ISetting): JSX.Element {
...
+			setModal(
+				<GenericModal
+					variant='info'
+					confirmText={t('Sync')}
+					cancelText={t('Cancel')}
+					title={t('Execute_Synchronization_Now')}
+					onConfirm={confirmSync}
+					onClose={closeModal}
+				>
+					<Box>{t('LDAP_Sync_Now_Description')}</Box>
```
Comment (tassoevan) [inline client/views/admin/settings/groups/LDAPGroupPage.tsx:70]: I don't think this container `Box` is necessary.

File: client/views/admin/settings/groups/LDAPGroupPage.tsx [hunk 2]
```diff
@@ -45,28 +49,70 @@ function LDAPGroupPage({ _id, ...group }: ISetting): JSX.Element {
...
+				<GenericModal
+					variant='info'
+					confirmText={t('Search')}
+					cancelText={t('Cancel')}
+					title={t('Test_LDAP_Search')}
+					onConfirm={confirmSearch}
+					onClose={closeModal}
+				>
+					<Field>
+						<Flex.Container>
```
Comment (tassoevan) [inline client/views/admin/settings/groups/LDAPGroupPage.tsx:105]: I'm sorry, we hadn't communicated it in the code yet: `Flex.Container` and `Flex.Item` are deprecated. I suggest using `display='flex'` on the child `Box`.

File: app/api/server/v1/ldap.ts [hunk 3]
```diff
@@ -31,3 +32,34 @@ API.v1.addRoute('ldap.testConnection', { authRequired: true }, {
...
+
+		if (settings.get('LDAP_Enable') !== true) {
+			throw new Error('LDAP_disabled');
+		}
+
+		try {
+			Promise.await(LDAP.testSearch(this.bodyParams.username));
+		} catch (error) {
+			SystemLogger.error(error);
+			throw new Error('LDAP_User_Not_Found');
```
Comment (sampaiodiego) [inline app/api/server/v1/ldap.ts:58]: is this the correct error if `LDAP.testSearch` fails?

**Review by sampaiodiego — APPROVED** [review]
