### PR TITLE
[FIX] Rate limit incoming integrations (webhooks)

### LINKED ISSUE #15029: Rate limit incoming webhooks - DoS vulnerability
# Motivation

As a provider of a ChatServer, I need to be safe against Denial Of Service attacks.
For this purpose, all APIs exposed by RC are rate-limited, which is fine.
Webhooks of incoming integrations however are not rate limited at all: Simply by `POST`ing to a webhook URL with unlimited rate will result in a huge load and render the system unusable.

# Solution Proposal 

Rate limit all incoming integration calls with the standard HTTP rate limit as defined in the existing settings.

### PR DESCRIPTION
**Pull request by mrsimpson**
Closes #15029

What it does:

```
| => curl -X POST -H 'Content-Type: application/json' --data '{"username":"dummy","text":"something"}' http://localhost:3000/hooks/SJwYdrorJ5upc4SWT/mEbn7LYASuwCbX9cRGHYzwFQBEFxNxTveZGxnhv7GW6X2unL
{"success":false,"error":"Error, too many requests. Please slow down. You must wait 28 seconds before trying this endpoint again. [error-too-many-requests]"}_____
```

@sampaiodiego as written in https://github.com/RocketChat/Rocket.Chat/issues/15029#issuecomment-514266316 , it was a bit tricky with respect to lifecycle to re-use the existing methods.
Since a `RateLimitedAPI` class would not add a meaningful layer compared to the existing `APIClass` (basically the `APIClass` would not redefine anything) and since the `APIClass` is already used as superclass (e. g. by the Apps-API, I decided to refactor this class. This has the benefit of easier understanding of the changes as well - at least I hope so.

### CODE REVIEW

File: app/api/server/api.js [hunk 1]
```diff
@@ -15,16 +15,17 @@ import { getDefaultUserFields } from '../../utils/server/functions/getDefaultUse
 
 const logger = new Logger('API', {});
 const rateLimiterDictionary = {};
-const defaultRateLimiterOptions = {
+export const defaultRateLimiterOptions = {
```
Comment (mrsimpson) [inline app/api/server/api.js]: This was necessary to be exported since else, subclasses can't access it: You cannot make it a member of `APIClass` since it's used in the `super.constructor`

File: app/api/server/api.js [hunk 2]
```diff
@@ -180,10 +210,24 @@ class APIClass extends Restivus {
...
 
+	getFullRouteName(route, method, apiVersion = null) {
+		let prefix = `/${ this.apiPath || '' }`;
+		if (apiVersion) {
+			prefix += `${ apiVersion }/`;
+		}
+		return `${ prefix }${ route }${ method }`;
+	}
+
+	namedRoutes(route, endpoints, apiVersion) {
```
Comment (mrsimpson) [inline app/api/server/api.js]: this was `nameRoute` earlier on, I found this to be misleading returning an array

**Comment by geekgonecrazy** [comment]
This seems like a must have to prevent a bug in another program from DDoS'ing a Rocket.Chat instance.  🙈

**Comment by mrsimpson** [comment]
@geekgonecrazy our „bug“ was a Cloudwatch-Alert for pod status: 60k messages per hour made our servers ache...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
