### PR TITLE
fix: Delete OTR messages on session end

### LINKED ISSUE #33909: OTR Chat is not removed on OTR session end
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Rocky Linux 9.4

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

4.1.1

### Rocket.Chat Server Version

7.0.0

### Describe the bug

OTR Chat is not removed on OTR session end.

The OTR message persists on the recipient's client, including between restarts. The message can only be removed if they click Reload in the Help menu.

### How to Reproduce

1. Open a direct message
2. Click the Options menu
3. Click OTR
4. Click Start OTR button
5. Wait for other user to accept
6. Send a message.
7. End the OTR session

### Describe your Expected behavior

The OTR message is removed from both users.

### Anything else

_No response_

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

Delete OTR messages from mini mongo collections on client, when OTR session is ended 
## Issue(s)

Closes #33909 
## Further comments

[CORE-801](https://rocketchat.atlassian.net/browse/CORE-801)

[CORE-801]: https://rocketchat.atlassian.net/browse/CORE-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/meteor/app/otr/client/OTRRoom.ts [hunk 1]
```diff
@@ -179,11 +180,16 @@ export class OTRRoom implements IOTRRoom {
 		this._sessionKey = null;
 	}
 
+	deleteOTRMessages(): void {
```
Comment (KevLehman) [inline apps/meteor/app/otr/client/OTRRoom.ts:183]: Can you add a UI test that ensures this is happening? 😬

**Review by KevLehman — CHANGES_REQUESTED** [review]

**Review by KevLehman — APPROVED** [review]
