### PR TITLE
[FIX] Missing sidebar default options on admin

### LINKED ISSUE #9941: Create admin-settings for the new view settings in the sidebar
### Description:

I couldnt find any admin setting where I can set a default for the new view options on the sidebar.

image

This view settings should have an admin setting to set this view in a default state for all users which not adjusted this setting yet (or for new users).

https://github.com/RocketChat/Rocket.Chat/pull/9608 
@johnyb0y mentioned this already in the pull request.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.62.0
* Operating System: Ubuntu Server 16.04 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #9941

I also removed the old view mode setting that we used to have on our messages box, this setting is not used anymore and can be confused with sidebar view mode.

image

image

image

### CODE REVIEW

File: packages/rocketchat-lib/server/startup/settings.js [hunk 1]
```diff
@@ -310,10 +310,29 @@ RocketChat.settings.addGroup('Accounts', function() {
...
+					key: 'extended',
+					i18nLabel: 'Extended'
+				},
+				{
+					key: 'medium',
+					i18nLabel: 'Medium'
+				},
+				{
+					key: 'condensed',
+					i18nLabel: 'Extended'
```
Comment (rodrigok) [inline packages/rocketchat-lib/server/startup/settings.js]: Wrong label

**Comment by johnyb0y** [comment]
Thanks @karlprieb. Much appreciated.
