### PR TITLE
[FIX] Bot Agents not being able to get Omnichannel Inquiries

### LINKED ISSUE #17405: Error when bot uses REST API endpoint livechat/inquiries.take.
Server version: 3.1.1

After the latest update we're getting an error when our bot user attempts to use REST API endpoint `livechat/inquiries.take` - error message `"error":"error-agent-offline"`.

Tried using the REST API  to manually set the bot user's status to 'online' and tried using the REST API to first login and then set the user status - unless we log into the app's GUI as the bot user, we always get this error returned from the `livechat/inquiries.take` endpoint.

### PR DESCRIPTION
**Pull request by renatobecker**
CLOSES #17405.

Since `3.1` version we only allow online agents/users to get Omnichannel Inquiries.
Unfortunately, external systems are now facing an issue because they have bot agents that get the Omnichannel Inquiries through the REST API endpoint -> `livechat/inquiries.take`.

As the current implementation doesn't check the `bot` role, the external user just can't get the inquiry because the `bot` role isn't being checked as we do in another similar process.

### CODE REVIEW

File: app/livechat/server/lib/Helper.js [hunk 1]
```diff
@@ -304,3 +305,17 @@ export const checkServiceStatus = ({ guest, agent }) => {
...
 };
+
+export const userCanTakeInquiry = (user) => {
+	check(user, Match.ObjectIncluding({
+		status: String,
+		statusLivechat: String,
+	}));
+
+	const { status, statusLivechat } = user;
+	if ((status === 'offline' || statusLivechat !== 'available') && !hasRole(user._id, 'bot')) {
```
Comment (sampaiodiego) [inline app/livechat/server/lib/Helper.js:316]: if you get the field `roles` from user, you can do like this:
```suggestion
	if ((status === 'offline' || statusLivechat !== 'available') && !roles.includes('bot')) {
```

while using `hasRole` is recommended most of the times, in this case you are checking only the `bot` role, and is receiving the user object as a param (that was previously fetched from database).. the `hasRole` would again fetch the same user from database and do an additional find to get the Role.. change to this will prevent then two finds on database.

I think you can change to do this here, but maybe add a `// TODO hasRole` so we can find afterwards if we need to change the `hasRole` function logic

Comment (renatobecker) [reply app/livechat/server/lib/Helper.js]: Yeah, I agree we can avoid fetching the user from DB again by calling `hasRole` method.
I applied your suggestion, I'm checking the user `roles` properties instead of the `hasRole` function.

Thanks.
