### PR TITLE
[FIX] Able to react with invalid emoji

### LINKED ISSUE #8336: Able to react with invalid emoji
Currently you're able to react to a message without providing a valid emoji.

`setReaction` needs to check for a valid emoji, regular and custom, before accepting the reaction.

Useful snippets:

`RocketChat.models.EmojiCustom.findByNameOrAlias(filterReg, options)`
`RocketChat.emoji.list[regularEmoji]`

### PR DESCRIPTION
**Pull request by mutdmour**
[FIX] For bug fixes

@RocketChat/core 

Closes #8336

Added verification to check if emoji is regular or custom

### CODE REVIEW

File: packages/rocketchat-reactions/setReaction.js [hunk 1]
```diff
@@ -17,6 +17,10 @@ Meteor.methods({
 			throw new Meteor.Error('error-not-allowed', 'Not allowed', { method: 'setReaction' });
 		}
 
+		if (!RocketChat.emoji.list[reaction] && RocketChat.models.EmojiCustom.findByNameOrAlias(reaction).count() === 0) {
+			throw new Meteor.Error('error-not-allowed', 'Not allowed', { method: 'setReaction' });
```
Comment (graywolf336) [inline packages/rocketchat-reactions/setReaction.js]: I know this is an older pull request, do you mind changing this to be `error-invalid-emoji` and the text be `Invalid emoji provided.`?
