### PR TITLE
Livechat minor fixes and improvements

### LINKED ISSUE #2276: Livechat guest can not register or chat when using allowed domain list
If your chat server is restricted to only allow new user accounts from a list of allowed domains, guests will not be able to chat with the livechat system. I understand this is because guests have to have an account registered, but I feel they should not be restricted to the allowed domain list as they are specifically a guest.

Further more, if you have enabled that guests have to register their name and email, even if they register with an email that is in the allowed domain list, they still receive the error message that they are not of a valid domain.

Thanks!

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

- Bypass user registration validations for livechat users - Closes #2276, #1963
- Set livechat count and order to zero when empty
- Pick a livechat departament if none selected and there is more than one
- Fix livechat warning hide message
- Add autolinker to livechat

### CODE REVIEW

File: server/lib/accounts.coffee [hunk 1]
```diff
@@ -136,6 +127,35 @@ Accounts.validateLoginAttempt (login) ->
...
+	# bypass for livechat users
+	if user.type is 'visitor'
+		return true
+
 	if RocketChat.settings.get('Accounts_Registration_AuthenticationServices_Enabled') is false and RocketChat.settings.get('LDAP_Enable') is false and not user.services?.password?
 		throw new Meteor.Error 'registration-disabled-authentication-services', 'User registration is disabled for authentication services'
 	return true
+
+
+Accounts.validateNewUser (user) ->
```
Comment (marceloschmidt) [inline server/lib/accounts.coffee]: Why using the `Accounts.validateNewUser` again, instead of using it from line 129?

**Comment by rodrigok** [comment]
LGTM

File: server/lib/accounts.coffee (hunk 1 above)
Comment (sampaiodiego) [inline server/lib/accounts.coffee]: because they are for different validations.. they could even be on different files.

File: packages/rocketchat-livechat/app/client/lib/autolinker.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+/* globals livechatAutolinker, Autolinker */
+var livechatAutolinker = new Autolinker({
```
Comment (sampaiodiego) [inline packages/rocketchat-livechat/app/client/lib/autolinker.js]: 😒 ofcourse it is
