### PR TITLE
[FIX] "Discussions" item in "More" menu not hidden, when Discussions are disabled (#14684)

### LINKED ISSUE #14684: "Discussions" item in "More" menu not hidden, when Discussions are disabled
### Description:

"Discussions" item in "More" menu is not hidden when Discussions are disabled by Administrator.

### Steps to reproduce:

1. Disable Discussions in Admin Panel
2. Check "More" menu in any channel

### Expected behavior:

"Discussions" item in "More" menu should be hidden

### Actual behavior:

Снимок экрана 2019-05-29 в 22 50 36

"Discussions" item in "More" menu is vissible

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0
- Operating System: macOS

### PR DESCRIPTION
**Pull request by ifantom**
"Discussions" item in "More" menu not hidden, when Discussions are disabled by Administrator

Closes #14684

### CODE REVIEW

File: app/discussion/client/tabBar.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import { Meteor } from 'meteor/meteor';
 
 import { TabBar } from '../../ui-utils/client';
+import { settings } from '../../settings';
```
Comment (sampaiodiego) [inline app/discussion/client/tabBar.js]:
```suggestion
import { settings } from '../../settings/client';
```
