### PR TITLE
[FIX] Invalid Code message for password protected channel

### LINKED ISSUE #6106: Invalid Code message for password protected channel
When there is a password set to a channel - users can't join the channel even when they know the password. When they click "Join" they are not prompted for the password but they get "Invalid Code" error immediately. 
Maybe I am missing something - how are users to supposed to join password protected channels when they know the password? And also I think the message should be "Invalid Password" after changing the terminology from Code to Password :)

The log is not saying anything useful even on Debug settings. The only information is (ids were changed):
`rocketchat_1  | Meteor ➔ method joinRoom -> userId: XXXXXXXXX , arguments:  { '0': YYYYYYYYYYYYY', '1': null }`

Rocket.Chat Version: 0.52
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #6106

- Fix: Room preview not opening on first click or redirecting to home on reload
- Fix: Console errors when room is in preview mode but code is trying to access the input
- Fix: Some locations uses the old label `Code`
- Fix: Password input not showing when room is protected

### CODE REVIEW

File: packages/rocketchat-lib/server/methods/joinRoom.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ Meteor.methods({
 		}
 
 		if ((room.joinCodeRequired === true) && (code !== room.joinCode) && !RocketChat.authz.hasPermission(Meteor.userId(), 'join-without-join-code')) {
-			throw new Meteor.Error('error-code-invalid', 'Invalid Code', { method: 'joinRoom' });
+			throw new Meteor.Error('error-code-invalid', 'Invalid Password', { method: 'joinRoom' });
```
Comment (geekgonecrazy) [inline packages/rocketchat-lib/server/methods/joinRoom.js]: Shouldn't we say room password or room join code?  I think password here is still just as ambiguous

Comment (rodrigok) [reply packages/rocketchat-lib/server/methods/joinRoom.js]: Ok, I'll change to Room Password

**Comment by rodrigok** [comment]
@geekgonecrazy Can you review again?
