### PR TITLE
[FIX] Unable to remove a user who joined a public team with a mention

### LINKED ISSUE #25817: Unable to remove an invited user from a public team
### Description:

After adding a member to a public team through a mention, it cannot be removed.
When attempting to remove a member, a Bad Request error appears.

### Steps to reproduce:

1. Go to the team creation menu. Switch the private setting to off. Create a team. 
2. Mention user with @. The user is added.
3. Remove user from the team. 
4. The user is not deleted. A Bad Request error appears.

### Expected behavior:

It is possible to remove users from public teams invited through a mention.

### Actual behavior:

It is not possible to remove a user from an invitee's public command via a mention.
error-team

### Server Setup Information:

Server Setup Information:
Version of Rocket.Chat Server: 4.6.4 (4.8.1 also reproduced)
Operating System: OL8.5
Deployment Method: docker
Number of Running Instances: 20
DB Replicaset Oplog: Enabled
NodeJS Version: 14.18.3
MongoDB Version: 4.4.14

### Client Setup Information

- Desktop App or Browser Version: Google Chrome | 100.0.4896.127, Rocket.chat client 3.8.6
- Operating System: Windows 10.0.19044

### Relevant logs:
I found error messages like this in the developer console:
Bjz4tG0em6UhwW0BsyGB.png:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
-M418Ul0aSTwf2PYsyPW.png:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5:43941
    at HTMLDivElement.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5:39263)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5:43941
    at HTMLDivElement.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5:39263)
-M418Ul0aSTwf2PYsyPW.png:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
Bjz4tG0em6UhwW0BsyGB.png:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5:43941
    at HTMLDivElement.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:5:39263)
api/v1/teams.removeMember:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493 Uncaught (in promise) Error: Bad Request
    at originalCallback (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:643043)
    at Object.processTwoFactorError (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:643979)
    at Object.o [as error] (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:642949)
    at s (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:24892)
    at Object.fireWith [as rejectWith] (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:25640)
    at E (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:76665)
    at XMLHttpRequest.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:79108)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1 Exception from Tracker recompute function:
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1 TypeError: Cannot read properties of undefined (reading 'announcement')
    at d.View.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:93252)
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19187
    at Function.c._withTemplateInstanceFunc (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:38718)
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19138
    at Object.d._withCurrentView (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:23280)
    at n (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19086)
    at t._compute (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:2329)
    at t._recompute (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:2484)
    at Object.o._runFlush (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:3495)
    at a (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1:3087)
api/v1/teams.removeMember:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493 Uncaught (in promise) Error: Bad Request
    at originalCallback (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:643043)
    at Object.processTwoFactorError (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:643979)
    at Object.o [as error] (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:642949)
    at s (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:24892)
    at Object.fireWith [as rejectWith] (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:25640)
    at E (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:76665)
    at XMLHttpRequest.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:79108)
api/v1/teams.removeMember:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493 Uncaught (in promise) Error: Bad Request
    at originalCallback (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:643043)
    at Object.processTwoFactorError (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:643979)
    at Object.o [as error] (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:642949)
    at s (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:24892)
    at Object.fireWith [as rejectWith] (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:25640)
    at E (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:76665)
    at XMLHttpRequest.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1053:79108)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1 Exception from Tracker recompute function:
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1 TypeError: Cannot read properties of undefined (reading 'announcement')
    at d.View.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:93252)
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19187
    at Function.c._withTemplateInstanceFunc (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:38718)
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19138
    at Object.d._withCurrentView (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:23280)
    at n (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19086)
    at t._compute (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:2329)
    at t._recompute (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:2484)
    at Object.o._runFlush (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:3495)
    at a (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1:3087)
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1 Exception from Tracker recompute function:
242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1 TypeError: Cannot read properties of undefined (reading 'announcement')
    at d.View.<anonymous> (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1493:93252)
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19187
    at Function.c._withTemplateInstanceFunc (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:38718)
    at 242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19138
    at Object.d._withCurrentView (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:23280)
    at n (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1308:19086)
    at t._compute (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:2329)
    at t._recompute (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:2484)
    at Object.o._runFlush (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1262:3495)
    at a (242c5d66c93b2ae19503c5a48338edb02a297cc9.js?meteor_js_resource=true:1:3087)

### PR DESCRIPTION
**Pull request by LucianoPierdona**
## Proposed changes (including videos or screenshots)

This PR fixes a bug where a user that joins a team by mention don't get added to the team.

## Issue(s)

Fix #25817

## Steps to test or reproduce

1. Go to the team creation menu. Switch the private setting to off. Create a team.
2. Mention user with @. The user is added.
3. Remove user from the team.
4. The user is not deleted. A Bad Request error appears.

### CODE REVIEW

File: apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js [hunk 1]
```diff
@@ -368,6 +369,10 @@ export async function sendAllNotifications(message, room) {
 			mentions.map(async (userId) => {
 				await callJoinRoom(userId, room._id);
 
+				if (room.teamId) {
+					Team.addMember(room.u._id, userId, room.teamId);
+				}
+
```
Comment (matheusbsilva137) [inline apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js:375]: I think a better option would be to change the `addUserToRoom` function instead of adding the team member here. This way, we'd also cover the case where a user joins a team using the "Join" button (I've just noticed we also don't create a new team member in this case)

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js (hunk 1 above)
Comment (LucianoPierdona) [reply apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js]: Updated!

File: apps/meteor/app/lib/server/functions/addUserToRoom.ts [hunk 2]
```diff
@@ -112,9 +112,11 @@ export const addUserToRoom = function (
 		});
 	}
 
-	if (room.teamMain && room.teamId && inviter) {
+	if (room.teamMain && room.teamId) {
+		const inviterId = inviter ? inviter._id : room.u._id;
+
 		// if user is joining to main team channel, create a membership
-		Promise.await(Team.addMember(inviter, userToBeAdded._id, room.teamId));
+		Promise.await(Team.addMember(inviterId, userToBeAdded._id, room.teamId));
```
Comment (matheusbsilva137) [inline apps/meteor/app/lib/server/functions/addUserToRoom.ts:119]: The first param of the `addMember` method should be an object containing the `_id` field. So here we should use `inviter || userToBeAdded` as the first param.
Using the `room.u._id` would mean that the room owner is the inviter, which is not always the case.

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: apps/meteor/app/lib/server/functions/addUserToRoom.ts (hunk 2 above)
Comment (LucianoPierdona) [reply apps/meteor/app/lib/server/functions/addUserToRoom.ts]: Updated!

File: apps/meteor/server/services/team/service.ts [hunk 3]
```diff
@@ -755,30 +755,36 @@ export class TeamService extends ServiceClassInternal implements ITeamService {
...
+							? {
+									byUser,
+							  }
+							: undefined,
+					);
+				}
+			} else if (subscription) {
+				// handle old cases where user was not added to team
+				await Subscriptions.removeById(subscription._id);
+				await Users.removeRoomsByRoomIdsAndUserId([team.roomId], member.userId);
```
Comment (matheusbsilva137) [inline apps/meteor/server/services/team/service.ts:785]: I think we should use the `removeUserFromRoom` function here instead of deleting the subscription and removing the room from the user's list. No system message is sent to the room if we don't call the `removeUserFromRoom` function.

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: apps/meteor/server/services/team/service.ts (hunk 3 above)
Comment (LucianoPierdona) [reply apps/meteor/server/services/team/service.ts]: updated!
