### PR TITLE
fix: Composer Popup doesn't scroll results

### LINKED ISSUE #35447: Composer popup doesn't scroll
### Description:

The list inside the Composer popup doesn't scroll with mouse. You can observe that only keydown arrow works but you can't scroll using mouse or touchpad.

### Steps to reproduce:

1. Go to message box
2. Type ':' or '@' or '#' and a list appears (emoji or list of users or channels)
3. Notice that it doesn't have scroll feature

### Expected behavior:

Should scroll through all items.

### Actual behavior:

https://github.com/user-attachments/assets/cb5c5457-19b6-4fe0-87bd-e8f1927e47ce

### Server Setup Information:

- Version of Rocket.Chat Server: 7.5.0-develop
- License Type: Starter
- Number of Users: 50-100
- Operating System: MacOS
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 22.13.1 - arm64
- MongoDB Version: 7.0.5

### Client Setup Information

- Desktop App or Browser Version: Safari version 17.6
- Operating System: MacOS Sonoma 14.7.2

### PR DESCRIPTION
**Pull request by samir0607**
Suppose there are a lot of people in the channel, when you try to mention someone you use '@' that opens a popup which has a list of people the list sometimes might be big that you need to scroll down. In the current version I can only go down int the using arrow down key but can't scroll.

## Proposed changes (including videos or screenshots)

Kapture 2025-05-19 at 19 29 47

Here, now the scrolling feature works well.

## Issue(s)
Closes #35447
[CORE-1155]

## Steps to test or reproduce

Use @ in a very big and active room to mention someone try to scroll down.

[CORE-1155]: https://rocketchat.atlassian.net/browse/CORE-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx [hunk 1]
```diff
@@ -91,7 +91,7 @@ function ComposerBoxPopup<
 						{title}
 					</Box>
 				)}
-				<Box pb={8} maxHeight='x320'>
+				<Box pb={8} maxHeight='x320' overflowY='auto'>
```
Comment (dougfabris) [inline apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx:94]: Hey, thanks for your contribution 🚀 

If you just add the overflow property it will use the native scrollbar, I will suggest to wrap this `Box` with our `CustomScrollbars`

**Review by dougfabris — CHANGES_REQUESTED** [review]

**Comment by samir0607** [comment]
I was thinking of that well will do that and raise my PR again

File: apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx (hunk 1 above)
Comment (samir0607) [reply apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx]: Raised a new PR

**Review by dougfabris — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx [hunk 2]
```diff
@@ -4,6 +4,7 @@ import type { UseQueryResult } from '@tanstack/react-query';
 import type { ReactElement } from 'react';
 import { useEffect, memo, useMemo, useRef, useId } from 'react';
 import { useTranslation } from 'react-i18next';
+import { CustomScrollbars } from '/client/components/CustomScrollbars';
```
[the remark this answers is not in the document]
Comment (samir0607) [reply apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx]: done🫡

**Review by dougfabris — APPROVED** [review]
