### PR TITLE
[FIX] Check settings for name requirement before validating

### LINKED ISSUE #6081: The user name is always required, ignoring the settings not to.
As an admin, when editing a user, the user name is always required, ignoring the settings in the registration not to require a name to register.

Rocket.Chat Version: 0.49
Running Instances: 1
DB Replicaset OpLog:
Node Version: 6.8.1

### PR DESCRIPTION
**Pull request by marceloschmidt**
Closes #6081 

When "Require Name For Signup" in Admin -> Accounts -> Registration is set to false, allows saving user info without providing a name, and also allows setting it to empty.

### CODE REVIEW

File: app/lib/server/functions/saveUser.js [hunk 1]
```diff
@@ -171,6 +171,11 @@ export const saveUser = function(userId, userData) {
 
 		const _id = Accounts.createUser(createUser);
 
+		// set userData.name to empty string to guarantee it's not undefined
+		if (!userData.name) {
+			userData.name = '';
```
Comment (rodrigok) [inline app/lib/server/functions/saveUser.js]: Why not? That way if I as admin edit a user that doesn't have a name `name === undefined` I'll update it to `name === ''` and all of his subscriptions.

Comment (marceloschmidt) [reply app/lib/server/functions/saveUser.js]: and how would you clear the username after it's been set to something?

File: app/lib/server/functions/setRealName.js [hunk 2]
```diff
@@ -20,7 +20,11 @@ export const _setRealName = function(userId, name) {
 	}
```
Comment (rodrigok) [inline app/lib/server/functions/setRealName.js]: On line 10 `name` will be converted from `undefined` to `''` and on line 18 the comparison will be false executing the following updates even when not setting the name
