### PR TITLE
[FIX] Image preview for image URLs on messages

### LINKED ISSUE #19714: Image preview stopped working - 3.9.0
### Description:
Prior to the upgrade (3.9.0), when someone posted a link to the image, either direct domain.com/image.png/jpg or via shorturl.com/random there was an image preview showing.

### Steps to reproduce:
1. Go to any channel or DM
2. Paste an image 
3. There is no preview displaying, just a link

### Expected behavior:
1. There should be a preview of the image

### Actual behavior:
This is how information is displayed
i4elate3K

### Server Setup Information:
* Version of Rocket.Chat Server: 3.9.0
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: Unknown - see rocketchat:3.4.1 image.
* MongoDB Version: 4.0.12

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 3.0.7

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

### PR DESCRIPTION
**Pull request by g-thome**
## Proposed changes

Add a null check to prevent an exception to stop the image preview workflow.

## Issue(s)

Closes #19714

## How to test or reproduce

1. Go to any channel or DM
2. Paste an image url

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

[FIX] Image previews not working

### CODE REVIEW

File: tests/end-to-end/api/05-chat.js [hunk 1]
```diff
@@ -699,6 +699,73 @@ describe('[Chat]', function() {
...
+						alias: 'Gruggy',
+						emoji: ':smirk:',
+						avatar: 'http://res.guggy.com/logo_128.png',
+						attachments: [],
+					},
+				})
+				.expect('Content-Type', 'application/json')
+				.expect(200);
+
+			this.timeout(100);
```
Comment (sampaiodiego) [inline tests/end-to-end/api/05-chat.js:753]: I'm not sure `this.timeout` has the expected result.. it is saying the following tests will cannot take longer than 100ms to execute.. is that what were you expecting?

if you want to delay the next `request.get`, you'll need to use `setTimeout` and call `done` after it pass.

**Review by sampaiodiego — CHANGES_REQUESTED** [review]

File: tests/end-to-end/api/05-chat.js (hunk 1 above)
Comment (g-thome) [reply tests/end-to-end/api/05-chat.js]: You're right. I've applied the changes to the branch

**Review by sampaiodiego — APPROVED** [review]
