### PR TITLE
[FIX] Several issues related to custom roles

### LINKED ISSUE #23989: Invalid roles are created and can't be deleted
### Description:

Permissions page allow to created invalid roles and does not allow to edit/delete these roles, as well as they cannot be assigned using API.

### Steps to reproduce:

1. go to /admin/permissions and click plus at top right
2. enter desired role name and description, for example "test123", use Global scope and click save
3. Try to assign this role: this gives the following error: 
Client error: `POST https://chat.cryptomates.io//api/v1/users.update` resulted in a `400 Bad Request` response:
{"success":false,"error":"The field Roles consist invalid role name [error-action-not-allowed]","errorType":"error-actio (truncated...)

4. try to edit/delete this role, by clicking on role name
It shows "Invalid role"

### Expected behavior:

Role with wrong names should not be allowed to create and anyway they should have a possibility to be deleted

### Actual behavior:
image

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 20
- Deployment Method: regular install
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 6.14.6
- MongoDB Version: 4.4.10

### Client Setup Information

- Desktop App or Browser Version: Chrome 86
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by pierre-lehnen-rc**
## Proposed changes (including videos or screenshots)

- Throw an error when trying to delete a role (User or Subscription role) that are still being used;
- Fix "Invalid Role" error for custom roles in Role Editing sidebar;
- Fix "Users in Role" screen for custom roles.

## Issue(s)

Fix #23989
Close #24059 

## Steps to test or reproduce

1 Go to **Admin > Permissions > +** and create a new Global (scope) role;
2. Select the new role in the list of roles (table header). The "Role Editing" sidebar will be shown. Go to **"Users in Role"** and assign users to this role;
3. Return to the Permissions page, select the same role and try to delete it. The following **error** should be displayed: `Cannot delete role because it's in use [error-role-in-use]`;
4. Repeat this process for a role in the "Rooms" scope.
5. Try to delete roles from users in the "Users in role" page. No error should be shown for both scopes.

https://user-images.githubusercontent.com/36537004/149013092-c305f183-3b56-4932-aaa3-434fed7d2ddf.mp4

https://user-images.githubusercontent.com/36537004/149020300-474e02c3-b371-40e2-acaf-b1d4aa7bbe5c.mp4

### CODE REVIEW

**Review by matheusbsilva137 — DISMISSED** [review]

**Review by dougfabris — CHANGES_REQUESTED** [review]
After updating some role it generates a new one with the same `_id` 
Reloading the page, it works normally 🤔 

Kapture 2022-01-13 at 12 49 53

**Review by dougfabris — DISMISSED** [review]

File: server/lib/roles/addUserRoles.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+import { validateRoleList } from './validateRoleList';
+
+export const addUserRolesAsync = async (userId: IUser['_id'], roleIds: IRole['_id'][], scope?: IRoom['_id']): Promise<boolean> => {
+	if (!userId || !roleIds?.length) {
+		return false;
+	}
+
+	const user = await Users.findOneById(userId, { projection: { _id: 1 } });
+	if (!user) {
+		throw new Error('error-invalid-user');
```
Comment (matheusbsilva137) [inline server/lib/roles/addUserRoles.ts:13]: Maybe we should throw `MeteorError`s instead to assure they are shown in the UI.

File: server/lib/roles/removeUserFromRoles.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+import { validateRoleList } from './validateRoleList';
+
+export const removeUserFromRolesAsync = async (userId: IUser['_id'], roleIds: IRole['_id'][], scope?: IRoom['_id']): Promise<boolean> => {
+	if (!userId || !roleIds) {
+		return false;
+	}
+
+	const user = await Users.findOneById(userId, { projection: { _id: 1 } });
+	if (!user) {
+		throw new Error('error-invalid-user');
```
Comment (matheusbsilva137) [inline server/lib/roles/removeUserFromRoles.ts:13]: Maybe it'd also be good to throw `MeteorError`s here

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: app/api/server/v1/roles.ts [hunk 3]
```diff
@@ -258,7 +245,7 @@ API.v1.addRoute(
 				throw new Meteor.Error('error-role-protected', 'Cannot delete a protected role');
 			}
 
-			const existingUsers = await Roles.findUsersInRole(role.name, role.scope);
+			const existingUsers = await Roles.findUsersInRole(role._id);
```
[the remark this answers is not in the document]
Comment (pierre-lehnen-rc) [reply app/api/server/v1/roles.ts:248]: The second param expects a room id, not a role scope. By sending undefined, it will search in all rooms.

File: app/authorization/server/functions/hasRole.ts [hunk 4]
```diff
@@ -1,18 +1,34 @@
...
 	}
 
-	return Roles.isUserInRoles(userId, roleNames, scope);
+	return Roles.isUserInRoles(userId, roleIds, scope);
+};
+
+export const hasRoleAsync = async (userId: IUser['_id'], roleId: IRole['_id'], scope?: IRoom['_id'] | undefined): Promise<boolean> => {
+	if (Array.isArray(roleId)) {
+		throw new Error('error-invalid-arguments');
+	}
```
[the remark this answers is not in the document]
Comment (pierre-lehnen-rc) [reply app/authorization/server/functions/hasRole.ts:25]: Both functions on this file can be called externally, so they both need to validate the input.

File: server/methods/afterVerifyEmail.ts [hunk 5]
```diff
@@ -2,9 +2,10 @@ import { Meteor } from 'meteor/meteor';
 
 import { Users } from '../../app/models/server';
 import { Roles } from '../../app/models/server/raw';
-import { IUser } from '../../definition/IUser';
+import { IUser, IRole } from '../../definition/IUser';
 
-const rolesToChangeTo: Map<string, [string]> = new Map([['anonymous', ['user']]]);
+// Shouldn't this respect role settings?
```
Comment (ggazzo) [inline server/methods/afterVerifyEmail.ts:7]:
```suggestion
```

File: server/startup/migrations/v258.ts [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+		const filteredRoles = roles.filter(({ _id, name }) => _id !== name);
+
+		const roleNames = filteredRoles.map(({ name }) => name);
+		const roleMap = filteredRoles.reduce(
+			(prev: Record<IRole['name'], IRole['_id']>, { _id, name }) => ({
+				...prev,
+				[name]: _id,
+			}),
+			{},
+		);
```
Comment (ggazzo) [inline server/startup/migrations/v258.ts:22]:
```suggestion
		const roleMap = Object.fromEntries(filteredRoles.map(
			(prev: Record<IRole['name'], IRole['_id']>, { _id, name }) => ([name,  _id]),
		));
```

File: server/startup/migrations/v258.ts [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+
+		// Find all users that have a role name in their roles attribute
+		const users = await Users.find<Pick<IUser, '_id' | 'roles'>>(
+			{ roles: { $in: roleNames } },
+			{ projection: { _id: 1, roles: 1 } },
+		).toArray();
```
Comment (ggazzo) [inline server/startup/migrations/v258.ts:28]: try to avoid toArray for large collections

**Review by ggazzo — CHANGES_REQUESTED** [review]

**Review by ggazzo — APPROVED** [review]
