### PR TITLE
[FIX] "View All Members" button inside channel's "User Info" is over sized

### LINKED ISSUE #9734: [BUG] View All Members button inside channel's User Info is over sized
### Description
Inside a channel, in **member list** > any member > **User info**, the **View All Members** button is over sized.
2018-02-15-17-27-open rocket chat

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #9734

image

### CODE REVIEW

**Comment by rodrigok** [comment]
Can you fix the tests?

File: tests/end-to-end/ui/12-settings.js [hunk 1]
```diff
@@ -431,7 +431,7 @@ describe('[Api Settings Change]', () => {
 		});
 	});
 
-	describe('Manually Approve New Users:', () => {
+	describe.only('Manually Approve New Users:', () => {
```
Comment (rodrigok) [inline tests/end-to-end/ui/12-settings.js]: Please remove this change!

**Comment by karlprieb** [comment]
All done @rodrigok
