### PR TITLE
[FIX] Notify with sound first message in queue list

### LINKED ISSUE #20554: Sound Notifications Do Not Work for Omnichannel New Chat Queue
### Description:

Agents are not notified by sound notification that there is new chat in queue. Once agent takes chat, then sound notifications work - but not during initial chat entry into queue to let agents know there is a new chat waiting.  Web browsers' sound notifications are enabled, so problem is not with web browser settings.  Windows sound notifications are also enabled.

### Steps to reproduce:

1. Set Omnichannel routing method to Manual.
2. Start new chat from widget.
3. New chat shows up in agent queue but there is no sound notification.
4. Once agent takes chat, then sound notification works.

### Expected behavior:

Agents are notified by sound notification that there is new chat in queue.

### Actual behavior:

Agents are not notified by sound notification that there is new chat in queue.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.7
- Operating System: Linux (Ubuntu)
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by tiagoevanp**
## Issue(s)

close #20554

### CODE REVIEW

File: client/startup/notifications/konchatNotifications.ts [hunk 1]
```diff
@@ -98,6 +98,10 @@ Meteor.startup(() => {
 				'muteFocusedConversations',
 			);
 
+			if (notification.payload.type === 'l') {
```
Comment (ggazzo) [inline client/startup/notifications/konchatNotifications.ts:101]: it doesnt look the best match only testing the 'l' to be sure its an queue notification

File: app/livechat/client/lib/stream/queueManager.js [hunk 2]
```diff
@@ -1,14 +1,32 @@
...
 
 const departments = new Set();
 
+const newInquirySound = () => {
+	const userId = Meteor.userId();
+	const audioVolume = getUserPreference(userId, 'notificationsSoundVolume');
+	const newRoomNotification = getUserPreference(userId, 'newRoomNotification');
+	const audioNotificationValue = getUserPreference(userId, 'audioNotifications');
+
+	if (audioNotificationValue === 'all') {
```
Comment (renatobecker) [inline app/livechat/client/lib/stream/queueManager.js:18]: Why do we need to check this here? In my case, `audioNotificationValue` is equal to `mentions`, but I have never changed that setting, so I didn't get any sound for new Omnichannel rooms.
The same will happens for regular agents, they need to get `newRoomNotification` sound regardless `audioNotificationValue` since that setting is not designed for Omnichannel.

**Review by renatobecker — CHANGES_REQUESTED** [review]

File: app/livechat/client/lib/stream/queueManager.js (hunk 2 above)
Comment (tiagoevanp) [reply app/livechat/client/lib/stream/queueManager.js:18]: I was looking for the example that we have in chat, where the setting is get by Subscription... Omnichannel is not a regular chat, I know, but is not important to consider this general setting as well?

Comment (renatobecker) [reply app/livechat/client/lib/stream/queueManager.js:18]: I got your point, but IMHO, for Omnichannel I'd check the opposite:
```suggestion
	if (audioNotificationValue !== 'none') {
```

Comment (tiagoevanp) [reply app/livechat/client/lib/stream/queueManager.js]: Fair enough! Maybe in another time we can discuss better about notification behaviors and best architecture for project, I was thinking about it and how to improve that in omnichannel 😉

Comment (renatobecker) [reply app/livechat/client/lib/stream/queueManager.js]: > Fair enough! Maybe in another time we can discuss better about notification behaviors and best architecture for project, I was thinking about it and how to improve that in omnichannel 😉

Definitely, It'd be great!

**Review by MartinSchoeler — APPROVED** [review]
Looks good to me

**Comment by ggazzo** [comment]
This is not as I had suggested, the code for emitting the sound was duplicated and like all the logic evaluating the settings. Where you call the method I don't really care. but if for some reason we remove the CustouSound or any other preference, you will quickly notice.

**Comment by lucassk8prof** [comment]
Hello everyone!
This fix was great for us, but when chat is transferred to another department, this sound should be emitted also ,what do you guys think about it? Regards for attention.

**Comment by tiagoevanp** [comment]
> Hello everyone!
> This fix was great for us, but when chat is transferred to another department, this sound should be emitted also ,what do you guys think about it? Regards for attention.

Thanks for your comment. Suggestion saved in our list!
