### PR TITLE
Regression: Prune Threads

### LINKED ISSUE #13673: Pruning Messages orphans threads
### Description:

If you use the use the prune message feature as is often done in #sandbox on open.rocket.chat.  All threads are orphaned with no way to access them.  But they are still around.

### Steps to reproduce:

1. Start a thread
2. Copy url of the thread
2. Prune messages in a range that includes the message that you started a thread from
3. look at threads list its empty.
4. paste thread url back in

### Expected behavior:

Thread should either go away... or still be viewable in threads list

### Server Setup Information:

- Version of Rocket.Chat Server: current commit ( open.rocket.chat )

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #13673

### CODE REVIEW

File: packages/rocketchat-models/server/models/Messages.js [hunk 1]
```diff
@@ -171,7 +171,7 @@ export class Messages extends Base {
 			query.pinned = { $ne: true };
 		}
 
-		if (!ignoreThreads) {
+		if (ignoreThreads) {
```
Comment (geekgonecrazy) [inline packages/rocketchat-models/server/models/Messages.js]: So this should prevent the message starting the thread from being pruned if they want to keep threads?

Comment (sampaiodiego) [reply packages/rocketchat-models/server/models/Messages.js]: yes
