### PR TITLE
chore(omnichannel): fix unsafe type assertions in CannedResponsesComposer

### LINKED ISSUE #38703: chore(omnichannel): fix unsafe type assertions in CannedResponsesComposer
### Description
This issue addresses technical debt in the [CannedResponsesComposer](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:22:0-126:2) component within the Omnichannel module. 

Currently, the component uses `as any` type assertions to bypass type checking for the `onChange` handler, and utilizes the `any` type in [InsertPlaceholderDropdown](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx:12:0-75:2). This occurs because the component's props are typed as `ComponentProps<typeof MessageComposerInput>` (which expects `ChangeEventHandler`), while the consumer ([CannedResponseForm](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponseForm.tsx:13:0-203:2)) passes a [(value: string) => void](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/RoomEdit/RoomEdit.tsx:52:0-175:1) handler via `react-hook-form`.

### Current Behavior
- Code uses `onChange?.(textAreaRef.current.value as any)` to silence TypeScript errors.
- [InsertPlaceholderDropdown](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx:12:0-75:2) uses `any` for `onChange` and `name` parameters.
- No runtime errors, but type safety is compromised.

### Expected Behavior
- The component should have improper `any` casts removed.
- [CannedResponsesComposer](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:22:0-126:2) should define a specific props interface that correctly types `onChange` as [(value: string) => void](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/RoomEdit/RoomEdit.tsx:52:0-175:1).
- [InsertPlaceholderDropdown](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx:12:0-75:2) should use strict types.

### Steps to Reproduce
1. Open [apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx](cci:7://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:0:0-0:0)
2. Observer `as any` casts at lines 56 and 71 (in `develop` branch).
3. Open [InsertPlaceholderDropdown.tsx](cci:7://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx:0:0-0:0) and observe `any` types.

### Proposed Solution
1. Define [CannedResponsesComposerProps](cci:2://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:18:0-20:2) that extends [MessageComposerInput](cci:2://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx:13:0-13:60) props but overrides `onChange`.
2. Update [InsertPlaceholderDropdownProps](cci:2://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx:6:0-10:2) to use specific types.
3. Remove all `as any` assertions.

### PR DESCRIPTION
**Pull request by NAME-ASHWANIYADAV**
## Proposed Changes

This PR resolves technical debt in the [CannedResponsesComposer](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:22:0-126:2) component by removing unsafe type assertions.

- **Refactor**: Replaced `as any` casts with proper type definitions in [CannedResponsesComposer.tsx](cci:7://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:0:0-0:0).
- **Typing**: Defined [CannedResponsesComposerProps](cci:2://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:18:0-20:2) to correctly override the `onChange` handler signature from `ChangeEvent` to [(value: string) => void](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/RoomEdit/RoomEdit.tsx:52:0-175:1), aligning with the usage in [CannedResponseForm](cci:1://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponseForm.tsx:13:0-203:2).
- **Cleanup**: Updated [InsertPlaceholderDropdown.tsx](cci:7://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx:0:0-0:0) to use strict types instead of `any`.

## Issue(s)

Closes #38703

## Steps to Test or Reproduce

1. Go to **Omnichannel > Canned Responses**.
2. Create or edit a canned response.
3. Verify that the "Message" composer works correctly (typing, emoji picker, formatting buttons).
4. Verify that "Insert Placeholder" dropdown works as expected.
5. (Dev) Check [apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx](cci:7://file://wsl$/Ubuntu/home/ashwaniyadav/Rocket.Chat/apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:0:0-0:0) to confirm no `as any` usage.

## Further Comments

This change is purely a code quality improvement (chore) and does not affect runtime behavior or UI. It ensures better type safety and maintainability.

## Summary by CodeRabbit

* **Refactor**
  * Strengthened input typing in the canned responses composer so text changes are forwarded reliably as plain strings.
  * Tightened placeholder handling to enforce string values for inserted placeholders, reducing unexpected behavior when composing or inserting responses.
 

 Task: [ARCH-2065]

[ARCH-2065]: https://rocketchat.atlassian.net/browse/ARCH-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NAME-ASHWANIYADAV** [comment]
Hi @KevLehman , this one has contrib: valid and is awaiting review. Since the milestone deadline is coming up, it would be great if this could be reviewed. Let me know if any changes are needed!

File: apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx [hunk 1]
```diff
@@ -8,15 +8,19 @@ import {
...
 import { useTranslation } from 'react-i18next';
 
 import InsertPlaceholderDropdown from './InsertPlaceholderDropdown';
 import { Backdrop } from '../../../../../components/Backdrop';
 import { useEmojiPicker } from '../../../../../contexts/EmojiPickerContext';
 
-const CannedResponsesComposer = ({ onChange, ...props }: ComponentProps<typeof MessageComposerInput>) => {
+type CannedResponsesComposerProps = Omit<ComponentProps<typeof MessageComposerInput>, 'onChange'> & {
+	onChange: (value: string) => void;
+};
```
Comment (ggazzo) [inline apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:21]: I dont think this is the right type

File: apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx [hunk 2]
```diff
@@ -91,7 +95,12 @@ const CannedResponsesComposer = ({ onChange, ...props }: ComponentProps<typeof M
 
 	return (
 		<MessageComposer>
-			<MessageComposerInput ref={textAreaRef} rows={10} onChange={onChange} {...props} />
+			<MessageComposerInput
+				ref={textAreaRef}
+				rows={10}
+				onChange={(e: ChangeEvent<HTMLTextAreaElement>): void => onChange(e.target.value)}
```
Comment (ggazzo) [inline apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:101]: you changed the way onChange is called, is this a fix or are we introducing a bug?

Comment (ggazzo) [reply apps/meteor/client/views/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx:101]: nvm react form accepts both

**Review by ggazzo — APPROVED** [review]

**Comment by NAME-ASHWANIYADAV** [comment]
Thankyou @ggazzo 😊😊🙏
