### PR TITLE
[FIX] Users autocomplete showing duplicated results

### LINKED ISSUE #20480: [BUG]While mentioning user, suggestions shows users of room twice.
### Description:
When we type @ in message then suggestions show users of the room twice.

### Steps to reproduce:

1. Select any channel
2. Message box
3. Type @

### Expected behavior:
Users of the room should not been shown twice.

### Actual behavior:
Users of the room are shown twice.

https://user-images.githubusercontent.com/55157259/106173784-51da3b80-61ba-11eb-8633-e4da01b2cad4.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
Working!

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Added new query for outside room users so that room members are not shown twice.

https://user-images.githubusercontent.com/55157259/106174582-33c10b00-61bb-11eb-9716-377ef7bba34e.mp4

## Issue(s)

Closes #20480

### CODE REVIEW

**Comment by Darshilp326** [comment]
@dougfabris Please review:)

**Comment by KevLehman** [comment]
@Darshilp326 I just found something interesting. Not sure if you have the same behavior. When the full username is typed, the values are duplicated

image

If, however, I apply both changes (mine in #20590 and yours), everything works as expected. Can you help me verify this?

File: server/publications/spotlight.js [hunk 1]
```diff
@@ -140,6 +140,11 @@ function searchUsers({ userId, rid, text, usernames }) {
 	}
 
 	const insiderExtraQuery = [];
+	const roomId = [rid];
+	const outsiderExtraQuery = [];
+	outsiderExtraQuery.push({
+		__rooms: { $nin: roomId },
+	});
```
Comment (KevLehman) [inline server/publications/spotlight.js:147]: Since this is just used once, can you define `ousiderExtraquery` in place instead of defining the array and pushing into it?

**Comment by Darshilp326** [comment]
@KevLehman Please review:)

**Comment by KevLehman** [comment]
Let me test this offline and I'll get back to you. Thanks!

**Review by KevLehman — APPROVED** [review]
Working as expected
