### PR TITLE
[FIX] Missing User when forwarding Omnichannel conversations via Apps-Engine

### LINKED ISSUE #17911: transferVisitor() method of App.Engine not working without optional param - TargetUserAgent
# Description:

When using [`transferVisitor`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/d257eb8253472b89dd0d84ac72e41245b710d615/src/definition/accessors/ILivechatUpdater.ts#L11) method from `App-Engine`, I'm getting the following error(Screenshot attached).
`TypeError: Cannot read property 'id' of undefined
rocketchat_1          |     at app/apps/server/bridges/livechat.js:140:26
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40`

_After a bit of debugging, here is what I found_
[`transferVisitor`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/d257eb8253472b89dd0d84ac72e41245b710d615/src/definition/accessors/ILivechatUpdater.ts#L11) method expects [`ILivechatTransferData`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/d257eb8253472b89dd0d84ac72e41245b710d615/src/definition/livechat/ILivechatTransferData.ts#L4) which contains 2 optional params, one is `TargetAgent` n other is `TargetDepartment`. 
In my case, I'm not passing the `TargetAgent` property, n because of this I'm getting an error. This shouldn't happen bcs it is an optional property.

The error is taking place at this line
https://github.com/RocketChat/Rocket.Chat/blob/d504638b36cfb27dda6b53e5db4f36a8261561bf/app/apps/server/bridges/livechat.js#L140
As u can see above:point_up: , `targetAgent` variable can be undefined, however here it is trying to access its `id` property

### Steps to reproduce:

1. Use [`transferVisitor`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/d257eb8253472b89dd0d84ac72e41245b710d615/src/definition/accessors/ILivechatUpdater.ts#L11) without `TargetAgent` property

### Expected behavior:
It should transfer the visitor to a live-agent in department

### Actual behavior:

image

### PR DESCRIPTION
**Pull request by murtaza98**
## Description
This PR attempts to close Issue #17911 
Additionally, it adds a missing property [`transferredBy`](https://github.com/murtaza98/Rocket.Chat/blob/27e22510f2f1a5feec9338bf01d6d5431f0858e2/app/apps/server/bridges/livechat.js#L148) to the `transferData` object begin passed on to `transfer` method :point_down: 
https://github.com/RocketChat/Rocket.Chat/blob/77aff86764abb4e195a8ec19c3529a7ae8a31b66/app/livechat/server/lib/Livechat.js#L580

This is property is required for the following `check` in [`saveTransferHistory`](https://github.com/RocketChat/Rocket.Chat/blob/77aff86764abb4e195a8ec19c3529a7ae8a31b66/app/livechat/server/lib/Livechat.js#L552) method.
https://github.com/RocketChat/Rocket.Chat/blob/77aff86764abb4e195a8ec19c3529a7ae8a31b66/app/livechat/server/lib/Livechat.js#L556

I'm assigning the `app-User` to this missing property since this method will always be triggered by an app.

## Issue(s)
Closes #17911 

## Screenshots
Handover Action is being processed properly
image

### CODE REVIEW

File: app/apps/server/bridges/livechat.js [hunk 1]
```diff
@@ -134,10 +134,18 @@ export class AppLivechatBridge {
...
+			username: appUser.username,
+			name: appUser.name,
+			type: appUser.type,
+		};
+
 		return Livechat.transfer(
 			this.orch.getConverters().get('rooms').convertAppRoom(currentRoom),
 			this.orch.getConverters().get('visitors').convertAppVisitor(visitor),
-			{ userId: targetAgent.id, departmentId },
+			{ userId: targetAgent ? targetAgent.id : undefined, departmentId,  transferredBy},
```
Comment (renatobecker) [inline app/apps/server/bridges/livechat.js:148]:
```suggestion
			{ userId: targetAgent ? targetAgent.id : undefined, departmentId, transferredBy },
```

File: app/apps/server/bridges/livechat.js [hunk 2]
```diff
@@ -134,10 +134,18 @@ export class AppLivechatBridge {
 			currentRoom,
 		} = transferData;
 
+		const appUser = Users.findOneByAppId(appId);
+		const transferredBy = {
```
Comment (renatobecker) [inline app/apps/server/bridges/livechat.js:138]:
```suggestion
		if (!appUser) {
			throw new Error('Invalid user, cannot transfer');
		}
		const { _id, username, name, type } = appUser;
		const transferredBy = {
			_id,
			username,
			name,
			type,
		}		
```

Comment (murtaza98) [reply app/apps/server/bridges/livechat.js:142]: Incorporated this change in the latest commit. REF https://github.com/RocketChat/Rocket.Chat/pull/17918/commits/997469ff029f7d9a9f3de1c5e4195219723233ad
