### PR TITLE
Fixes admin create / edit users

### LINKED ISSUE #2709: Blank user managing panel is shown
Your Rocket.Chat version: 0.24
Steps to reproduce:
1. Log in as admin and go to Administration -> User
2. Click "Add User" in right sidebar
3. Click "CANCEL" button in "Add User" panel.

if "DELETE" button is clicked in the above blank panel,
last selected user in center "Users" view would be deleted.

### PR DESCRIPTION
**Pull request by marceloschmidt**
@RocketChat/core 

Closes #2709

### CODE REVIEW

File: packages/rocketchat-lib/server/functions/setEmail.js [hunk 1]
```diff
@@ -32,5 +32,5 @@ RocketChat._setEmail = function(userId, email) {
 };
 
 RocketChat.setEmail = RocketChat.RateLimiter.limitFunction(RocketChat._setEmail, 1, 60000, {
-	0: function(userId) { return !RocketChat.authz.hasPermission(userId, 'edit-other-user-info'); } // Administrators have permission to change others emails, so don't limit those
+	0: function(userId) { return !Meteor.userId() || !RocketChat.authz.hasPermission(Meteor.userId(), 'edit-other-user-info'); } // Administrators have permission to change others emails, so don't limit those
```
Comment (rodrigok) [inline packages/rocketchat-lib/server/functions/setEmail.js]: Codacy Issue found: ['userId' is defined but never used.](https://www.codacy.com/app/RocketChat/Rocket-Chat/file/2334233417/issues/source?bid=3199634&fileBranchId=3208512#l35)

Comment (rodrigok) [inline packages/rocketchat-lib/server/functions/setEmail.js]: Codacy Issue found: ["userId" is defined but never used](https://www.codacy.com/app/RocketChat/Rocket-Chat/file/2334233417/issues/source?bid=3199634&fileBranchId=3208512#l35)
