### PR TITLE
fix: Notify user stream when enabling/disabling TOTP 2FA

### LINKED ISSUE #35184: Bug: UI not reflecting 2FA totp and email status change
### Description:

The UI does not update immediately after enabling or disabling two-factor authentication via both totp and email. The state is correctly updated in the backend, but the component does not re-render with the new state until the page is reloaded. This results in the UI showing the old 2FA status even after the action has been completed.

### Steps to reproduce:

1. Go to the 2FA settings page. (Profile -> Security)
2. Enable the 2FA for any totp or email (or "Disable" if already enabled).
3. Observe that the UI does not update immediately to reflect the new state.
4. A page reload is required to see the updated 2FA status.

### Expected behavior:

The UI should update immediately after enabling or disabling 2FA email to reflect the correct state without needing a page to reload.

### Actual behavior:

The UI does not immediately reflect the updated 2FA status. A page reload is required to see the new status.

Attaching Video for only one case:

https://github.com/user-attachments/assets/2de1a286-eb5a-46cd-bbc3-04abe21af586

### Server Setup Information:
- open.rocket.chat (which always runs in the latest)
- 7.3.1

### Client Setup Information

- Browser Version: Chrome
- Operating System: WSL2 - Ubuntu

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Issue(s)

Closes #35184

## Steps to test or reproduce

- Enable/Disable TOTP 2FA, changes should reflect in realtime.
## Further comments

[CORE-986](https://rocketchat.atlassian.net/browse/CORE-986)

[CORE-986]: https://rocketchat.atlassian.net/browse/CORE-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/meteor/client/views/account/security/TwoFactorTOTP.tsx [hunk 1]
```diff
@@ -117,6 +118,8 @@ const TwoFactorTOTP = (props: TwoFactorTOTPProps): ReactElement => {
 		setModal(<TwoFactorTotpModal onConfirm={onRegenerate} onClose={closeModal} />);
 	}, [closeModal, dispatchToastMessage, regenerateCodesFn, setModal, t]);
 
+	console.log({ user });
```
Comment (MarcosSpessatto) [inline apps/meteor/client/views/account/security/TwoFactorTOTP.tsx:121]:
```suggestion
```

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/account/security/TwoFactorTOTP.tsx (hunk 1 above)
Comment (yash-rajpal) [reply apps/meteor/client/views/account/security/TwoFactorTOTP.tsx]: Oops!! Removed it

**Review by dougfabris — CHANGES_REQUESTED** [review]
any test coverage on this one?

**Review by MarcosSpessatto — APPROVED** [review]
