### PR TITLE
[FIX] Leave and hide buttons was removed

### LINKED ISSUE #7872: LEAVE and HIDE channels buttons are missing on the new UI
image

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #7872 

image

### CODE REVIEW

File: packages/rocketchat-ui/client/views/app/popover.js [hunk 1]
```diff
@@ -129,5 +127,84 @@ Template.popover.events({
...
+		popover.close();
+		const { rid, name, template } = instance.data.data;
+
+		if (e.currentTarget.dataset.id === 'hide') {
+			let warnText;	
+			switch (template) {
+				case 'c': warnText = 'Hide_Room_Warning'; break;
+				case 'p': warnText = 'Hide_Group_Warning'; break;
+				case 'd': warnText = 'Hide_Private_Warning'; break;
+			}
```
Comment (geekgonecrazy) [inline packages/rocketchat-ui/client/views/app/popover.js]: What are we doing about livechat?  I have 2 rooms stuck open on mine that I can't hide or get rid of :joy:

Comment (karlprieb) [reply packages/rocketchat-ui/client/views/app/popover.js]: I'll add a warning text for livechat :)

Comment (geekgonecrazy) [reply packages/rocketchat-ui/client/views/app/popover.js]: \o/ awesome 🙂
