### PR TITLE
[FIX] Undefined MediaDevices error on HTTP

### LINKED ISSUE #26379: Unable to access server from certain interface after upgrade to 5.0.0
### Description:

Unable to access server from certain interface after upgrade to 5.0.0

### Steps to reproduce:
(This probably won't work in testing nor am I sure of a way to describe the steps)
### Expected behavior:
The app loads, and functions normally

### Actual behavior:

The interface fails to load and returns three possibly unrelated errors(described later) in the console.
image

### Server Setup Information:

- Version of Rocket.Chat Server: `5.0.0`
- Operating System: `Ubuntu 20.04.3 LTS`
- Deployment Method: `Manual installation`
- Number of Running Instances: `1`
- DB Replicaset Oplog: `enabled`
- NodeJS Version: `14.19.3`
- MongoDB Version: `5.0.5 wiredTiger`

### Client Setup Information

- Desktop App or Browser Version: Desktop App: `3.8.6`
- Operating System: `Windows 10`

### Additional context

Currently my installation is set up to be accessed across my local network, as well as through a Cloudflare Argo tunnel as required for usage of the Mobile app. Before upgrading the server to version 5.0.0, everything was functioning normally. After upgrading, I have become unable to access my instance from across my local network, while access through the Argo tunnel continues to function.
(local network)
image

(Argo tunnel)
image

### Relevant logs:

**Server**
```
{"level":35,"time":"2022-07-27T16:33:07.220Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/v1/commands.list","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":1} 
{"level":35,"time":"2022-07-27T16:33:07.391Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/apps/actionButtons","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":0} 
{"level":35,"time":"2022-07-27T16:33:07.393Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/apps/languages","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":0} 
{"level":35,"time":"2022-07-27T16:33:07.404Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/v1/roles.list","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":9} 
{"level":35,"time":"2022-07-27T16:33:07.411Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/v1/emoji-custom.list","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":5} 
{"level":35,"time":"2022-07-27T16:33:07.417Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/v1/banners?platform=web","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":8} 
{"level":35,"time":"2022-07-27T16:33:08.049Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":null,"userId":null,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":20,"time":"2022-07-27T16:33:08.087Z","pid":42850,"hostname":"rocket","name":"Callbacks","msg":"Executing callback with id 2fa for hook onValidateLogin"} 
{"level":20,"time":"2022-07-27T16:33:08.093Z","pid":42850,"hostname":"rocket","name":"Callbacks","msg":"Executing callback with id vnHMkYx9BPBoTTGqz for hook afterValidateLogin"} 
{"level":35,"time":"2022-07-27T16:33:08.097Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":null,"userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.108Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.109Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.110Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-roles","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.113Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-all","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.113Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-all","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.114Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.115Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.115Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.116Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.116Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.117Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.117Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.118Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.120Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.120Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.121Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.121Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.121Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.122Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-apps","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.122Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.123Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.123Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.124Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.124Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.126Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.127Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.127Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.128Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.128Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.129Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.129Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.130Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.130Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.131Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.131Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.134Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.134Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.135Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-all","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.136Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-logged","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.137Z","pid":42850,"hostname":"rocket","name":"Meteor","publication":"stream-notify-user","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.154Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/license%3AgetModules","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"95","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":0} 
{"level":35,"time":"2022-07-27T16:33:08.155Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"listCustomSounds","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.160Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/listCustomSounds","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"93","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":5} 
{"level":35,"time":"2022-07-27T16:33:08.163Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"apps/is-enabled","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.164Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/apps%3Ais-enabled","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"92","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":3} 
{"level":35,"time":"2022-07-27T16:33:08.166Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"listCustomUserStatus","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.174Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/license%3AisEnterprise","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"97","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":0} 
{"level":35,"time":"2022-07-27T16:33:08.176Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/listCustomUserStatus","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"97","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":10} 
{"level":35,"time":"2022-07-27T16:33:08.178Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"getUserRoles","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.181Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/getUserRoles","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"89","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":4} 
{"level":35,"time":"2022-07-27T16:33:08.211Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/v1/me","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":2} 
{"level":35,"time":"2022-07-27T16:33:08.221Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"UserPresence:online","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.227Z","pid":42850,"hostname":"rocket","name":"API","method":"GET","url":"/api/apps/languages","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":1} 
{"level":35,"time":"2022-07-27T16:33:08.248Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"rooms/get","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.252Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/rooms%3Aget","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"111","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":4} 
{"level":35,"time":"2022-07-27T16:33:08.279Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"autoTranslate.getProviderUiMetadata","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.279Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/autoTranslate.getProviderUiMetadata","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"113","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":0} 
{"level":35,"time":"2022-07-27T16:33:08.283Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"autoTranslate.getSupportedLanguages","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.285Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"UserPresence:online","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":null,"instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.289Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/autoTranslate.getSupportedLanguages","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"119","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":6} 
{"level":35,"time":"2022-07-27T16:33:08.299Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/cloud%3AcheckRegisterStatus","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"103","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":13} 
{"level":35,"time":"2022-07-27T16:33:08.356Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"subscriptions/get","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.358Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/subscriptions%3Aget","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"120","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":2} 
{"level":35,"time":"2022-07-27T16:33:08.421Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/permissions%3Aget","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"118","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":10} 
{"level":35,"time":"2022-07-27T16:33:08.477Z","pid":42850,"hostname":"rocket","name":"Meteor","method":"public-settings/get","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","instanceId":"356h2qH6Yew48FfCL"} 
{"level":35,"time":"2022-07-27T16:33:08.478Z","pid":42850,"hostname":"rocket","name":"API","method":"POST","url":"/api/v1/method.call/public-settings%3Aget","userId":"ToePJ5h7aiJhLNd5n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.6 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"122","host":"192.168.50.40:3000","referer":"http://192.168.50.40:3000/admin/info","remoteIP":"192.168.50.218","status":200,"responseTime":1} 
```
**Client**
```
07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124 TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at eval (:3000/client/providers/DeviceProvider/DeviceProvider.tsx:1:833)
    at lu (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:104532)
    at t.unstable_runWithPriority (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1142:3778)
    at _a (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:45381)
    at su (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:103995)
    at 07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:103906
    at R (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1142:2838)
    at MessagePort.v.port1.onmessage (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1142:1561)
Ti @ 07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124
07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1142 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at eval (:3000/client/providers/DeviceProvider/DeviceProvider.tsx:1:833)
    at lu (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:104532)
    at t.unstable_runWithPriority (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1142:3778)
    at _a (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:45381)
    at su (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:103995)
    at 07209f7aff72860ca8f6c4de51803a1e16f37033.js:1124:103906
    at R (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1142:2838)
    at MessagePort.v.port1.onmessage (07209f7aff72860ca8f6c4de51803a1e16f37033.js:1142:1561)
07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
```

### PR DESCRIPTION
**Pull request by MartinSchoeler**
Fixes #26379

### CODE REVIEW

File: apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx [hunk 1]
```diff
@@ -60,6 +60,11 @@ const DeviceSettingsModal = (): ReactElement => {
 						</Box>
 					</Box>
 				)}
+				{!isSecureContext && (
```
Comment (ggazzo) [inline apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx:63]: c'mon provide some error/info from the provider and dont spread the `isSecureContext` thats why you create this provider thats right?

File: apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx [hunk 2]
```diff
@@ -21,6 +21,13 @@ export const DeviceProvider = ({ children }: DeviceProviderProps): ReactElement
 		type: 'audio',
 	});
 
+	const setAudioInputDevice = (device: Device): void => {
+		if (!isSecureContext) {
+			throw new Error('Device Changes are not available on insecure contexts');
+		}
+		setSelectedAudioInputDevice(device);
+	};
+
```
Comment (ggazzo) [inline apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx:30]: I think we could handle this better this case errors, maybe setting some state 

also isSecureContext is not mutable so you could make the WHOLE provider behave differently if `false`, if it wasn't a safe environment, and not only guarantee that the functions won't break


btw at least do typeof isSecureContext && isSecureContext, we still have IE support

**Review by ggazzo — CHANGES_REQUESTED** [review]

File: apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx [hunk 3]
```diff
@@ -60,6 +67,11 @@ const DeviceSettingsModal = (): ReactElement => {
 						</Box>
 					</Box>
 				)}
+				{!useIsDeviceManagementEnabled && (
```
Comment (aleksandernsilva) [inline apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx:70]: Do you really want to verify is the hook exists?

**Review by aleksandernsilva — CHANGES_REQUESTED** [review]

File: apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx (hunk 3 above)
Comment (MartinSchoeler) [reply apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx]: Nope, fixed!

**Review by aleksandernsilva — APPROVED** [review]
