### PR TITLE
[FIX] DMs being created with username instead of user's name

### LINKED ISSUE #23093: [Bug] 4.1.2 does not show the real name of new users in several places.
### Description:

The option to use real name is checked from previous versions.

After upgrading to 3.18.0 new registered users do not show real name in several places.

On the top and left side bar the user is shown and the real name should be shown.

### Steps to reproduce:

1. Register a new user manually, also tested with users coming from LDAP

### Actual behavior:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: wiredTiger
- NodeJS Version: 12.22.1
- MongoDB Version: 4.4.8

### Additional context

@pierre-lehnen-rc and @ankar84

This issue is closely related to #19046 since version 3.9.3. The difference is that it now directly affects the new users who register in the system.

The option **Use real name** is updated correctly, even if the modification comes from LDAP, the only problem is that these values are not shown in the left column and in the title of the chat, however in the messages it is shown correctly.

### PR DESCRIPTION
**Pull request by gabriellsh**
## Issue(s)

closes #23093

### CODE REVIEW

**Comment by ankar84** [comment]
@gabriellsh hey!
What do you think is that PR fix that issue https://github.com/RocketChat/Rocket.Chat/issues/23093 ?
Or it fix different issue?

**Comment by gabriellsh** [comment]
> @gabriellsh hey! What do you think is that PR fix that issue #23093 ? Or it fix different issue?

hey @ankar84 ! Reading through that issue, I believe this is the fix. Thanks for the tip! I'll close it when this is merged.

**Review by dougfabris — APPROVED** [review]

**Review by sampaiodiego — COMMENTED** [review]
do you mind adding tests @gabriellsh ? 🤗 

thx for the fix anyways

File: tests/end-to-end/api/04-direct-message.js [hunk 1]
```diff
@@ -481,34 +485,55 @@ describe('[Direct Messages]', function() {
...
+			userCredentials = await login(user.username, password);
+			otherUserCredentials = await login(otherUser.username, password);
+			thirdUserCredentials = await login(thirdUser.username, password);
 		});
 
 		after(async () => {
-			if (roomId) {
-				await deleteRoom({ type: 'd', roomId });
-			}
+			Promise.all(Object.values(roomIds).map((roomId) => deleteRoom({ type: 'd', roomId })));
```
Comment (sampaiodiego) [inline tests/end-to-end/api/04-direct-message.js:515]:
```suggestion
			await Promise.all(Object.values(roomIds).map((roomId) => deleteRoom({ type: 'd', roomId })));
```

File: tests/end-to-end/api/04-direct-message.js [hunk 2]
```diff
@@ -517,35 +542,66 @@ describe('[Direct Messages]', function() {
...
+					expect(res.body.room).to.have.property('usernames').and.to.have.members([user.username]);
+					roomIds = { ...roomIds, self: res.body.room._id };
 				})
 				.end(done);
 		});
+
+		async function testRoomFNameForUser(credentials, rid, fullName) {
+			return request.get(api('subscriptions.getOne'))
+				.set(credentials)
+				.query({ roomId: rid })
```
Comment (sampaiodiego) [inline tests/end-to-end/api/04-direct-message.js:579]: being very picky here.. but since there is a `credentials` variable on the scope above, would be good to call this different to avoid confusion..

what about changing to `roomId` as well to make things cleaner 😬 

```suggestion
		async function testRoomFNameForUser(testCredentials, roomId, fullName) {
			return request.get(api('subscriptions.getOne'))
				.set(testCredentials)
				.query({ roomId })
```

File: tests/end-to-end/api/04-direct-message.js [hunk 3]
```diff
@@ -517,35 +542,66 @@ describe('[Direct Messages]', function() {
...
+				.expect('Content-Type', 'application/json')
+				.expect((res) => {
+					expect(res.body).to.have.property('success', true);
+					expect(res.body).to.have.property('subscription').and.to.be.an('object');
+					expect(res.body.subscription).to.have.property('fname', fullName);
+				});
+		}
+
+		describe('Rooms fullName', () => {
+			it('should be own user\'s name for self dm', async () => {
```
Comment (sampaiodiego) [inline tests/end-to-end/api/04-direct-message.js:590]:
```suggestion
			it('should be own user\'s name for self DM', async () => {
```

File: tests/end-to-end/api/04-direct-message.js [hunk 4]
```diff
@@ -517,35 +542,66 @@ describe('[Direct Messages]', function() {
...
+				await testRoomFNameForUser(userCredentials, roomIds.self, userFullName);
+			});
+
+			it('should be other user\'s name concatenated for multiple users\'s dm for every user', async () => {
```
Comment (sampaiodiego) [inline tests/end-to-end/api/04-direct-message.js:594]:
```suggestion
			it('should be other user\'s name concatenated for multiple users\'s DM for every user', async () => {
```

File: tests/end-to-end/api/04-direct-message.js [hunk 5]
```diff
@@ -517,35 +542,66 @@ describe('[Direct Messages]', function() {
...
+				await testRoomFNameForUser(userCredentials, roomIds.multipleDm, [otherUserFullName, thirdUserFullName].join(', '));
+				await testRoomFNameForUser(otherUserCredentials, roomIds.multipleDm, [userFullName, thirdUserFullName].join(', '));
+				await testRoomFNameForUser(thirdUserCredentials, roomIds.multipleDm, [userFullName, otherUserFullName].join(', '));
+			});
+
+			it('should be other user\'s name for dm for both users', async () => {
```
Comment (sampaiodiego) [inline tests/end-to-end/api/04-direct-message.js:600]:
```suggestion
			it('should be other user\'s name for DM for both users', async () => {
```

**Review by sampaiodiego — CHANGES_REQUESTED** [review]
found a missing `await` on the `Promise.all` call..

added other suggestions for improving readability and consistency :)

**Comment by sampaiodiego** [comment]
oh, awesome job overall btw.. that's a single line fix that required a lot of tests to prove it works.. thanks for this great improvements

**Review by sampaiodiego — APPROVED** [review]

**Comment by a89h4ya** [comment]
#11598 says that the issue is also in 3.18. Shouldnt the fix be backported to that major version too?
