### PR TITLE
[FIX] Issue #7365: added check for the existence of a parameter in the CAS URL

### LINKED ISSUE #7365: CAS redirection: wrong postfix of the redirection
Rocket.Chat Version:  0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

The CAS redirection URL is built from `SSO Login URL` by adding a `?service=...`. This breaks when  `SSO Login URL` already has a parameter (in my case the URL is `https://example.com/cas/login?gateway=true`).

**The postfixing function should check whether no parameters exist in the base URL.**

### PR DESCRIPTION
**Pull request by wsw70**
@RocketChat/core 
Closes #7365

The fix checks whether the URL contains `?`, which means that the configured URL already has parameters(s). In that case instead of adding a `?`, a `&` will allow the chaining of parameters.

### CODE REVIEW

File: packages/rocketchat-cas/cas_client.js [hunk 1]
```diff
@@ -33,7 +33,12 @@ Meteor.loginWithCas = function(options, callback) {
 	}
 
 	const appUrl = Meteor.absoluteUrl().replace(/\/$/, '') + __meteor_runtime_config__.ROOT_URL_PATH_PREFIX;
-	const loginUrl = `${ login_url }?service=${ appUrl }/_cas/${ credentialToken }`;
+	// check if the provided CAS URL already has some parameters
+	if (login_url.split('?').length > 1) {
+		const loginUrl = `${ login_url }&service=${ appUrl }/_cas/${ credentialToken }`;
```
Comment (gdelavald) [inline packages/rocketchat-cas/cas_client.js]: There is a issue here, since const is block scoped it will not exist outside the if/else blocks, so I recommend using a 
> let loginurl = [else value here]
and then changing it in case the if condition is true.
