### PR TITLE
fix: #31722 roomName is not getting update 

### LINKED ISSUE #31722: Unable to change room names
### Description:

On 2 snap installations I cannot change the names of existing rooms. When I edit the room name a message pops up saying it was successful, though it does not actually update the name. They are both on the current version 6.6.0

### Steps to reproduce:

1. Go to workspace
2. Go to Rooms
3. Edit Room name
4. Change does not reflect

### Expected behavior:

It should update the room name on the front end

### Actual behavior:

The room name does not update 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 2

### PR DESCRIPTION
**Pull request by Pritam-sd-dev**
## Issue(s)

closes #31722

### CODE REVIEW

File: apps/meteor/client/views/admin/rooms/EditRoom.tsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ const EditRoom = ({ room, onChange, onDelete }: EditRoomProps) => {
 	const handleArchive = useArchiveRoom(room);
 
 	const handleUpdateRoomData = useEffectEvent(async ({ isDefault, roomName, favorite, ...formData }) => {
-		const data = getDirtyFields(formData, dirtyFields);
```
Comment (Pritam-sd-dev) [inline apps/meteor/client/views/admin/rooms/EditRoom.tsx:100]: since roomName is not passed due to which edit_room_name functionality was not working

File: apps/meteor/client/views/admin/rooms/EditRoom.tsx [hunk 2]
```diff
@@ -97,7 +97,7 @@ const EditRoom = ({ room, onChange, onDelete }: EditRoomProps) => {
...
+		const data = getDirtyFields({ isDefault, roomName, favorite, ...formData }, dirtyFields);
```
Comment (yash-rajpal) [inline apps/meteor/client/views/admin/rooms/EditRoom.tsx:100]: API doesn't accept `isDefault` field and that case is taken into account below, so this can cause errors when this field is update, I would suggest that we remove `isDefault` from here.

Comment (yash-rajpal) [inline apps/meteor/client/views/admin/rooms/EditRoom.tsx:100]: Case for updating `roomName` is also handled below, having it here would override that. I would suggest instead of overriding the roomName, better delete roomName from `data` object.

**Comment by Pritam-sd-dev** [comment]
@yash-rajpal 
thanks for correcting me, i got the point that why you have overriden my change
