### PR TITLE
[FIX] Add Authorization Bearer to allowed Headers

### LINKED ISSUE #8292: Curl : Error with Rest API + Sandstorm - Although login returns success
Hi,

I am using Rocket Chat  0.52  inside sandstorm and I have a [webkey](https://docs.sandstorm.io/en/latest/developing/http-apis/) for rocket chat and sandstorm and a user with username + passwort in rocket chat.
When calling  the REST API from curl for login, I get the success message, the Auth Token and the User ID.
However, on any other following call I always get the "you must be logged in to do this" error.
I tried several different endpoints and I always get the same error.
Any idea what is wrong? 

```
curl -H "Authorization: Bearer pj3zB0InEU72yaAIDrqJf-TqK0RR8QHBwcTC9fIi8aC" "http://api-65af6951d1056c4ace2e0e752b990945.tools.xxxxxxxxxx.de:44449/api/v1/login" -d "username=user&password=pwd"
{
  "status": "success",
  "data": {
    "authToken": "_FASwTWPDuj_LNbJJwurgAV9MhPyDk-6laPfORkOG5a",
    "userId": "6ozFJSS2LHreRNXaa"
  }

```
```
curl -H "Authorization: Bearer pj3zB0InEU72yaAIDrqJf-TqK0RR8QHBwcTC9fIi8aC" -H "X-Auth-Token: "_FASwTWPDuj_LNbJJwurgAV9MhPyDk-6laPfORkOG5a" -H "X-User-Id: 6ozFJSS2LHreRNXaa" "http://api-65af6951d1056c4ace2e0e752b990945.tools.xxxxxxxxxx.de:44449/api/v1/me"

{
  "status": "error",
  "message": "You must be logged in to do this."
}
```

### PR DESCRIPTION
**Pull request by Siedlerchr**
This should hopefully fix the problem described in  #8292 

@RocketChat/core 

Closes #8292

### CODE REVIEW

File: packages/rocketchat-api/server/api.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ class API extends Restivus {
 				if (RocketChat.settings.get('API_Enable_CORS') === true) {
 					this.response.writeHead(200, {
 						'Access-Control-Allow-Origin': RocketChat.settings.get('API_CORS_Origin'),
-						'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token'
+						'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token, Authorization: Bearer'
```
Comment (graywolf336) [inline packages/rocketchat-api/server/api.js]: Sorry, but I fail to see how this will fix anything. ` Bearer` is part of the `Authorization` header's value. So, removing that would maybe make it work...maybe I am wrong though. What are your thoughts? Have you tried both ways?

Comment (Siedlerchr) [reply packages/rocketchat-api/server/api.js]: I have outlined my idea behind and my tests behind this fix in the original issue: https://github.com/RocketChat/Rocket.Chat/issues/8292#issuecomment-332585692

Comment (graywolf336) [reply packages/rocketchat-api/server/api.js]: And I understand that, however for a header's key to be properly name it must not contain any spaces or symbols other than a hyphen. Thus, having `Authorization: Bearer` will be invalid and instead changing it to just `Authorization` will have the desired effect. For more information, please see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

Comment (Siedlerchr) [reply packages/rocketchat-api/server/api.js]: Thank you very much for your feedback. I looked a bit around and you are right, it seems that Authorization is the correct "header name". This [spec](https://fetch.spec.whatwg.org/#cors-non-wildcard-request-header-name) helped me understanding it.

**Comment by Siedlerchr** [comment]
Any updates if this can be merged?
