### PR TITLE
[FIX] Oembed request not respecting payload limit

### LINKED ISSUE #24395: posting direct download links to large files in chat hangs the server for a while
### Description:

Posting direct download links to large files in chat hangs the server for a while

### Steps to reproduce:

1. Open a conversation
2. Post URL to file to download
3. This shows up in the server log after a while (various minutes) during which server is completely unresponsive
```json
{"level":50,"time":"2022-02-02T15:10:31.656Z","pid":1,"hostname":"2a97f41cfad9","name":"","name":"System","msg":"OEmbed duplicated record 'https://github.com/balena-io/etcher/releases/download/v1.7.3/balenaEtcher-1.7.3.dmg'"}
```

### Expected behavior:

(maybe) when generating the chat preview and `content-type: application/octet-stream` header is found, don't go through with reading the response body?

### Actual behavior:

Attempting to send further messages fails (messages are grayed out), server becomes completely unresponsive for a while

### Server Setup Information:

- Version of Rocket.Chat Server: 
```
Version
4.4.0
Deployment ID
redacted
Apps Engine Version
1.30.0
Node Version
v14.18.3
Database Migration
253 (January 30, 2022 1:11 AM)
MongoDB
4.4.10 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (f32fdfb36)
Branch: HEAD
PID
1
```
- Operating System: debian bullseye container
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: see above
- NodeJS Version: see above
- MongoDB Version: see above

### Client Setup Information

- Desktop App or Browser Version: I posted the message from a Firefox 96 web client but every other user of the server was unable to interact with RocketChat for some time
- Operating System: any

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Issue(s)

Closes #24395

### CODE REVIEW

File: app/oembed/server/server.js [hunk 1]
```diff
@@ -108,17 +108,26 @@ const getUrlContent = async function (urlObj, redirectCount = 5) {
...
 
+	let totalSize = 0;
+	const chunks = [];
 	for await (const chunk of response.body) {
+		totalSize += chunk.length;
 		chunks.push(chunk);
+
+		if (totalSize > sizeLimit) {
+			SystemLogger.info({ msg: 'OEmbed request size exceeded', url });
+			break;
```
Comment (sampaiodiego) [inline app/oembed/server/server.js:125]: I didn't found any issue on breaking the async iterator loop this way.
not sure if this could produce a memory though

**Review by pierre-lehnen-rc — APPROVED** [review]
