### PR TITLE
fix: Favoriting room through rooms page

### LINKED ISSUE #31545: "Favorite" Setting in Room Settings Not Functioning
### Description:
When attempting to mark a room as a favorite in the room settings, the action does not produce any result. The room is not added to the favorites list, indicating a potential bug in the favorite room functionality.

### Steps to Reproduce:
1. Go to > Home > Customise > Rooms 
2. Click on any room > try to update favourite setting

### Expected Behavior:
When a room is marked as a favorite through the room settings, it should be added to the user's list of favorite rooms, easily accessible from the main interface.

### Actual Behavior:
After marking the 'Favorite' option in the room settings, the room is not added to the favorites list. There is no change in the interface, and the room remains unmarked as a favorite.

### Server Setup Information:
Version of Rocket.Chat Server: 6.6.0
Operating System: macOs
NodeJS Version: 14.21.4
MongoDB Version: 6.0.3

### Client Setup Information
Desktop App or Browser Version: Chrome 120
Operating System: macOs

### Additional Context

https://github.com/RocketChat/Rocket.Chat/assets/125182653/d27c10f4-51d5-4e24-9d3f-cba92882ba6a

### PR DESCRIPTION
**Pull request by shivang-16**
### Proposed changes 
Fixed a bug where the favorite field in the save room settings payload was being overridden by the favorite field returned from the getDirtyFields function. Consequently, this resulted in always sending the favorite field as undefined to the back-end. Deleting the field before building the payload solved the issue.

Demo gif:
rooms_favorite_regression

### Issue(s)
Closes #31545

### Steps to test or reproduce
Introduced here: #28318

1. Go to > Home > Customise > Rooms
2. Click on any room > try to update favourite setting

[WM-225](https://rocketchat.atlassian.net/browse/WM-225?atlOrigin=eyJpIjoiNjA3OGU4ZWVmMTAwNDc2MzlhZDk1ODdkODFlOTZmZDUiLCJwIjoiaiJ9)

[WM-225]: https://rocketchat.atlassian.net/browse/WM-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by shivang-16** [comment]
There is a problem occurring with retaining the favorite setting in room information. Upon investigation, it appears that there are issues with the data obtained from the API endpoint `'GET', '/v1/rooms.adminRooms.getRoom'`. Specifically, the favorite option is not included in the data retrieved from this API, causing difficulties in preserving the saved favorite setting.

**Comment by rique223** [comment]
> There is a problem occurring with retaining the favorite setting in room information. Upon investigation, it appears that there are issues with the data obtained from the API endpoint `'GET', '/v1/rooms.adminRooms.getRoom'`. Specifically, the favorite option is not included in the data retrieved from this API, causing difficulties in preserving the saved favorite setting. Screenshot 2024-01-27 at 3 28 33 AM
> 
> That's why when attempting to retain the value from the data obtained through the aforementioned API, the favorite option is not present.
> 
> Screenshot 2024-01-27 at 3 29 53 AM
> can anybody please help me with this issue??

Hey Shivang, thanks for your contribution. I did a small research on this but there's still some loose ends so I sent this issue to engineering and will get in touch as soon as I have some clarifications.

**Comment by shivang-16** [comment]
> > There is a problem occurring with retaining the favorite setting in room information. Upon investigation, it appears that there are issues with the data obtained from the API endpoint `'GET', '/v1/rooms.adminRooms.getRoom'`. Specifically, the favorite option is not included in the data retrieved from this API, causing difficulties in preserving the saved favorite setting. Screenshot 2024-01-27 at 3 28 33 AM
> > That's why when attempting to retain the value from the data obtained through the aforementioned API, the favorite option is not present.
> > Screenshot 2024-01-27 at 3 29 53 AM
> > can anybody please help me with this issue??
> 
> Hey Shivang, thanks for your contribution. I did a small research on this but there's still some loose ends so I sent this issue to engineering and will get in touch as soon as I have some clarifications.

okay and Thanks

**Comment by gabriellsh** [comment]
Hello, thanks for reporting this issue!

This `favorite` toggle on admin is NOT related to your favorite rooms. It behaves pretty much the same as the `default` toggle, in the sense that it will flag the rooms as favorite when new people join the workspace.

File: apps/meteor/client/views/admin/rooms/EditRoom.tsx [hunk 1]
```diff
@@ -117,9 +118,9 @@ const EditRoom = ({ room, onChange, onDelete }: EditRoomProps) => {
 		}
 	});
 
-	const handleSave = useMutableCallback(async (data) => {
-		await Promise.all([isDirty && handleUpdateRoomData(data), changeArchiving && handleArchive()].filter(Boolean));
-	});
+	const handleSave = useMutableCallback(async (data) =>
+		Promise.all([isDirty && handleUpdateRoomData(data), changeArchiving && handleArchive()].filter(Boolean)),
+	);
```
Comment (hugocostadev) [inline apps/meteor/client/views/admin/rooms/EditRoom.tsx:123]: remove the `async` from this fn since you removed the `await`

File: apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx [hunk 2]
```diff
@@ -119,9 +119,9 @@ const EditRoomInfo = ({ room, onClickClose, onClickBack }: EditRoomInfoProps) =>
 		}
 	});
 
-	const handleSave = useMutableCallback(async (data) => {
-		await Promise.all([isDirty && handleUpdateRoomData(data), changeArchiving && handleArchive()].filter(Boolean));
-	});
+	const handleSave = useMutableCallback(async (data) =>
+		Promise.all([isDirty && handleUpdateRoomData(data), changeArchiving && handleArchive()].filter(Boolean)),
+	);
```
Comment (hugocostadev) [inline apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx:124]: remove the `async` from this fn since you removed the `await`

File: apps/meteor/tests/e2e/administration.spec.ts [hunk 3]
```diff
@@ -87,6 +87,33 @@ test.describe.parallel('administration', () => {
...
+		test.describe.serial('Default rooms', () => {
+			test('expect target channell to be default', async () => {
+				await poAdmin.inputSearchRooms.type(targetChannel);
+				await poAdmin.getRoomRow(targetChannel).click();
+				await poAdmin.defaultLabel.click();
+				await poAdmin.btnSave.click();
+	
+				// The contextual bar closes after the save, because of that it has to be opened again
+				// Also, this flow assumes the data is not stale which can cause false positives
+				// TODO: If this feature is not removed in the future, Use api to check if the room is default for test optimization
```
Comment (hugocostadev) [inline apps/meteor/tests/e2e/administration.spec.ts:100]: no need for this comments, please, remove them

**Review by hugocostadev — APPROVED** [review]

**Review by hugocostadev — APPROVED** [review]
