### PR TITLE
[FIX] UI was not disabling the actions when users has had no permissions to create channels or add users to rooms

### LINKED ISSUE #10200: No indication that a user is not permitted to create public channels
### Description:

I revoked the permission to create public channels for certain user groups. The issue with this is, that there is no indicator that the user is not permitted to create a new public channel, the button is just not clickable. (and nothing happens)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Ubuntu Server 16.04.4 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 3
* DB Replicaset Oplog: YES

### Steps to Reproduce:

1. Revoke permission for users to create new public channels
2. Try to create a new public channel

### Expected behavior:

There should be a screen that says the user that he is not permitted to do so..

### Actual behavior:

Nothing happens.

### Relevant logs:

image

### LINKED ISSUE #10508: Permission's bug for creating channels
### Server Setup Information:

- Version of Rocket.Chat Server: 0.62.2
- Operating System: Linux, Debian 9
- Deployment Method(snap/docker/tar/etc): snap
- Number of Running Instances: 1
- DB Replicaset Oplog: none
- Node Version: v8.8.1

### Steps to Reproduce:

1. Make a role e.g. Client, uncheck all permissions, except "View Direct Messages" and View Joined Room
2. User with this role (Client) goes to "Directory" in the sidebar -> clicks " + " on the right and has a create room window, where can enter channel's name and invite users. But, while inviting users, autosuggestion can show nicknames of all people. In other cases, this user can not find any user, except direct messages.
3. Of course, this room won't be created due to permissions of this type of user.

### Expected behavior:

Do not show any other users in autosuggestion. Or, do not show button " + " for creating rooms by users who have not these type of permission.
For example, by adding another permission "Create Channel"

### PR DESCRIPTION
**Pull request by chuckAtCataworx**
Closes #10508
Closes #10200

This fix will
-Hide + icon in the top right of the directory to users who don't have permission to create channels and groups.
-If the user has only one of the two create room permissions (create-c, create-p), it will prevent user from changing between both room types. Only display the room type they can create.

-Hide addUser Icon in the flexTabBar if user doesn't have the permission to add user to any channel, or add user to joined room when in channels.
- Hide addUser Icon in the flexTabBar if user doesn't have the permission to add user to  any private group, or add user to joined room when in private groups.

-When the icon is removed the additional tab bar buttons are kept in their place, and not duplicated

### CODE REVIEW

File: packages/rocketchat-ui-flextab/client/flexTabBar.js [hunk 1]
```diff
@@ -188,15 +188,30 @@ Template.RoomsActionTab.helpers({
 		if (Template.instance().small.get()) {
 			return [];
 		}
+		let removedButton = false;
+		const canAddToChannel = RocketChat.authz.hasAllPermission('add-user-to-any-c-room');
+		const canAddToGroup = RocketChat.authz.hasAllPermission('add-user-to-any-p-room');
+		const canAddToJoinedRoom = RocketChat.authz.hasAllPermission('add-user-to-joined-room');
```
Comment (gdelavald) [inline packages/rocketchat-ui-flextab/client/flexTabBar.js]: Need to make sure the _room_ is created before he is able to `add-user-to-joined-room`.

File: packages/rocketchat-ui/client/views/app/createChannel.js [hunk 2]
```diff
@@ -258,7 +261,11 @@ Template.createChannel.onCreated(function() {
 	this.extensions_validations = {};
 	this.extensions_submits = {};
 	this.name = new ReactiveVar('');
-	this.type = new ReactiveVar('p');
+	if (!RocketChat.authz.hasAllPermission(['create-p'])) {
```
Comment (gdelavald) [inline packages/rocketchat-ui/client/views/app/createChannel.js]: 👍

File: packages/rocketchat-ui-flextab/client/flexTabBar.js (hunk 1 above)
Comment (chuckAtCataworx) [reply packages/rocketchat-ui-flextab/client/flexTabBar.js]: Yes. I think your comment on the createChannel.js file looks like you saw where that happens. I could take a look at how we use the add-user-to-joined-room permission. In this implementation this user must have both permissions 'add-user-to-any-c-room'('add-user-to-any-p-room' for groups) and 'add-user-to-joined-room' to view the 'add users' button. Perhaps it should only rely on the 'add-user-to-joined-room'? It is as simple as deleting the two const 'canAddToChannel' and 'canAddToGroup' then removing them from the if statement on line 202 and 206.

Comment (gdelavald) [reply packages/rocketchat-ui-flextab/client/flexTabBar.js]: Yep, checking the permissions page show that users do not have the `add-user-to-any-p-room` (same for `c`) by default, and only admins do. Also there could be cases where users don't have the `add-user-to-joined-room` permission (which would be weird, but could happen) and the former permission should overrule this one.
I'm doing some tests on the PR deployment to check for edge cases.

**Comment by gdelavald** [comment]
@chuckAtCataworx Since you are fixing this, would you feel like adding a check for the Invite Users button in the contextual tab bar?
image
The button is showing even though user doesn't have permissions to invite.

**Comment by chuckAtCataworx** [comment]
Sure, I can take a look at that

File: packages/rocketchat-ui/client/views/app/createChannel.html [hunk 3]
```diff
@@ -14,10 +14,12 @@ <h1 class="create-channel__title">{{_ "Create_A_New_Channel"}}</h1>
 				<div class="create-channel__switches">
 					<div class="rc-switch">
 						<label class="rc-switch__label" tabindex="-1">
-							<input type="checkbox" class="rc-switch__input" name="type" value="p" checked>
-							<span class="rc-switch__button">
-							<span class="rc-switch__button-inside"></span>
-						</span>
+							{{#if canCreateBothTypes}}
+								<input type="checkbox" class="rc-switch__input" name="type" value="p" checked>
```
Comment (ggazzo) [inline packages/rocketchat-ui/client/views/app/createChannel.html]: @chuckAtCataworx could you change this code to 

`<input type="checkbox" class="rc-switch__input" name="type" value="p" checked="{{helperTestingIfTypeEqualtoP}}" disabled="{{cantCreateBothTypes}}"/>`

File: packages/rocketchat-ui-flextab/client/flexTabBar.js [hunk 4]
```diff
@@ -188,15 +188,30 @@ Template.RoomsActionTab.helpers({
 		if (Template.instance().small.get()) {
 			return [];
 		}
+		let removedButton = false;
```
Comment (ggazzo) [inline packages/rocketchat-ui-flextab/client/flexTabBar.js]: you dont need this variable

File: packages/rocketchat-ui-flextab/client/flexTabBar.js [hunk 5]
```diff
@@ -188,15 +188,30 @@ Template.RoomsActionTab.helpers({
...
+		const canAddToJoinedRoom = RocketChat.authz.hasAllPermission('add-user-to-joined-room');
 		const buttons = RocketChat.TabBar.getButtons().filter(button => {
 			if (!Meteor.userId() && !this.anonymous) {
 				return false;
 			}
 			if (button.groups.indexOf(Template.instance().tabBar.currentGroup()) === -1) {
 				return false;
 			}
+			if (!canAddToJoinedRoom && !canAddToChannel && Template.instance().tabBar.currentGroup() === 'channel' && button.id === 'addUsers') {
+				removedButton = true;
```
Comment (ggazzo) [inline packages/rocketchat-ui-flextab/client/flexTabBar.js]: remove ;)

File: packages/rocketchat-ui-flextab/client/flexTabBar.js [hunk 6]
```diff
@@ -188,15 +188,30 @@ Template.RoomsActionTab.helpers({
...
+				return false;
+			}
+			if (!canAddToJoinedRoom && !canAddToGroup && Template.instance().tabBar.currentGroup() === 'group' && button.id === 'addUsers') {
+				removedButton = true;
```
Comment (ggazzo) [inline packages/rocketchat-ui-flextab/client/flexTabBar.js]: remove ;)

File: packages/rocketchat-ui-flextab/client/flexTabBar.js [hunk 7]
```diff
@@ -188,15 +188,30 @@ Template.RoomsActionTab.helpers({
...
+				return false;
+			}
 			return true;
 		});
+		if (removedButton) {
```
Comment (ggazzo) [inline packages/rocketchat-ui-flextab/client/flexTabBar.js]: remove ;)

File: packages/rocketchat-ui/client/views/app/createChannel.html (hunk 3 above)
Comment (ggazzo) [inline packages/rocketchat-ui/client/views/app/createChannel.html]: instead of `{{#if canCreateBothTypes}}` use
` <input type="checkbox" class="rc-switch__input" name="type" value="p" checked={{testIfTypeEqualP}} disabled="{{cantCreateBothTypes}}">`

File: packages/rocketchat-ui/client/views/app/createChannel.js (hunk 2 above)
Comment (ggazzo) [reply packages/rocketchat-ui/client/views/app/createChannel.js]:
```javascript this.type = new ReactiveVar(RocketChat.authz.hasAllPermission(['create-p']) ? 'p' : 'c')

File: packages/rocketchat-ui-flextab/client/flexTabBar.js (hunk 4 above)
Comment (chuckAtCataworx) [reply packages/rocketchat-ui-flextab/client/flexTabBar.js]: Removing this variable creates a potential issue. When the `add users` button isn't displayed, then `files list` gets duplicated. It stays in it's original `more` section and takes the place of the `add users` button

**Comment by chuckAtCataworx** [comment]
@ggazzo Thanks for reviewing! I updated what you asked, expect about the one variable removal. Not sure if keeping it as is, is an acceptable solution?

**Comment by ggazzo** [comment]
@chuckAtCataworx, are you sure about the bug?(because if yes I think we should have always a duplicate item...) we want 4 items on top, no matter with one, and we cant guarantee `invite user icon` will be always the 4th element =/

**Comment by ggazzo** [comment]
hey @chuckAtCataworx here we must insert your test again https://github.com/chuckAtCataworx/Rocket.Chat/blob/aee7a945b52ad28c2301b490e6f6ad14c46c9d2e/packages/rocketchat-ui-flextab/client/flexTabBar.js#L134 then I think we will have the duplicate bug no more.

**Comment by chuckAtCataworx** [comment]
Okay, that commit should fix the duplication error, while keeping 4 buttons displayed on top at for every room type

**Comment by chuckAtCataworx** [comment]
I noticed another issue, unrelated to this pull request. It would be pretty simple to fix it however. 
In this file `packages/rocketchat-lib/client/defaultTabBars.js` there is an error with the keyboard shorcuts not getting displayed in groups our directs. Checkout line 60 compared to line 51

``` RocketChat.TabBar.addButton({
	groups: ['channel', 'group', 'direct'],
	id: 'rocket-search',
	i18nTitle: 'Search_Messages',
	icon: 'magnifier',
	template: 'RocketSearch',
	order: 1
});

RocketChat.TabBar.addButton({
	groups: ['direct'],
	id: 'user-info',
	i18nTitle: 'User_Info',
	icon: 'user',
	template: 'membersList',
	order: 2
});

RocketChat.TabBar.addButton({
	groups: ['channel', 'group'],
	id: 'members-list',
	i18nTitle: 'Members_List',
	icon: 'team',
	template: 'membersList',
	order: 2,
	condition() {
		const rid = Session.get('openedRoom');
		const room = RocketChat.models.Rooms.findOne({
			_id: rid
		});

		if (!room || !room.broadcast) {
			return true;
		}

		return RocketChat.authz.hasRole(Meteor.userId(), ['admin', 'moderator', 'owner'], rid);
	}
});

RocketChat.TabBar.addButton({
	groups: ['channel', 'group'],
	id: 'addUsers',
	i18nTitle: 'Add_users',
	icon: 'user-plus',
	template: 'inviteUsers',
	order: 2
});


RocketChat.TabBar.addButton({
	groups: ['channel', 'group', 'direct'],
	id: 'uploaded-files-list',
	i18nTitle: 'Room_uploaded_file_list',
	icon: 'clip',
	template: 'uploadedFilesList',
	order: 3
});

RocketChat.TabBar.addButton({
	groups: ['channel', 'privategroup', 'directmessage'],
	id: 'keyboard-shortcut-list',
	i18nTitle: 'Keyboard_Shortcuts_Title',
	icon: 'keyboard',
	template: 'keyboardSdeabhortcuts',
	order: 4
});
```

**Comment by ggazzo** [comment]
@chuckAtCataworx yes, please do, and thanks for your contribution :)

**Comment by chuckAtCataworx** [comment]
Alright, It's pushed. That should be all
