### PR TITLE
[FIX] Compact view

### LINKED ISSUE #14322: View mode Compact no longer has timestamp and text on a single line
### Description:

We just got upgraded to 1.0.1. The view mode setting inside the user preferences stopped working. If I understand correctly, then no matter what the setting is, "Normal" is used.

### Steps to reproduce:

1. Go to Profile -> My Account -> Preferences
2. Set View Mode to "Compact"

### Expected behavior:

View mode changes to "Compact" mode, which is one line per chat entry.

### Actual behavior:

View mode stays at "Normal" mode, with separate lines for username/date and chat message.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.1
- Operating System: Linux
- Number of Running Instances: Multiple
- NodeJS Version: n/a
- MongoDB Version: n/a

### PR DESCRIPTION
**Pull request by MartinSchoeler**
Closes #14322

This restores the functionality of the compact view mode.

Screenshots:
<details>

Screen Shot 2019-09-19 at 15 56 13

RTL

Screen Shot 2019-09-19 at 16 00 20

### CODE REVIEW

File: app/ui-message/client/message.js [hunk 1]
```diff
@@ -172,6 +172,12 @@ Template.message.helpers({
 			return 'false';
 		}
 	},
+	isMultiline() {
```
Comment (ggazzo) [inline app/ui-message/client/message.js]: this approach will not work for all cases =/

Comment (MartinSchoeler) [reply app/ui-message/client/message.js]: Did some changes via CSS, can you check again?
