### PR TITLE
Only use "File Uploaded" prefix on files

### LINKED ISSUE #7645: "File Uploaded" in chat.postMessage API Calls
### Description:

Commit b84d06817f695e4c59acc75075e275fc06b5d1c9 modified packages/rocketchat-message-attachments/client/messageAttachment.html which prepends i18n "Attachment_File_Uploaded" to the title of chat.postMessage API calls which do not necessarily have actual file attachments.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: FreeBSD 11.0-RELEASE-p2
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: No
* Node Version: 4.8.3

### Steps to Reproduce:

1. POST chat.postMessage with the following payload:

```json
{
  "icon_emoji": ":robot:",
  "channel": "#projectmanagement",
  "attachments": [
    {
      "collapsed": false,
      "title": "[ProjectName] Task \"Test Task\" moved to Complete",
      "title_link": "https://test.link/projectId=12345",
      "text": "Line 1\nLine 2"
    }
  ]
}
```

### Expected behavior:

expected

### Actual behavior:

actual

### Relevant logs:

N/A

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #7645

### CODE REVIEW

File: packages/rocketchat-message-attachments/client/messageAttachment.js [hunk 1]
```diff
@@ -70,5 +70,10 @@ Template.messageAttachment.helpers({
 	},
 	injectIndex(data, previousIndex, index) {
 		data.index = `${ previousIndex }.attachments.${ index }`;
+	},
+
+	isFile() {
+		console.log(this.type === 'file');
```
Comment (sampaiodiego) [inline packages/rocketchat-message-attachments/client/messageAttachment.js]: oops

Comment (MartinSchoeler) [inline packages/rocketchat-message-attachments/client/messageAttachment.js]: oops indeed :smile:
