### PR TITLE
[FIX] Emoji detection at line breaks

### LINKED ISSUE #13059: Emote detection fails around linebreaks
### Description:

Emote detection fails around linebreaks.

### Steps to reproduce:

1. Open a chat, for example a direct message to yourself.
2. Send the following single, multi-line message, which contains no trailing or leading whitespace:

       :D foo :D bar :D baz :D quux :D
       :D this :D is :D a simple :D test :D
       without :D leading :D or :D trailing :D emote
       :D hello :D world :D

### Expected behavior:

The message is sent and all occurrences of `:D` get replaced by `😃`.

### Actual behavior:

The message is sent and *MOST* occurrences of `:D` get replaced by `😃`, *EXCEPT* those around the linebreaks.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0
- Operating System: dunno, shouldn't be relevant
- Deployment Method: dunno
- Number of Running Instances: 1, I guess, shouldn't be relevant
- DB Replicaset Oplog: dunno, shouldn't be relevant
- NodeJS Version: dunno
- MongoDB Version: dunno

### Additional context

I found this issue while using a private instance.  I'm just the end user, and have been told to direct any bug reports upstream.

### Relevant logs:

JS console log: `Loading: false` (nothing else; seems irrelevant)

Server log: unavailable; this is a private instance.  Shouldn't be relevant.

### PR DESCRIPTION
**Pull request by savish28**
Closes #13059 

Initially emojis at linebreaks were not detected.
rocketchat issue 13059 before

This PR solves the issue and now it looks like:
rocketchat issue 13059 after

Input given in both the cases:
:D foo :D bar :D baz :D quux :D
:D this :D is :D a simple :D test :D
without :D leading :D or :D trailing :D emote
:D hello :D world :D

(contains no trailing or leading whitespace)

### CODE REVIEW

File: packages/rocketchat-emoji/client/emojiParser.js [hunk 1]
```diff
@@ -49,6 +52,9 @@ callbacks.add('renderMessage', (message) => {
 
 		// apostrophe (') back to &#39;
 		message.html = message.html.replace(/\'/g, '&#39;');
+
+		// apostrophe ' <br> ' back to '<br>'
+		message.html = message.html.replace(/ <br> /g, '<br>');
```
Comment (sampaiodiego) [inline packages/rocketchat-emoji/client/emojiParser.js]: wondering if this could break other things as it will change *all* ` <br> ` to `<br>` and not *only* the previously changed ones.

Comment (savish28) [reply packages/rocketchat-emoji/client/emojiParser.js]: Initally all the '<br>' will change to ' <br> ' irrespective of anything in the input message. We are just reversing the process in which all the ' <br> ' will be reverted back to '<br>' in the input message.

Comment (savish28) [reply packages/rocketchat-emoji/client/emojiParser.js]: Initiall _all_ `<br>` were converted to ` <br> ` and in this step we are reversing the process. So the input message remains the same.

Comment (savish28) [reply packages/rocketchat-emoji/client/emojiParser.js]: @sampaiodiego Requesst for FInal review.

Comment (sampaiodiego) [reply packages/rocketchat-emoji/client/emojiParser.js]: right, that previous comment is obviously true :stuck_out_tongue:
