### PR TITLE
[FIX] Empty URL in user avatar doesn't show error and enables save

### LINKED ISSUE #20439: [BUG] Empty URL in user avatar doesn't show error and enables save
### Description:
When clicked on the URL button while setting avatar with an empty URL, it shows a loading image and enables us to save (which apparently causes no change in the avatar)

### Steps to reproduce:
See video

### Expected behavior:

It must show an error and the save button should be disabled.

### Actual behavior:

https://user-images.githubusercontent.com/64399555/105963551-231f7080-60a7-11eb-8e01-42b95d8cf4fd.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by im-adithya**
## Proposed changes (including videos or screenshots)

Added toast and disabled save.

## Issue(s)

This PR closes #20439 

https://user-images.githubusercontent.com/64399555/105963707-53ffa580-60a7-11eb-9e2f-c5bac5742bfd.mp4

### CODE REVIEW

File: client/components/avatar/UserAvatarEditor.js [hunk 1]
```diff
@@ -40,6 +42,10 @@ export function UserAvatarEditor({ currentUsername, username, setAvatarObj, sugg
 	const [clickUpload] = useFileInput(setUploadedPreview);
 
 	const clickUrl = () => {
+		if (avatarFromUrl === '') {
+			toastr.error('Please Enter a URL');
+			throw new Meteor.Error();
+		}
```
Comment (gabriellsh) [inline client/components/avatar/UserAvatarEditor.js:48]: We don't use `Meteor` and `toastr` directly on React components, we have a hook for `useToastMessageDispatch` for this. Btw, I think you should only disable the button, instead of showing a toast.

**Review by gabriellsh — CHANGES_REQUESTED** [review]

File: client/components/avatar/UserAvatarEditor.js (hunk 1 above)
Comment (im-adithya) [reply client/components/avatar/UserAvatarEditor.js]: I removed the toast and disabled the button now! Please review it :D

Comment (dougfabris) [reply client/components/avatar/UserAvatarEditor.js]: @im-adithya I think just stop the event isn't a nice user experience. We need to give some affordance to the user. Maybe we should use the hook that @gabriellsh mentioned or disable the action button if the URL field is empty.

Comment (im-adithya) [reply client/components/avatar/UserAvatarEditor.js]: Yes, @dougfabris, I've done the same; the test has failed due to the same regex error here as well.

**Review by dougfabris — APPROVED** [review]
