### PR TITLE
Fix: chat.react api not accepting previous emojis

### LINKED ISSUE #10286: [BUG] API chat.react is not working anymore
### Description:

The API `v1/chat.react` was being used in the development of the Android v2 and we're migrating our React method also to iOS. In 0.63.0-rc.1 it doesn't work anymore.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0-rc.1
* Operating System: Linux

### Logs (trying to react with :blush: emoji):

```
:method: POST
:path: /api/v1/chat.react
:authority: open.rocket.chat
:scheme: https
x-auth-token: (private information)
x-user-id: (private information)
content-type: application/json; charset=utf-8
content-length: 49
accept-encoding: gzip
user-agent: okhttp/3.10.0

{"messageId":"rapbr5GuaM5ZrGPvr","emoji":"blush"}

:status: 400
access-control-allow-origin: *
cache-control: no-store
content-encoding: gzip
content-type: application/json
date: Sun, 01 Apr 2018 00:29:38 GMT
pragma: no-cache
vary: Accept-Encoding
x-instance-id: rGYBHkzA5SDEEteHa
content-length: 99

{"success":false,"error":"Invalid emoji provided. [error-not-allowed]","errorType":"error-not-allowed"}
```

### Logs (trying to react with :rocket: emoji):

```
:method: POST
:path: /api/v1/chat.react
:authority: open.rocket.chat
:scheme: https
x-auth-token: (private information)
x-user-id: (private information)
content-type: application/json; charset=utf-8
content-length: 50
accept-encoding: gzip
user-agent: okhttp/3.10.0

{"messageId":"mWfp2fCQkwfbMBhW6","emoji":"rocket"}

:status: 400
access-control-allow-origin: *
cache-control: no-store
content-encoding: gzip
content-type: application/json
date: Sun, 01 Apr 2018 00:29:18 GMT
pragma: no-cache
vary: Accept-Encoding
x-instance-id: LKF4dXafsniMQkW9c
content-length: 99

{"success":false,"error":"Invalid emoji provided. [error-not-allowed]","errorType":"error-not-allowed"}
```

### PR DESCRIPTION
**Pull request by graywolf336**
@RocketChat/core 

Closes #10286

This happened because verification was added which checked if the emoji passed actually is one. However, this verification did not account for missing colons which has a very high chance to break existing systems.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@sampaiodiego @rodrigok important to get this one in.  Otherwise we break mobile apps, and aren't compatible with anything using the reaction api.

**Comment by sampaiodiego** [comment]
added tests to cover this regression.. pls review

File: packages/rocketchat-reactions/setReaction.js [hunk 1]
```diff
@@ -39,8 +39,6 @@ Meteor.methods({
 			return false;
 		}
 
-		reaction = `:${ reaction.replace(/:/g, '') }:`;
```
Comment (graywolf336) [inline packages/rocketchat-reactions/setReaction.js]: Heh I knew we had this code in place somewhere, but I just didn't open my eyes enough to see that it was a few lines below.
