### PR TITLE
[FIX] transfer message when tranferring room by Apps Engine

### LINKED ISSUE #23073: [BUG] New Chat Transfer: Transfer Room transferred the chat to undefined
### Description:

Transferring room to target agent by apps shows wrong transfer notification in the chat

image

### Steps to reproduce:

1. Transfer Chat to target agent by Apps Engine

### Expected behavior:

Notification shows with target agent name

### Actual behavior:

 `New Chat Transfer: Transfer Room transferred the chat to undefined`

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by cuonghuunguyen**
## Issue(s)
Closes #23073

### CODE REVIEW

File: app/apps/server/bridges/livechat.ts [hunk 1]
```diff
@@ -166,10 +166,28 @@ export class AppLivechatBridge extends LivechatBridge {
 			type,
 		};
 
+		let userId;
+		let transferredTo;
+
+		if (targetAgent?.id) {
+			const targetUser = Users.findOneByAppId(targetAgent.id, {});
```
Comment (KevLehman) [inline app/apps/server/bridges/livechat.ts:173]: Did you mean to use `fibdOneById` here instead?

**Review by KevLehman — CHANGES_REQUESTED** [review]

File: app/apps/server/bridges/livechat.ts (hunk 1 above)
Comment (murtaza98) [reply app/apps/server/bridges/livechat.ts:173]:
```suggestion
			const targetUser = Users.findOneById(targetAgent.id, { fields: { _id: 1, username: 1, name: 1 } });
```

Comment (cuonghuunguyen) [reply app/apps/server/bridges/livechat.ts]: Hi, I made the change, pls check it again

**Review by murtaza98 — APPROVED** [review]

**Review by KevLehman — APPROVED** [review]
