### PR TITLE
[FIX] Removed fields from User Info for which the user doesn't have permissions.

### LINKED ISSUE #20138: [BUG] Wrong information in user info page for non-admin users.
### Description:
While opening user info from list of members gives wrong information of Last Login and Created at if you are a non-admin user.

### Steps to reproduce:

1. Register as a non-admin user
2. Join any room and open members list from contexual bar
3. Click on any of the member

### Expected behavior:
Correct information should be displayed for both admin as well as non-admin users.

### Actual behavior:
Correct information is only displayed when a user is an admin.

https://user-images.githubusercontent.com/55157259/104119939-20a7e180-5359-11eb-9bd4-b4e78ac185d2.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:3.11.0-develop 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
I am working on it :)

### LINKED ISSUE #20394: Unable to list/get roles for other members as channel owner
### Description:
When trying to find out if a member in a channel is an owner or not, the field "roles" in user info of a member is empty. This concerns all channels, no matter if owner or only user of the channel. For my own user, the role is "user", no matter if I'm owner of the channel or not.

### Steps to reproduce:

1. create a channel and add some members
2. within the channel open members, by clicking on the members-icon
3. select a user, so the user info opens
4. check the roles

user-role

### Expected behavior:

roles for the user are listed

### Actual behavior:

roles are empty, for all users except mine
for my own user, the role is always "user", even if I'm owner of the channel (can set some users as owners, remove users, 

FWIW: it works for instance admins.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: linux, centos 7
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: Chrome 88.0.4324.96 and Firefox
- Operating System: Linux and Windows

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Removed LastLogin, CreatedAt and Roles for users who don't have permission.

https://user-images.githubusercontent.com/55157259/109381351-f2c62e80-78ff-11eb-9289-e11072bf62f8.mp4

## Issue(s)

Closes #20138
Closes #20394
## Further comments

In video second user is an Admin.

### CODE REVIEW

**Comment by Darshilp326** [comment]
@dougfabris Please review :smile:

File: client/views/room/contextualBar/UserInfo/index.js [hunk 1]
```diff
@@ -81,9 +81,10 @@ export const UserInfo = React.memo(function UserInfo({
 				<Info>{username}</Info>
 			</>}
 
-			<Label>{t('Last_login')}</Label>
-			<Info>{lastLogin ? timeAgo(lastLogin) : t('Never')}</Info>
-
+			{lastLogin && <>
+				<Label>{t('Last_login')}</Label>
+				<Info>{timeAgo(lastLogin)}</Info>
```
Comment (dougfabris) [inline client/views/room/contextualBar/UserInfo/index.js:86]: @Darshilp326 We need to find a way to verify when the user never did log in and when he's not allowed to see the last login

**Review by dougfabris — CHANGES_REQUESTED** [review]

File: client/views/room/contextualBar/UserInfo/index.js (hunk 1 above)
Comment (Darshilp326) [reply client/views/room/contextualBar/UserInfo/index.js:86]: Not able to get your point! :worried:

Comment (Darshilp326) [reply client/views/room/contextualBar/UserInfo/index.js:86]: @dougfabris Can you explain your point one more time so I can solve the issue?

Comment (dougfabris) [reply client/views/room/contextualBar/UserInfo/index.js:86]: I mean, the code before checks if we don't get `lastLogin`'s value we'll show 'Never'. At this point, we should find a way to verify if we're receiving an empty value or if we shouldn't show the value because of the permission

**Review by dougfabris — CHANGES_REQUESTED** [review]

File: client/views/room/contextualBar/UserInfo/index.js (hunk 1 above)
Comment (dougfabris) [reply client/views/room/contextualBar/UserInfo/index.js:86]: I mean, the code before checks if we don't get `lastLogin`'s value we'll show 'Never'. At this point, we should find a way to verify if we're receiving an empty value or if we shouldn't show the value because of the permission

Comment (Darshilp326) [reply client/views/room/contextualBar/UserInfo/index.js:86]: Ok got your point!

Comment (Darshilp326) [reply client/views/room/contextualBar/UserInfo/index.js:86]: That case would occur when the admin adds an user and that user has not logged in. Am I right?

Comment (Darshilp326) [reply client/views/room/contextualBar/UserInfo/index.js:86]: Sorry. Am I correct?

> That case would occur when the admin adds a new user and that user has not logged in. Am I right?

**Review by dougfabris — APPROVED** [review]

**Comment by suninuni** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/1202b45da1d60d06326c3692eb26e56fe6a222ed/app/lib/server/functions/getFullUserData.js#L94-L95

This caused a unexpected error when user is not found. @Darshilp326 @dougfabris 

```
{
    "success": false,
    "error": "Cannot set property 'canViewAllInfo' of undefined"
}
```

**Comment by dougfabris** [comment]
> https://github.com/RocketChat/Rocket.Chat/blob/1202b45da1d60d06326c3692eb26e56fe6a222ed/app/lib/server/functions/getFullUserData.js#L94-L95
> 
> This caused a unexpected error when user is not found. @Darshilp326 @dougfabris
> 
> ```
> {
>     "success": false,
>     "error": "Cannot set property 'canViewAllInfo' of undefined"
> }
> ```

@suninuni The issue you mentioned is already fixed: #23372
Thanks for reporting!
