### PR TITLE
[FIX] Notification not working for group mentions and not respecting ignored users

### LINKED ISSUE #11018: Desktop Notifications not appearing with "@all" or "@here"
### Description:

I've reproduced this bug on a newly installed server.
When doing an "@all" or "@here" mention in any public or private channel the desktop notification doesn't show, however when mentioning someone directly "@username" it does show.
Increasing the Setting (Admin > General > Notifications > Max Room Members Before Disabling All Message Notifications) doesn't fix the issue.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* Browser: Chrome 66.0.3359.181

### Steps to Reproduce:

1. Type a message with "@all" mention in the general channel 

### Expected behavior:

See a desktop notification on the other account

### Actual behavior:

Do not see the desktop notification on the other account

### PR DESCRIPTION
**Pull request by sampaiodiego**
Closes #11018

### CODE REVIEW

File: packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js [hunk 1]
```diff
@@ -199,11 +199,15 @@ function sendAllNotifications(message, room) {
 				[notificationField]: 'mentions',
 				'u._id': { $in: mentionIdsWithoutGroups }
 			});
+		} else if ((hasMentionToAll || hasMentionToHere) && !disableAllMessageNotifications) {
```
Comment (ggazzo) [inline packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js]: I like to make the small test before

File: packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js [hunk 2]
```diff
@@ -199,11 +199,15 @@ function sendAllNotifications(message, room) {
...
+			query.$or.push({
+				[notificationField]: 'mentions'
+			});
 		}
 
 		const serverField = kind === 'email' ? 'emailNotificationMode' : `${ kind }Notifications`;
 		const serverPreference = RocketChat.settings.get(`Accounts_Default_User_Preferences_${ serverField }`);
-		if ((room.t === 'd' && serverPreference === 'mentions') || (serverPreference === 'all' && !disableAllMessageNotifications)) {
+		if ((room.t === 'd' && serverPreference === 'mentions') || ((serverPreference === 'all' || hasMentionToAll || hasMentionToHere) && !disableAllMessageNotifications)) {
```
Comment (ggazzo) [inline packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js]: I think you changed the logic here I mean, 

(room.t === 'd' && serverPreference === 'mentions')  OR

Comment (sampaiodiego) [reply packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js]: yes we do.. because `serverPreference` can be `nothing`
