### PR TITLE
fix: login blocked after block time

### LINKED ISSUE #26828: User blocked = "Die Anmeldung wurde für diesen Benutzer vorübergehend gesperrt"
### Description:
See also #21158
Same Problem = "Login has been temporarily blocked for this User" = "Die Anmeldung wurde für diesen Benutzer vorübergehend gesperrt"

Unfortunately, it happens several times a year that a user is blocked. Even if username and password were entered correctly (because stored in the password list)!

The user enters username, password and TOTP and then the message "Login has been temporarily blocked for this User" is displayed.

At the moment I solve the problem by playing around with 
- Change user
- Change email address
- activate/deactivate "Verify User"
- enable/disable 2FA

At some point the user works again. Unfortunately I can't exactly reproduce the process because I'm just "playing around". 

Currently I use RC 5.1.0
Application engine version 1.34.0
Node version v14.20.0
Database migration 281 (September 6, 2022 11:10)
MongoDB 5.0.11 / wiredTiger (oplog Enabled)

Whereas all this information is secondary as the problem has been there for years.
And all details are also described in #21158

A solution approach as described by @benji1000 in [#21158#issuecomment-856884323 ](https://github.com/RocketChat/Rocket.Chat/issues/21158#issuecomment-856884323) would be to aim for.
image

### PR DESCRIPTION
**Pull request by sampaiodiego**
## Issue(s)

Closes #27212
Closes #26828
[TC-183](https://rocketchat.atlassian.net/browse/TC-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)

## Further comments

[TC-183]: https://rocketchat.atlassian.net/browse/TC-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MarcosSpessatto — APPROVED** [review]

**Review by matheusbsilva137 — APPROVED** [review]

File: apps/meteor/app/authentication/server/lib/restrictLoginAttempts.ts [hunk 1]
```diff
@@ -58,36 +57,42 @@ export const isValidLoginAttemptByIp = async (ip: string): Promise<boolean> => {
...
 	}
 
-	const lastAttemptAt = (await ServerEvents.findLastFailedAttemptByIp(ip))?.ts;
+	const minutesUntilUnblock = settings.get<number>('Block_Multiple_Failed_Logins_Time_To_Unblock_By_Ip_In_Minutes');
 
-	if (!lastAttemptAt) {
+	const lockoutTimeStart = addMinutesToADate(new Date(), minutesUntilUnblock * -1);
+	const lastSuccessfulAttemptAt = (await ServerEvents.findLastSuccessfulAttemptByIp(ip))?.ts;
+
+	// succesful logins should reset the counter
```
Comment (heitortanoue) [inline apps/meteor/app/authentication/server/lib/restrictLoginAttempts.ts:77]:
```suggestion
	// successful logins should reset the counter
```

**Review by heitortanoue — CHANGES_REQUESTED** [review]

**Review by heitortanoue — APPROVED** [review]

**Review by matheusbsilva137 — APPROVED** [review]

**Review by heitortanoue — APPROVED** [review]

**Review by ggazzo — APPROVED** [review]
