### PR TITLE
[FIX] Threads contextual bar button visible even with threads disabled

### LINKED ISSUE #14796: Disabling Threads doesn't hide the "Threads" button
### Description:

When disabling threads, the "Threads" button keeps showing on room actions bar (top right).

### Steps to reproduce:

1. Disable threads going into `Administration > Threads > Enable` and setting it to `False`.
2. Open a room.

### Expected behavior:

Do not see "Threads" button on the room actions bar.

### Actual behavior:

The button is present. On clicking on it, the "Threads" tab is shown empty on the contextual bar and an error toast is triggered with "Not allowed" message.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0-develop
- Operating System: MacOS Mojave
- Deployment Method: source code
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.2

### Additional context

Jun-12-2019 15-09-30

### PR DESCRIPTION
**Pull request by cesarmal**
Closes #14796
This change hides the Threads button when threads are disabled.

### CODE REVIEW

File: app/ui-flextab/client/tabs/inviteUsers.js [hunk 1]
```diff
@@ -138,9 +138,7 @@ Template.inviteUsers.onCreated(function() {
 	this.ac = new AutoComplete({
 		selector: {
 			item: '.rc-popup-list__item',
-			container: '.rc-popup-list__list',
```
Comment (MartinSchoeler) [inline app/ui-flextab/client/tabs/inviteUsers.js]: Can you explain why are these changes needed? The PR seems to work fine without this.

Comment (cesarmal) [reply app/ui-flextab/client/tabs/inviteUsers.js]: Sure. It was just a mistake. In the rush to submit a new fix, I chose the wrong branch and mixed the solutions to two different bugs. Now the fix to #14796 is the only remaining commit.

**Comment by zdumitru** [comment]
related PR - #14687
