### PR TITLE
[FIX] Add user object to responses in /*.files Rest endpoints

### LINKED ISSUE #10449: [BUG] REST /channels.files endpoint returns inconsistent data
The endpoint `/channels.files` return inconsistent data. It returns some different data from web, sometimes more files than the web does for the same channel. These "extra" files usually come with missing information, such as `userId`.

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Add user object to responses in /[groups, channels, im].files Rest endpoints.
Closes #10449.

### CODE REVIEW

File: packages/rocketchat-api/server/helpers/replaceUserIdKeyByUserObject.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+RocketChat.API.helperMethods.set('replaceUserIdKeyByUserObject', function _addUserToObject({ object, userId }) {
+	const { username, name } = RocketChat.models.Users.findOneById(userId);
+	if (object.hasOwnProperty('userId')) {
+		delete object.userId;
```
Comment (Hudell) [inline packages/rocketchat-api/server/helpers/replaceUserIdKeyByUserObject.js]: I'm not sure if removing the userId is a good idea, as it may break something that relies on it, but I tested the application and didn't find any problem.
