### PR TITLE
[FIX] Fix Join Channel Without Preview Room Permission

### LINKED ISSUE #7534: Joinning channel - users block on loading screen
Hi,

I have updated Rocket.Chat two days ago from 0.56.0 to 0.57.2. It was fine, even if the installation process is a bit complex on an offline server (internal company network without internet) because of npm use.

However, since two days my team knows issues to join public channel. In fact, we have chosen to disable channel preview for user (uncheck the box "preview-c-room"), but when a user wants to join a channel, loading is infinitely long. So users cannot join any new channel by themselves, but they can only be added by an administrator.

This issue only concern user when "preview-c-room" is disabled, because when I activate the preview for users, they can join any public channel without problem.

Thanks for your help,

Crivaledaz

Rocket.Chat Version: 0.57.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0 and 4.8.2 (I have tried both)
OS : Centos 7

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #7534

This bug was created on the coffeescript conversions.

### CODE REVIEW

File: packages/rocketchat-ui/client/lib/RoomHistoryManager.js [hunk 1]
```diff
@@ -51,11 +51,12 @@ export const RoomHistoryManager = new class {
 			typeName = (curRoomDoc != null ? curRoomDoc.t : undefined) + (curRoomDoc != null ? curRoomDoc.name : undefined);
 		}
 
-		return Meteor.call('loadHistory', rid, ts, limit, ls, function(err, result) {
+		Meteor.call('loadHistory', rid, ts, limit, ls, function(err, result) {
 			if (err) {
 				return;
 			}
 			let previousHeight;
+			const messages = result && result.messages || [];
```
Comment (ggazzo) [inline packages/rocketchat-ui/client/lib/RoomHistoryManager.js]: you can do it different, try it:
```javascript
const {messages = []} = result;
```

**Comment by MartinSchoeler** [comment]
@ggazzo Done!
