### PR TITLE
[FIX] Deleting message with store last message not removing

### LINKED ISSUE #9332: Deleting message with store last message not removing
### Description:

If you have store last message turned on and then delete last message... that message still is on the channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3

### Steps to Reproduce:

1. Turn on Store Last Message
2. Send a message
3. Delete that message

### Expected behavior:

Remove.  Or show something like message deleted or something

### Actual behavior:

Message stays

### PR DESCRIPTION
**Pull request by sampaiodiego**
@RocketChat/core 

Closes #9332

### CODE REVIEW

File: packages/rocketchat-lib/server/models/Messages.js [hunk 1]
```diff
@@ -284,9 +284,11 @@ RocketChat.models.Messages = new class extends RocketChat.models._Base {
 		return this.findOne(query);
 	}
 
-	getLastMessageSentWithNoTypeByRoomId(rid) {
+	getLastVisibleMessageSentWithNoTypeByRoomId(rid, messageId) {
 		const query = {
+			_id: { $ne: messageId },
```
Comment (geekgonecrazy) [inline packages/rocketchat-lib/server/models/Messages.js]: I assume this is safe?  if this is undefined will this have negative effects on this query?
