### PR TITLE
[FIX] Files list missing from popover menu when owner of room

### LINKED ISSUE #11105: Files List icon in private channels not visible when user is owner
### Description:

When a user is the **owner** or a **moderator** of a channel (privat and public) the icon for "List files" (paper clip icon) is replaced with the "Add User" icon. The "List files" icon is also not shown in the burger menu. 

### Steps to reproduce:

1. Create a channel or enter an existing private channel you are the owner of
2. upload some files (probably optional)
3. See no "List files" icon on the top right
noclip
4. Remove ownership of the channel from your user or enter channel as non-owner user
5. See paper clip icon on top right
clip

### Expected behavior:
The List files icon moves to the burger menu or is shown directly on top right

### Actual behavior:
The List files icon disappears

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.2
- MongoDB Version: 3.2.7

### PR DESCRIPTION
**Pull request by tassoevan**
Closes #11105 

Replacing `this` with `Template.instance()` in helpers fixed the problem.

### CODE REVIEW

File: packages/rocketchat-ui-flextab/client/flexTabBar.js [hunk 1]
```diff
@@ -73,69 +73,69 @@ Template.flexTabBar.helpers({
 		});
 	},
 
-	embeddedVersion() {
+	embeddVersion() {
```
Comment (ggazzo) [inline packages/rocketchat-ui-flextab/client/flexTabBar.js]: typo?

Comment (tassoevan) [reply packages/rocketchat-ui-flextab/client/flexTabBar.js]: Eww, a random deletion...
