### PR TITLE
[FIX] Auto hide Livechat room from sidebar on close

### LINKED ISSUE #11118: Auto-hide livechat room on close
### Expected Behaviour

When closing a livechat room, the room should be removed from the room list in the left sidebar. This option was available in past releases.

### Actual Behaviour

Livechat rooms are not removed when closing a room. It does not matter if you close the room via the Smarti widget nor the info panel. 

### Steps to Reproduce

1. Open new Livechat
2. Write anything
3. Close room by clicking on the button in the Smarti UI (or the close button in the info panel)
4. Room is still listed in the sidebar

### PR DESCRIPTION
**Pull request by knrt10**
Closes #11118 

cc @renatobecker would you please review

### CODE REVIEW

File: imports/message-read-receipt/server/hooks.js [hunk 1]
```diff
@@ -14,6 +14,10 @@ callbacks.add('afterSaveMessage', (message, room) => {
 
 	// mark message as read as well
 	ReadReceipt.markMessageAsReadBySender(message, room._id, message.u._id);
+
+	if (message.t === 'livechat-close') {
```
Comment (renatobecker) [inline imports/message-read-receipt/server/hooks.js]: This is not a good idea.
Let's check if the room is not closed before calling the method, like this:
```
	if (room && !room.closedAt) {
		Subscriptions.setAsReadByRoomIdAndUserId(room._id, message.u._id);
	}
```

But, to make it works fine, you will need to send an updated room object here:
 https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/lib/Livechat.js#L317

Comment (knrt10) [reply imports/message-read-receipt/server/hooks.js]: ok, let me update.
