### PR TITLE
Cache sync without oplog

### LINKED ISSUE #5212: Cannot read property 'onOplogEntry' of null (Database Bricked)
Your Rocket.Chat version: 0.49.0-develop

```
2016-12-13T23:08:42.980527+00:00 app[web.1]:     at require (packages/modules-runtime.js:106:16)
2016-12-13T23:08:42.980538+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:343:11
2016-12-13T23:08:42.980537+00:00 app[web.1]:     at Function.run (/app/.meteor/heroku_build/app/programs/server/profile.js:480:12)
2016-12-13T23:08:42.980536+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:128:5
2016-12-13T23:09:05.364725+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=(URL Had to censor) request_id=39f5ebf6-3835-4278-b310-00081832f6fd fwd="(IP Had to censor)" dyno= connect= service= status=503 bytes=
2016-12-13T23:09:35.738224+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-12-13T23:09:35.738352+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-12-13T23:09:35.866785+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-13T23:09:35.841403+00:00 heroku[web.1]: Process exited with status 137
```

### LINKED ISSUE #5309: OpLog is Disabled on Sandstorm apps.
Sandstorm apps run with OpLog: Disabled

This won't be supported on version 0.49.0 for performance.

image

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #5309 
Closes #5212

- [x] Do not load data when cache is disabled
- [x] Move room find to models (we are using subscriptions to find rooms when using cache)
- [x] Prevent infinity loop on join system when cache is disabled
- [x] Sync inserts
- [x] Sync updates
- [x] Sync upserts
- [x] Sync removals
- [x] Enable sync when oplog is not available
- [x] Add setting to force use sync instead of oplog (default false)
- [ ] Send statistics to datadog
- [x] Change travis to run tests with and without oplog?
- [x] Pass on tests

### CODE REVIEW

**Comment by engelgabriel** [comment]
@kentonv I hope you like this :)

**Comment by engelgabriel** [comment]
@jadeqwang @kentonv @paulproteus @jparyani your input is welcome here :)

**Comment by rodrigok** [comment]
Hey guys,

This PR is woking now, you can test it without oplog.

I'll implement some statistics and settings soon, but the mains goal is done, fell free to review and test the code.

🍾  Happy new Year for you all 😸

File: packages/rocketchat-lib/server/models/_BaseCache.js [hunk 1]
```diff
@@ -744,6 +747,154 @@ class ModelsBaseCache extends EventEmitter {
 		}
 	}
 
+	updateRecord(record, update) {
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/models/_BaseCache.js]: should we make clear we're compatible with a specific mongodb version? since we have now support to specific operators (e.g.: `$set`, `$unset`, `$min`, etc).

if mongodb adds a new operator, we'll have to add specific support to it, even if Meteor already supports.

Comment (rodrigok) [inline packages/rocketchat-lib/server/models/_BaseCache.js]: I don't think so. We should be updated with the latest mongodb version as we are now.
