### PR TITLE
[FIX] Emoticons not displayed in room topic

### LINKED ISSUE #6305: Allow emoji in channel topic
Rocket.Chat Version: 0.53.0

When setting a topic to `:thumbsup:` it should convert it into emoji, rather that just showing `:thumbsup:` in the channel topic.

### LINKED ISSUE #12696: Emoticons not displayed in room topic
Emoticons are not displayed in rooms topic when used, only the name or alias surrounded by period is displayed.

### PR DESCRIPTION
**Pull request by alexbartsch**
Closes #6305

### CODE REVIEW

File: packages/rocketchat-ui/client/components/header/header.js [hunk 1]
```diff
@@ -57,8 +57,21 @@ Template.header.helpers({
...
+		roomTopic = roomTopic.replace(/&#39;/g, '\'');
+
+		Object.keys(RocketChat.emoji.packages).forEach((emojiPackage) => {
+			roomTopic = RocketChat.emoji.packages[emojiPackage].render(roomTopic);
+		});
+
+		// apostrophe (') back to &#39;
+		roomTopic = roomTopic.replace(/\'/g, '&#39;');
+
+		return roomTopic;
```
Comment (marceloschmidt) [inline packages/rocketchat-ui/client/components/header/header.js]: I'd like this to be reviewed for possible XSS injection.

Comment (tassoevan) [reply packages/rocketchat-ui/client/components/header/header.js]: LGTM
