### PR TITLE
[FIX] Hide system message add/remove owner 

### LINKED ISSUE #16772: Hide "Was Set Role" messages doesn't work
### Description:

Hide "Was Set Role" messages doesn't work

### Steps to reproduce:

1. Set some users owner and moderator roles
2. Set **Hide System Messages** in channel settings
3. Set **Hide "Was Set Role" messages** in hide settings
4. Make sure that system messages are still in chat

### Expected behavior:

All expected system messages are hide when corresponding settings are set

### Actual behavior:

image
image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: CentOS
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: 2.17.7 and Chrome 80.0.3987.122
- Operating System: Windows 10 1809

### PR DESCRIPTION
**Pull request by ggazzo**
closes #16772
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: server/startup/migrations/v193.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+		Rooms.update({ sysMes: { $in: ['subscription_role_added'] } }, {
+			$pull: {
+				sysMes: 'subscription_role_added',
+			},
+		}, { multi: true });
+		Rooms.update({ sysMes: { $in: ['subscription_role_removed'] } }, {
+			$pull: {
+				sysMes: 'subscription_role_removed',
+			},
+		}, { multi: true });
```
Comment (rodrigok) [inline server/startup/migrations/v193.js:27]:
```suggestion
		Promise.await(Rooms.col.updateMany({
			sysMes: 'subscription_role_added'
		}, {
			$set: {
				'sysMes.$': 'subscription-role-added',
			}
		}));

		Promise.await(Rooms.col.updateMany({
			sysMes: 'subscription_role_removed'
		}, {
			$set: {
				'sysMes.$': 'subscription-role-removed',
			},
		}));
```

File: server/startup/migrations/v193.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
+import { Migrations } from '../../../app/migrations/server';
+import { Rooms } from '../../../app/models/server';
```
Comment (rodrigok) [inline server/startup/migrations/v193.js:2]:
```suggestion
import { Rooms } from '../../../app/models/server/raw'
```
