### PR TITLE
[FIX] Emails' logo and links

### LINKED ISSUE #12230: Emails do not render in outlook (starting with 0.70 I believe)
### Description:

I believe the email changes in 0.70 release have caused mails to not render well in outlook.

image

### Steps to reproduce:

DM someone while they are away and they receive an email that does not look complete.

### Expected behavior:

Complete looking email.

### Actual behavior:

See screenshot above.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.70
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### LINKED ISSUE #12231: Footer links on the new emails are broken
### Description:

None of the footer links are working, they've spaces after the protocol.

```
<!-- FOOTER --><table class=3D"wrap" style=3D"width: 100%; =
clear: both;"><tr><td class=3D"container" style=3D"display: block; =
max-width: 640px; margin: 0 auto; clear: both; border-radius: 2px;"><!-- =
content --><div class=3D"content" style=3D"list-style-position: inside; =
padding: 36px;"><table width=3D"100%"><tr><td align=3D"center" =
class=3D"social" style=3D"font-size: 12px;"><a href=3D"https: //rocket.=
chat/blog" style=3D"color: #1D74F5; font-weight: bold; text-decoration: =
none; line-height: 1.8; padding-left: 2px; padding-right: 2px;">Blog</a> | =
<a href=3D"https: //github.com/RocketChat" style=3D"color: #1D74F5; =
font-weight: bold; text-decoration: none; line-height: 1.8; padding-left: =
2px; padding-right: 2px;">Github</a> | <a href=3D"https: //www.facebook.=
com/RocketChatApp" style=3D"color: #1D74F5; font-weight: bold; =
text-decoration: none; line-height: 1.8; padding-left: 2px; padding-right: =
2px;">Facebook</a> | <a href=3D"https: //www.instagram.com/rocket.chat" =
style=3D"color: #1D74F5; font-weight: bold; text-decoration: none; =
line-height: 1.8; padding-left: 2px; padding-right: =
2px;">Instagram</a></td></tr><tr><td align=3D"center"><h6 style=3D"margin: =
0 0 16px 0; font-weight: 500; font-size: 10px; color: #6c727A; line-height:=
 1.7;">=C2=A9 Rocket.Chat Technologies Corp.</h6><h6 style=3D"margin: 0 0 =
16px 0; font-weight: 500; font-size: 10px; color: #6c727A; line-height: 1.=
7;">Made with =E2=9D=A4=EF=B8=8F in =F0=9F=87=A7=F0=9F=87=B7 =
=F0=9F=87=A8=F0=9F=87=A6 =F0=9F=87=A9=F0=9F=87=AA =F0=9F=87=AE=F0=9F=87=B3 =
=F0=9F=87=AC=F0=9F=87=A7 =F0=9F=87=BA=F0=9F=87=B8 </h6></td></tr></table></=
div><!-- /content --></td></tr></table><!-- /FOOTER =
--></td></tr></table></body></html>
----_NmP-3f8311e7a7f74d41-Part_1--
```

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #12230
Closes #12231
This pr doesnt fix the broken logo but fix other problems

### CODE REVIEW

File: packages/rocketchat-lib/server/startup/email.js [hunk 1]
```diff
@@ -129,13 +129,13 @@ RocketChat.settings.addGroup('Email', function() {
...
+		this.add('Email_Header', '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><!-- If you delete this tag, the sky will fall on your head --><meta name="viewport" content="width=device-width" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Rocket.Chat Cloud</title></head><body bgcolor="#F7F8FA"><table class="body" bgcolor="#F7F8FA" width="100%"><tr><td><!-- HEADER --><table class="wrap" bgcolor="#F7F8FA"><tr><td class="header container"><div class="header-content"><table bgcolor="#F7F8FA" width="100%"><tr><td><img src="[Site_Url]/assets/logo" alt="Rocket.chat-logo" width="150px" /></td></tr></table></div></td></tr></table><!-- /HEADER --></td></tr><tr><td><!-- BODY --><table class="wrap"><tr><td class="container" bgcolor="#FFFFFF"><div class="content"><table><tr><td>', {
```
Comment (tassoevan) [inline packages/rocketchat-lib/server/startup/email.js]: `` `alt` attribute value should be `Rocket.Chat`, the same textual content inside the logo.

Comment (sampaiodiego) [reply packages/rocketchat-lib/server/startup/email.js]: fixed =)
