### PR TITLE
[FIX] SAML is flooding logfile

### LINKED ISSUE #7107: SAML is flooding logfile
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: 4.5

I've set debug to false in ./programs/server/packages/steffo_meteor-accounts-saml.js, but on each login a lot of stuff is logged into logfile (e.g. certificates, the complete SAML result). Global Rocket.Chat log is set to errors only

```
        Accounts.saml = {                                                                                                   // 5
                settings: {                                                                                                        // 6
                        debug: false,  
```

Ciao!

### PR DESCRIPTION
**Pull request by Hudell**
Closes #7107

### CODE REVIEW

File: packages/meteor-accounts-saml/saml_server.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ import _ from 'underscore';
 if (!Accounts.saml) {
 	Accounts.saml = {
 		settings: {
-			debug: true,
+			debug: false,
```
Comment (rodrigok) [inline packages/meteor-accounts-saml/saml_server.js]: Can you transform this in a setting? That way it's possible to enable it in production env

Comment (Hudell) [reply packages/meteor-accounts-saml/saml_server.js]: Done
