### PR TITLE
[FIX] Nested Markdown blocks not parsed properly

### LINKED ISSUE #11656: code after quote scrambles the code (also in code fences)
### Description:

Posting code directly after a quoted text scrambles it.

### Steps to reproduce:

1. Go to a channel
2. Post a quote + `window.location.reload`
```
> some quote
`window.location.reload();`
```

### Expected behavior:

> some quote

`window.location.reload();`

### Actual behavior:

> some quote

=!=JzaQxzAZZDpLZ4AvK=!=

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System:Ubuntu 16.04.4 `Linux version 4.4.0-87-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017`
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### PR DESCRIPTION
**Pull request by Hudell**
Closes #11656

It also affects #12996, but doesn't fix it completely.

### CODE REVIEW

File: packages/rocketchat-markdown/lib/markdown.js [hunk 1]
```diff
@@ -45,13 +45,31 @@ class MarkdownClass {
 		return parsers.original(message);
 	}
 
-	mountTokensBack(message, useHtml = true) {
-		if (message.tokens && message.tokens.length > 0) {
-			for (const { token, text, noHtml } of message.tokens) {
-				message.html = message.html.replace(token, () => (useHtml ? text : noHtml)); // Uses lambda so doesn't need to escape $
+	mountTokensBackRecursively(message, tokenList, useHtml = true) {
```
Comment (rodrigok) [inline packages/rocketchat-markdown/lib/markdown.js]: Can we add unit tests that replicates the problem?
