### PR TITLE
feat: Setting for enabling files encryption and fix whitelist media types stopping E2EE uploads

### LINKED ISSUE #32963: File upload inside E2E channels / direct messages
### Description:

Since 6.10.0, file uploads no longer work inside e2e channels or direct messages.

### Steps to reproduce:

1. Open an e2e encrypted channel or direct message conversation.
2. Drag and drop or click on "Upload file."
3. Select an attachment of your choice, e.g., a PNG image.
4. Click on "Send"

### Expected behavior:

The file should be uploaded (unencrypted) to the server and sent to the recipient.

### Actual behavior:

The file upload keeps reappearing / nothing happens.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.2
- License Type: Starter
- Number of Users: 15
- Operating System: Debian 12
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 7.0.12

### Client Setup Information

- Desktop App or Browser Version: Brave 1.68.128 (Chromium: 127.0.6533.73)
- Operating System: macOS 14.5

### Additional context

- When E2E is temporarily disabled, the file upload works.
- Media type whitelist (/admin/settings/FileUpload): `image/*,audio/*,video/*,text/*,application/zip,application/x-rar-compressed,application/pdf,application/msword,application/vnd.openxmlformats-*,application/xml,application/json,application/vnd.apple.*,application/svg+xml`
- Storage type: GridFS

### Relevant logs:

Browser-Network Log
Request URL: "https://domain.tld/api/v1/rooms.media/Z9o42DDYLJrXFKbTkcdqxKMmTtttLFbK9J"
Status Code: 400

Response:
```
{
    "success": false,
    "error": "File type is not accepted. [error-invalid-file-type]",
    "errorType": "error-invalid-file-type"
}
```

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

E2EE files and uploads are uploaded as files of mime type `application/octet-stream` as we can't reveal the mime type of actual content since it is encrypted.

The server resolves the mime type of file as `application/octet-stream` but currently this doesn't play nicely with existing settings related to whitelisted and blacklisted media types.

E2EE files upload gets blocked if `application/octet-stream` is not a whitelisted media type.

This PR solves this issue by always accepting E2EE uploads even if `application/octet-stream` is not whitelisted but it will block the upload if `application/octet-stream` is black listed.

We also created a new setting for enabling/disabling encrypted uploads and mention this limitation in our settings description.
## Issue(s)

Closes #32963 
## Further comments

[CORE-614](https://rocketchat.atlassian.net/browse/CORE-614)

[CORE-614]: https://rocketchat.atlassian.net/browse/CORE-614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/meteor/tests/end-to-end/api/rooms.ts [hunk 1]
```diff
@@ -417,6 +417,7 @@ describe('[Rooms]', () => {
 				.split(',')
 				.filter((type) => type !== 'image/svg+xml')
 				.join(',');
+			console.log({ newBlockedMediaTypes, blockedMediaTypes });
```
[the remark this answers is not in the document]
Comment (yash-rajpal) [reply apps/meteor/tests/end-to-end/api/rooms.ts]: You're fast, lol

File: apps/meteor/server/settings/e2e.ts [hunk 2]
```diff
@@ -16,6 +16,14 @@ export const createE2ESettings = () =>
 			enableQuery: { _id: 'E2E_Enable', value: true },
 		});
 
+		await this.add('E2E_Enable_Encrypt_Files', true, {
+			type: 'boolean',
+			i18nLabel: 'E2E_Enable_Encrypt_Files',
+			i18nDescription: 'E2E_Enable_Encrypt_Files_Description',
```
Comment (matheusbsilva137) [inline apps/meteor/server/settings/e2e.ts:22]:
```suggestion
```
It should be ok to omit this

File: apps/meteor/tests/end-to-end/api/rooms.ts [hunk 3]
```diff
@@ -708,6 +708,78 @@ describe('[Rooms]', () => {
...
+					expect(res.body).to.have.property('message');
+					expect(res.body.message).to.have.property('files');
+					expect(res.body.message.files).to.be.an('array').of.length(1);
+					expect(res.body.message.files[0]).to.have.property('type', 'application/octet-stream');
+					expect(res.body.message.files[0]).to.have.property('name', 'diagram.drawio');
+				});
+		});
+
+		it('should fail encrypted file upload when files encryption is disabled', async () => {
+			await updateSetting('E2E_Enable_Encrypt_Files', false);
```
Comment (matheusbsilva137) [inline apps/meteor/tests/end-to-end/api/rooms.ts:749]: Can you please use `before` and `after` to set this setting's value to true?

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]
Also, can you please link this PR to a task?

File: apps/meteor/server/settings/e2e.ts (hunk 2 above)
Comment (yash-rajpal) [reply apps/meteor/server/settings/e2e.ts:22]: I think it should be okay to mention these properties, good to be explicit, especially for people who are new to this project and codebase.

File: apps/meteor/tests/end-to-end/api/rooms.ts (hunk 3 above)
Comment (yash-rajpal) [reply apps/meteor/tests/end-to-end/api/rooms.ts:749]: Doing so, will affect other tests in same block 🤔 

If we want to do that, maybe we should create a new describe block for this test.

File: apps/meteor/tests/e2e/e2e-encryption.spec.ts [hunk 4]
```diff
@@ -425,6 +425,147 @@ test.describe.serial('e2e-encryption', () => {
...
+
+				await test.step('send a test encrypted message to check e2ee is working', async () => {
+					await poHomeChannel.content.sendMessage('This is an encrypted message.');
+
+					await expect(poHomeChannel.content.lastUserMessageBody).toHaveText('This is an encrypted message.');
+					await expect(poHomeChannel.content.lastUserMessage.locator('.rcx-icon--name-key')).toBeVisible();
+				});
+
+				await test.step('send a text file in channel, file should not be encryption', async () => {
+					await poHomeChannel.content.dragAndDropTxtFile();
```
Comment (matheusbsilva137) [inline apps/meteor/tests/e2e/e2e-encryption.spec.ts:556]: Can you please add `application/octet-stream` to the blacklist just so that we're sure this file is not being mapped to the default type when file encryption is disabled? You could do that in the `before` block in this `describe` (and revert it back to the default value in an `afterAll`)
You did so in the last `describe`, but you have an `afterAll` that reverts it there

File: apps/meteor/tests/e2e/e2e-encryption.spec.ts [hunk 5]
```diff
@@ -425,6 +425,147 @@ test.describe.serial('e2e-encryption', () => {
...
+				await poHomeChannel.content.btnModalConfirm.click();
+
+				await expect(poHomeChannel.content.lastUserMessage.locator('.rcx-icon--name-key')).toBeVisible();
+				await expect(poHomeChannel.content.getFileDescription).toHaveText('any_description');
+				await expect(poHomeChannel.content.lastMessageFileName).toContainText('any_file1.txt');
+			});
+		});
+
+		test('File encryption with whitelisted and blacklisted media types', async ({ page, api }) => {
+			await test.step('create an encrypted channel', async () => {
```
Comment (matheusbsilva137) [inline apps/meteor/tests/e2e/e2e-encryption.spec.ts:464]:
```suggestion
			await test.step('create an encrypted room', async () => {
```
I believe it's not worth it to have distinct tests for groups and channels, so we couldhave a broader description here

File: apps/meteor/tests/e2e/e2e-encryption.spec.ts [hunk 6]
```diff
@@ -425,6 +425,147 @@ test.describe.serial('e2e-encryption', () => {
...
+			});
+
+			await test.step('set blacklisted media type setting to not accept application/octet-stream media type', async () => {
+				expect((await api.post('/settings/FileUpload_MediaTypeBlackList', { value: 'application/octet-stream' })).status()).toBe(200);
+			});
+
+			await test.step('send text file again with blacklisted setting set, file upload should fail', async () => {
+				await poHomeChannel.content.dragAndDropTxtFile();
+				await poHomeChannel.content.descriptionInput.fill('message 3');
+				await poHomeChannel.content.fileNameInput.fill('any_file1.txt');
```
Comment (matheusbsilva137) [inline apps/meteor/tests/e2e/e2e-encryption.spec.ts:513]:
```suggestion
				await poHomeChannel.content.fileNameInput.fill('any_file2.txt');
```
just to make sure...

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: apps/meteor/tests/e2e/e2e-encryption.spec.ts (hunk 5 above)
Comment (yash-rajpal) [reply apps/meteor/tests/e2e/e2e-encryption.spec.ts:464]: I understand your concern here, but this is just a naming convention, channels are public rooms, we can't have encrypted "channels" as encrypted rooms can only be private groups.

Also, in code we refer to them everywhere as encrypted channels, so 🤷

**Review by matheusbsilva137 — APPROVED** [review]

File: apps/meteor/tests/e2e/e2e-encryption.spec.ts [hunk 7]
```diff
@@ -425,6 +425,149 @@ test.describe.serial('e2e-encryption', () => {
...
+				await poHomeChannel.sidenav.btnCreate.click();
+
+				await expect(page).toHaveURL(`/group/${channelName}`);
+
+				await poHomeChannel.dismissToast();
+
+				await expect(poHomeChannel.content.encryptedRoomHeaderIcon).toBeVisible();
+			});
+
+			await test.step('send a file in channel', async () => {
```
Comment (jessicaschelly) [inline apps/meteor/tests/e2e/e2e-encryption.spec.ts:451]:
```suggestion
			await test.step('send a file with description in channel', async () => {
```

**Review by matheusbsilva137 — APPROVED** [review]

**Review by rodrigok — COMMENTED** [review]
Mobile should handle this new setting as well
