### PR TITLE
[FIX] REST API OAuth services endpoint were missing fields and flag to indicate custom services

### LINKED ISSUE #10298: Add flag to indicate if service is custom in the endpoint settings.oauth
Add flag( `custom: true` ) to indicate if service is custom in the REST endpoint settings.oauth.

### LINKED ISSUE #10332: [IMPROVEMENT] REST API /settings.oauth missing many fields
Real-Time API:
```
    "mergeUsers" : false,
    "clientId" : "e16c620e65e27c6417b9",
    "identityTokenSentVia" : null,
    "scope" : "user",
    "custom" : true,
    "authorizePath" : "/login/oauth/authorize",
    "serverURL" : "https://github.com",
    "service" : "ouathhhh",
    "loginStyle" : "popup",
    "tokenSentVia" : "payload",
    "buttonColor" : "#13679A",
    "buttonLabelText" : "GitHub",
    "buttonLabelColor" : "#FFFFFF",
    "tokenPath" : "/login/oauth/access_token",
    "identityPath" : "https://api.github.com/user",
    "usernameField" : ""
```

REST API:
```
    "id": "Xcsm32mjTAHZfRQ4M"
    "appId" : "e16c620e65e27c6417b9",
    "name" : "ouathhhh",
    "buttonColor" : "#13679A",
    "buttonLabelText" : "GitHub",
    "buttonLabelColor" : "#FFFFFF"
```

We need all the other fields, especially for custom OAuth!

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Add oauth services missing fields and add field to indicate whether the oauth service is customized.
Closes #10298
Closes #10332
@rafaelks , @filipedelimabrito, @cardoso .

### CODE REVIEW

**Comment by filipedelimabrito** [comment]
Thank you @MarcosSpessatto! 👊

File: packages/rocketchat-api/server/v1/settings.js [hunk 1]
```diff
@@ -29,6 +29,30 @@ RocketChat.API.v1.addRoute('settings.public', { authRequired: false }, {
...
+
+			return oAuthServicesEnabled.map((service) => {
+				return {
+					id: service._id,
+					name: service.service,
+					appId: service.appId || service.clientId,
+					buttonLabelText: service.buttonLabelText || '',
+					buttonColor: service.buttonColor || '',
+					buttonLabelColor: service.buttonLabelColor || '',
+					custom: Boolean(service.custom)
```
Comment (graywolf336) [inline packages/rocketchat-api/server/v1/settings.js]: Can you explain why you're using `Boolean(service.custom)` here when we don't use it anywhere else?

Comment (MarcosSpessatto) [reply packages/rocketchat-api/server/v1/settings.js]: @graywolf336 to convert to Boolean if it is some value considered false by JS.

Comment (graywolf336) [reply packages/rocketchat-api/server/v1/settings.js]: @MarcosSpessatto Please reconsider another way, because if the string is `"false"` then it will result in a value of `true`: https://stackoverflow.com/a/264037

Comment (MarcosSpessatto) [reply packages/rocketchat-api/server/v1/settings.js]: Okay, I'm going to change the validation, but I don't agree that the string  'false'  should be considered Boolean, IMHO  'false' is a string and not a boolean, just as 'true' should be considered a string and not a boolean. So in both cases, casting a Boolean must be true. Why should I consider the string 'false'?

Comment (graywolf336) [reply packages/rocketchat-api/server/v1/settings.js]: You misunderstood what I was saying. If the value of `service.custom` is a string and the value is `'false'` then doing `Boolean(service.custom)` will result in `true` being the value instead of the expected `false`.

Comment (geekgonecrazy) [reply packages/rocketchat-api/server/v1/settings.js]: image
a non-empty string in javascript evaluates to true, regardless of content of string

Comment (MarcosSpessatto) [reply packages/rocketchat-api/server/v1/settings.js]: The question was, why store in the database a Boolean value as a string and not as Boolean, if you expect it to be Boolean, but @graywolf336  already explained that to me. Thanks.

**Comment by rafaelks** [comment]
Is this one good to go guys?
