### PR TITLE
[FIX] Drag and drop disabled when file upload is disabled

### LINKED ISSUE #7816: Drag and drop upload option displayed even when file uploads are disabled
### Description:

Drag and drop functionality still active even when file uploads have been disabled. The eventual file upload fails with an accurate error message (file uploads being disabled), but it would reduce user confusion / efficiency to not allow the upload process at all. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58

### Steps to Reproduce:

1. Disable file uploads in administration
2. Navigate to any channel (e.g. #general)
3. Drag a file onto the channel

### Expected behavior:

I would expect nothing to happen as file uploads have been disabled.

### Actual behavior:

I am shown a modal dialog and option to upload the file (which will always fail as file uploads are disabled).

### PR DESCRIPTION
**Pull request by mariaeduardacunha**
Closes #7816

Drag and Drop now is disabled when the File Upload is disabled.

### CODE REVIEW

File: app/ui/client/views/app/room.js [hunk 1]
```diff
@@ -586,6 +597,11 @@ export const dropzoneEvents = {
 
 		e.stopPropagation();
 
+		if (!userCanDrop() || !settings.get('FileUpload_Enabled')) {
```
Comment (MartinSchoeler) [inline app/ui/client/views/app/room.js]: I think here we can add the `!settings.get('FileUpload_Enabled')` to the `userCanDrop` instead of testing both

File: app/ui/client/views/app/room.js [hunk 2]
```diff
@@ -254,6 +254,17 @@ callbacks.add('enter-room', wipeFailedUploads);
 const ignoreReplies = getConfig('ignoreReplies') === 'true';
 
 Template.room.helpers({
+	dragAndDrop() {
+		return settings.get('FileUpload_Enabled') && 'dropzone--disabled';
+	},
+
+	isDisabled() {
```
Comment (MartinSchoeler) [inline app/ui/client/views/app/room.js]: We are already checking the `settings.get('FileUpload_Enabled')` on `dragAndDrop`. I believe with a bit of wording tweaks on the classes, we can use only one helper

File: app/ui/client/views/app/room.js (hunk 1 above)
Comment (MartinSchoeler) [reply app/ui/client/views/app/room.js]: Also, this check can be done earlier in the event, maybe right after removing the `over` class from the element

File: app/ui/client/views/app/room.html [hunk 3]
```diff
@@ -11,8 +11,8 @@
 				{{/headerRoom}}
```
Comment (MartinSchoeler) [inline app/ui/client/views/app/room.html]: You need to add this logic to the thread view as well https://github.com/RocketChat/Rocket.Chat/blob/fix-drag-drop/app/threads/client/flextab/thread.html#L14

Comment (mariaeduardacunha) [reply app/ui/client/views/app/room.html]: Done

File: app/ui/client/views/app/room.js (hunk 2 above)
Comment (mariaeduardacunha) [reply app/ui/client/views/app/room.js]: Done

File: app/ui/client/views/app/room.js (hunk 1 above)
Comment (mariaeduardacunha) [reply app/ui/client/views/app/room.js]: Done

File: app/ui/client/views/app/room.js [hunk 4]
```diff
@@ -253,7 +253,28 @@ callbacks.add('enter-room', wipeFailedUploads);
...
+	dragAndDrop() {
+		return settings.get('FileUpload_Enabled') && 'dropzone--disabled';
+	},
+
+	isDropzoneDisabled() {
+		return settings.get('FileUpload_Enabled') ? 'dropzone-overlay--enabled' : 'dropzone-overlay--disabled';
+	},
+
+	dragAndDropLabel() {
+		if (!userCanDrop) {
```
Comment (ggazzo) [inline app/ui/client/views/app/room.js]: should be `userCanDrop(this._id)`

File: app/ui/client/views/app/room.js (hunk 1 above)
Comment (ggazzo) [reply app/ui/client/views/app/room.js]: same here: `userCanDrop(this._id)`
