### PR TITLE
[FIX] Omnichannel session monitor is not starting

### LINKED ISSUE #18259: Omnichannel/Sessions chat closed not working
### Description:

Omnichannel/Sessions chat closed not working.
image

### Steps to reproduce:

1. In Admin/Omnichannel/Sessions, we have Livechat_agent_leave_action_timeout configured at 10 or 600 seconds.
2. We start a Livechat conversation between Guest1 and Agent1 (bot).
3. Guest1 closes Livechat (closes browser) so the conversation remains open.
4. We force a logout-login in Agent1, expecting that after 10 or 600 seconds, the conversation closes.

### Expected behavior:

After 10 or 600 seconds, Agent1 closes the conversation, so in Omnichannel/Chat History we will see:

image

### Actual behavior:

Expected behavior was working until Rocket.Chat 3.3.3. Since Rocket.Chat 3.4.0, nothing happens. The conversation reamains open:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Chrome 83.0.4103.116
- Operating System: Windows 10

### Additional context

As I mentioned before, this issue happens with 3.4.0, 3.4.1 and 3.4.2. We still have another server with 3.3.3 where we still have the expected behavior.

We also think that maybe this could be something similar to another issue https://github.com/RocketChat/Rocket.Chat/issues/18132 which started in 3.4.0 but was resolved in 3.4.1.

### Relevant logs:

N/A

### PR DESCRIPTION
**Pull request by renatobecker**
## Proposed changes
The Omnichannel session monitor wasn't being initiated due to bad implementation, there was a wrong type cast statement which was causing the issue.

## Issue(s)
CLOSES #18259

## How to test or reproduce

- Go to Omnichannel admin area
- Go to the `Sessions` section
- Set `Close` or `Forward` to `How to Handle Open Sessions When Agent Goes Offline` setting
- Set a valid value to the `How Long to Wait After Agent Goes Offline` setting
- Set the agent's status to `offline`
- Wait for the system to perform the selected action set on the `How to Handle Open Sessions When Agent Goes Offline` after the `How Long to Wait After Agent Goes Offline` is reached

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/livechat/server/lib/stream/agentStatus.ts [hunk 1]
```diff
@@ -17,17 +17,8 @@ settings.get('Livechat_agent_leave_action_timeout', (_key, value) => {
...
-	monitorAgents = value;
-});
-
-settings.get('Livechat_agent_leave_action', (_key, value) => {
-	if (typeof value !== 'string') {
-		return;
-	}
-	action = value;
+	monitorAgents = value !== 'none';
+	action = value as string;
```
Comment (sampaiodiego) [inline app/livechat/server/lib/stream/agentStatus.ts:21]: you don't need this type casting right?
```suggestion
	action = value;
```

Comment (sampaiodiego) [reply app/livechat/server/lib/stream/agentStatus.ts:21]: it is actually needed 🤦
