### PR TITLE
[FIX] Read Receipt for Livechat Messages fixed

### LINKED ISSUE #13302: Read Receipt for Livechat Messages is not showing information of livechat-guest
Rocketchat Version : 0.73

Steps to Reproduce
1. Enable Showing Detailed Message Read Receipts 
2. Start Livechat as a guest from any website having livechat script installed.
3. See the Read Receipt of that livechat message.
4. livechat-guest info is missing whereas it is fine for a RC user as per screenshot.

screenshot-demotest1 rampwin com-2019 01 31-20-43-46

### PR DESCRIPTION
**Pull request by knrt10**
Closes #13302
  
  Screenshot 2019-03-21 at 10 59 29 PM
  
  
  cc @renatobecker please review.

### CODE REVIEW

File: imports/message-read-receipt/server/lib/ReadReceipt.js [hunk 1]
```diff
@@ -81,6 +81,7 @@ export const ReadReceipt = {
 		return ReadReceipts.findByMessageId(message._id).map((receipt) => ({
 			...receipt,
 			user: Users.findOneById(receipt.userId, { fields: { username: 1, name: 1 } }),
```
Comment (renatobecker) [inline imports/message-read-receipt/server/lib/ReadReceipt.js]: On the `getReceipts` method the `message` is passed by parameter. We can check the message object to ensure that the message came from a Livechat user or not. If the `message.token` exists, then you need to get the `guest` by finding it with the `LivechatVisitors` model, as you can see below:

```suggestion
		user:  message.token? LivechatVisitors.findById(receipt.userId, { fields: { username: 1, name: 1 } }) : Users.findOneById(receipt.userId, { fields: { username: 1, name: 1 } }) ,
```

Comment (knrt10) [reply imports/message-read-receipt/server/lib/ReadReceipt.js]: Ok, let me update that.

File: imports/message-read-receipt/client/readReceipts.html [hunk 2]
```diff
@@ -6,7 +6,11 @@
 		<ul class="read-receipts">
 			{{#each receipts}}
 				<li class="read-receipts__user background-transparent-dark-hover">
-					{{> avatar username=user.username}}
+                                        {{#if user}}
```
[the remark this answers is not in the document]
Comment (knrt10) [reply imports/message-read-receipt/client/readReceipts.html]: @renatobecker  Do you want an avatar with guest name or username, cause if it is the guest name, it will change accordingly, otherwise it will always be **G**

[the remark this answers is not in the document]
Comment (renatobecker) [reply imports/message-read-receipt/client/readReceipts.html]: We don't have Avatars for Livechat users.
It's ok showing the default avatar as you just described.

File: imports/message-read-receipt/server/hooks.js [hunk 3]
```diff
@@ -13,7 +13,7 @@ callbacks.add('afterSaveMessage', (message, room) => {
 	Subscriptions.setAsReadByRoomIdAndUserId(room._id, message.u._id);
 
 	// mark message as read as well
-	ReadReceipt.markMessageAsReadBySender(message, room._id, message.u._id);
+	ReadReceipt.markMessageAsReadBySender(message, room._id, message.u._id, message.token);
```
Comment (renatobecker) [inline imports/message-read-receipt/server/hooks.js]: This is not a good approach.
The `token` needs to come from a specific Livechat Room Type method.
In addition, the `markMessageAsReadBySender` needs to expect an object, not a regular variable.

File: imports/message-read-receipt/server/lib/ReadReceipt.js [hunk 4]
```diff
@@ -40,7 +40,7 @@ export const ReadReceipt = {
 		updateMessages(roomId);
 	},
 
-	markMessageAsReadBySender(message, roomId, userId) {
+	markMessageAsReadBySender(message, roomId, userId, extraData) {
```
Comment (renatobecker) [inline imports/message-read-receipt/server/lib/ReadReceipt.js]:
```suggestion
	markMessageAsReadBySender(message, roomId, userId, extraData = {}) {
```

File: imports/message-read-receipt/server/lib/ReadReceipt.js [hunk 5]
```diff
@@ -63,6 +63,7 @@ export const ReadReceipt = {
 				userId,
 				messageId: message._id,
 				ts,
+				token: extraData,
```
Comment (renatobecker) [inline imports/message-read-receipt/server/lib/ReadReceipt.js]:
```suggestion
				...extraData,
```

File: imports/message-read-receipt/server/lib/ReadReceipt.js [hunk 6]
```diff
@@ -80,7 +81,7 @@ export const ReadReceipt = {
 	getReceipts(message) {
 		return ReadReceipts.findByMessageId(message._id).map((receipt) => ({
 			...receipt,
-			user: Users.findOneById(receipt.userId, { fields: { username: 1, name: 1 } }),
+			user: (receipt.token && !(Object.keys(receipt.token).length === 0 && receipt.token.constructor === Object)) ? LivechatVisitors.getVisitorByToken(message.token, { fields: { username: 1, name: 1 } }) : Users.findOneById(receipt.userId, { fields: { username: 1, name: 1 } }),
```
Comment (renatobecker) [inline imports/message-read-receipt/server/lib/ReadReceipt.js]:
```suggestion
			user: receipt.token ? LivechatVisitors.getVisitorByToken(receipt.token, { fields: { username: 1, name: 1 } }) : Users.findOneById(receipt.userId, { fields: { username: 1, name: 1 } }),
```

File: app/utils/lib/RoomTypeConfig.js [hunk 7]
```diff
@@ -264,4 +264,17 @@ export class RoomTypeConfig {
 		return false;
 	}
 
+	/**
+   * Get receipt's extra token for livechat users
```
Comment (renatobecker) [inline app/utils/lib/RoomTypeConfig.js]: These comments are related to Livechat stuff, not the default Room Type Config

File: app/utils/lib/RoomTypeConfig.js [hunk 8]
```diff
@@ -264,4 +264,17 @@ export class RoomTypeConfig {
...
+   * @param {object} message
+   * @return {object} Token for user
+   */
+	getReadReceiptsExtraData(message) {
+		if (!Meteor.isServer) {
```
Comment (renatobecker) [inline app/utils/lib/RoomTypeConfig.js]: Here the return will be always `return {}`;

Comment (knrt10) [reply app/utils/lib/RoomTypeConfig.js]: updated

Comment (renatobecker) [reply app/utils/lib/RoomTypeConfig.js]: @knrt10, are you sure? The code has not change to me.

File: imports/message-read-receipt/server/lib/ReadReceipt.js [hunk 9]
```diff
@@ -50,11 +51,12 @@ export const ReadReceipt = {
 		if (message.unread && message.ts < firstSubscription.ls) {
 			Messages.setAsReadById(message._id, firstSubscription.ls);
 		}
+		const extraData = roomTypes.getConfig('l').getReadReceiptsExtraData(message);
```
Comment (renatobecker) [inline imports/message-read-receipt/server/lib/ReadReceipt.js]: He discussed about it last week:
```suggestion
		const extraData = roomTypes.getConfig(room.t).getReadReceiptsExtraData(message);
```

You need to find the room and get the room type field:
const room = Rooms.findOneById(roomId, { fields: { t: 1 } });

**Comment by knrt10** [comment]
Rebased and updated, latest changes
