### PR TITLE
[FIX] Send Livechat back to Guest Pool

### LINKED ISSUE #7397: LiveChat Switch Department
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

There is a bug in switching dept.
Conversation closed is not noticed by agent and even after dept. change previous agent keeps on receiving messages. The department switching just doesn't work out perfectly.

### LINKED ISSUE #9278: Livechat return conversation to the pool if agent goes offline
### Description:
Currently if an agent goes offline you can only choose to close his opened livechats or forward them. Would be nice to have an option to send it back to the pool (when using Guest Pool routing method), so any other online agent can take it.

### LINKED ISSUE #11347: Error 404 when accepting new Live Chat request
### Description:

Updated from 0.64.2 to 0.66.0 then to 0.66.1. Same problem.
When accepting new LiveChat, error appears both in MacOSX app and in browser.

Error:404
Oops, page not found
Sorry, page you requested does not exists or was deleted!

### Steps to reproduce:

1. Start new live chat on the site and write first message
2. Operator clicks on new live chat from Incoming Livechats section.
3. Message appeared with user message and Take It! button.
4. Click button to accept new live chat. Error 404 appears instead of chat room.

### Expected behavior:

No 404 error. Chat room with user activated.

### Actual behavior:

Error:404
Oops, page not found
Sorry, page you requested does not exists or was deleted!

screenshot 2018-07-04 23 52 33

screenshot 2018-07-04 23 52 41

screenshot 2018-07-04 23 52 56

### Server Setup Information:

- Version of Rocket.Chat Server:  0.66.1
- Operating System: CentOS 7 x64
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.3 - x64
- MongoDB Version: v2.6.12

### Relevant logs:

[Error] TypeError: undefined is not an object (evaluating 'chatMessages[this._id].input=e.find(".js-input-message")')
	focus .js-input-message (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:251:66483)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:38104)
	_withTemplateInstanceFunc (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:37673)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:38076)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:27002)
	_withCurrentView (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:23080)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:26974)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:9124)
	dispatch (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1392774)
	trigger (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1420538)
	simulate (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1421043)
	n (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1421333)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:183:50411)
	_compute (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:43:2360)
	_recompute (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:43:2613)
	_runFlush (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:43:3809)
	a (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:1:2695)

There are nothing in server logs.

### PR DESCRIPTION
**Pull request by renatobecker**
Closes #7397 
Closes #9278 
Closes #11347

This PR fixes the `forward chat` in Livechat rooms when using the `Guest Pool` routing method. Until then, when a chat was redirected to a department, for example, it was being assigned to an agent randomly instead of returning to the pool.
In addition, it also fixes the #9278, having the same behaviour when an agent goes offline and the `Livechat_agent_leave_action` setting is set to `forward`.

### CODE REVIEW

File: packages/rocketchat-livechat/server/lib/Livechat.js [hunk 1]
```diff
@@ -307,7 +307,7 @@ RocketChat.Livechat = {
 
 	forwardOpenChats(userId) {
 		RocketChat.models.Rooms.findOpenByAgent(userId).forEach((room) => {
-			const guest = RocketChat.models.Users.findOneById(room.v._id);
+			const guest = LivechatVisitors.findOneById(room.v._id);
```
Comment (sampaiodiego) [inline packages/rocketchat-livechat/server/lib/Livechat.js]: oh... this is an important fix.

File: packages/rocketchat-livechat/server/methods/returnAsInquiry.js [hunk 2]
```diff
@@ -1,21 +1,56 @@
...
+
+		if (!room) {
+			throw new Meteor.Error('error-invalid-room', 'Invalid room', { method: 'livechat:returnAsInquiry' });
+		}
+
+		//When an user goes offline, for example, their user is no longer available
+		//In this case, an error is raised, so to avoid this the room user is instantiated
+		let user = Meteor.user();
+		if (!user) {
+			user = RocketChat.models.Users.findOne(room.servedBy._id);
```
Comment (sampaiodiego) [inline packages/rocketchat-livechat/server/methods/returnAsInquiry.js]: you cannot get the room agent at this point because on lines bellow you're validating if the user has permission..

on the validation bellow you **must** validate the logged in user who is performing the action.

Comment (sampaiodiego) [inline packages/rocketchat-livechat/server/methods/returnAsInquiry.js]: you cannot get the room agent at this point because on lines bellow you're validating if the user has permission..

on the validation bellow you **must** validate against the logged in user who is performing the action.

File: packages/rocketchat-livechat/server/methods/returnAsInquiry.js [hunk 3]
```diff
@@ -1,21 +1,56 @@
...
 		}
 
-		// //delete agent and room subscription
+		if (!user._id || !RocketChat.authz.hasPermission(user._id, 'view-l-room')) {
```
Comment (sampaiodiego) [inline packages/rocketchat-livechat/server/methods/returnAsInquiry.js]: if the `user` is `null` or `undefined` this will throw an error.

File: packages/rocketchat-livechat/server/methods/returnAsInquiry.js [hunk 4]
```diff
@@ -1,21 +1,56 @@
...
+				agentIds.push(agent.agentId);
+			});
+		}
+
+		//delete agent and room subscription
 		RocketChat.models.Subscriptions.removeByRoomId(rid);
 
 		// remove user from room
-		const username = Meteor.user().username;
+		const username = user.username;
```
Comment (sampaiodiego) [inline packages/rocketchat-livechat/server/methods/returnAsInquiry.js]: this **must** be the agent and not the logged in user.. imagine a situation where the manager is returning the livechat to the queue.

**Comment by renatobecker** [comment]
@sampaiodiego, all requested changes are made.

**Comment by sampaiodiego** [comment]
can you please fix the conflicts? thx
