### PR TITLE
fix: initial stuck client if root_url is wrong

### LINKED ISSUE #30931: 3 dots when trying to login - relating to SiteURL - and wrong Node.JS version
We are on Ubuntu 22.04.3 LTS on DigitalOcean, and used a SNAP install originally, and it was working great for a long time. But the chat server started having issues with RocketChat around 6.4.x, where we just saw the 3 dots upon trying to login (transferring from [www.derekandromaine.com](http://www.derekandromaine.com/) to dnrchat.dnrstudios.com for login). I found many others having this issue:

https://forums.rocket.chat/t/latest-rocketchat-snap-permanently-loading-3-dots/18095/11

https://forums.rocket.chat/t/rocket-chat-docker-server-running-but-page-stuck-on-the-three-dots-loading-page/17979/17

It sounds like version 6.4.3 had the problem, and 6.4.4 works for some, but 6.4.5 causes the problem again? And apparently with snap, every time the server restarts, it attempts an upgrade, so we go right to 6.4.5 upon a restart.

It seems to be relating to the SiteURL being changed by RocketChat back to defaults. Once I used the command below, and restarted, then I was able to get logged in:

sudo snap set rocketchat-server siteurl=https://dnrchat.dnrstudios.com/

But above doesn't work for everyone, so who knows.

Right now the site is functioning, but I also noticed that it's not using the correct Node.JS of 14.21.3. Mine is using 14.21.2 - as per what it says under Workspace > Deployment:

Deployment
Version
6.4.5
Deployment ID
xxxxdeleted-on-post
Apps Engine Version
1.41.0-alpha.312
Node Version
v14.21.2
Database Migration
303 (November 11, 2023 2:12 PM)
MongoDB
5.0.15 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (xxxxdeleted-on-post)
Branch: HEAD
PID
xxxxdeleted-on-post

I tried upgrading to the correct node.js by following "Option 3" on this page - and installing nvm to manage node.js:

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04

But after I clearly updated and ran: nvm install v14.21.3, then ran: nvm list, it shows me I'm running 14.21.3:

-> v14.21.3
default -> v14.21.3
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v14.21.3) (default)
stable -> 14.21 (-> v14.21.3) (default)
lts/* -> lts/iron (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.21.3
lts/gallium -> v16.20.2 (-> N/A)
lts/hydrogen -> v18.18.2 (-> N/A)
lts/iron -> v20.9.0 (-> N/A)

But then after doing a reboot of the server, then again confirming that the correct 14.21.3 is loaded, when I then launch rocketchat > workspace > deployment - it STILL shows me 14.21.2 is running?

So maybe I need to do something specific with snap, to get this updated?

Thanks for your help

### LINKED ISSUE #30990: RocketChat 6.4.x fails to load
### Description:

After upgrading from RocketChat version 6.3.3 to any of the 6.4 versions (actually tested with 6.4.0 and 6.4.6), it fails to load (or more accurately, it fails to display). Trying to access it show the three dots "spinner" and it stays stuck here.

### Steps to reproduce:

1. Start from a working 6.3 installation
2. Upgrade it to 6.4
3. Try to access it. If a tab (when viewing from a browser) or the desktop app was already open, refresh it.

### Expected behavior:

RocketChat should load properly

### Actual behavior:

When accessing it, it stays on the three dots spinner.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.0 and 6.4.6
- Operating System: Debian 12
- Deployment Method: Manual install from tarballs
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.11

### Client Setup Information

- Desktop App Version: 3.9.10
- Browser Version: Opera 104.0.4944.54
- Operating System: Windows 10

### Additional context

I already searched for similar issues and some also report being stuck on the 3 dots. As those mention the site URL it should be noted that this happens on a staging environment where the site URL stored in DB doesn't match the one actually used to access the instance.

### Relevant logs:

Server logs don't show anything of interest. Just the "SERVER RUNNING" box when startup finished and nothing more.

The clients on the other hand...
```
Uncaught (in promise) Error: Cannot find module '/client/polyfills/index.ts'
    at y (url_common.js:80:1)
    at g (url_common.js:80:1)
    at d.r [as require] (url_common.js:80:1)
    at d.x [as link] (verifyErrors.js:34:1)
    at verifyErrors.js:34:1
    at dynamics_browser.js:74:1
```
This might be related to meteor. I'm not sure how I can get its version but here what npm tells me:
```
rocketchat@server:~/rocketchat-6.4.0/programs/server$ npm list | grep meteor
meteor-dev-bundle@ /var/www/rocketchat/rocketchat-6.4.0/programs/server
├─┬ @meteorjs/reify@0.24.0
├── meteor-promise@0.9.0
```

### LINKED ISSUE #31169: Rocket Chat no Termina de Cargar
buenos dias

tengo el siguiente problema con el servidor rocket que no termina de cargar por la web, se queda la pantalla en gris y los errores que salen en el navegador son los siguientes:

Screenshot_20231206_110841

la version que tengo instalada es la siguiente y esta en ubuntu 22.

Screenshot_20231206_103510

### PR DESCRIPTION
**Pull request by debdutdeb**
closes #30990
closes #30931
closes #31169

### CODE REVIEW

File: apps/meteor/server/startup/initialData.js [hunk 1]
```diff
@@ -13,6 +13,20 @@ import { validateEmail } from '../../lib/emailValidator';
 import { addUserRolesAsync } from '../lib/roles/addUserRoles';
 
 Meteor.startup(async () => {
+	if (!Meteor.settings?.public) {
+		Meteor.settings = {
+			public: {},
+		};
+	}
+
+	if (Meteor.settings.public.packages) {
```
Comment (debdutdeb) [inline apps/meteor/server/startup/initialData.js:22]:
```suggestion
	if (!Meteor.settings.public.packages) {
```
Come on u stupid

**Review by geekgonecrazy — DISMISSED** [review]
This is extremely disruptive to brand new deployments.

Our 1-click installation images are all affected by this.  Because you can't access them with your browser at localhost but Rocket.Chat by default has localhost on root_url and site url

So they'll access at the public ip and it's broken.  Very bad first impression

**Review by KevLehman — APPROVED** [review]

**Comment by HassbergKliniken** [comment]
Hello,

I still have the 3 dots after the update.

It's a clean environment. I tested a lot with the ROOT_URL variable and also tested in MongoDB with the SITE_URL for examble:

```
mongosh
use rocketchat
db.rocketchat_settings.update({"_id" : "Site_Url"},{$set:{value:"<http://chat2:3000>"}})

```

I can rotate it however I want, the 3 dots remain.

Another idea what I can test?
