### PR TITLE
[FIX] Properly escape custom emoji names for pattern matching

### LINKED ISSUE #10925: [BUG] NEW Custom emojis not working after upgrade in chats.
### Description:
After upgrading Rocket.Chat from some version (can't remember exactly sorry, let's call it `0.5.late` (about 4 months ago) or `0.6.early` to newer ones `0.6.late`, at the same time of https://github.com/RocketChat/Rocket.Chat/pull/10171

I was hoping on it getting solved through many upgrades, or that someone else would have the problem (and that I wasn't uniquely having this issue) such that I could comment and add my information to it. But sadly I have not been able to find a ticket that seems to be pointing on the same issue.

I have always given permissions for everyone in the chat to add Emojis, and it has not been a special privilege for users.

### Server Setup Information:

* Version of Rocket.Chat Server: `0.65.0` (`:latest`) (`0.69.2` updated 2018-09-18)
* Operating System: `Fedora release 24 (Twenty Four)`
* Deployment Method(snap/docker/tar/etc): `Docker version 17.05.0-ce, build 89658be` 
* Number of Running Instances: `1`
* DB Replicaset Oplog: `disabled`
* Node Version: `v8.9.3`(inside docker container)
* mongoDB Version: `v3.0.15` (Mongo 3.0 docker container)

### Steps to Reproduce:
_This is just a guesstimate, and I am sorry that I do not know exactly if it is reproduceable in this way_ 

Setup an old setup with rocketchat from:
https://hub.docker.com/_/rocket.chat/
Guessing let's start with `0.60.0`.
Upgrade using newer versions.

Migrate to: 
https://hub.docker.com/r/rocketchat/rocket.chat/
(because this project was more updated, and thus for us would hopefully solve bugs faster)

See that old added emojis still work.

Try to add new emojis, and try to use them, probably not working?

### Expected behavior:
Expected behaviour would be that adding new custom emojis after upgrades would still work, no matter who add them and when they were added.
They should show up in chat as well as they do in the administration view.

### Actual behavior:
Adding new pictures works as expected, and are shown in the `Custom_emoji` administration page.
2018-05-29-111338_1810x570_scrot

But when using new emojis, they only show text, in all menus during chat.

But *old* emojis added ~4-3 months ago before upgrading do work still as intended.
2018-05-29-111622_1223x1130_scrot

### Relevant logs:
(There are no relevant logs)
```
20180528-15:24:24.123(0) Will load cache for users 
20180528-15:24:24.152(0) 13 records load from users 
20180528-15:24:24.154(0) Will load cache for rocketchat_room 
20180528-15:24:24.161(0) 56 records load from rocketchat_room 
20180528-15:24:24.161(0) Will load cache for rocketchat_subscription 
20180528-15:24:24.192(0) 155 records load from rocketchat_subscription 
20180528-15:24:24.193(0) Will load cache for rocketchat_settings 
20180528-15:24:24.250(0) 678 records load from rocketchat_settings 
20180528-15:24:26.075(0) Updating process.env.MAIL_URL 
20180528-15:24:26.501(0) Starting Email Intercepter... 
20180528-15:24:27.010(0) Will load cache for rocketchat_permissions 
20180528-15:24:27.013(0) 78 records load from rocketchat_permissions 
20180528-15:24:27.018(0) Will load cache for rocketchat_roles 
20180528-15:24:27.019(0) 12 records load from rocketchat_roles 
20180528-15:24:28.903(0) LocalStore: store created at  
20180528-15:24:28.904(0) LocalStore: store created at  
20180528-15:24:28.904(0) LocalStore: store created at  
20180528-15:24:29.435(0) Setting default file store to GridFS 
20180528-15:24:32.971(0) (rocketchat_migrations.js:160) Migrations: Migrating from version 119 -> 121
20180528-15:24:32.973(0) (rocketchat_migrations.js:160) Migrations: Running up() on version 120
20180528-15:24:32.990(0) (rocketchat_migrations.js:160) Migrations: Running up() on version 121
20180528-15:24:33.006(0) (rocketchat_migrations.js:160) Migrations: Finished migrating.
20180528-15:24:43.008(0) Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds. 
20180528-15:24:43.021(0) (rocketchat_migrations.js:160) Migrations: Not migrating, already at version 121
20180528-15:24:43.662(0) Updating process.env.MAIL_URL 
20180528-15:24:43.718(0) Using GridFS for custom sounds storage 
20180528-15:24:43.724(0) Using GridFS for custom emoji storage 
20180528-15:24:43.728(0) ufs: temp directory created at "/tmp/ufs" 
20180528-15:24:46.136(0) ➔ System ➔ startup 
20180528-15:24:46.137(0) ➔ +----------------------------------------+ 
20180528-15:24:46.138(0) ➔ |             SERVER RUNNING             | 
20180528-15:24:46.138(0) ➔ +----------------------------------------+ 
20180528-15:24:46.139(0) ➔ |                                        | 
20180528-15:24:46.139(0) ➔ |  Rocket.Chat Version: 0.65.0           | 
20180528-15:24:46.140(0) ➔ |       NodeJS Version: 8.9.3 - x64      | 
20180528-15:24:46.140(0) ➔ |             Platform: linux            | 
20180528-15:24:46.141(0) ➔ |         Process Port: 3000             | 
20180528-15:24:46.141(0) ➔ |             Site URL: https://slaptop  | 
20180528-15:24:46.141(0) ➔ |     ReplicaSet OpLog: Disabled         | 
20180528-15:24:46.142(0) ➔ |          Commit Hash: 6d6d8be980       | 
20180528-15:24:46.142(0) ➔ |        Commit Branch: HEAD             | 
20180528-15:24:46.143(0) ➔ |                                        | 
20180528-15:24:46.143(0) ➔ +----------------------------------------+ 
```

### PR DESCRIPTION
**Pull request by tassoevan**
Closes #10925

### CODE REVIEW

File: packages/rocketchat-emoji-custom/client/lib/emojiCustom.js [hunk 1]
```diff
@@ -128,7 +128,8 @@ RocketChat.emoji.packages.emojiCustom = {
 	list: [],
 
 	render(html) {
-		const regShortNames = new RegExp(`<object[^>]*>.*?<\/object>|<span[^>]*>.*?<\/span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|(${ RocketChat.emoji.packages.emojiCustom.list.join('|') })`, 'gi');
+		const emojisMatchGroup = RocketChat.emoji.packages.emojiCustom.list.map(RegExp.escape).join('|');
```
Comment (ggazzo) [inline packages/rocketchat-emoji-custom/client/lib/emojiCustom.js]: could you cache that result?
