### PR TITLE
Regression: Update checker not being disabled properly.

### LINKED ISSUE #18113: All Admins Received Unsolicited Direct Message From Rocket.Cat Bot
### Description:

This may fall under 'design flaw' but anyway.

Yesterday all the admins on my private rocket.chat server got a direct message from the bot (rocket.cat) about the 3.4.0 upgrade.

This is unacceptable.     This type of push notification should be, at best, an opt-in.

(This may be a repeat of https://github.com/RocketChat/Rocket.Chat/issues/18092 but that issue talks about e-mail.)

### Steps to reproduce:

Not applicable.

### Expected behavior:

I do not expect to get random, unsolicited messages from my own server.

### Actual behavior:

All admins got a random, unsolicited message on our private server.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: All
- Operating System: All

### Additional context

None

### Relevant logs:

Not applicable

### PR DESCRIPTION
**Pull request by pierre-lehnen-rc**
## Issue(s)

Closes #18113

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [X] I have added necessary documentation (if applicable)
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/version-check/server/index.js [hunk 1]
```diff
@@ -24,18 +25,24 @@ const addVersionCheckJob = () => {
...
+	Meteor.defer(() => {
+		if (settings.get('Register_Server') && settings.get('Update_EnableChecker')) {
+			checkVersionUpdate();
+		}
+	});
 });
 
-settings.get('Register_Server', (key, value) => {
-	if (value && SyncedCron.nextScheduledAtDate(jobName)) {
+settings.get(/(Register_Server)|(Update_EnableChecker)/, _.debounce(() => {
```
Comment (sampaiodiego) [inline app/version-check/server/index.js:35]: you don't need a capturing group =)
```suggestion
settings.get(/Register_Server|Update_EnableChecker/, _.debounce(() => {
```
