### PR TITLE
[FIX] Stop adding push messages to queue if push is disabled

### LINKED ISSUE #17765: Disabling push messages
### Description:

Push messages are disables but still I see in the logs the following messages

```
server.js:204 Push ➔ debug Sent message "#channelname" to 3 ios apps 1 android apps
```

I.e. it's seems like push messages are still active, or at least some parts of it. No custom APN or FCM is set and the gateway has been disabled too.

### Expected behavior:

When disabling `Push`, no push messages are sent via the push gateway or via the native push implementation (APN/FCM).

### Actual behavior:

Push is disabled but still "push sent" log messages are generated.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Deployment Method: docker

### PR DESCRIPTION
**Pull request by pierre-lehnen-rc**
## Issue(s)

Closes #17765

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [X] I have added necessary documentation (if applicable)
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/notification-queue/server/NotificationQueue.ts [hunk 1]
```diff
@@ -92,6 +93,10 @@ class NotificationClass {
 	}
 
 	push({ uid, rid, mid }: INotification, item: INotificationItemPush): void {
+		if (settings.get('Push_enable') !== true) {
```
Comment (sampaiodiego) [inline app/notification-queue/server/NotificationQueue.ts:96]: this function is called when the queue is actually being "cleared".

the idea is to not even add to the queue, so the `Push_enable` setting should be checked earlier in the flow.

here is where items are added to the queue:
https://github.com/RocketChat/Rocket.Chat/blob/142b3171170b321f55e63f63b2224a0d6cabac45/app/lib/server/lib/sendNotificationsOnMessage.js#L181

but I think the check could be done in the `shouldNotifyMobile` function:
https://github.com/RocketChat/Rocket.Chat/blob/142b3171170b321f55e63f63b2224a0d6cabac45/app/lib/server/functions/notifications/mobile.js#L74

**Review by sampaiodiego — CHANGES_REQUESTED** [review]
