### PR TITLE
fix: `startup` iframe event

### LINKED ISSUE #36881: Missing startup iframe event since 7.9.0
### Description:

Starting from version 7.9.0 certain iframe events seem to be missing. In particular the 'startup' event (documented in https://developer.rocket.chat/docs/iframe-events isn't fired anymore). I originally reported this in #36657 and closed it as a duplicate of #36638, however the fix deployed in 7.10 (#36820) does not fix the missing iframe messages. Since it was pointed out that my original issue issues did not include all the required information i decided to go with a new one that hopefully includes everything needed.

### Steps to reproduce:

Open Rocketchat in an iframe and observe the events it sends, for example with the following code snippet:
```
window.addEventListener('message', event => console.log('IFrame ' + event.data.eventName)) 
```

### Expected behavior (<7.9.0):

The iframe should fire the startup event, this is a screenshot from 7.8.4.

Image

As you can see the startup event is present and is used to detect when the application is ready for a `login-with-token` command (see https://developer.rocket.chat/docs/iframe-integration-sending-commands for details). 
After the command was issued we can see the events happening in case of a successful login.

### Actual behavior (>7.9.0):

The iframe does not fire the startup event. 
Screenshot from 7.10.0, same behavior exists since 7.9.0 (Same behavior has been confirmed for 7.11.0):

Image

As you can see the iframe didn't send the startup event, causing the logic that listens for it to never perform the login.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.10.0
- License Type: Community Edition
- Number of Users:  ~ 30
- Operating System: Oracle Linux 
- Deployment Method: Docker Compose
- Number of Running Instances: 1 
- DB Replicaset Oplog: -
- NodeJS Version: 22.19.0 - x64  
- MongoDB Version: 6.0.13

### Client Setup Information

- Desktop App or Browser Version: Firefox 142.0.1 (64-bit), Edge 139.0.3405.125 (64 bit)
- Operating System: Windows

### Additional context

In https://github.com/RocketChat/Rocket.Chat/commit/dd20d85defcd89e10af5534070322e3876cb33e6 `fireGlobalEvent` was modified, in particular sending the event message was moved outside of `Tracker.autorun`. My guess (without any evidence) is that this somehow messed up the iframe events. 

### Relevant logs:

I am unsure what logs would be of interest for this, but i am happy to provide them if something is requested.

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes (including videos or screenshots)

When Rocket.Chat is embedded in web clients, Rocket.Chat is supposed to emit a `startup` event upon loading to inform the parent window when Rocket.Chat is ready. Currently we were not emitting this event as expected.
This PR fixes this issue and moves the implementation to react.
## Issue(s)

- Fixes #36881 
## Steps to test or reproduce

- Embed Rocket.Chat into a web page
- Listen the events emitted by the Rocket.Chat iframe
- `startup` event is not emitted.
## Further comments

[CORE-1536](https://rocketchat.atlassian.net/browse/CORE-1536)

[CORE-1536]: https://rocketchat.atlassian.net/browse/CORE-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed an issue where the global startup event was not dispatched on client initialization; startup-dependent behaviors now reliably receive the startup notification.
  * Ensured the startup event is triggered at the correct point in the app lifecycle to improve reliability of components that run on initial load.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/meteor/client/views/root/hooks/useStartupEvent.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { useEffect } from 'react';
+
+import { useFireGlobalEvent } from '../../../hooks/useFireGlobalEvent';
+
+export const useStartupEvent = () => {
+	const { mutate: fireStartupEvent } = useFireGlobalEvent('startup');
```
Comment (gabriellsh) [inline apps/meteor/client/views/root/hooks/useStartupEvent.ts]:
```suggestion
	const { mutate: fireStartupEvent } = useFireGlobalEvent('startup', 'global');
```
We should pass the `scope` parameter here, so that we ensure this event won't be fired multiple times due to rerenders. This won't probably happen in a production environment, but certainly will be triggered at least twice due to strict mode.

Inside the `useFireGlobalEvent` hook there's an extra check that saves the eventName + scope in a ref to ensure it's triggered just once. But that only happens if scope is given.
