### PR TITLE
Fix: Regression on users avatar in admin pages

### LINKED ISSUE #10825: Avatars looking weird in some places
### Description:

The lazy load images PR broke some places where avatars are being shown.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.0-develop
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. Go to /admin/users and see
2. Or go to /livechat-manager/users and see

### Expected behavior:

Avatars looking normal.

### Actual behavior:

`/admin/users`:

image

`/livechat-manager/users`:

image

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #10825 

before:
image
after:
image

### CODE REVIEW

File: packages/rocketchat-ui-message/client/popup/messagePopup.js [hunk 1]
```diff
@@ -268,21 +270,26 @@ Template.messagePopup.onDestroyed(function() {
...
+				.replace(/\sselected/, '')
+				.replace('sidebar-item__popup-active', '');
 		}
 		e.currentTarget.className += ' selected sidebar-item__popup-active';
 		return template.value.set(this._id);
 	},
 	'mousedown .popup-item, touchstart .popup-item'() {
 		const template = Template.instance();
-		return template.clickingItem = true;
+		return (template.clickingItem = true);
```
Comment (rodrigok) [inline packages/rocketchat-ui-message/client/popup/messagePopup.js]: Wtf? :)

File: packages/rocketchat-ui-message/client/popup/messagePopup.js [hunk 2]
```diff
@@ -268,21 +270,26 @@ Template.messagePopup.onDestroyed(function() {
...
+	},
 	'mouseenter .popup-item'(e) {
 		if (e.currentTarget.className.indexOf('selected') > -1) {
 			return;
 		}
 		const template = Template.instance();
 		const current = template.find('.popup-item.selected');
 		if (current != null) {
-			current.className = current.className.replace(/\sselected/, '').replace('sidebar-item__popup-active', '');
+			current.className = current.className
```
Comment (rodrigok) [inline packages/rocketchat-ui-message/client/popup/messagePopup.js]: Please, do not introduce unnecessary changes

File: packages/rocketchat-ui-message/client/popup/messagePopup.js (hunk 1 above)
Comment (ggazzo) [reply packages/rocketchat-ui-message/client/popup/messagePopup.js]: https://eslint.org/docs/rules/no-return-assign

File: packages/rocketchat-ui-message/client/popup/messagePopup.js (hunk 2 above)
Comment (ggazzo) [reply packages/rocketchat-ui-message/client/popup/messagePopup.js]: it was the auto fix... I think we should accept because the auto linter will try lint each time somebody save the file (:
