### PR TITLE
Prevent error with positional operator

### LINKED ISSUE #5586: User rename via admin panel throws internal server error
Your Rocket.Chat version: 0.49.1

Seems like the username rename feature is broken again. Now some users are in an inconsistent state e.g. messages are showing the new name but direct messages channels still the old one :(

```
[34mI20170116-10:23:29.628(0) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at MongoConnection.<anonymous> (packages/meteor.js:213:24)   at MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:766:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/app/bundle/programs/server/packages/mongo.js:4007:31)   at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:8632:32)   at _Class.update (/app/bundle/programs/server/packages/rocketchat_lib.js:3592:36)   at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (/app/bundle/programs/server/packages/rocketchat_lib.js:4296:17)   at /app/bundle/programs/server/packages/rocketchat_lib.js:3153:41   at SynchronousCursor.forEach (/app/bundle/programs/server/packages/mongo.js:1038:18)   at Cursor.(anonymous function) [as forEach] (/app/bundle/programs/server/packages/mongo.js:890:44)   at RocketChat._setUsername (/app/bundle/programs/server/packages/rocketchat_lib.js:3150:64)   at Object.setUsername (/app/bundle/programs/server/packages/rocketchat_lib.js:1122:19)   at Object.RocketChat.saveUser (/app/bundle/programs/server/packages/rocketchat_lib.js:2534:15)   at [object Object].Meteor.methods.insertOrUpdateUser (/app/bundle/programs/server/packages/rocketchat_lib.js:11576:23)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1029:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)   at /app/bundle/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1040:48   at Session.method (/app/bundle/programs/server/packages/ddp-server.js:1018:23)   at /app/bundle/programs/server/packages/ddp-server.js:880:89      - - - - -   at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1048:67   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:436:9)   at process._tickDomainCallback (node.js:406:13) 
```

### PR DESCRIPTION
**Pull request by rodrigok**
Closes #5586

@RocketChat/core

### CODE REVIEW

File: packages/rocketchat-lib/server/models/_BaseDb.js [hunk 1]
```diff
@@ -158,6 +158,24 @@ class ModelsBaseDb extends EventEmitter {
 		return 'cache';
 	}
 
+	updateHasPositionalOperator(update) {
```
Comment (graywolf336) [inline packages/rocketchat-lib/server/models/_BaseDb.js]: Is `update` always an object?

Comment (rodrigok) [inline packages/rocketchat-lib/server/models/_BaseDb.js]: @graywolf336 Yes, it is
