### PR TITLE
[FIX] users.getPreferences when the user doesn't have any preferences

### LINKED ISSUE #12976: When user doesn't have any preferences, users.getPreferences fails with "Cannot set property 'language' of undefined"
### Description:

When user doesn't have preferences, the REST API call https://rocket.chat/docs/developer-guides/rest-api/users/get-preferences/ fails with `{"success":false,"error":"Cannot set property 'language' of undefined"}`.

The problem is in this line: https://github.com/RocketChat/Rocket.Chat/blob/3dacacc8ca300b56a7b43ab1265c75450109ae51/packages/rocketchat-api/server/v1/users.js#L376

There needs to be a guard there.

### PR DESCRIPTION
**Pull request by thayannevls**
Closes #12976

When **normal users** doesn't have any preferences, `user.settings` is an empty object instead of undefined. My solution was to check both.

Maybe a better solution is all users start with settings as undefined.

### CODE REVIEW

File: packages/rocketchat-api/server/v1/users.js [hunk 1]
```diff
@@ -402,7 +402,7 @@ API.v1.addRoute('users.createToken', { authRequired: true }, {
 API.v1.addRoute('users.getPreferences', { authRequired: true }, {
 	get() {
 		const user = Users.findOneById(this.userId);
-		if (user.settings) {
+		if (user.settings && !_.isEmpty(user.settings)) {
 			const { preferences } = user.settings;
```
Comment (rodrigok) [inline packages/rocketchat-api/server/v1/users.js]: Your solution doesn't solve the problem because if the `user.settings` is not empty, containing any other setting, but doesn't contains the `preferences` property, it will still fail with the same error of trying to access `language` of undefined.

```suggestion
			const { preferences = {} } = user.settings;
```

**Comment by thayannevls** [comment]
@rodrigok should I keep checking if is an empty object?

**Comment by MarcosSpessatto** [comment]
@thayannevls no, you can remove it.

**Comment by MarcosSpessatto** [comment]
@thayannevls can you please fix the conflicts?

**Comment by thayannevls** [comment]
@MarcosSpessatto Fixed it! Sorry for the delay.
