### PR TITLE
[FIX] Add tooltips to Thread header buttons

### LINKED ISSUE #20455: [BUG] No tooltips in ThreadView header for expand and follow/unfollow
### Description:

The top right buttons in Threadview beside Close do not have the tooltips when you hover over them, while the close button does.

### Steps to reproduce:

1. Open any thread
2. Hover over top-right buttons and wait for tooltip.

### Expected behavior:

For the tooltips to appear.

### Actual behavior:

No tooltip

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.10
- Deployment Method: develop
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.88
- Operating System: Ubuntu 20.10

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Checklist

- [x] I have read the Contributing Guide
- [x]  I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Added tooltips to "Expand" and "Follow Message"/"Unfollow Message" in ThreadView for coherency.

## Issue(s)

Closes #20455 

## Steps to test or reproduce

1. Open any thread
2. Hover over top-right buttons and wait for tooltip.

### CODE REVIEW

File: app/threads/client/components/ThreadView.tsx [hunk 1]
```diff
@@ -69,9 +69,9 @@ const ThreadView = forwardRef<Element, ThreadViewProps>(({
 				<VerticalBar.Header>
 					<VerticalBar.Icon name='thread' />
 					<VerticalBar.Text dangerouslySetInnerHTML={{ __html: title }} />
-					{hasExpand && <VerticalBar.Action aria-label={expandLabel} name={expandIcon} onClick={handleExpandActionClick} />}
+					{hasExpand && <VerticalBar.Action title={t('Expand')} aria-label={expandLabel} name={expandIcon} onClick={handleExpandActionClick} />}
 					<VerticalBar.Actions>
-						<VerticalBar.Action aria-label={followLabel} name={followIcon} onClick={handleFollowActionClick} />
+						<VerticalBar.Action title={t(following ? 'Unfollow_message' : 'Follow_message')} aria-label={followLabel} name={followIcon} onClick={handleFollowActionClick} />
```
Comment (ggazzo) [inline app/threads/client/components/ThreadView.tsx:74]: you can use the value applied on the aria-label, and since you are using title, no need to use aria please remove ;)

**Review by ggazzo — CHANGES_REQUESTED** [review]

File: app/threads/client/components/ThreadView.tsx (hunk 1 above)
Comment (aKn1ghtOut) [reply app/threads/client/components/ThreadView.tsx]: @ggazzo Made the changes :)

**Review by ggazzo — APPROVED** [review]
