### PR TITLE
[FIX] Large files crashed browser when trying to show preview

### LINKED ISSUE #5789: Memory leak when uploading file in Chrome
Rocket.Chat Version: 0.50.1
Deploy Method: Docker
Running Instances: 1
Node Version: v4.7.1
Linux Chrome Version: 55.0.2883.87 (64-bit) 
Linux Memory: 24GB

According to Chrome's Task Manager, RocketChat page shows high memory consumption when uploading files (much higher than the actual file size). 

Page will crash when uploading file bigger than 4GB

Is this mean that RocketChat will store the whole file in client memory before upload to the server?

### LINKED ISSUE #6534: Why I upload more than 80MB or more files will show the browser crash, the system settings have been modified to more than 80MB
Rocket.Chat Version: 0.53
Running Instances: 
DB Replicaset OpLog:
Node Version:4.7.3

### PR DESCRIPTION
**Pull request by geekgonecrazy**
@RocketChat/core 

We were loading every single file into memory.

This loads only if:
* Allowed file type
* Not over 10MB of size ( this might should be increased... But a 100MB file crashed my browser )
* An Image / Audio / Video file

Also if you upload a file of type other then image it'll now actually show the preview it.  It was accessing `file.type` and file.type was empty

Closes #6534 
Possibly also closes #5789

### CODE REVIEW

File: packages/rocketchat-ui/client/lib/fileUpload.coffee [hunk 1]
```diff
@@ -5,6 +5,31 @@ readAsDataURL = (file, callback) ->
...
+getUploadPreview = (file, callback) ->
+	if file.file.type.indexOf('audio') > -1 or file.file.type.indexOf('video') > -1 or file.file.type.indexOf('image') > -1
+		file.type = file.file.type.split('/')[0]
+
+		readAsDataURL file.file, (content) ->
+			callback(file, content)
+	else
+		callback(file, null)
+
+formatBytes = (bytes, decimals) ->
```
Comment (sampaiodiego) [inline packages/rocketchat-ui/client/lib/fileUpload.coffee]: please change this function's code to tabs

Comment (geekgonecrazy) [inline packages/rocketchat-ui/client/lib/fileUpload.coffee]: fixed :+1:
