### PR TITLE
fix: limit outgoing webhook response size to prevent memory exhaustion

### LINKED ISSUE #38758: Improve stability of Outgoing Webhooks by limiting response size
### Description:
The current implementation of `triggerHandler.ts` fetches webhook responses without a `size limit`. Node.js attempts to buffer the entire response body into memory (using `res.text()`).

If an integration endpoint returns a large response (e.g., >2GB file, infinite stream, or compromised server), the Node.js process runs out of heap memory and terminates.
This can be triggered by:
- A misconfigured integration URL pointing to a large file.
- A compromised external integration server.
- An Infinite data stream from an external source.

### Steps to reproduce:

1. Create an Outgoing Webhook integration.
2. Point the URL to an endpoint that serves a very large file or infinite stream or larger than the available Node.js heap memory, typically >2GB
3. Trigger the webhook like by sending a message or uploading a file.
4. Observe the Rocket.Chat server terminal.

### Expected behavior:

The server should enforce a reasonable limit on the response size like `20MB` and abort the request if the limit is exceeded, logging an error instead of crashing.

### Actual behavior:

The Node.js process consumes all available memory buffering the response and crashes with

Image

### Server Setup Information:

- Version of Rocket.Chat Server:  8.2.0-develop
- Operating System: Linux 
- NodeJS Version: 22.18.0

### Additional context

The fix involves adding the `size` option to the `fetch` call in `apps/meteor/app/integrations/server/lib/triggerHandler.ts`

### PR DESCRIPTION
**Pull request by Khizarshah01**
## Proposed changes (including videos or screenshots)

Enforced a **10MB size limit** on the `fetch` request for Outgoing Webhooks in `triggerHandler.ts` 
Currently, the `triggerHandler.ts` fetches webhook responses without specifying a `size` limit. If an integration endpoint returns an unexpectedly large response (e.g., infinite stream or large file), the Node.js process attempts to buffer the entire content into memory using `res.text()`. This leads to a (OOM) crash and terminates the server.

### Before (Buggy)

https://github.com/user-attachments/assets/6065b770-957e-4e76-852c-071068063743

### After (fixed)

https://github.com/user-attachments/assets/e12b4850-907d-483a-82d6-b40d3b7d07df

## Issue(s)

Fixes #38758
[COMM-144]

## Further comments

I chose **10MB** as the limit because standard JSON payloads for webhooks are typically much smaller (<1MB). This limit allows for legitimate large responses while sufficiently protecting the server from OOM exploits or misconfigurations.

## Summary by CodeRabbit

* **Improvements**
  * Outgoing webhook responses are now limited to 10 MB.
* **Chores**
  * Added a patch release changelog entry for the update.

[COMM-144]: https://rocketchat.atlassian.net/browse/COMM-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Khizarshah01** [comment]
PR is ready for review

File: apps/meteor/app/integrations/server/lib/triggerHandler.ts [hunk 1]
```diff
@@ -621,6 +621,7 @@ class RocketChatIntegrationHandler {
 				...(opts.data && { body: opts.data }),
 				// SECURITY: Integrations can only be configured by users with enough privileges. It's ok to disable this check here.
 				ignoreSsrfValidation: true,
+				size: 20 * 1024 * 1024,
```
Comment (KevLehman) [inline apps/meteor/app/integrations/server/lib/triggerHandler.ts]: Reduce the size to 5MB

**Review by KevLehman — CHANGES_REQUESTED** [review]
Pls, after adding the setting, add a changeset explaining the changes as this would need to appear on release notes.

File: apps/meteor/app/integrations/server/lib/triggerHandler.ts (hunk 1 above)
Comment (KevLehman) [reply apps/meteor/app/integrations/server/lib/triggerHandler.ts]: after discussing internally, pls update it to be 10Mb

Comment (Khizarshah01) [reply apps/meteor/app/integrations/server/lib/triggerHandler.ts]: updated to 10MB

**Comment by Khizarshah01** [comment]
@KevLehman I have made the requested changes

File: .changeset/shiny-pears-admire.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+'@rocket.chat/meteor': patch
+---
+
+Fix: Limit outgoing webhook response size to 10MB to prevent memory exhaustion
+
+Added a 10MB size limit to outgoing webhook responses to prevent the server from crashing when integrations return unexpectedly large responses.
```
Comment (KevLehman) [inline .changeset/shiny-pears-admire.md]:
```suggestion
Limits `Outgoing webhook` maximum response size to 10mb.
```

[the remark this answers is not in the document]
Comment (KevLehman) [reply .changeset/shiny-pears-admire.md]: @Khizarshah01 would u pls update the pr description too? 🤗 so the bot is happy.

[the remark this answers is not in the document]
Comment (Khizarshah01) [reply .changeset/shiny-pears-admire.md]: Done!

**Comment by Khizarshah01** [comment]
Thanks @KevLehman for the review and getting this merged :)

**Comment by KevLehman** [comment]
You're welcome, thx for the good work :)
