### PR TITLE
[FIX] Internal Error when requesting user data download

### LINKED ISSUE #10777: Error when using Download My Data or Export My Data
### Description:

When attempting to export or download a user's data, the system errors out. No additional configuration has been done to User Data Download section, other than it is enabled.

### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: Ubuntu 18.04 LTS
* Deployment Method(snap/docker/tar/etc): docker ```rocketchat/rocket.chat:latest```
* Number of Running Instances:  1

#### Rocket.Chat

| Version                 | 0.64.1                                                    |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 115                                                       |
| Database Migration Date | Mon May 07 2018 10:41:14 GMT-0500 (Central Daylight Time) |
| Installed at            | Mon Jan 29 2018 16:02:11 GMT-0600 (Central Standard Time) |
| Uptime                  | 8 days, 2 hours, 28 seconds                               |
| Deployment ID           | JAELT9iyADPbKEGbG                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

#### Commit

| Hash    | 54738c011b1fededb198dbf64be11ba48889c762                 |
| ------- | -------------------------------------------------------- |
| Date    | Thu May 3 13:37:12 2018 -0300                            |
| Branch  | HEAD                                                     |
| Tag     | 0.64.1                                                   |
| Author  | Rodrigo Nascimento                                       |
| Subject | Merge pull request #10660 from RocketChat/release-0.64.1 |

### Steps to Reproduce:

1. Go to User -> My Account -> My Data -> Download/Export My Data

### Expected behavior:

The data should be made available for download.

### Actual behavior:
System errors out with "Internal Server Error" message:
image

### Relevant logs:
```
Exception while invoking method 'requestDataDownload' Error: ENOENT: no such file or directory, mkdir '/tmp/userData/*********'
    at Object.fs.mkdirSync (fs.js:885:18)
    at MethodInvocation.requestDataDownload (/app/bundle/programs/server/app/app.js:10356:10)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2186:28)
    at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)
    at /app/bundle/programs/server/packages/ddp-server.js:754:85
```

### PR DESCRIPTION
**Pull request by Hudell**
Closes #10777

### CODE REVIEW

File: server/methods/requestDataDownload.js [hunk 1]
```diff
@@ -27,6 +27,10 @@ Meteor.methods({
 			}
 		}
 
+		if (!fs.existsSync(tempFolder)) {
```
Comment (sampaiodiego) [inline server/methods/requestDataDownload.js]: any reason to use sync functions? why not using async ones?

Comment (graywolf336) [reply server/methods/requestDataDownload.js]: I think he is keeping it consistent with the code below this. All of them currently use the `sync` versions.
