### PR TITLE
[FIX] Prune messages not removing thumbnails

### LINKED ISSUE #26287: Prune Messages doesn't delete thumbnail files
### Description:
Storage Type > File System. 
Prune Messages doesn't delete thumbnail files. 

### Steps to reproduce:

1. Go to Prune Messages
2. Click on Prune. After Prune completed successfully
3. Go and click on Files
4. All tumbnail files are still there

### Expected behavior:

When "prune messages" the expected behavior to delete all type of messages - thumbnail of images too

### Actual behavior:

All tumbnail files are still there

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.1
- Operating System: 20.04
- Deployment Method: snapd
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v14.18.3
- MongoDB Version: 4.2.17 

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: windows 10 Pro /Android 12

### PR DESCRIPTION
**Pull request by LucianoPierdona**
## Proposed changes (including videos or screenshots)

This PR adds a method on `Uploads` called `findOneByName`, and excludes a thumbnail of an image on `cleanRoomHistory`

## Issue(s)

Fix #26287

## Steps to test or reproduce

- Go to Prune Messages
- Click on Prune. After Prune completed successfully
- Go and click on Files
- All tumbnail files are still there

### CODE REVIEW

**Review by matheusbsilva137 — DISMISSED** [review]

File: apps/meteor/app/lib/server/functions/cleanRoomHistory.ts [hunk 1]
```diff
@@ -28,10 +28,15 @@ export const cleanRoomHistory = function ({
...
+		fields: { 'file._id': 1, 'file.name': 1, 'pinned': 1 },
 		limit,
 	}).forEach((document: IMessage) => {
-		FileUpload.getStore('Uploads').deleteById(document.file?._id);
+		const thumbName = `thumb-${document.file?.name}`;
+
+		const uploadsStore = FileUpload.getStore('Uploads');
+
+		uploadsStore.deleteById(document.file?._id);
+		uploadsStore.deleteByName(thumbName);
```
Comment (sampaiodiego) [inline apps/meteor/app/lib/server/functions/cleanRoomHistory.ts:39]: `IMessage` has a property `files` which is an array of files that also stores the thumbs of uploaded files.. you should use this property to remove all files associated to the message instead of "trying" to remove by name.

https://github.com/RocketChat/Rocket.Chat/blob/a39086d569f8543e9596554f7931cd8b278c17f4/packages/core-typings/src/IMessage/IMessage.ts#L163

**Review by sampaiodiego — CHANGES_REQUESTED** [review]

File: apps/meteor/app/lib/server/functions/cleanRoomHistory.ts (hunk 1 above)
Comment (LucianoPierdona) [reply apps/meteor/app/lib/server/functions/cleanRoomHistory.ts]: @sampaiodiego updated!

**Review by sampaiodiego — APPROVED** [review]

**Comment by alekdimitrov** [comment]
Hi. Im sorry that but I want open this issue again. I am on 5.2.3 version and issue is still not fixed.
Thanks.
