### PR TITLE
[FIX] Wrong message when reseting password and 2FA is enabled

### LINKED ISSUE #8472: Error on setting a new password on recovery
### Description:

A complex issue of the password recovery showing an Error when it should be working and showing an Error and still setting the password, but not informing the user of it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

```
1. request password recovery
2. try to change password with being logged in as another user = error, no password change
3. try to change password without being logged = no error, password changed
no 2fa set

1. request password recovery
2. try to change password with being logged in as another user = error, no password change
3. try to change password without being logged in = error, no password change
4. request new password recovery
5. try to login without being logged in = error, password changed

Second was with 2fa, though i'm not convinced that it was a deciding factor
```

### Expected behavior:

Password is changed without an error and user is informed that the password was successfully changed.

### Actual behavior:

This seems like either a complex issue or multiple issues, finding consistency on the behaviour was difficult. Sometimes you get the error for no apparant reason, sometimes you get the error when you're logged in as another user and sometimes you get the error and the password is actually changed nonetheless.

### Relevant logs:
Nothing in the logs with verbosity 0, Errors only.

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #8472

When password is reset the user is logged in automatically, but one error is received when the user has 2FA enabled requiring to pass the token, that is why we have the password reset but one error is displayed.

This PR just check the error message and redirect the user to the login page when 2FA is required and show a success alert about the message reset.

The 2 possible results are:
- 2FA Disabled: After a successful password reset the user will be logged in automatically
- 2FA Enabled: After a successful password reset the user will receive a successful message and will be redirect to the login page

### CODE REVIEW

File: packages/rocketchat-ui-login/client/reset-password/resetPassword.js [hunk 1]
```diff
@@ -44,10 +44,16 @@ Template.resetPassword.events({
 				RocketChat.Button.reset(button);
 				if (error) {
 					console.log(error);
-					swal({
-						title: t('Error_changing_password'),
-						type: 'error'
-					});
+					if (error.error === 'totp-required') {
```
Comment (geekgonecrazy) [inline packages/rocketchat-ui-login/client/reset-password/resetPassword.js]: Does it throw this error even if successfully changing password?

Comment (rodrigok) [reply packages/rocketchat-ui-login/client/reset-password/resetPassword.js]: Yes, cuz after the change the process proceed to login, then we receive this error, if password was not changed the error will be different
