### PR TITLE
[FIX] Fix iframe login API response (issue #8145)

### LINKED ISSUE #8145: IFrame login checks for presence of "token" value, while documentation says "loginToken" is enough
### Description:

When using iframe login, the client code checks for presence of "token" value in the response ( https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-iframe-login/iframe_client.js#L69 ). But the documentation at https://rocket.chat/docs/developer-guides/iframe-integration/authentication/ says :

> Or you can respond with native account token using loginToken:
> ```
> {
>   "loginToken":"your-auth-token"
> }
> 
> ```
> 

The workaround is simple - the response needs to include both properties, but it takes time to figure out what's the problem. Either the code or documentation needs to be fixed.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version:

### Steps to Reproduce:

1. Enable and configure iframe integration as described in documentation, using "loginToken" only in the response
2. Open Rocket.Chat in browser and monitor network data in dev tools
3. Note the network requests in browser dev tools

### Expected behavior:

Apart from Rocket.Chat resources, one request to login API URL

### Actual behavior:

One request to API URL. Then another request to iframe URL.

### PR DESCRIPTION
**Pull request by astax-t**
@RocketChat/core 

Closes #8145

Fixes iframe login API response to match what documentation says.

### CODE REVIEW

File: packages/rocketchat-iframe-login/iframe_client.js [hunk 1]
```diff
@@ -82,27 +82,27 @@ class IframeLogin {
...
 		if (!this.enabled) {
 			return;
 		}
 
-		if (Match.test(token, String)) {
-			token = {
-				token
+		if (Match.test(tokenData, String)) {
+			tokenData = {
+				tokenData
```
Comment (rodrigok) [inline packages/rocketchat-iframe-login/iframe_client.js]: This part should be:
```
tokenData = {
  token: tokenData
}
```

**Comment by astax-t** [comment]
You're absolutely right, sir. ES6 is not my strongest side, unfortunately. That's fixed now.
