### PR TITLE
[FIX] Call button is still displayed when the user doesn't have permission to use it

### LINKED ISSUE #19441: [Improvement] Some errors in RC logs looks like unhandled
### Description:

I see a lot of entries in logs near some errors, e.g. `server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted`  and it looks like that is unhandled error

### Steps to reproduce:

1. Mute user in some chat
2. Try to start Jitsi call as muted user
3. Get a lot of entries in RC logs

### Expected behavior:

Get only one entry:
`server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted`

### Actual behavior:

Actually it's not a bug, because logically all fine - muted user can't write message and start call, but logs need to be corrected.
That behaviour is flooding logs and make them hard to read.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24 wiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.0.5
- Operating System: Windows 10

### Additional context

Actually it's not a bug, because logically all fine - muted user can't write message and start call, but logs need to be corrected
**Updated 25 of May 2021**
I guess there is actually bug that lead to endless `server.js:204 System ➔ error Error starting video call: Error: error-not-allowed` error, see comment https://github.com/RocketChat/Rocket.Chat/issues/19441#issuecomment-847564347

### Relevant logs:

```
I20201102-16:15:42.588(0) server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted     at app/authorization/server/functions/canSendMessage.js:37:9     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20201102-16:15:52.570(0) server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted     at app/authorization/server/functions/canSendMessage.js:37:9     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20201102-16:16:02.577(0) server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted     at app/authorization/server/functions/canSendMessage.js:37:9     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20201102-16:16:12.606(0) server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted     at app/authorization/server/functions/canSendMessage.js:37:9     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20201102-16:16:22.596(0) server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted     at app/authorization/server/functions/canSendMessage.js:37:9     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
```

Similar logs  I see if there is Incoming Integration where bot is not a member of chat
```
at packages/nimble_restivus/lib/route.coffee:59:33
at packages/simple_json-routes.js:98:9
at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at app/api/server/api.js:394:82
at processWebhookMessage (app/lib/server/functions/processWebhookMessage.js:90:4)
at Object.executeIntegrationRest (app/integrations/server/api/api.js:250:19)
at validateRoomMessagePermissions (app/authorization/server/functions/canSendMessage.js:48:101)
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/authorization/server/functions/canSendMessage.js:32:10
Error: You can't send messages because the room is readonly.
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

### PR DESCRIPTION
**Pull request by matheusbsilva137**
## Proposed changes (including videos or screenshots)

- Hide 'Call' buttons from the tab bar for muted users;
- Display an error when a muted user attempts to enter a call using the 'Click to Join!' button.

## Issue(s)

[Task - ClickUp](https://app.clickup.com/t/5z5123)
Fixes #19441 

## Steps to test or reproduce

1. Create a room and add a member to it;
2. Members > select the added user > Mute User;
3. Login as the muted user. **_Expected behavior:_** the Call button won't be displayed to the muted user in the tab bar;
4. Start a call as an unmuted user and press the "Click to Join!" button as the muted user. **_Expected Behavior:_** an error toast will be displayed to the user and the sidebar will be closed.

### CODE REVIEW

File: app/videobridge/server/methods/jitsiSetTimeout.js [hunk 1]
```diff
@@ -50,9 +50,7 @@ Meteor.methods({
 
 			return jitsiTimeout || nextTimeOut;
 		} catch (error) {
-			SystemLogger.error('Error starting video call:', error);
-
-			throw new Meteor.Error('error-starting-video-call', error.message);
+			SystemLogger.error('Error starting video call:', error.message);
```
Comment (KevLehman) [inline app/videobridge/server/methods/jitsiSetTimeout.js:53]: But in this case, this will silently fail isn't it? 🤔 so the user won't receive feedback of why it failed? (or SystemLogger takes care of that?)

**Review by KevLehman — COMMENTED** [review]
:)

File: app/videobridge/server/methods/jitsiSetTimeout.js (hunk 1 above)
Comment (matheusbsilva137) [reply app/videobridge/server/methods/jitsiSetTimeout.js:53]: Well, no warnings were being shown to the user (in the UI) even before the changes here -- so removing the `Meteor.Error` made no difference to the user. I guess this `Meteor.Error` should be doing that, shouldn't it?

**Comment by KevLehman** [comment]
It would be good to have a kind of error filter, so we can remove all stack traces there before returning them to the client instead of modifying the throws to be only logs 🤔 (out of the scope of this task, but throwing the idea here for consideration)

File: app/videobridge/server/methods/jitsiSetTimeout.js (hunk 1 above)
Comment (ankar84) [reply app/videobridge/server/methods/jitsiSetTimeout.js:53]: Yeah, I can confirm. User in that case don't get aby feedback now, But admin gets flooded logs with Meteor stack trace.

**Comment by ankar84** [comment]
Important additional to that fix - removing of stack traces from RC logs it's really good for RC admins like me.
But problem here is a bit more complex - I described all details here https://github.com/RocketChat/Rocket.Chat/issues/19441#issuecomment-847564347

**Comment by ankar84** [comment]
> It would be good to have a kind of error filter, so we can remove all stack traces there before returning them to the client instead of modifying the throws to be only logs 🤔 (out of the scope of this task, but throwing the idea here for consideration)

Rocket chat is a corporate grade software and having such stack traces in production code is not a best solution, IMHO.
Some development deployments could be with all that traces (enabled optionally when setting that deployment as test or development) but in production code that traces just floods logs and nothing else.

**Comment by KevLehman** [comment]
Yup, agreed on that. That's why I suggested the error filter, one central place to remove the stack traces from errors (and log/message just the actual error). The configurable part would be cool too.

File: app/videobridge/server/methods/jitsiSetTimeout.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (sampaiodiego) [reply app/videobridge/server/methods/jitsiSetTimeout.js:53]: I'm ok with this particular change, but I'm with Kevin on removing the `Meteor.Error`, we should not remove it.. if the UI is not showing the error, that's a bug that should be fixed on frontend.. but if we remove the `Meteor.Error` will be breaking the API, as it will start returning success instead of an error.

**Review by sampaiodiego — CHANGES_REQUESTED** [review]

**Comment by pierre-lehnen-rc** [comment]
The stack traces are being logged by the `method.call/:method` api. 

https://github.com/RocketChat/Rocket.Chat/blob/d0fcad237df223c495ecaf2f528060485aa636a0/app/api/server/v1/misc.js#L274

**Comment by matheusbsilva137** [comment]
> The stack traces are being logged by the `method.call/:method` api.
> 
> https://github.com/RocketChat/Rocket.Chat/blob/d0fcad237df223c495ecaf2f528060485aa636a0/app/api/server/v1/misc.js#L274

Hey @sampaiodiego , do you think we can just remove this line? 🤔

**Review by gabriellsh — DISMISSED** [review]

File: app/videobridge/client/tabBar.tsx [hunk 2]
```diff
@@ -26,8 +27,11 @@ addAction('bbb_video', ({ room }) => {
 		enabledTeams && 'team',
 		enabledChannel && 'channel',
 	].filter(Boolean) as ToolboxActionConfig['groups']);
+	const user = Meteor.user();
```
[the remark this answers is not in the document]
Comment (matheusbsilva137) [reply app/videobridge/client/tabBar.tsx]: Good suggestion, I've just replaced all the `Meteor.user()` in this file by `useUser()`. Guess I can't do the same in the `actionLink` file, right? (I'll need to keep using `Meteor.user()` in this one)

[the remark this answers is not in the document]
Comment (gabriellsh) [reply app/videobridge/client/tabBar.tsx]: I believe so too.

File: app/api/server/v1/misc.js [hunk 3]
```diff
@@ -271,8 +272,10 @@ const methodCall = () => ({
 			const result = Meteor.call(method, ...params);
 			return API.v1.success(mountResult({ id, result }));
 		} catch (error) {
-			Meteor._debug(`Exception while invoking method ${ method }`, error.stack);
-
+			SystemLogger.error('Error starting video call:', error.message);
```
Comment (pierre-lehnen-rc) [inline app/api/server/v1/misc.js:275]:
```suggestion
			SystemLogger.error(`Exception while invoking method ${ method }`, error.message);
```

This will catch any error from any meteor method call, so the log message should not be related to the video call.

File: client/views/room/contextualBar/Call/Jitsi/CallJitsWithData.js [hunk 4]
```diff
@@ -119,43 +124,76 @@ const CallJitsWithData = ({ rid }) => {
...
-			jitsi.off('HEARTBEAT', testAndHandleTimeout);
-			jitsi.dispose();
-		};
+			jitsi.on('HEARTBEAT', testAndHandleTimeout);
 
-		return jitsi.openNewWindow ? none : clear;
-	}, [accepted, jitsi, rid, testAndHandleTimeout, updateTimeout]);
+			return jitsi.openNewWindow ? none : clear;
+		}
+		return fetchData();
```
Comment (tassoevan) [inline client/views/room/contextualBar/Call/Jitsi/CallJitsWithData.js:186]: **You cannot return a `Promise` object from `useEffect` callback.** In this case, you are returning a promise of type `Promise<() => void>`; it should be a clean up function of type `() => void`.
If you need to await for the `updateTimeout` to decide for calling `jitsi.dispose()` or not on effect clean up, consider using a local boolean variable. E.g.:

```
useEffect(() => {
  let shoudDispose = false;
  
  async function fetchData() {
     ...
     shouldDispose = !jitsi.openNewWindow;
  }
  
  fetchData();
  
  return () => {
    if (shouldDispose) {
      jitsi.dispose();
      // whatever more
    }
  };
}, [...]);
```

**Review by tassoevan — CHANGES_REQUESTED** [review]

**Review by tassoevan — APPROVED** [review]
