### PR TITLE
[FIX] You must join to view messages in this channel

### LINKED ISSUE #14425: Rocket.Chat displays 'You must join to view messages in this channel' for guest users
### Description:

Rocket.Chat displays the 'You must join to view messages in this channel' banner for guest users even though they're subscribed to the channel and can view and send messages.

### Steps to reproduce:

1. Create a guest user and invite them to a channel. Make sure that `allow anonymous read` is _not_ globally enabled and that the guest group does not have the `preview-c-room` permission.
2. The guest user should see the `You must join to view messages in this channel` banner.

### Expected behavior:

Users who are subscribed to a channel should not see this banner.

### Actual behavior:

The banner is shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2 / abf67ce98521b115c4c85d2ff86394098c92bbf3
- Operating System: Debian stretch
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.2.21

### Additional context

I believe the problem is in the `canPreview` function - more specifically at https://github.com/RocketChat/Rocket.Chat/blob/develop/app/ui/client/views/app/room.js#L498

According to Chrome DevTools `state.get('subscribed')` is `true` for the affected user and channel. Shouldn't `canPreview` return `true` for channels which the user is subscribed to?

### Relevant logs:

None.

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #14425

### CODE REVIEW

File: app/ui/client/views/app/room.js [hunk 1]
```diff
@@ -492,7 +492,7 @@ Template.room.helpers({
 			return true;
 		}
 
-		return !state.get('subscribed');
+		return !!state.get('subscribed');
```
Comment (tassoevan) [inline app/ui/client/views/app/room.js]:
```suggestion
		return state.get('subscribed');
```
I don't think the double negation is needed because `subscribed` is set by doubly negating the `subscription` value: it's always a boolean value.
