### PR TITLE
[FIX] The process was freezing in some cases when HTTP calls exceeds timeout on integrations

### LINKED ISSUE #10062: Long-running outgoing webhook breaks sending of messages
### Description:

**Short version**
When having a **slow** Outgoing WebHook Integration for `sendMessage`, it'll crash with a timeout. That sometimes leads to a few further errors where messages are not sent properly.

**Environment**
I'm using both the REST & Realtime API to create a custom chat integration to an existing platform. For testing purposes, I fully checked this error with the standard Rocket.Chat UI.

**Details**
- I'm using a `sendMessage` WebHook for sending message information to another project
  - In short, it's a special form of offline notification
  - The WebHook checks several things while making calls to `Subscriptions` / `Messages` model.
  - If the message is suitable (the opponent should be notified), a manual `HTTP` call is triggered to propagate that information to a different project
  - Usually, that (local area) request takes just a few ms. But with high load, the script + request may take >3000ms
- I know the current timeout of [3000ms](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/lib/triggerHandler.js#L306). That's hardcoded.
- As far as I see (from the code), the hook should be very independent and should not affect the sending of other messages.

### Server Setup Information:
I mainly get this error when using Rocket.Chat with a vagrant VM. In some rare cases, the described error affects a medium-sized kubernetes cluster (3 instances), as well.

* Version of Rocket.Chat Server: 0.62.1 (tested with 0.59.3 as well)
* Operating System: Linux (4.4.0-116-generic)
* Deployment Method(snap/docker/tar/etc): manually (local VM)
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.9.4
* mongoDB Version: v3.4.13

### Steps to Reproduce:

1. Create Outgoing WebHook for `sendMessage`, that'll take longer than 3 seconds (in my case: HTTP request)
2. Restart Rocket.Chat server (just for having a clean env); Open logs
3. Open Rocket.Chat UI, create new room (1on1 private chat in my example)
4. Write a message for triggering the webhook
5. Look at the log :-)

_(If I deactivate the WebHook, the error isn't there at all)_

### Expected behavior:

- All sent messages are handled correctly and will be displayed to me and my opponent.

### Actual behavior:

- Sent messages aren't handled correctly
- Different sort of further errors:
  - WebSocket frames doesn't show any outgoing requests to the server
  - Message arrive server, but JSON looks defect (see log below)

### Relevant logs:
- Most obvious log: **Script execution timed out** after 3000ms
```
Mar 06 12:44:06 calida RocketChat[11645]: rocketchat_logger rocketchat_logger.js:278 Integrations ➔ Outgoing WebHook.error   Error: Script execution timed out.
Mar 06 12:44:06 calida RocketChat[11645]:       at ContextifyScript.Script.runInContext (vm.js:59:29)
Mar 06 12:44:06 calida RocketChat[11645]:       at ContextifyScript.Script.runInNewContext (vm.js:65:15)
Mar 06 12:44:06 calida RocketChat[11645]:       at Object.runInNewContext (vm.js:135:38)
Mar 06 12:44:06 calida RocketChat[11645]:       at RocketChatIntegrationHandler.executeScript (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_integrations.js:731:30)
Mar 06 12:44:06 calida RocketChat[11645]:       at RocketChatIntegrationHandler.executeTriggerUrl (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_integrations.js:1115:19)
Mar 06 12:44:06 calida RocketChat[11645]:       at RocketChatIntegrationHandler.executeTrigger (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_integrations.js:1025:12)
Mar 06 12:44:06 calida RocketChat[11645]:       at RocketChatIntegrationHandler.executeTriggers (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_integrations.js:1018:14)
Mar 06 12:44:06 calida RocketChat[11645]:       at _wrapperFunction (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_integrations.js:2565:51)
Mar 06 12:44:06 calida RocketChat[11645]:       at /var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:1162:30
Mar 06 12:44:06 calida RocketChat[11645]:       at Array.reduce (<anonymous>:null:null)
```
- Error where the message JSON seems to be **totally** broken.
```
[34mI20180307-10:09:30.536(0) Discarding message with invalid JSON :"stream-notify-room","9rams":["3h5LawnS7Jm2kQxyZ/typing","GuidoVanRossum",true]}{{"msg":"methtd","id":"28","method" 
[34mI20180307-10:09:36.072(0) Discarding message with invalid JSON :"stream-notify-room",33arams":["3h5LawnS7Jm2kQxyZ/typing","GuidoVanRossum",true]}{"msg":"method","id":"253","method": 
[34mI20180307-10:09:29.913(0) Discarding message with invalid JSON {"msg":"method","id":"28sum",true]}{"msg":"method","id":"234","method":"readMessages","params":["3h5LawnS7Jm2kQxyZ"]}{ 
```
- Once I got a duplicate key error. But that _may_ be unrelated / some other error.
```
Mar 08 13:06:44 calida RocketChat[27939]: Exception while invoking method 'sendMessage' WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id_ dup key: { : \"oy5HL3ZTcHcLD76gu\" }","op":{"_id":"oy5HL3ZTcHcLD76gu","rid":"Frv7BoZmepnfsJoAy","msg":"zrtz","ts":"2018-03-08T13:06:44.440Z","u":{"_id":"w6fSjr4mLYZ9HoqWP","username":"customer100","name":"customer100"},"unread":true,"mentions":[],"channels":[],"_updatedAt":"2018-03-08T13:06:44.449Z"}})
```

### Questions:
- Can you tell me why one failing WebHook execution affects other executions of that WebHook? AFAIK the hook will be compiled just once, but runs in a separate `vm` context on every call.
- Is that possibly somehow related to #9926?
- Do you have any tips on how to write a WebHook? Any pitfalls to avoid, is it very ugly to make an external API call (well, most integrations are based on that^^)?

### PR DESCRIPTION
**Pull request by rodrigok**
Closes #10062

The problem happens when we have a timeout exception triggered by some async method like the HTTP, this async method is turned sync by the usage of Fibers, for some reason that exception, some times we need more than one, stops the oplog tail method that uses Fibers too leading to a stop of reactivity we use to sync the clients.

The solution was start a new Fiber inside the VM to prevent the exceptions to stop the fibers, in my tests this change solved the problem.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
previously, if the HTTP call exceeds the vm time out, the integration execution would failure and a message would not be sent.

with this change, the integration runs successfully after the timeout..

is this an intentional change?

**Comment by rodrigok** [comment]
@sampaiodiego yes, cuz the async time does not count in the script execution time.

File: packages/rocketchat-integrations/server/api/api.js [hunk 1]
```diff
@@ -236,9 +240,19 @@ function executeIntegrationRest() {
 			sandbox.script = script;
 			sandbox.request = request;
 
-			const result = vm.runInNewContext('script.process_incoming_request({ request: request })', sandbox, {
+			const result = Future.fromPromise(vm.runInNewContext(`
+				new Promise((resolve, reject) => {
```
Comment (sampaiodiego) [inline packages/rocketchat-integrations/server/api/api.js]: please, add a `catch` to this `Promise`, otherwise calling `reject` will thrown a `unhandled promise rejection`

**Comment by rodrigok** [comment]
LGTM
