### PR TITLE
fix: custom emoji update issues

### LINKED ISSUE #26980: Cannot modify custom emoji without re-uploading it
### Description:

When editing a custom emoji without uploading a new file, the error message "No file uploaded" appears when clicking the "Save" button and the changes will not be saved.

### Steps to reproduce:

1. Add a custom emoji in case you don't already have one.
2. Select a custom emoji for editing.
3. Edit its name or aliases.
4. Click the "Save" button.

### Expected behavior:

The changes are saved without an error.

### Actual behavior:

An error message is shown and the changes will not be saved:

image

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.4
- Operating System: Debian GNU/Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.12

### Client Setup Information

- Desktop App or Browser Version: Chromium 106.0.5249.61 (Offizieller Build) Arch Linux (64-Bit), Firefox 105.0.1 (64-Bit)
- Operating System: Arch Linux

### PR DESCRIPTION
**Pull request by abhinavkrin**
## Proposed changes (including videos or screenshots)

This PR addresses two main issues with custom emoji updates in Rocket.Chat:

1. **Issue with Alias Update:**
   - Users were required to upload the image again when updating a custom emoji's alias or name, leading to an error if no file was uploaded.
   - **Solution:** Made the file optional for the `emoji-custom.update` endpoint.

2. **Issue with Image Update Not Reflecting:**
   - The new image was indeed updated but not reflected in browser due to browser cache. The max-age for caching is set for one year, so even if the image changed (without changing the emoji name), the URL remained the same, causing the old emoji to be loaded from the cache.
   - **Solution:** Created an additional hash for the emoji each time its image is changed. While rendering, attached the hash as a query to the image URL.

Also, there was a minor issue with the test related to the first issue. The test was already there but was not being executed, so we never caught the bug as it always appeared to pass. **[Fixed]**

#### Before
The aliases are not saved. The emoji could not be updated without a new file

https://github.com/user-attachments/assets/51c74dc7-64bf-47f7-a757-9b6da03c3dc3

#### After

https://github.com/user-attachments/assets/35b15ffa-3166-4741-a842-7537c19c1689

## Issue(s)

closes #26980 

closes https://github.com/RocketChat/Rocket.Chat/pull/20318
closes https://github.com/RocketChat/Rocket.Chat/pull/21821

Closes https://github.com/RocketChat/Rocket.Chat/issues/20317
Closes https://github.com/RocketChat/Rocket.Chat/issues/20316
## Further comments

[SUP-622](https://rocketchat.atlassian.net/browse/SUP-622)

[SUP-622]: https://rocketchat.atlassian.net/browse/SUP-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]
@abhinavkrin I saw we are fixing multiple issues in this PR, would it be possible to split different fixes in different PRs? I mean, really dependent ones there should not be a problem, but I see some different and unrelated issues. WDYT?

**Review by KevLehman — CHANGES_REQUESTED** [review]

File: apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts [hunk 1]
```diff
@@ -41,9 +43,12 @@ export async function uploadEmojiCustomWithBuffer(
 		throw new Meteor.Error('not_authorized');
 	}
 
+	if (!Array.isArray(emojiData.aliases)) {
```
[the remark this answers is not in the document]
Comment (abhinavkrin) [reply apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts:46]: In the previous revision of this file, the aliases were deleted without any checking, since it was always expected to be a string. Now, 
1. the data received from the insertOrUpdateEmoji is sent to this function. the data here will have aliases as array.
2. this function is called in emoji.create where aliases are query string.

File: apps/meteor/app/emoji/client/helpers.ts [hunk 2]
```diff
@@ -149,7 +149,10 @@ export const removeFromRecent = (emoji: string, recentEmojis: string[], setRecen
 	setRecentEmojis(recentEmojis);
 };
 
-export const updateRecent = (recentList: string[]) => {
+export const updateRecent = (recentList: string | string[]) => {
+	if (!Array.isArray(recentList)) {
```
Comment (abhinavkrin) [inline apps/meteor/app/emoji/client/helpers.ts:153]: This fixes: `The client threw an error on updating the emoji list in memory after receiving the updates from the server. `

Screenshot 2024-07-12 at 2 26 20 PM

File: apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx [hunk 3]
```diff
@@ -95,7 +95,7 @@ const CustomEmoji = ({ onClick, reload }: CustomEmojiProps) => {
 											<Box withTruncatedText>{emojis.name}</Box>
 										</GenericTableCell>
 										<GenericTableCell color='default'>
-											<Box withTruncatedText>{emojis.aliases}</Box>
+											<Box withTruncatedText>{Array.isArray(emojis.aliases) ? emojis.aliases.join(', ') : emojis.aliases}</Box>
```
Comment (abhinavkrin) [inline apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx:98]: This fixes `The aliases were not displayed properly in the custom emoji list`

File: apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts [hunk 4]
```diff
@@ -67,8 +70,14 @@ export async function uploadEmojiCustomWithBuffer(
 			encodeURIComponent(`${emojiData.name}.${emojiData.extension}`),
 			contentType,
 		);
-		ws.on('end', () => {
-			setTimeout(() => api.broadcast('emoji.updateCustom', emojiData), 500);
+		ws.on('end', async () => {
+			const etag = Random.hexString(6);
+			if (emojiData._id) {
```
Comment (KevLehman) [inline apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts:75]: in which cases will emojiData not contain an _id? when creating?

File: apps/meteor/tests/end-to-end/api/emoji-custom.ts [hunk 5]
```diff
@@ -95,7 +95,7 @@ describe('[EmojiCustom]', () => {
 				})
```
Comment (KevLehman) [inline apps/meteor/tests/end-to-end/api/emoji-custom.ts:95]: Can you add more cases? (in case they're not there already)
- what happens when no file is provided to update
- what happens when file is provided but none of the data is updated (just the file)
- Updating the emoji data but no file
- Requesting emoji without passing the etag (for old emojis)
- Requesting an emoji with an invalid etag

**Review by KevLehman — CHANGES_REQUESTED** [review]

File: apps/meteor/app/api/server/v1/emoji-custom.ts [hunk 6]
```diff
@@ -136,9 +136,11 @@ API.v1.addRoute(
 			fields.previousName = emojiToUpdate.name;
 			fields.previousExtension = emojiToUpdate.extension;
 			fields.aliases = fields.aliases || '';
-			const newFile = Boolean(emoji && fileBuffer.length);
 
-			if (fields.newFile) {
+			let newFile = false;
```
[the remark this answers is not in the document]
Comment (abhinavkrin) [reply apps/meteor/app/api/server/v1/emoji-custom.ts:140]: I added this line. But when I use newFile in if clause, i am getting type error of `mimetype could be undefined`.
So I did not change the if clause.

File: apps/meteor/tests/end-to-end/api/emoji-custom.ts (hunk 5 above)
Comment (abhinavkrin) [reply apps/meteor/tests/end-to-end/api/emoji-custom.ts:95]: Some tests are already there.
- what happens when no file is provided to update
- Updating the emoji data but no file
These should be covered by
https://github.com/RocketChat/Rocket.Chat/blob/e0fb435ef0b89ef413145205672c5e3382649811/apps/meteor/tests/end-to-end/api/emoji-custom.ts#L99
- what happens when file is provided but none of the data is updated (just the file)
The end point is implemented in such a way that it replaces the provided data completely with the data in db. So it always expects a complete new data in body. So aliases is the only optional field required for the endpoint. This case is covered by https://github.com/RocketChat/Rocket.Chat/blob/e0fb435ef0b89ef413145205672c5e3382649811/apps/meteor/tests/end-to-end/api/emoji-custom.ts#L115

File: apps/meteor/app/api/server/v1/emoji-custom.ts [hunk 7]
```diff
@@ -136,9 +136,10 @@ API.v1.addRoute(
 			fields.previousName = emojiToUpdate.name;
 			fields.previousExtension = emojiToUpdate.extension;
 			fields.aliases = fields.aliases || '';
-			const newFile = Boolean(emoji && fileBuffer.length);
 
-			if (fields.newFile) {
+			const newFile = !!fileBuffer?.length;
+
+			if (fileBuffer?.length) {
```
Comment (KevLehman) [inline apps/meteor/app/api/server/v1/emoji-custom.ts:142]:
```suggestion
			if (newFile) {
```

File: apps/meteor/app/api/server/v1/emoji-custom.ts [hunk 8]
```diff
@@ -160,9 +161,9 @@ API.v1.addRoute(
 				newFile,
 			};
 
-			await insertOrUpdateEmoji(this.userId, emojiData);
-			if (fields.newFile) {
-				await uploadEmojiCustomWithBuffer(this.userId, fileBuffer, mimetype, emojiData);
+			const updatedEmojiData = await insertOrUpdateEmoji(this.userId, emojiData);
+			if (newFile && fileBuffer) {
```
Comment (KevLehman) [inline apps/meteor/app/api/server/v1/emoji-custom.ts:165]: isn't it enough with checking `newFile`?

**Review by KevLehman — DISMISSED** [review]

File: apps/meteor/app/api/server/v1/emoji-custom.ts (hunk 8 above)
Comment (KevLehman) [inline apps/meteor/app/api/server/v1/emoji-custom.ts:164]:
```suggestion
			if (newFile) {
```

**Review by KevLehman — APPROVED** [review]

File: apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts [hunk 9]
```diff
@@ -67,8 +70,10 @@ export async function uploadEmojiCustomWithBuffer(
 			encodeURIComponent(`${emojiData.name}.${emojiData.extension}`),
 			contentType,
 		);
-		ws.on('end', () => {
-			setTimeout(() => api.broadcast('emoji.updateCustom', emojiData), 500);
+		ws.on('end', async () => {
+			const etag = Random.hexString(6);
+			await EmojiCustom.setETagByName(emojiData.name, etag);
```
Comment (KevLehman) [inline apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts:75]: @abhinavkrin i did this here but i'm not sure how safe it is to update by name. Are emoji names unique somehow? Will update this potentially update also other emojis?

(Had to fallback to this because the `uploadEmojiCustom` method was only accepting name/alias/file, so making _id required could break it.

**Review by KevLehman — DISMISSED** [review]

File: apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts (hunk 9 above)
Comment (abhinavkrin) [reply apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts:75]: The emoji names are indeed unique.

**Review by KevLehman — APPROVED** [review]

File: .changeset/green-papayas-thank.md [hunk 10]
```diff
@@ -0,0 +1,7 @@
+---
+'@rocket.chat/model-typings': patch
+'@rocket.chat/core-typings': patch
+'@rocket.chat/meteor': patch
+---
+
+Fixed: 🛠️ Resolved issues with updating custom emojis, including file upload and image caching problems.
```
Comment (tiagoevanp) [inline .changeset/green-papayas-thank.md:7]: Please, follow the patterns described in a section of this page: https://developer.rocket.chat/docs/development-workflow

File: apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx [hunk 11]
```diff
@@ -50,7 +51,7 @@ const EditCustomEmoji = ({ close, onChange, data, ...props }: EditCustomEmojiPro
 		}
 
 		if (data) {
-			return absoluteUrl(`/emoji-custom/${encodeURIComponent(data.name)}.${data.extension}`);
+			return absoluteUrl(`/emoji-custom/${encodeURIComponent(data.name)}.${data.extension}${data.etag ? `?etag=${data.etag}` : ''}`);
```
Comment (tiagoevanp) [inline apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx:54]: I'm not sure this is right? Can you explain why eTag after the extension?

**Review by tiagoevanp — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx (hunk 11 above)
Comment (abhinavkrin) [reply apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx:54]: The url of an emoji is basically depended on the emoji name. So even if the file changes. The url remained the same. Hence, the old emoji was loaded from the browser cache instead of the new file. 

The etag is generated for each new uploads. The is attached to url as query param to load the emoji image. 
This way the emoji will not load from the cache when the new file is upload, since the url will be changed.

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]

File: apps/meteor/app/api/server/lib/getUploadFormData.ts
[the remark this answers is not in the document]
Comment (abhinavkrin) [reply apps/meteor/app/api/server/lib/getUploadFormData.ts:1]: Hey @MarcosSpessatto 
I agree it would be much clearer to have another function, but to implement it, I will have to modify the original function to support optional file. And will have to add a parameter to tell the function if the file is optional or not.

I do believe the 'optional' variable could be confusing. So i have renamed some variables to make its use more clear. wdys?

**Review by MarcosSpessatto — APPROVED** [review]

**Review by KevLehman — APPROVED** [review]

**Review by tassoevan — APPROVED** [review]

**Review by tiagoevanp — APPROVED** [review]
