### PR TITLE
fix: Ensure Translations Work in Offline Registration Setup Wizard

### LINKED ISSUE #35490: Placeholder Text Displayed in Offline Registration Setup Wizard Instead of Translations
### Title
[BUG] Placeholder Text Displayed in Offline Registration Setup Wizard Instead of Translations

### Description
When running the Rocket.Chat setup wizard (workspace registration) locally in offline mode (`http://localhost:3000/setup-wizard/3`), the registration form displays placeholder keys (e.g., `page.form.title`, `form.registerOfflineForm.title`, `component.form.action.next`, `component.form.action.back`) instead of the expected translated text. This issue occurs specifically when attempting to register offline, suggesting a problem with how translations are loaded in this mode.

### Steps to Reproduce
1. Clone the Rocket.Chat repository: `git clone https://github.com/RocketChat/RocketChat.git`.
2. Navigate to the project directory: `cd RocketChat`.
3. Install dependencies and start the app: `meteor reset && meteor`.
4. Open `http://localhost:3000/setup-wizard/3` in your browser.
5. Select the "Register offline" option and observe the form.

### Expected Behavior
The form should display translated text, such as
- "Register Your Workspace" for `page.form.title`.
- "Offline Registration" for `form.registerOfflineForm.title`.
- "Next" for `component.form.action.next`.
- "Back" for `component.form.action.back`.

### Actual Behavior
The form displays the raw placeholder keys instead of the translated text (see the attached video for a demonstration).

### Video Evidence
- Before - Bug Demonstration:

https://github.com/user-attachments/assets/a83885d8-41ab-4328-9079-a0a200a4b869

### Environment
- OS: macOS 13.7.4
- Node.js Version: v22.13.1
- Meteor Version: Meteor 3.1.2
- Browser: Chrome

### Additional Context
- The issue appears to be related to the `RegisterOfflinePage` component not being wrapped in an `I18nextProvider`, which prevented it from accessing the `onboarding` namespace translations.
- I have a potential fix (see the pull request link below) that resolves this by ensuring the component is properly wrapped.

### Possible Fix
- A pull request with the fix has been submitted: #35493

### PR DESCRIPTION
**Pull request by sem22-dev**
### Title
[FIX] Ensure Translations Work in Offline Registration Setup Wizard

### Description
This PR fixes an issue where the offline registration setup wizard (`/setup-wizard/3`) displayed placeholder keys (e.g., `page.form.title`, `form.registerOfflineForm.title`) instead of translated text. The problem was caused by the `RegisterOfflinePage` component not being wrapped in an `I18nextProvider`, preventing it from accessing the `onboarding` namespace translations. The fix involves wrapping both `RegisterServerPage` and `RegisterOfflinePage` in the same `I18nextProvider`.

### Changes
- Modified `app/client/views/setupWizard/RegisterServerStep.tsx` to wrap the conditional rendering of `RegisterServerPage` and `RegisterOfflinePage` in an `I18nextProvider` with the `onboarding` namespace.
- Added `before-video.webm` and `after-video.webm` to `docs/videos/` to demonstrate the bug and fix.
- Tested locally to confirm translations now display correctly.

### Video Evidence
- Before - Bug Demonstration:

https://github.com/user-attachments/assets/5de1e68e-2582-4aa2-ae51-1737d6dcc8a6

- After - Fix Demonstration:

https://github.com/user-attachments/assets/6f9af465-9d33-4a10-8313-83e00ac6ee0b

 

### Issue(s)
- Fixes #35490  

### Testing
1. Clone the repository and checkout this branch.
2. Run `meteor reset && meteor`.
3. Navigate to `http://localhost:3000/setup-wizard/3`.
4. Select "Register offline" and verify that translated text (e.g., "Offline Registration") appears instead of placeholders.

### Checklist
- [x] I have tested this code locally
- [x] I have signed the CLA
- [x] I have followed the Rocket.Chat contributor guidelines
- [x] This contribution is part of my preparation for GSoC 2025

[CORE-1015](https://rocketchat.atlassian.net/browse/CORE-1015)

[CORE-1015]: https://rocketchat.atlassian.net/browse/CORE-1015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sem22-dev** [comment]
Hi maintainers, I’m unable to set a milestone as the dropdown isn’t editable. Could you please assign an appropriate milestone  to this PR? 

Additionally, I’ve tested this fix locally and believe it’s ready for review. Could you please add the 'stat: QA assured' label after verification? This is part of my GSoC 2025 preparation, and I’d appreciate feedback during the workshop on March 15, 2025. Thank you!

**Comment by sem22-dev** [comment]
@changeset-bot This is a bug fix to the core app (RegisterServerStep.tsx) and shouldn’t require a version bump. Please let me know if a changeset is still needed!

**Comment by sem22-dev** [comment]
Hi @yash-rajpal  , thanks for self-assigning PR #35493 ! 
Could you please review it? 

It fixes the offline registration setup wizard translations (issue #35490 ) with `I18nextProvider` and includes before/after videos evidence. Thanks!

File: apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx [hunk 1]
```diff
@@ -16,6 +16,10 @@ const SERVER_OPTIONS = {
 
 const RegisterServerStep = (): ReactElement => {
 	const { t, i18n } = useTranslation();
+	console.log('testing')
```
Comment (MartinSchoeler) [inline apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx:19]: Plz remove the console.logs :)

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx (hunk 1 above)
Comment (sem22-dev) [reply apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx]: Hi @MartinSchoeler , thanks for the feedback! I’ve removed the `console.log('testing')` statement from `RegisterServerStep.tsx` as requested and pushed the change in a new commit.

**Review by yash-rajpal — DISMISSED** [review]
LGTM!

Thanks for the contribution 🚀

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]
Please don't forget to add a changeset

**Review by yash-rajpal — APPROVED** [review]
