### PR TITLE
Fix 'You' on reactions

### LINKED ISSUE #6975: Emoticon reaction: wrong name
Rocket.Chat Version: 2.7.0
Running Instances: Mac desktop client

Emoticon reaction shows a wrong name when someone with the same partial name reacted.

My usename is 'max' and someone else in the chat group is called 'max.s'.

When I hover the emoticon the label shows: 'You.s reacted with :emoticon:'.

So in 'max.s' (my colleague's username) 'max' (my username) is replaced by 'You'. 

I believe the error is in this part of the code.

[https://github.com/RocketChat/Rocket.Chat/blob/ddc6822b33380f34769684d409df73bd4d2da623/packages/rocketchat-ui-message/client/message.coffee#L123](url)

### PR DESCRIPTION
**Pull request by MartinSchoeler**
@RocketChat/core 

Closes #6975

### CODE REVIEW

File: packages/rocketchat-ui-message/client/message.coffee [hunk 1]
```diff
@@ -120,7 +120,8 @@ Template.message.helpers
 			total = reaction.usernames.length
 			usernames = '@' + reaction.usernames.slice(0, 15).join(', @')
 
-			usernames = usernames.replace('@'+userUsername, t('You').toLowerCase())
+			reg = new RegExp('@'+userUsername+'$')
```
Comment (rodrigok) [inline packages/rocketchat-ui-message/client/message.coffee]: You should escape the username cuz it could contains dots or other special characters.
`_.escapeRegExp()`
