### PR TITLE
[FIX] Integrations with room data not having the usernames filled in

### LINKED ISSUE #10416: No Usernames in Request at Outgoing Webhook for Direct Messages
I'm trying to create a webhook that sends a notification when a direct message has been written to a specified user. For that, I want to add a script that just checks whether the direct message is sent to the specified user. Unfortunately, the username of the user who receives the message is not part of the request that I can access in the script. The request only consists of this:

`
{
	_id: 'TAQvbQBejX3HDEcKQzyaX5AbGaA9bH7APu',
	_updatedAt: 2018 - 04 - 11T08: 44: 35.812Z,
	t: 'd',
	msgs: 16,
	ts: 2018 - 04 - 11T08: 17: 22.471Z,
	username: 'assistify.admin',
	lm: 2018 - 04 - 11T08: 44: 35.805Z,
	usernames: ['this_will_be_filled_in_with_usernames_when_replayed']
}
`

So the array for the usernames is not filled but only show this info-string "**this_will_be_filled_in_with_usernames_when_replayed**". It should actually contain the list of users in that room. Also, replaying the outgoing webhook event doesn't help.

### PR DESCRIPTION
**Pull request by graywolf336**
Closes #10416

Also, this fixes an issue happening inside of Zapier.

Basically we are writing to history and doing it by reference then updating the reference of the rooms. So, we are now cloning the data going onto history due to us adjusting the data stored three.

cc: @mrsimpson

### CODE REVIEW

File: packages/rocketchat-integrations/server/lib/triggerHandler.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ RocketChat.integrations.triggerHandler = new class RocketChatIntegrationHandler
 		}
 
 		if (data) {
-			history.data = data;
+			history.data = { ...data };
```
Comment (graywolf336) [inline packages/rocketchat-integrations/server/lib/triggerHandler.js]: Sadly, this does not work as you expect it to work. So, we need to revert this change:
image

**Comment by sampaiodiego** [comment]
I don't know what to do.. lol

even [underscore docs](http://underscorejs.org/#clone) says `_.clone` should now work:

> Create a shallow-copied clone of the provided _plain_ **object**. Any nested objects or arrays will be copied by reference, not duplicated.

File: packages/rocketchat-integrations/server/lib/triggerHandler.js (hunk 1 above)
Comment (rodrigok) [reply packages/rocketchat-integrations/server/lib/triggerHandler.js]: @graywolf336 the _clone doesn't do the same? Copying only the first level of the object?
