### PR TITLE
[FIX] API to retrive rooms was returning empty objects

### LINKED ISSUE #9531: [BUG] API rooms.get may be returning empty object when caching isn't found
screen shot 2018-01-27 at 2 20 01 pm

File (found by @geekgonecrazy): https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/models/Rooms.js#L155

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #9531

### CODE REVIEW

File: packages/rocketchat-lib/server/models/Rooms.js [hunk 1]
```diff
@@ -127,8 +127,8 @@ class ModelRooms extends RocketChat.models._Base {
 					return item._room;
 				}
 				console.log('Empty Room for Subscription', item);
-				return {};
 			});
+			data = data.filter(item => item);
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/models/Rooms.js]: this is weird to see, but it works :joy:

Comment (geekgonecrazy) [reply packages/rocketchat-lib/server/models/Rooms.js]: I suppose returning null evaluates to false during the filter resulting in null being excluded? 

Very odd looking indeed 😁
