### PR TITLE
[FIX] start/unstar message

### LINKED ISSUE #3876: Starred message can't be re-starred after the first time until client is refreshed
Rocket.Chat version: 0.35.0

If you star and unstar a message, the star stays filled and can't be starred again until the client refreshes.

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #3876

peek 2017-05-02 17-41

### CODE REVIEW

File: packages/rocketchat-message-star/client/actionButton.js [hunk 1]
```diff
@@ -18,7 +18,10 @@ Meteor.startup(function() {
 			if (RocketChat.models.Subscriptions.findOne({ rid: message.rid }) == null) {
 				return false;
 			}
-			return RocketChat.settings.get('Message_AllowStarring') && !message.starred;
+
+			const starred = _.findWhere(message.starred, {_id: Meteor.userId()});
+
+			return RocketChat.settings.get('Message_AllowStarring') && !starred;
```
Comment (sampaiodiego) [inline packages/rocketchat-message-star/client/actionButton.js]: there is no need to to a `findWhere` if `RocketChat.settings.get('Message_AllowStarring')` isn't `true`..
