### PR TITLE
[FIX] Exposing some fields on server logs at debug level

### LINKED ISSUE #15360: User passwords are shown in cleartext at the logs when adding a webdav server
# Description:

User passwords are shown in cleartext at the logs when adding a webdav server.

### Steps to reproduce:

1. Enable Log Level "2 - Errors, Information And Debug"
2. User adds a webdav server
3. View the logs

### Expected behavior:

The users password shouldn't be shown in cleartext.

### Actual behavior:

The users password ist shown in cleartext.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: CentOS 7.4
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 4.2.0

### Relevant logs:

I20190913-12:29:01.079(0) Meteor -> method addWebdavAccount -> userId: vQJy96q6h3BvzHhTS , arguments:  [ { name: 'webdav',     serverURL: 'test.fqdn.domain',     username: 'username',     pass: 'password' } ]

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #15360

### CODE REVIEW

File: app/lib/server/lib/debug.js [hunk 1]
```diff
@@ -58,7 +60,7 @@ const wrapMethods = function(name, originalHandler, methodsMap) {
 			has_user: this.userId != null,
 		});
 		const args = name === 'ufsWrite' ? Array.prototype.slice.call(originalArgs, 1) : originalArgs;
-		logger.method(name, '-> userId:', Meteor.userId(), ', arguments: ', args);
+		logger.method(name, '-> userId:', Meteor.userId(), ', arguments: ', omitKeyArgs(args));
```
Comment (sampaiodiego) [inline app/lib/server/lib/debug.js]: to not waste the processing time used to omit fields and not even show the log (because of the log level) I'd consider using the deferred version that is called only when the log will be shown:
```suggestion
		logger.method(() => `${ name } -> userId: ${ Meteor.userId() }, arguments: ${ omitKeyArgs(args) }`);
```

File: app/lib/server/lib/debug.js [hunk 2]
```diff
@@ -79,7 +81,7 @@ const originalMeteorPublish = Meteor.publish;
 Meteor.publish = function(name, func) {
 	return originalMeteorPublish(name, function(...args) {
 		traceConnection(Log_Trace_Subscriptions, Log_Trace_Subscriptions_Filter, 'subscription', name, this.connection, this.userId);
-		logger.publish(name, '-> userId:', this.userId, ', arguments: ', args);
+		logger.publish(name, '-> userId:', this.userId, ', arguments: ', omitKeyArgs(args));
```
Comment (sampaiodiego) [inline app/lib/server/lib/debug.js]: to not waste the processing time used to omit fields and not even show the log (because of the log level) I'd consider using the deferred version that is called only when the log will be shown:
```suggestion
		logger.publish(() => `${ name } -> userId: ${ this.userId }, arguments: ${ omitKeyArgs(args) }`);
```
