### PR TITLE
Regression: sorting direct message by asc on favorites group

### LINKED ISSUE #11088: [BUG] List of channels sorts automatically on new messages
### Description:

**Version:** 0.66.0-develop
**Server:** open.rocket.chat

The list of favorited rooms is sorting automatically on new messages even when the sorting is alphabetically.

Here's a GIF that demonstrates it:

### PR DESCRIPTION
**Pull request by ggazzo**
Actually we don't have name on direct message rooms, so we cant set `lowerCaseName` and `lowerCaseFName` without use and subscriptions

Closes #11088

### CODE REVIEW

File: packages/rocketchat-ui-sidenav/client/roomList.js [hunk 1]
```diff
@@ -116,13 +119,15 @@ const mergeSubRoom = (record/*, t*/) => {
 	}
 	record.lastMessage = room.lastMessage;
 	record.lm = room._updatedAt;
-	return _.extend(record, getLowerCaseNames(record));
+	return _.extend(record, getLowerCaseNames(record, record.name));
```
Comment (tassoevan) [inline packages/rocketchat-ui-sidenav/client/roomList.js]: Isn't redundant to pass `record.name` here?
