### PR TITLE
[FIX] Searching by `undefined` via REST when using `query` param

### LINKED ISSUE #11599: [BUG] 0.68.0 Rest API users.list return empty result
### Description:

The users.list API return an empty result since RC 0.67.0 (again in 0.68.0).

### Steps to reproduce:

CURL on the /api/v1/users.list endpoint with an authennticated user

### Expected behavior:

Return user list

### Actual behavior:

Return empty list : 

```
Httpful\Response {#1108
  +body: {#1109
    +"users": []
    +"count": 0
    +"offset": 0
    +"total": 0
    +"success": true
  }
  +raw_body: "{"users":[],"count":0,"offset":0,"total":0,"success":true}"
  +headers: Httpful\Response\Headers {#1123
    -headers: array:11 [
      "server" => "nginx"
      "date" => "Sun, 29 Jul 2018 16:51:09 GMT"
      "content-type" => "application/json"
      "transfer-encoding" => "chunked"
      "connection" => "keep-alive"
      "vary" => "Accept-Encoding"
      "access-control-allow-origin" => "*"
      "x-instance-id" => "*************"
      "cache-control" => "no-store"
      "pragma" => "no-cache"
      "strict-transport-security" => "max-age=31536000"
    ]
  }
  +raw_headers: """
    HTTP/1.1 200 OK\r\n
    Server: nginx\r\n
    Date: Sun, 29 Jul 2018 16:51:09 GMT\r\n
    Content-Type: application/json\r\n
    Transfer-Encoding: chunked\r\n
    Connection: keep-alive\r\n
    Vary: Accept-Encoding\r\n
    Access-Control-Allow-Origin: *\r\n
    X-Instance-ID: **************\r\n
    Cache-Control: no-store\r\n
    Pragma: no-cache\r\n
    Vary: Accept-Encoding\r\n
    Strict-Transport-Security: max-age=31536000
    """
  +request: Httpful\Request {#1121
    +uri: "https://***********/api/v1/users.list"
    +method: "GET"
    +headers: array:3 [
      "X-Auth-Token" => "**********************************"
      "X-User-Id" => "****************"
      "Content-Length" => 0
    ]
    +raw_headers: """
      GET /api/v1/users.list HTTP/1.1\r\n
      Host: r*************\r\n
      Expect:\r\n
      User-Agent: Httpful/0.2.20 (cURL/7.52.1 PHP/7.2.8-1+0~20180725124257.2+stretch~1.gbp571e56 (Linux))\r\n
      Content-Type: application/json\r\n
      Accept: */*; q=0.5, text/plain; q=0.8, text/html;level=3;q=0.9, application/json\r\n
      X-Auth-Token: ************************\r\n
      X-User-Id: ******************\r\n
      Content-Length: 0\r\n
      """
    +strict_ssl: false
    +content_type: "application/json"
    +expected_type: "application/json"
    +additional_curl_opts: []
    +auto_parse: true
    +serialize_payload_method: 2
    +username: null
    +password: null
    +serialized_payload: null
    +payload: null
    +parse_callback: null
    +error_callback: null
    +send_callback: null
    +follow_redirects: false
    +max_redirects: 25
    +payload_serializers: []
    +_ch: Closed resource @812
    +_debug: null
  }
  +code: 200
  +content_type: "application/json"
  +parent_type: "application/json"
  +charset: "utf-8"
  +meta_data: array:26 [
    "url" => "https://rc.*******************/api/v1/users.list"
    "content_type" => "application/json"
    "http_code" => 200
    "header_size" => 355
    "request_size" => 384
    "filetime" => -1
    "ssl_verify_result" => 0
    "redirect_count" => 0
    "total_time" => 0.02388
    "namelookup_time" => 1.8E-5
    "connect_time" => 0.000356
    "pretransfer_time" => 0.011102
    "size_upload" => 0.0
    "size_download" => 58.0
    "speed_download" => 2428.0
    "speed_upload" => 0.0
    "download_content_length" => -1.0
    "upload_content_length" => -1.0
    "starttransfer_time" => 0.023849
    "redirect_time" => 0.0
    "redirect_url" => ""
    "primary_ip" => "**********"
    "certinfo" => []
    "primary_port" => 443
    "local_ip" => "**********"
    "local_port" => 55654
  ]
  +is_mime_vendor_specific: false
  +is_mime_personal: false
  -parsers: null
}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.0
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v8.11.3
- MongoDB Version: na

### LINKED ISSUE #11636: Users.list doesn't list all users
I have a user called api.test:
`http://localhost:3000/api/v1/users.info?username=api.test`
```
{
    "user": {
        "name": "api.test",
        "username": "api.test",
        "status": "offline",
        "utcOffset": 2,
        "type": "user",
        "active": true,
        "emails": [
            {
                "address": "ApiTest@test.com",
                "verified": true
            }
        ],
        "statusConnection": "offline",
        "createdAt": "2018-02-05T09:17:07.622Z",
        "lastLogin": "2018-07-30T08:56:40.480Z",
        "services": {
            "resume": {
                "loginTokens": [
                    ...
                ]
            },
            "password": {}
        },
        "requirePasswordChange": false,
        "roles": [
            "user"
        ],
        "_id": "YJoHTEqxZJRuQnHeq"
    },
    "success": true
}
```

When I call `http://localhost:3000/api/v1/users.list` it returns a list but the user api.test is not there (just some other users).

I logged in via api as admin.
I can see the user in the admin UI when logged in as an admin.
There is no error shown in the log.

I don't know how to reproduce this since newly created users are always listed in the `users.list` call.

Maybe someone else noticed the same problem.

### LINKED ISSUE #11760: users.list endpoint returning no users at all
### Description:
 When sending a GET request to the mentioned endpoint it does not return any user at all. However I'm able to make requests to `im.list.everyone` without any issue.

### Steps to reproduce:

Make a GET request to the endpoint.

### Expected behavior:

Return the system's users.

### Actual behavior:

Returning empty object.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubuntu Server 18.04 Bionic
- Deployment Method: snap
- Number of Running Instances: 1 
- NodeJS Version: 8.11.3

### Relevant logs:

What the endpoint is actually returning me:
```json
{
    "users": [],
    "count": 0,
    "offset": 0,
    "total": 0,
    "success": true
}

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Closes #11636 
Closes #11599 
Closes #11760

### CODE REVIEW

File: packages/rocketchat-api/server/helpers/parseJsonQuery.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ RocketChat.API.helperMethods.set('parseJsonQuery', function _parseJsonQuery() {
 		}
 	}
 
-	let query;
+	let query = {};
```
Comment (sampaiodiego) [inline packages/rocketchat-api/server/helpers/parseJsonQuery.js]: with this change I guess the test on [line 58](https://github.com/RocketChat/Rocket.Chat/pull/11657/files#diff-7cea0c6e8f09f3c8044452a26c50567bR58) isn't required anymore, right?

Comment (rodrigok) [reply packages/rocketchat-api/server/helpers/parseJsonQuery.js]: Wrong, since `JSON.parse('false');` can generate `query = false`;
