### PR TITLE
[FIX] Compile CSS color variables

### LINKED ISSUE #6931: RC 0.56.0-rc.1 Not apply changes in layout
Rocket.Chat Version: 0.56.0-rc.1
any changes in css or colors not apply in admin/Layout
must restart to apply it...

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #6931

### CODE REVIEW

File: packages/rocketchat-theme/server/server.js [hunk 1]
```diff
@@ -71,25 +71,23 @@ RocketChat.theme = new class {
 		this.compileDelayed = _.debounce(Meteor.bindEnvironment(this.compile.bind(this)), 100);
 		Meteor.startup(() => {
 			RocketChat.settings.onAfterInitialLoad(() => {
-				RocketChat.settings.get('*', Meteor.bindEnvironment((key, value) => {
+				RocketChat.settings.get(/^theme-./, Meteor.bindEnvironment((key, value) => {
```
Comment (sampaiodiego) [inline packages/rocketchat-theme/server/server.js]: is this RegExp correct? looks like it's missing `+`

Comment (rodrigok) [inline packages/rocketchat-theme/server/server.js]: It works cuz the regex does not define the end ($)
