### PR TITLE
[FIX] Broken slack compatible webhook

### LINKED ISSUE #11506: Grafana Web Integration Via Slack Broken
### Description:

Upon creating a notification channel in Grafana using the Slack channel, sending any notification over error are reported in Rocket Chat

### Steps to reproduce:

1. Create notification channel using Slack in Grafana and send notification 
2. Check for errors in Rocket Chat Logs

### Expected behavior:

Messages are displayed within the configured chat room

### Actual behavior:

The following log is displayed;

```
Jul 19 14:28:45  rocketchat: #033[34mIntegrations ➔ Incoming WebHook.info#033[39m Post integration: localhost - Grafana
Jul 19 14:28:45  rocketchat: #033[34mIntegrations ➔ Incoming WebHook.debug#033[39m @urlParams: { integrationId: 'xxxxxxxxxxxx',
Jul 19 14:28:45  rocketchat: token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
Jul 19 14:28:45  rocketchat: #033[34mIntegrations ➔ Incoming WebHook.debug#033[39m @bodyParams: { attachments:
Jul 19 14:28:45  rocketchat: [ { color: '#D63232',
Jul 19 14:28:45  rocketchat: fallback: '[Alerting] Test notification',
Jul 19 14:28:45  rocketchat: fields: [Array],
Jul 19 14:28:45  rocketchat: footer: 'Grafana v5.2.1',
Jul 19 14:28:45  rocketchat: footer_icon: 'https://grafana.com/assets/img/fav32.png',
Jul 19 14:28:45  rocketchat: image_url: '',
Jul 19 14:28:45  rocketchat: text: '@all Someone is testing the alert notification within grafana.',
Jul 19 14:28:45  rocketchat: title: '[Alerting] Test notification',
Jul 19 14:28:45  rocketchat: title_link: 'http://localhost/',
Jul 19 14:28:45  rocketchat: ts: 1532010525 } ],
Jul 19 14:28:45  rocketchat: channel: '#critical-alerts',
Jul 19 14:28:45  rocketchat: parse: 'full' }
Jul 19 14:28:45  rocketchat: #033[34mAPI ➔ debug#033[39m Failure { statusCode: 400,
Jul 19 14:28:45  rocketchat: body:
Jul 19 14:28:45  rocketchat: { success: false,
Jul 19 14:28:45  rocketchat: error: 'Match error: Match error: Expected string, got number in field value' } }
```

### Server Setup Information:

- Version of Rocket.Chat Server:  0.66.3
- Operating System: Centos 7.5
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.9.3
- MongoDB Version: 2.6.12

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Closes #11506

I added integer as a safe type.  Also added Boolean.  Both of which I can see being used, and are safe toString.

Are there any other that are safe to string we could/should include?

### CODE REVIEW

**Comment by kapkoi** [comment]
https://github.com/brave/browser-laptop/commit/248c4e4dca53045aeb94da39de4e9ccdc0a3ed23

Pada Jum, 10 Ogo 2018 11:49 PM Aaron Ogle <notifications@github.com>
menulis:

File: packages/rocketchat-lib/server/functions/sendMessage.js [hunk 1]
```diff
@@ -15,15 +15,20 @@ const objectMaybeIncluding = (types) => {
...
 	}));
 
-	check(attachmentFields, objectMaybeIncluding({
+	check(attachmentField, objectMaybeIncluding({
 		title: String,
-		value: String
+		value: Match.OneOf(String, Match.Integer, Boolean)
 	}));
+
+	if (typeof(attachmentField.value) !== undefined) {
```
Comment (rodrigok) [inline packages/rocketchat-lib/server/functions/sendMessage.js]: Do we need to enforce it as String? I think it's fine to keep it saved in the original format, what do you think?

Comment (geekgonecrazy) [reply packages/rocketchat-lib/server/functions/sendMessage.js]: @rodrigok initially I didn't convert.  But looking at slack's it looks like they are converting to string so added.

But yeah I don't think it matters so much since all accepted will easily be converted to string when displayed in UI

Comment (geekgonecrazy) [reply packages/rocketchat-lib/server/functions/sendMessage.js]: I'll ping mobile teams and see which is better compatible

Comment (geekgonecrazy) [reply packages/rocketchat-lib/server/functions/sendMessage.js]: @rodrigok confirmed with mobile.  Because both clients are using typed languages having as a string is the best way.

**Comment by geekgonecrazy** [comment]
@RocketChat/core lets make sure we get this merged on next release.  Having to personally use the script provided here: https://github.com/RocketChat/Rocket.Chat/issues/11506#issuecomment-407445878 a script shouldn't be needed for a slack payload

File: packages/rocketchat-lib/server/functions/sendMessage.js [hunk 2]
```diff
@@ -13,15 +13,20 @@ const objectMaybeIncluding = (types) => Match.Where((value) => {
 	return true;
 });
 
-const validateAttachmentsFields = (attachmentFields) => {
-	check(attachmentFields, objectMaybeIncluding({
+const validateAttachmentsFields = (attachmentField) => {
+	check(attachmentField, objectMaybeIncluding({
 		short: Boolean,
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/functions/sendMessage.js]: do you mind merging these two checks? 😬

Comment (geekgonecrazy) [reply packages/rocketchat-lib/server/functions/sendMessage.js]: Done 👍
