### PR TITLE
[FIX] Allows to display more than 25 users maximum in the users list

### LINKED ISSUE #21505: Memberlist shows max 25 entries
### Description:

In a channel with many members, memberlist shows at the very most 25 members.

### Steps to reproduce:

1. Go to a channel with more than 25 members.
2. Open memberlist.
3. Force scrollbar to show itself by switching connected/all menu (bypassing other bug, cf. https://github.com/RocketChat/Rocket.Chat/issues/21282).
4. Select (if not already set) to show all members.
5. Results : Text says "Showing: 25 Total [yournumber]" and list shows only 25 persons, even if scrolling down.

### Expected behavior:
See all members when scrolling and have correct counting in text.

### Actual behavior:

See "Steps to reproduce".

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1
- Operating System: Linux

### Client Setup Information

- Desktop App or Browser Version: Firefox ESR and Chromium

### PR DESCRIPTION
**Pull request by Jeanstaquet**
## Proposed changes (including videos or screenshots)

Now when you scroll to the bottom of the users list, it shows more users. Before the fix, the limit for the query for loadMore was calculated so that no additional users could be loaded.

Before

https://user-images.githubusercontent.com/45966964/114249739-baece500-999b-11eb-9bb0-3a5bcee18ad8.mp4

After

https://user-images.githubusercontent.com/45966964/114249895-364e9680-999c-11eb-985c-47aedc763488.mp4

## Issue(s)

Fixes #21505

### CODE REVIEW

**Comment by Jeanstaquet** [comment]
@sampaiodiego Can you review please ? :)

File: client/views/hooks/useMembersList.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export const useMembersList = (
 				options.rid,
 				options.type,
 				{
-					limit: end - start,
+					limit: end,
```
Comment (MartinSchoeler) [inline client/views/hooks/useMembersList.ts:39]: This might fix the immediate issue, but the list is supposed to have a `load more...` when you reach 25 users. Applying this fix would be pretty chaotic in bigger channels (like `#general` in open.rocket.chat, with 351039 users).

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
We should try to restore the `load more` part of the feature instead of removing the limiters. Feel free to dm me at https://open.rocket.chat/direct/martin.schoeler if you want to work together on this.

**Review by MartinSchoeler — APPROVED** [review]
Seems to be working fine after the reactivity fix. Tested with 1000+ users and it is working fine
