### PR TITLE
[FIX] Create channel button on Firefox

### LINKED ISSUE #7919: [BUG] [Redesign] Can't create channel or group on firefox 55
Hey,
I can't create new channel or group on new design (version  0.59. develop) from Firefox 55 but it's works well on chromium 60.0.3112.78 (Developer Build).
When I create channel on Firefox form `Create a New Channel` form closed and page refreshed and nothing created.

### PR DESCRIPTION
**Pull request by karlprieb**
@RocketChat/core 

Closes #7919

### CODE REVIEW

File: tests/chimp-config.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ module.exports = {
 // 	showXolvioMessages: true,
 
 // 	// - - - - CUCUMBER - - - -
-	path: 'tests/end-to-end',
+	path: 'tests/end-to-end/ui',
```
Comment (rodrigok) [inline tests/chimp-config.js]: Why?
