### PR TITLE
[FIX] auto translate cache

### LINKED ISSUE #15762: Recompute message cache for auto translation.
### Description:

The messages on UI are cached. This prevents the re-computation of auto translated messages. Therefore, when the re-render of translated message happens the original message has to be replaced by the translated message. 

Reason: The key for each cached message is `msg._id + _updated.id`. So the translated message with same key exists already in the cache and therefore the translated message will be ignored.

### Steps to reproduce:

1. Subscribe to a channel and activated the auto translate feature to your wish language.
2. Ask someone to write a message to the channel in a different language then you have configured.
3. The translated message will not replace the original message. Although the message has been translated which can be seen in the database.

### Expected behavior:

The original message has to be replaced with the translated message.

### Actual behavior:

This behaviour is intermittent. Sometimes the original message is not replaced by the translated message.

### PR DESCRIPTION
**Pull request by vickyokrm**
This PR closes #15762  and also #15769

### CODE REVIEW

File: app/ui-utils/client/lib/renderMessageBody.js [hunk 1]
```diff
@@ -32,4 +33,4 @@ export const renderMessageBody = mem((message) => {
 
 	return (Array.isArray(tokens) ? tokens.reverse() : [])
 		.reduce((html, { token, text }) => html.replace(token, () => text), html);
-}, 500, ({ _id, _updatedAt }) => _id && _updatedAt && _id + _updatedAt);
+}, 500, (message) => md5(JSON.stringify(message)));
```
Comment (ggazzo) [inline app/ui-utils/client/lib/renderMessageBody.js]: instead  of insert a new lib and hash all the message, what do you think about just use your fields here? we inserted that cache to skip some computations (usually, we just need update a message if the `_updatedAt ` changes), believe there are some fields we dont want to invalidate the message...

Comment (vickyokrm) [reply app/ui-utils/client/lib/renderMessageBody.js]: @ggazzo imho by using additional fields for example `translations` in this case would add complexity to the cache key and will not have any difference since the cache will be invalidated after 500ms. At least i cannot imagine where this add additional keys will be beneficial.

Comment (vickyokrm) [reply app/ui-utils/client/lib/renderMessageBody.js]: If your concern lies around adding a new lib, then how about [cypto](https://nodejs.org/docs/v0.6.18/api/crypto.html#crypto_crypto_createhash_algorithm)?
