### PR TITLE
[FIX] Cannot create a discussion from top left sidebar as a user

### LINKED ISSUE #22534: [3.16.x] Cannot create a discussion from the top left sidebar as a user.
### Description:

Since at least 3.16.0, it's impossible to create a discussion from the "Create new" icon on the top left sidebar as a user.
The channel/group list is seen as "Empty" so the "Create" button will stay greyed out. 

### Steps to reproduce:

1. Start a fresh install
2. Create an admin user and a normal user
3. As the admin, try to create a discussion from the top left sidebar, it will work (you will see the general channel in the channel list)
4. As a user, try to create a discussion from the top left sidebar, it will **not** work (the channel list will remains empty)

### Expected behavior:

A user should be able to create a discussion from the top left sidebar.

### Actual behavior:

A user can't create a discussion from the top left sidebar.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Debian Buster
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.1.1 or any browser (like chromium for example)
- Operating System: Debian Buster

### Additional context

Creating a discussion directly from the parent room is working, so the issue is probably in the RoomAutoComplete part I guess (which is related to /api/v1/rooms.autocomplete.channelAndPrivate AFAIK).

### Relevant logs:

There is an object (most likely the room list) return for the admin, not the user.

Admin logs:
```
I20210701-13:12:34.232(2)? API ➔ debug GET: /api/v1/rooms.autocomplete.channelAndPrivate?selector={%22name%22:%22%22}
I20210701-13:12:34.238(2)? API ➔ debug Success { statusCode: 200, body: { items: [ [Object] ], success: true } }
I20210701-13:12:34.274(2)? API ➔ debug GET: /api/v1/users.autocomplete?selector={%22term%22:%22%22}
I20210701-13:12:34.280(2)? API ➔ debug Success {
I20210701-13:12:34.280(2)?   statusCode: 200,
I20210701-13:12:34.280(2)?   body: { items: [ [Object], [Object], [Object] ], success: true }
I20210701-13:12:34.281(2)? }
```

User logs:
```
I20210701-13:11:39.711(2)? API ➔ debug GET: /api/v1/rooms.autocomplete.channelAndPrivate?selector={%22name%22:%22%22}
I20210701-13:11:39.720(2)? API ➔ debug Success { statusCode: 200, body: { items: [], success: true } }
I20210701-13:11:39.725(2)? API ➔ debug GET: /api/v1/users.autocomplete?selector={%22term%22:%22%22}
I20210701-13:11:39.730(2)? API ➔ debug Success {
I20210701-13:11:39.730(2)?   statusCode: 200,
I20210701-13:11:39.731(2)?   body: { items: [ [Object], [Object], [Object] ], success: true }
I20210701-13:11:39.731(2)? }
```

### PR DESCRIPTION
**Pull request by lucassartor**
## Proposed changes (including videos or screenshots)

When trying to create a discussion using the top left sidebar modal with an role that don't have the `view-other-user-channels ` permission, an empty list would be shown, which is a wrong behavior.
Also, when being able to use this modal, discussions were listed as options, which is also a wrong behavior as there can't be nested discussions.

This PR looks to fix both these issues.

**Old behavior:**
old

**New behavior:**
image

## Issue(s)

[Task - ClickUp](https://app.clickup.com/t/zdfvmu)
Fixes #22534

## Steps to test or reproduce

1. Start a fresh install
2. Create an admin user and a normal user
3. As the admin, try to create a discussion from the top left sidebar, it will work (you will see the general channel in the channel list)
4. As a user, try to create a discussion from the top left sidebar, it will not work (the channel list will remains empty)

### CODE REVIEW

**Review by matheusbsilva137 — APPROVED** [review]

File: app/api/server/lib/rooms.js [hunk 1]
```diff
@@ -110,11 +107,12 @@ export async function findChannelAndPrivateAutocomplete({ uid, selector }) {
...
 		},
 	};
-	const userRooms = Subscriptions.cachedFindByUserId(uid, { fields: { rid: 1 } })
+
+	const userRoomsIds = Subscriptions.cachedFindByUserId(uid, { fields: { rid: 1 } })
 		.fetch()
 		.map((item) => item.rid);
 
-	const rooms = await Rooms.findChannelAndPrivateByNameStarting(selector.name, userRooms, options).toArray();
+	const rooms = await Rooms.findRoomsWithoutDiscussionsByRoomIds(selector.name, userRoomsIds, options).toArray();
```
Comment (pierre-lehnen-rc) [inline app/api/server/lib/rooms.js:115]: This will affect every room auto complete field on rocket.chat, not only the one in the create discussion modal.
I don't know if that's ok or not.

Comment (matheusbsilva137) [reply app/api/server/lib/rooms.js:115]: I think that's ok considering that currently we filter rooms in autocomplete by the `name` field, BUT discussions' "real names" are stored in the `fname` field (`name` only stores a code in discussions).
So I guess that currently autocomplete is not efficient to find discussions (which means this change would just remove these discussions' codes from the autocomplete). What do you think?
