### PR TITLE
[FIX] CORS config not accepting multiple origins

### LINKED ISSUE #13889: [BUG] Rocket chat will always set header Access-Control-Allow-Origin
### Description:

Comes from: [DocsIssues 1155](https://github.com/RocketChat/docs/issues/1155)

If you embed RocketChat in a second web, lets call it **https://domain2.com**
There is a problem:
You cant specify more than 1 url in 'Access-Control-Allow-Origin'.
RFC says Yes (delimited by comas ",") but most major browsers still say No and will throw a error.

The big problem is that RocketChat server will always include 'Access-Control-Allow-Origin' ignoring the option in Administration -> General -> Rest-Api (see image)

CORS PROBLEM

It doesn't matter if you set it to **True** or **False**. It will always include **'Access-Control-Allow-Origin'**.

The thing is that this way you **can not** do websocket, Rest-Api or RealTimeApi request. They will fail when Authentication is needed and a preflight OPTION needs to be passed to RocketChat Server. Browser will deny it.

You should allow 'Access-Control-Allow-Origin' to be specified in the Apache2 virtualhost, Nginx or whatever everyone else is using.

If you try to include **'Access-Control-Allow-Origin'** in the **virtualhost** file you get a error for duplicate, and it throws it with both **True** and **False** option selected.
Remember that in authenticated request you cant specify "*" and even if you could its a security breach if you do it.

### Steps to reproduce:

1. Embed RocketChat in a **first** domain. For example: https://**domain1**.com
2. If you want Authenticated Request across CORS you have to go to: https://my.Rocket.Chat.Url/ -> Administration -> General -> Rest-Api -> Enable CORS and in CORS Origin write https://**domain1**.com (like in image)

CORS PROBLEM 1

3. Till now all good.
4. Now embed RocketChat in a **second** domain. For example: https://**domain2**.com
5. Again, if you want Authenticated Request across CORS you have to go to: https://my.Rocket.Chat.Url/ -> Administration -> General -> Rest-Api -> Enable CORS and in CORS Origin write https://**domain2**.com (but we dont want to deny access to: https://**domain1**.com, so we add our second domain at the end, like in image)

CORS PROBLEM 2

### Expected behavior:

domain1 and domain2 should be allowed to perform CORS request.

### Actual behavior:

Browser says NO:
`The 'Access-Control-Allow-Origin' header contains multiple values 'https://domain1.com,https://comain2.com', but only one is allowed. Origin 'https://domain2.com' is therefore not allowed access.`

The easy way should be (under Apache2):
1. Create a subdomain called chat.domain2.com
2. Edit the virtualhost config file adding:
**'Header always set Access-Control-Allow-Origin https://domain2.com'**
(plus additional config specified in [DocsIssues 1155](https://github.com/RocketChat/docs/issues/1155) )

3. But for now you cant specify 'Access-Control-Allow-Origin' parameter because it will throw a **duplicate** error.

### Server Setup Information:

Version of Rocket.Chat Server: 0.74.2
Operating System: Linux x64, Ubuntu 18.04
Deployment Method: snap
Number of Running Instances: 1
NodeJS Version: v8.11.4

### PR DESCRIPTION
**Pull request by g-thome**
## Proposed changes (including videos or screenshots)

always include only one value in access-control-allow-origin

## Issue(s)

Closes #13889

### CODE REVIEW

File: app/api/server/api.js [hunk 1]
```diff
@@ -392,6 +399,18 @@ export class APIClass extends Restivus {
...
 
 						result = DDP._CurrentInvocation.withValue(invocation, () => originalAction.apply(this));
+
+						if (multiOrigin) {
+							console.log('should support multi origin');
+
+							if (origin.includes(this.request.headers.origin)) {
+								console.log('allowed header');
+								this.response.setHeader('Access-Control-Allow-Origin', this.request.headers.origin);
+								this.response.setHeader('x-oloco-bixo', 'essa fera ai meu');
```
Comment (ggazzo) [inline app/api/server/api.js:409]:
```suggestion
								this.response.setHeader('x-oloco-bixo', 'oito e sete galera');
```

**Review by ggazzo — CHANGES_REQUESTED** [review]

File: app/api/server/api.js (hunk 1 above)
Comment (g-thome) [reply app/api/server/api.js:409]: oh my

**Review by sampaiodiego — APPROVED** [review]
