### PR TITLE
[FIX] Error when user roles is missing or is invalid

### LINKED ISSUE #8958: Error if user has no role
### Description:
If some how the user has no role a user cannot login and things break all around for that user.

We should handle this more gracefully 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3

### Steps to Reproduce:

1. Create user with out roles field.

### PR DESCRIPTION
**Pull request by paulovitin**
@RocketChat/core 

Closes #8958

Adds:
  - Check if roles is present in user and is valid array;
  - i18n messages;

### CODE REVIEW

File: server/lib/accounts.js [hunk 1]
```diff
@@ -168,6 +168,12 @@ Accounts.validateLoginAttempt(function(login) {
 		});
 	}
 
+	if (!{}.hasOwnProperty.call(login.user, 'roles') || !Array.isArray(login.user.roles)) {
```
Comment (graywolf336) [inline server/lib/accounts.js]: I'm not sure about others, but I find `!{}.hasOwnProperty.call` to be a tad confusing at first glance. Can we change this to something like `if (login.user && (!login.user.roles || Array.isArray(login.user.roles)) {}`?

Comment (paulovitin) [reply server/lib/accounts.js]: Why not?! I will change and update the branch too.

Sorry about that, I like to follow [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins).

Comment (graywolf336) [reply server/lib/accounts.js]: Because if you look through the rest of our code base, you will see the style is how I mentioned. So, it's more about being consistent than anything to be honest.

Comment (geekgonecrazy) [reply server/lib/accounts.js]: Maybe we should look at making part of our style guide if this is a more proper way of checking for the property?

But I do agree on we need to stay consistent, I don't think we use that elsewhere.  Not to say we shouldn't... just we don't so does make it stick out.

Even a comment with a note about the style guide would help a bit in regards to readability here.

All for better code.

Comment (paulovitin) [reply server/lib/accounts.js]: I agree about the consistency of style. In this particular piece of code, even the user.roles is undef or null or false, we have the second criteria to check if is array, so this dont cause any bug.

But is good idea too make the things in most safety away. Is a good idea add this in style guide in future.

Comment (geekgonecrazy) [reply server/lib/accounts.js]: I believe we have an issue discussion code style #1163 this would be good to add to discussion as something to include

Comment (paulovitin) [reply server/lib/accounts.js]: Sure @geekgonecrazy :)
