### PR TITLE
fix(ux): show error message for invalid email domain on signup

### LINKED ISSUE #38933: Signup does not display error message when email domain validation fails
### Description

When attempting to sign up with an invalid email domain, the API returns an error response:

{
  "success": false,
  "error": "Invalid domain [error-invalid-domain]",
  "errorType": "error-invalid-domain"
}

However, no visible error message is displayed to the user after clicking "Join your team".

The user receives no feedback in the UI, making it unclear why signup failed.

This was observed on the public workspace at:

https://open.rocket.chat/channel/opensource2026

### Steps to reproduce

1. Go to https://open.rocket.chat/channel/opensource2026

2. Click "Join your team"

3. Enter an email with an invalid domain

4. Click submit

5. Observe that no error message is shown in the UI

6. Check browser network tab -> API returns error-invalid-domain

### Expected behavior

A clear and visible error message should be shown to the user, such as:

"Please enter a valid email address."
or

"This email domain is not allowed."

### Actual behavior

No visible error message is displayed in the UI.

The API correctly returns an error response, but it is not surfaced to the user.

Image

### Server Setup Information

Version of Rocket.Chat Server: Observed on open.rocket.chat (public instance)

License Type: Not applicable (testing on public instance)

Number of Users: Not applicable (testing on public instance)

Operating System: Not applicable (testing on public instance)

Deployment Method: Public hosted instance

Number of Running Instances: Not applicable

DB Replicaset Oplog: Not applicable

NodeJS Version: Not applicable

MongoDB Version: Not applicable

### Client Setup Information

Browser: Google Chrome (latest)

Operating System: Windows 11

### Additional context

This appears to be a frontend error handling issue where error-invalid-domain is not mapped to a visible user-facing message during signup.

### Relevant logs

Browser Network Response

Request URL: https://open.rocket.chat/api/v1/users.register

Response:

{
  "success": false,
  "error": "Invalid domain [error-invalid-domain]",
  "errorType": "error-invalid-domain",
  "details": {
    "function": "RocketChat.validateEmailDomain"
  }
}

Browser Console

No visible frontend error displayed.
No additional console errors observed related to signup failure.

Server Logs

Not available (testing on public instance: open.rocket.chat)

### PR DESCRIPTION
**Pull request by mossae**
## Proposed changes

This pull request enhances the user signup experience by properly displaying a localized error message when the `error-invalid-domain` response is returned by the API. Previously, submitting an email with an invalid email domain resulted in no visible feedback in the UI, leaving users confused. The change adds specific error handling in the registration form and introduces a new translation key so that users will see:

**“The entered email has invalid email domain”** (or its localized equivalent) when this error occurs. 

- Added handling for `error-invalid-domain` in the registration form (`RegisterForm.tsx`)
- Introduced the `registration.component.form.invalidEmailDomain` key to the i18n language files

This improves the overall UX and aligns server error responses with visible UI feedback.

## Issue(s)
[COMM-144]
Closes #38933 

## Steps to test or reproduce

1. Navigate to the open.rocket.chat/channel/opensource2026 page.
2. Enter an email address having an invalid domain (one disallowed by the server’s domain policy).
3. Click “Join team” 
4. Observe that the localized error message **“The entered email has invalid email domain”** appears under the email field.

## Further comments

This fix adds straightforward error mapping and i18n support without altering any existing flows beyond improving user feedback. The change follows Rocket.Chat’s backend-to-UI error handling conventions and ensures that developers and end users receive clear and appropriate messaging for domain validation failures.

Also added corresponding i18n entries for this new translation key in the language files (English plus other languages). Ensure translations are in the appropriate i18n directory so Rocket.Chat’s internationalization system picks them up correctly.

## Summary by CodeRabbit

* **New Features**
  * Registration form now shows a domain-specific email validation error when applicable.
  * The new error message is translated and available across many locales, appearing in the user’s selected language.

[COMM-144]: https://rocketchat.atlassian.net/browse/COMM-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mossae** [comment]
Thank you for reviewing this PR 

Once the code review is complete, could a maintainer please:

- Add the `stat: QA assured` label
- Assign the appropriate milestone or project

Happy to address any feedback or fix any issues!

**Comment by ricardogarim** [comment]
Hey @mossae, thank you for the contribution!

Could you please add a changeset and run the linter on the TS/TSX files? This will help us move the PR forward.

File: packages/web-ui-registration/src/RegisterForm.tsx [hunk 1]
```diff
@@ -93,6 +93,9 @@ export const RegisterForm = ({ setLoginRoute }: { setLoginRoute: DispatchLoginRo
 					if (error.errorType === 'error-user-already-exists') {
 						setError('username', { type: 'user-already-exists', message: t('registration.component.form.usernameAlreadyExists') });
 					}
+				if (error.errorType === 'error-invalid-domain') {
+					setError('email', { type: 'invalid-domain', message: t('registration.component.form.invalidEmailDomain') });
+				}
```
Comment (ggazzo) [inline packages/web-ui-registration/src/RegisterForm.tsx]:
```suggestion
					if (error.errorType === 'error-invalid-domain') {
						setError('email', { type: 'invalid-domain', message: t('registration.component.form.invalidEmailDomain') });
					}
```

**Review by ggazzo — DISMISSED** [review]

**Comment by mossae** [comment]
Thank you for the feedback.

I’ve added the required changeset and resolved the linting issues for the TS/TSX files.
 
The PR should be ready for review again. Please let me know if anything else needs adjustment. #

> Hey @mossae, thank you for the contribution!
> 
> Could you please add a changeset and run the linter on the TS/TSX files? This will help us move the PR forward.
