### PR TITLE
[FIX] Send a message when muted returns inconsistent result in chat.sendMessage

### LINKED ISSUE #10696: [BUG] Send a message when muted returns inconsistent result
### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1

### Steps to Reproduce:

1. User is muted.
2. Tries to send a message.
3. The result returned is: `{"message":false,"success":true}`

This was tested on main public server `open.rocket.chat` using the REST endpoint:

> /api/v1/chat.sendMessage

Maybe it helps to point out that on the realtime api the response is different: `a["{\"msg\":\"result\",\"id\":\"25\",\"result\":false}"]`.

### Expected behavior:

We should use a proper HTTP status code response. If it's not possible, I think we should at least get a consistent result such as an empty object, but not false.

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Change the message that returns, when a muted or blocked user tries to send a message using that endpoint.
Closes #10696

### CODE REVIEW

File: packages/rocketchat-api/server/v1/chat.js [hunk 1]
```diff
@@ -156,7 +156,7 @@ RocketChat.API.v1.addRoute('chat.sendMessage', { authRequired: true }, {
 		}
 
 		let message;
-		Meteor.runAsUser(this.userId, () => message = Meteor.call('sendMessage', this.bodyParams.message));
+		Meteor.runAsUser(this.userId, () => message = Meteor.call('sendMessage', this.bodyParams.message, 'RESTAPI'));
```
Comment (graywolf336) [inline packages/rocketchat-api/server/v1/chat.js]: We do not need to be adding origins and where things are coming from. Let's just always throw an error and if the web client needs to change to handle it, then we will need to change it.
