### PR TITLE
[FIX] SAML login not working when user has multiple emails

### LINKED ISSUE #11603: ya Login crash SAML 0.68.0
### Description:

Another SAML logi bug

### Steps to reproduce:

1. Click on the non-descriptive blue button to start the LOGIN saml process
1. Login on to the SAML provider
1. Rocketchat gives internal server error

### Expected behavior:

This is kinda what im slowly considering to expect from Rocket.Chat, considering https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+saml but it's not desirable behavior

### Actual behavior:

internal server error

```
rocketchat_1          | rocketchat
rocketchat_1          | { actionName: 'validate',
rocketchat_1          |   serviceName: 'rocketchat',
rocketchat_1          |   credentialToken: undefined }
rocketchat_1          | [ { provider: 'rocketchat',
rocketchat_1          |     entryPoint: 'https://sso.xdfgdxg.com/simplesaml/saml2/idp/SSOService.php',
rocketchat_1          |     idpSLORedirectURL: 'https://sso.xdgxdgdxfg.com/simplesaml/saml2/idp/SingleLogoutService.php',
rocketchat_1          |     issuer: 'https://chat.xrtrdtdg.com/_saml/metadata/rocketchat',
rocketchat_1          |     cert: 'MIIDezCCAmOgAwIBAgIJAMrWKKuUpZ/LMA0GCSqGSIb3DQEBCwUAMFQxCzAJBgNV\nBAYTAk5MMRMwEQYDVQQIDApTb21lLVN0YXRlMRUwEwYDVQQKDAxKYW1pb3VzIFNB\nTUwxGTAXBgNVBAMMEHNhbWwuamFtaW91cy5jb20wHhcNMTcxMTEzMDkzMTM3WhcN\nMjcxMTEzMDkzMTM3WjBUMQswCQYDVQQGEwJOTDETMBEGA1UECAwKU29tZS1TdGF0\nZTEVMBMGA1UECgwMSmFtaW91cyBTQU1MMRkwFwYDVQQDDBBzYW1sLmphbWlvdXMu\nY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCA6xY8yfvjoc=\n-----END CERTIFICATE-----',
rocketchat_1          |     privateKey: '-----BEGIN PRIVATE asdasd adsasdaPRIVATE KEY-----',
rocketchat_1          |     callbackUrl: 'https://chat.sfsdfsdfsfsd.com/_saml/validate/rocketchat',
rocketchat_1          |     id: 'id-SLWYw9Q2MgBwX4bWs',
rocketchat_1          |     protocol: 'https://',
rocketchat_1          |     path: '/saml/consume',
rocketchat_1          |     identifierFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
rocketchat_1          |     authnContext: 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport' } ]
rocketchat_1          | rocketchat
rocketchat_1          | RESULT :{"profile":{"inResponseToId":"id-SLWYw9Q2MgBwX4bWs","issuer":"https://sso.dfsfsdfsdf.com/simplesaml/saml2/idp/metadata.php","nameID":"_d6fa783f7193ec505fb134739fe9d5da749e119f24","nameIDFormat":"urn:oasis:names:tc:SAML:2.0:nameid-format:transient","sessionIndex":"_05da668232588db0ec965ddc3380152e2fff71a431","uid":"aahrouch","mail":["email1","email2"],"givenName":"firstname","displayName":"first name last name","sn":"lastname","cn":"commonname","memberOf":["cn=wah,ou=company,dc=wha,dc=com"],"entryDN":"cn=username,ou=people,dc=asdad,dc=com","groups":["dgdfg","xgdf","xdg"],"email":["email1","email2"]}}
rocketchat_1          | Exception while invoking method 'login' TypeError: s.replace is not a function
rocketchat_1          |     at Function.RegExp.js.RegExp.escape (/app/bundle/programs/server/app/app.js:13197:12)
rocketchat_1          |     at MethodInvocation.<anonymous> (/app/bundle/programs/server/packages/steffo_meteor-accounts-saml.js:164:26)
rocketchat_1          |     at /app/bundle/programs/server/packages/accounts-base.js:876:30
rocketchat_1          |     at tryLoginMethod (/app/bundle/programs/server/packages/accounts-base.js:702:14)
rocketchat_1          |     at AccountsServer.Ap._runLoginHandlers (/app/bundle/programs/server/packages/accounts-base.js:875:18)
rocketchat_1          |     at AccountsServer.Accounts._runLoginHandlers (/app/bundle/programs/server/packages/rocketchat_lib.js:3345:36)
rocketchat_1          |     at MethodInvocation.methods.login (/app/bundle/programs/server/packages/accounts-base.js:933:27)
rocketchat_1          |     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
rocketchat_1          |     at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)
rocketchat_1          |     at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)
rocketchat_1          |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
rocketchat_1          |     at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)
rocketchat_1          |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
rocketchat_1          |     at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)
rocketchat_1          |     at new Promise (<anonymous>:null:null)
rocketchat_1          |     at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)
rocketchat_1          |     at /app/bundle/programs/server/packages/ddp-server.js:754:85
rocketchat_1          |
```

### Server Setup Information:

rocketchat_1          | Using GridFS for custom sounds storage
rocketchat_1          | Using GridFS for custom emoji storage
rocketchat_1          | ➔ System ➔ startup
rocketchat_1          | ➔ +-------------------------------------------------+
rocketchat_1          | ➔ |                  SERVER RUNNING                 |
rocketchat_1          | ➔ +-------------------------------------------------+
rocketchat_1          | ➔ |                                                 |
rocketchat_1          | ➔ |  Rocket.Chat Version: 0.68.0                    |
rocketchat_1          | ➔ |       NodeJS Version: 8.11.3 - x64              |
rocketchat_1          | ➔ |             Platform: linux                     |
rocketchat_1          | ➔ |         Process Port: 3000                      |
rocketchat_1          | ➔ |             Site URL: https://chat.szfszfsfsfsdfs.com  |
rocketchat_1          | ➔ |     ReplicaSet OpLog: Enabled                   |
rocketchat_1          | ➔ |          Commit Hash: e22ea70284                |
rocketchat_1          | ➔ |        Commit Branch: HEAD                      |
rocketchat_1          | ➔ |                                                 |
rocketchat_1          | ➔ +-------------------------------------------------+

### PR DESCRIPTION
**Pull request by Hudell**
Closes #11603

### CODE REVIEW

File: packages/meteor-accounts-saml/saml_server.js [hunk 1]
```diff
@@ -114,10 +114,12 @@ Accounts.registerLoginHandler(function(loginRequest) {
 				name: loginResult.profile.cn || loginResult.profile.username,
 				active: true,
 				globalRoles: ['user'],
-				emails: [{
-					address: loginResult.profile.email,
-					verified: true
-				}]
+				emails: emailList.map(email => {
```
Comment (sampaiodiego) [inline packages/meteor-accounts-saml/saml_server.js]: this can be simplified to:
```javascript
emails: emailList.map((email) => {
	address: email,
	verified: true
})

File: packages/meteor-accounts-saml/saml_server.js [hunk 2]
```diff
@@ -103,8 +103,8 @@ Accounts.registerLoginHandler(function(loginRequest) {
 	}
 
 	if (loginResult && loginResult.profile && loginResult.profile.email) {
-		const email = RegExp.escape(loginResult.profile.email);
-		const emailRegex = new RegExp(`^${ email }$`, 'i');
+		const emailList = Array.isArray(loginResult.profile.email) ? loginResult.profile.email : [loginResult.profile.email];
```
Comment (sampaiodiego) [inline packages/meteor-accounts-saml/saml_server.js]: in this cases I usually do something like: `const emailList = [].concat(loginResult.profile.email);`

**Comment by ChessSpider** [comment]
👍 nice and quick
I do wonder how it works with user-matching though? Bcause that happens on email address too right?

**Comment by Hudell** [comment]
It'll search for each email separately.
