### PR TITLE
[FIX] Prune messages by cron if room not updated

### LINKED ISSUE #12862: 0.72.1 GDPR / Policy retention : Message not removed.
### Steps to reproduce:

1. Add policy retention for channels or private groups
2. Wait
3. Wait
4. Message are not removed

### Expected behavior:

Message shoud be removed.

### Actual behavior:

Policy retention was configured since 1 month ago, so should by good for crons. I can see this log in my log file: 
`[34mI20181205-09:15:21.027(1) rocketchat_logger rocketchat_logger.js:299 [34mSyncedCron ➔ info Scheduled "Prune old messages by retention policy" next run @Thu Dec 06 2018 00:00:00 GMT+0100 (CET)`

Actual policy retention is configured for 3 months, but I can see message from 1st january 2018.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.1
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: disable
- NodeJS Version: 8.12.0
- MongoDB Version: no idea

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #12862
@sampaiodiego I removed the lastPrune tweak... lets see if we face any performance problem...

otherwise we have to save the `lastprune - maxAge` on each room...

### CODE REVIEW

File: app/retention-policy/server/cronPruneMessages.js [hunk 1]
```diff
@@ -27,11 +27,11 @@ function job() {
 	// get all rooms with default values
 	types.forEach((type) => {
 		const maxAge = maxTimes[type] || 0;
-		const latest = new Date(now.getTime() - maxAge * toDays);
+		const latest = new Date(now.getTime() - toDays(maxAge));
 
 		Rooms.find({
 			t: type,
-			_updatedAt: { $gte: latest },
+			// _updatedAt: { $gte: latest },
```
Comment (sampaiodiego) [inline app/retention-policy/server/cronPruneMessages.js]:
```suggestion
```

File: app/retention-policy/server/cronPruneMessages.js [hunk 2]
```diff
@@ -46,25 +46,25 @@ function job() {
 		'retention.enabled': { $eq: true },
 		'retention.overrideGlobal': { $eq: true },
 		'retention.maxAge': { $gte: 0 },
-		_updatedAt: { $gte: lastPrune },
+		// _updatedAt: { $gte: lastPrune },
```
Comment (sampaiodiego) [inline app/retention-policy/server/cronPruneMessages.js]:
```suggestion
```

File: app/retention-policy/server/cronPruneMessages.js [hunk 3]
```diff
@@ -46,25 +46,25 @@ function job() {
...
 	}).forEach((room) => {
 		const { maxAge = 30, filesOnly, excludePinned } = room.retention;
-		const latest = new Date(now.getTime() - maxAge * toDays);
+		const latest = new Date(now.getTime() - toDays(maxAge));
 		cleanRoomHistory({ rid: room._id, latest, oldest, filesOnly, excludePinned, ignoreDiscussion });
 	});
-	lastPrune = new Date(now.getTime() - gracePeriod);
+	// lastPrune = new Date(now.getTime() - getGrace(settings.get('RetentionPolicy_Precision')));
```
Comment (sampaiodiego) [inline app/retention-policy/server/cronPruneMessages.js]:
```suggestion
```

File: app/retention-policy/server/cronPruneMessages.js [hunk 4]
```diff
@@ -83,27 +83,28 @@ function deployCron(precision) {
 
 function reloadPolicy() {
 	types = [];
+	// lastPrune = oldest;
```
Comment (sampaiodiego) [inline app/retention-policy/server/cronPruneMessages.js]:
```suggestion
```
