### PR TITLE
[FIX] 50 custom emoji limit

### LINKED ISSUE #14743: Custom Emoji Admin Pane capped at 50
### Description:

Custom Emoji Admin Pane capped at 50?

### Steps to reproduce:

1. Upload more than 50 Emoji.  (We have about 116 uploaded.)
2. Go to the Custom Emoji Pane in Admin Settings 
3. Try searching for emoji that are past the 50 limit

### Expected behavior:

**On the Admin -> Custom Emoji Pane**
The list should populate with all custom emoji.

### Actual behavior:

**On the Admin -> Custom Emoji Pane**
The list is capped at 50 out of 116 so anything past 50 is cannot be deleted or edited.
Emoji that are past the 50 cannot be searched for either in the admin pane.  

**In a channel, DM, Thread, Discussion, etc.**
All 116 do show up in the chat screen emoji menu.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 16.04
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.9

### Additional context

I'm not seeing any buttons for pagination so I'm assuming that it is a bug that only pulls 50 emoji.  We're on 1.0.3 but I checked the release logs and searched the issues but didn't see anything regarding this.

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #14743

### CODE REVIEW

File: app/emoji-custom/client/admin/adminEmoji.js [hunk 1]
```diff
@@ -31,7 +31,10 @@ Template.adminEmoji.helpers({
 	hasMore() {
 		if (Template.instance().limit != null) {
 			if (typeof Template.instance().customemoji === 'function') {
-				return Template.instance().limit.get() === Template.instance().customemoji().length;
+				return (
+					Template.instance().limit.get()
+					=== Template.instance().customemoji().length
```
Comment (graywolf336) [inline app/emoji-custom/client/admin/adminEmoji.js]: Please revert this change, makes it hard to read...

Comment (ggazzo) [reply app/emoji-custom/client/admin/adminEmoji.js]: sorry, autolint 😞

Comment (graywolf336) [reply app/emoji-custom/client/admin/adminEmoji.js]: Yikes, that's an aggressive one 😮
