### PR TITLE
fix: Responsiveness of New Integration

### LINKED ISSUE #27634: Integrations section is not responsive.
### Description 
In Integrations section, the page is not responsive for the screen size of width less than 650px.

### Steps to reproduce
1. Navigate to _Integrations_ inside _fully featured_
2. Press _New_ to create an integration.

## Preview
image

### Server Setup Information:

Version : 5.5.0-develop
Deployment ID : e59SBD8ijDSbKw2o3
Apps Engine Version : 1.36.0
Node Version : v14.19.3
Database Migration : 281 (December 24, 2022 11:35 AM)
MongoDB : 5.0.5 / wiredTiger (oplog Enabled)

### PR DESCRIPTION
**Pull request by adijr9487**
## Proposed changes (including videos or screenshots)

Improved the responsiveness by adding maxWidth property.
image

## Issue(s)

Closes #27634 
## Steps to test or reproduce

Switch to chrome dev tool and test it below 600px width.
## Reviewer

### CODE REVIEW

File: apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js [hunk 1]
```diff
@@ -45,15 +45,15 @@ export default function IncomingWebhookForm({ formValues, formHandlers, extraDat
 
 	return (
 		<Page.ScrollableContentWithShadow
-			pb='x24'
-			mi='neg-x24'
+			// pb='x24'
+			// mi='neg-x24'
```
Comment (ggazzo) [inline apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js:49]: Remove comments

**Review by ggazzo — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js (hunk 1 above)
Comment (adijr9487) [reply apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js]: Removed !! @ggazzo

**Comment by adijr9487** [comment]
@dougfabris Please review

**Review by dougfabris — APPROVED** [review]
