### PR TITLE
[FIX] New Integration page was not being displayed

### LINKED ISSUE #20667: Integrations broken on latest develop
### Description:

Integrations seem to be broken on latest develop. When clicking the 'New' button, nothing is displayed and you see only a 'Back' button.

### Steps to reproduce:

1. Deploy latest 3.12-develop (a875da3f3)
2. Go to Administration -> Integrations.
3. Attempt to add an integration

### Expected behavior:

You should see the form to enter details for the new integration

### Actual behavior:
No form is shown to enter integration, there is only a back button, the rest is blank.

2ZPIYP4H3T

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12-develop
- Operating System: Ubuntu 20.04.2 LTS
- Deployment Method: docker 
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.1.1 / Firefox 85.0.1
- Operating System: Windows 10 20H2

### PR DESCRIPTION
**Pull request by yash-rajpal**
- [x] I have read the Contributing Guide
  - [x] I have signed the CLA 
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

New or edit page for Integrations was never being displayed as told in issue #20667 
## Issue(s)

fixes #20667 
## Steps to test or reproduce

Check issue.
## Further comments

The components which displayed the page were wraped in Page.ScrollableContentWithShadow, when I removed Page.ScrollableContentWithShadow, the pages were visible.

It's happening because Page.ScrollableContent is being wrapped inside Page.ScrollableContentWithShadow, due to which its not visible. So I removed first Wrap of Page.ScrollableContentWithShadow and made 2nd one in IncomingWebhookForm as Page.ScrollableContentWithShadow.

fix-admin-integrations

### CODE REVIEW

**Comment by bkraul** [comment]
@ggazzo just wondering, is there an inherent issue with this PR?

**Comment by yash-rajpal** [comment]
What do you mean @bkraul ?

**Comment by bkraul** [comment]
I see that PR is relatively trivial, and passes all required tests and just needs 1 approved review, yet, it hasn't, whereas a number of other, more involved PRs done around the same time, have already been merged into develop.

**Comment by yash-rajpal** [comment]
Yeah, It takes sometime before the PRs get reviewed from community. The team is certainly busy with other priorities. No problem, it should get reviewed within upcoming days. :)

**Comment by ggazzo** [comment]
Thanks @yash-rajpal for understanding the situation. 

The best (if there is one) good explanation is: we need to test, and to be honest even though it seems trivial we need to test and check if makes sense or not, to be honest only by the diff I cannot say if makes sense or not, I need to make a checkout and see if the other pages will follow the same pattern or not.

btw I was mentioned at least 72x times only last week, I swear I try to read all (the github notifications is amazing) but still take some time =/, no excuse only facts.. So I try to answer by how urgent is the situation


again, thank you both for dedicating your time to help rocket.chat :)

File: client/views/admin/integrations/new/NewIntegrationsPage.js [hunk 1]
```diff
@@ -45,11 +45,9 @@ export default function NewIntegrationsPage({ ...props }) {
 				{t('Outgoing')}
 			</Tabs.Item>
 		</Tabs>
-		<Page.ScrollableContentWithShadow>
-			{
-				(tab === 'incoming' && <NewIncomingWebhook key='incoming'/>)
-				|| (tab === 'outgoing' && <NewOutgoingWebhook key='outgoing'/>)
-			}
-		</Page.ScrollableContentWithShadow>
+		{
```
Comment (MartinSchoeler) [inline client/views/admin/integrations/new/NewIntegrationsPage.js:48]: You need to fix this on the edit page as well, since as of it now, when you click in an integration, it still shows the white page.

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
Just a little bit more and we can approve this PR. Thanks!

File: client/views/admin/integrations/new/NewIntegrationsPage.js (hunk 1 above)
Comment (yash-rajpal) [reply client/views/admin/integrations/new/NewIntegrationsPage.js:48]: Sure, I am on it. :)

**Comment by yash-rajpal** [comment]
@MartinSchoeler Done for edit flow as well.
image

**Review by MartinSchoeler — APPROVED** [review]
Looks good to me now!

**Comment by bkraul** [comment]
That's awesome guys thanks! Now the ci-builds are kinda acting up.... 😭
