### PR TITLE
[FIX] open conversation from room info

### LINKED ISSUE #11007: Clicking a user mention on a direct message should enable you to open a new direct message with that user
### Description:

If I'm on a direct message and click on a user mention `@username` the User Info show up, but there's no button to open a direct message with that user. If you do the same on a channel or private group, it enables you to create a direct message with the user.

The current implementation checks if room type is direct message, then hides the button, assuming user is viewing the current DM's user info. It should check if the user info refers to the current user or some other mentioned user.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1

### Steps to Reproduce:

1. Open a direct message with someone
2. Mention someone else
3. Click on the mentioned user; user info shows up on the right
4. There's no "Conversation" button to start a new direct message

### Expected behavior:

I'd like to see a "Conversation" button to start a new direct message with the mentioned user

Screenshots: 
## When clicking from within a channel:
image

## When clicking from within a direct message:
image

### PR DESCRIPTION
**Pull request by ggazzo**
Closes #11007

### CODE REVIEW

File: packages/rocketchat-ui-flextab/client/tabs/userActions.js [hunk 1]
```diff
@@ -55,7 +55,8 @@ export const getActions = function({ user, directActions, hideAdminControls }) {
 	};
 	const canDirectMessage = (username) => {
 		const user = Meteor.user();
-		return RocketChat.authz.hasAllPermission('create-d') && user && user.username !== username;
+		const rid = Session.get('openedRoom');
+		return username && (!directActions && rid && RocketChat.models.Subscriptions.findOne({ rid }).name !== username) || (directActions && RocketChat.authz.hasAllPermission('create-d') && user && user.username !== username);
```
Comment (sampaiodiego) [inline packages/rocketchat-ui-flextab/client/tabs/userActions.js]: what about describing what each conditions does assigning a new variable?

```
const whatThisDoes = (!directActions && rid && RocketChat.models.Subscriptions.findOne({ rid }).name !== username);
const whatThisDoesAsWell = (directActions && RocketChat.authz.hasAllPermission('create-d') && user && user.username !== username);

return username && whatThisDoes || whatThisDoesAsWell;
```

this will make the code easy to read and understand
