### PR TITLE
[FIX] Case insensitive SAML email check

### LINKED ISSUE #8215: meteor SAML detect existing user by email case insensitive
the meteor saml code used in rocketchat, does compare the users email address case sensitive

### PR DESCRIPTION
**Pull request by arminfelder**
this fix, makes the email lookup for saml accounts case insensitve 
fixes  #8215

### CODE REVIEW

File: packages/meteor-accounts-saml/saml_server.js [hunk 1]
```diff
@@ -102,8 +102,9 @@ Accounts.registerLoginHandler(function(loginRequest) {
 	}
 
 	if (loginResult && loginResult.profile && loginResult.profile.email) {
+		const emailRegex = new RegExp(`^${ loginResult.profile.email }$`, 'i');
```
Comment (rodrigok) [inline packages/meteor-accounts-saml/saml_server.js]: Hey, you should escape the string to insert in regex, you can use `s.escapeRegExp` or `RegExp.escape`

Comment (arminfelder) [reply packages/meteor-accounts-saml/saml_server.js]: done
