### PR TITLE
[FIX] Usernames are shown instead of real names in reactions

### LINKED ISSUE #27378: Usernames are shown instead of real names in reactions
### Description:

The setting UI_use_real_name is ignored in the desktop app and browser, usernames are always shown for reactions. 
In other interface elements real names are displayed.
### Steps to reproduce:

1. Go to **Administration** - **Settings** - **Layout** - **User Interface**
2. Set **Use Real Name**

### Expected behavior:

Real names must be shown.

### Actual behavior:

image
image

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.2
- Operating System: Centos 7
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 107.0.5304.108, (64 bit)/Rocket.Chat3.8.12/3.8.13/3.8.14
- Operating System: Windows 10 Pro/Windows 7 Pro

### PR DESCRIPTION
**Pull request by henit-chobisa**
## Issue
Rocket.Chat has a setting where the user can select if the server should `Real Names` or `Usernames`, hence when the `usernames` is turned on, the server should use real names everywhere including emojis, but this is not happening.

## Steps to test or reproduce
1. Go to Administration - Settings - Layout - User Interface
2. Set Use Real Name

## Technical Reasoning
The main problem I think is the way the messages' reactions are filtered, which should include both the usernames and names of the person reacting to it.
- ### Issue : 
   - After a good research I found that my thoughts are correct and the way reactions are filtered is the actual issue.
   -  In `Message.ts` (packages / core-typings / src / IMessage ), message `reactions` was considered as an *ARRAY* but the `reactions` property is of type **INDEX SIGNATURE** which can be accessed by **keys, not by index** 
    - image
     - Screenshot 2022-11-29 at 12 34 18 AM
     - For both the client side and server side, while updating the reactions, the `names` property for each reaction is not considered which means that *name of the person reacting, is not pushed to the `names ` array in a particular reaction* object, only the username is pushed to the `usernames` array, which led to inconsistency in both the `usernames` and `names` array.
     For such a setting of `USE_REAL_NAME`, Inside names and usernames array of a reaction object, we must have a name for a particular username, and vice-versa, so we can use them interchangeably, when toggled.

- ### Solution : 
  - I consider extracting keys and values separately and fulfilling the objective of the `normalizer` function, resolving the issue.
  - Screenshot 2022-11-29 at 12 38 38 AM
  - The client side and the server side is modified to resolve the following issue, whenever a particular reaction is triggered, both the name and usernames would be pushed to their respective arrays.

- ## Preview : 
 ### Before : 

Screenshot 2022-11-29 at 2 01 48 AM

 ### After applying the above change : 
usernamesRealNames
usernames
Screenshot 2022-12-01 at 3 22 28 PM
Screenshot 2022-12-01 at 3 20 57 PM

## Issue(s)
Closes #27378

### CODE REVIEW

**Comment by henit-chobisa** [comment]
Hey @dudanogueira, @ggazzo & @debdutdeb, I proposed a solution for the above issue by means of this PR, 
I would be more than grateful if you can please review it and give your suggestions on this, 
Thanks You!

**Comment by henit-chobisa** [comment]
Hey @debdutdeb, I have fixed the linter issues, this should resolve the failed test.

**Comment by henit-chobisa** [comment]
Hello Everyone, On talking with my amazing reviewer @debdutdeb, I concluded that this PR needs more work to be done, else the following state will create regression. Hence, I am declaring it as *Work In Progress* again and make more changes to avoid regression and inconsistency.

**Comment by henit-chobisa** [comment]
Hii @debdutdeb, I have made all the necessary changes and resolved the issue, 
Kindly review, thank you so much!

**Comment by henit-chobisa** [comment]
Hello @debdutdeb, I have made the necessary changes for resolving the issues that you suggested on this one.
I have attached some more screenshots and added more points in the reasoning section, for a better explanation of my view and approach. 📜

Thank you so much for your support and guidance, I'm really grateful to it 🙏

File: apps/meteor/app/reactions/client/methods/setReaction.js [hunk 1]
```diff
@@ -36,6 +36,10 @@ Meteor.methods({
 		if (message.reactions && message.reactions[reaction] && message.reactions[reaction].usernames.indexOf(user.username) !== -1) {
 			message.reactions[reaction].usernames.splice(message.reactions[reaction].usernames.indexOf(user.username), 1);
 
+			if (message.reactions[reaction].names && message.reactions[reaction].names.indexOf(user.name) !== -1) {
+				message.reactions[reaction].names.splice(message.reactions[reaction].names.indexOf(user.name), 1);
+			}
+
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/client/methods/setReaction.js:42]: Let's take this out since we're planning on changing the outline anyway.

File: apps/meteor/app/reactions/client/methods/setReaction.js [hunk 2]
```diff
@@ -55,9 +59,11 @@ Meteor.methods({
 			if (!message.reactions[reaction]) {
 				message.reactions[reaction] = {
 					usernames: [],
+					names: [],
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/client/methods/setReaction.js:62]:
```suggestion
```
Same here

File: apps/meteor/app/reactions/client/methods/setReaction.js [hunk 3]
```diff
@@ -55,9 +59,11 @@ Meteor.methods({
...
 				};
 			}
 			message.reactions[reaction].usernames.push(user.username);
+			message.reactions[reaction].names.push(user.name);
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/client/methods/setReaction.js:66]:
```suggestion
```
Same here

File: apps/meteor/app/reactions/server/setReaction.js [hunk 4]
```diff
@@ -11,8 +11,9 @@ import { canAccessRoom, hasPermission } from '../../authorization/server';
 import { api } from '../../../server/sdk/api';
 import { AppEvents, Apps } from '../../apps/server/orchestrator';
 
-const removeUserReaction = (message, reaction, username) => {
+const removeUserReaction = (message, reaction, username, name) => {
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/server/setReaction.js:14]:
```suggestion
```

File: apps/meteor/app/reactions/server/setReaction.js [hunk 5]
```diff
@@ -11,8 +11,9 @@ import { canAccessRoom, hasPermission } from '../../authorization/server';
...
 	message.reactions[reaction].usernames.splice(message.reactions[reaction].usernames.indexOf(username), 1);
+	message.reactions[reaction].names.splice(message.reactions[reaction].names.indexOf(name), 1);
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/server/setReaction.js:16]:
```suggestion
```

File: apps/meteor/app/reactions/server/setReaction.js [hunk 6]
```diff
@@ -58,7 +59,7 @@ async function setReaction(room, user, message, reaction, shouldReact) {
 
 	if (userAlreadyReacted) {
 		const oldMessage = JSON.parse(JSON.stringify(message));
-		removeUserReaction(message, reaction, user.username);
+		removeUserReaction(message, reaction, user.username, user.name);
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/server/setReaction.js:62]:
```suggestion
```

File: apps/meteor/app/reactions/server/setReaction.js [hunk 7]
```diff
@@ -82,9 +83,12 @@ async function setReaction(room, user, message, reaction, shouldReact) {
 		if (!message.reactions[reaction]) {
 			message.reactions[reaction] = {
 				usernames: [],
+				names: [],
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/server/setReaction.js:86]:
```suggestion
```

File: apps/meteor/app/reactions/server/setReaction.js [hunk 8]
```diff
@@ -82,9 +83,12 @@ async function setReaction(room, user, message, reaction, shouldReact) {
...
 			};
 		}
 		message.reactions[reaction].usernames.push(user.username);
+		message.reactions[reaction].names.push(user.name);
```
Comment (debdutdeb) [inline apps/meteor/app/reactions/server/setReaction.js:90]:
```suggestion
```

File: apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx [hunk 9]
```diff
@@ -26,6 +26,7 @@ export const MessageListProvider: FC<{
 	const user = useUser();
 	const uid = user?._id;
 	const username = user?.username;
+	const displayName = user?.name;
```
Comment (debdutdeb) [inline apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx:29]:
```suggestion
	const realName = user?.name;
```

File: apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx [hunk 10]
```diff
@@ -66,12 +67,8 @@ export const MessageListProvider: FC<{
 							if (!username) {
 								return message.reactions[reaction].names;
 							}
-							const index = message.reactions[reaction].usernames.indexOf(username);
-							if (index === -1) {
-								return message.reactions[reaction].names;
-							}
 
-							return message.reactions[reaction].names.splice(index, 1);
+							return message.reactions[reaction].names.filter((user) => user !== displayName);
```
Comment (debdutdeb) [inline apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx:71]:
```suggestion
							return message.reactions[reaction].names.filter((user) => user !== realName);
```

File: packages/core-typings/src/IMessage/IMessage.ts [hunk 11]
```diff
@@ -248,7 +248,9 @@ export interface IMessageReactionsNormalized extends IMessage {
 }
 
 export const isMessageReactionsNormalized = (message: IMessage): message is IMessageReactionsNormalized =>
-	Boolean('reactions' in message && message.reactions && message.reactions[0] && 'names' in message.reactions[0]);
+	Boolean(
+		'reactions' in message && message.reactions && Object.keys(message.reactions)[0] && 'names' in Object.values(message.reactions)[0],
```
Comment (debdutdeb) [inline packages/core-typings/src/IMessage/IMessage.ts:252]:
```suggestion
		'reactions' in message && message.reactions && Object.keys(message.reactions).length && 'names' in Object.values(message.reactions)[0],
```

**Review by debdutdeb — CHANGES_REQUESTED** [review]
Couple changes considering the path we're [we'll be] taking; filling those entries are not necessary for now.

And, two nits.

File: apps/meteor/app/reactions/client/methods/setReaction.js (hunk 1 above)
Comment (debdutdeb) [reply apps/meteor/app/reactions/client/methods/setReaction.js:42]:
```suggestion
```

**Review by debdutdeb — APPROVED** [review]
we can come back to it later if needed;
