### PR TITLE
[FIX] Add parameter to REST chat.react endpoint, to make it work like a setter

### LINKED ISSUE #10370: [API] Add "value" parameter to /api/v1/chat.react
Currently /api/v1/chat.react works like a toggle. We call it once, it either removes or adds the reaction.

This behavior causes some difficulties when working with optimistic UI updates.

My proposal is we add a "value" parameter.

"value": true = adds the reaction (returns error if already added)
"value": false = removes the reaction (returns error if not found)
"value" not present = retains old behavior (doesn't break old API usage)

I think this would qualify as a non-breaking update to an existing API

@rafaelks @MarcosSpessatto @graywolf336 

What do you think?

### PR DESCRIPTION
**Pull request by MarcosSpessatto**
Add parameter to REST chat.react endpoint, to make it work like a setter
Closes #10370.

### CODE REVIEW

File: packages/rocketchat-reactions/setReaction.js [hunk 1]
```diff
@@ -39,12 +39,21 @@ Meteor.methods({
...
+		const removeUserReaction = () => {
 			message.reactions[reaction].usernames.splice(message.reactions[reaction].usernames.indexOf(user.username), 1);
-
+		};
+		const removeMessageReactionIfNeed = () => {
 			if (message.reactions[reaction].usernames.length === 0) {
 				delete message.reactions[reaction];
 			}
+		};
+		if (userAlreadyReacted) {
```
Comment (ggazzo) [inline packages/rocketchat-reactions/setReaction.js]: why not just do something like?
```javascript
if(userAlreadyReacted === shouldReact) {
	return;
}
```

Comment (MarcosSpessatto) [reply packages/rocketchat-reactions/setReaction.js]: I think we should not simply return if they are the same in this case, because if we do not throw an error when we try to react in a message already reacted, the REST API will end up returning success, without actually having performed the react action. What do you think?

Comment (ggazzo) [reply packages/rocketchat-reactions/setReaction.js]: I'm not sure... but this change aims allow set the reaction instead toggle. if you want react but you already reacted, I think you got it, its not a ERROR...

Comment (Hudell) [reply packages/rocketchat-reactions/setReaction.js]: I think there's no need to throw an error if the end result is going to be the same as when the method is successful.

Comment (vynmera) [reply packages/rocketchat-reactions/setReaction.js]: We'd need to change quite a few REST things, then. We have more methods that error with "The current status is the same as it would be set to"

Comment (Hudell) [reply packages/rocketchat-reactions/setReaction.js]: It's something that is worth looking into, then. We should get everybody's opinion on which approach is better and then standardize every method.

**Comment by ggazzo** [comment]
@MarcosSpessatto could you update the docs?
https://rocket.chat/docs/developer-guides/realtime-api/method-calls/set-reaction/#set-reaction

**Comment by MarcosSpessatto** [comment]
@ggazzo here it is https://github.com/RocketChat/docs/pull/804 ;)
