### PR TITLE
[FIX]Selected hide system messages would now be viewed in vertical bar.

### LINKED ISSUE #20357: [BUG]Selecting more than 3 hide system messages, content goes out of the screen.
### Description:
While selecting more than 3 system messages content goes out of the screen view.
Also, the user cannot select more options after closing the select box once.

### Steps to reproduce:

1. Select any room
2. Room info and edit
3. Toggle hide system message and select system messages.

### Expected behavior:
All hide system message options should be visible on the screen.

### Actual behavior:
All selected messages go out of screen view.

https://user-images.githubusercontent.com/55157259/105642465-dde51e00-5eaf-11eb-81bc-c98e6e87379e.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
Working!

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

All selected hide system messages are now in vertical Bar.

https://user-images.githubusercontent.com/55157259/105642624-d5411780-5eb0-11eb-8848-93e4b02629cb.mp4

## Issue(s)

Closes #20357

### CODE REVIEW

File: client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.js [hunk 1]
```diff
@@ -374,7 +374,9 @@ function EditChannel({ room, onClickClose, onClickBack }) {
 						</Field.Row>
 					</Box>
 					<Field.Row>
-						<MultiSelect options={sysMesOptions} disabled={!hideSysMes} value={systemMessages} onChange={handleSystemMessages} placeholder={t('Select_an_option')} flexGrow={1}/>
+						<VerticalBar.ScrollableContent>
```
Comment (MartinSchoeler) [inline client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.js:377]: I don't think this is the right place for a ScrollableContent. You should play with the element's css properties a bit, as I'm sure this can be fixed via CSS.

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
Requested some changes.

Tip: try out a bit with the maxWidth property

Thanks!

**Comment by Darshilp326** [comment]
@MartinSchoeler Working!

**Comment by Darshilp326** [comment]
https://user-images.githubusercontent.com/55157259/105739155-d11f0380-5f5d-11eb-9952-b9a5e4a55506.mp4

@MartinSchoeler Please review:)

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
Looking way better! Let me give you another tip for making this PR perfect:

Almost all of our components can receive css properties directly as props, you only need to camel case the css property name, e.g. `<Element maxWidth='100%'></Element>` with this Rocket.Chat is creating CSS rules at runtime and squeezing a little bit more performance out of its components, also this is the pattern that we are following with our React Components.

If you want to know more, you can check our Components documentation (we call it 'Fuselage').

**Comment by Darshilp326** [comment]
@MartinSchoeler Done!

**Comment by Darshilp326** [comment]
@MartinSchoeler Please review:)

**Review by MartinSchoeler — APPROVED** [review]
Looks good to me now!
