### PR TITLE
[FIX] Several problems with read-only rooms and muted users

### LINKED ISSUE #4769: readonly and post-readonly permission not working properly
Your Rocket.Chat version: 0.45.0-develop

The `post-readonly` permission is not checked when the user tries to send a message, but only when the room is set to readonly.

re: https://github.com/RocketChat/Rocket.Chat/pull/4034#issuecomment-256892300

### PR DESCRIPTION
**Pull request by Hudell**
Closes #4769

The permission was checked when adding users to readonly channel (to determine if they are muted or not) but if the user received or lost the permission later, it would never be checked again.

### CODE REVIEW

**Comment by rodrigok** [comment]
@Hudell wouldn't be better to ignore the array of muted users since we are putting everyone in there?

**Comment by Hudell** [comment]
Looks like there are some places where only the `muted` list is checked. I'll take a better look into the whole feature.

**Comment by Hudell** [comment]
With the new changes, the `muted` list will only be used for manually muted users. When a room is set as readonly, the permission for sending messages anyway will be checked to determine if the user can send it. 

I've also added a migration to clear the `muted` list of readonly rooms, since that list used to have every user in the room added automatically to it.

File: packages/rocketchat-lib/client/lib/roomTypes.js [hunk 1]
```diff
@@ -59,7 +59,20 @@ RocketChat.roomTypes = new class RocketChatRoomTypes extends RoomTypesCommon {
...
+		if (userOwner) {
+			return false;
+		}
+
+		if (room) {
+			if (Array.isArray(room.muted) && room.muted.indexOf(user.username) !== -1) {
+				return true;
+			}
+
+			return (room.ro === true && !RocketChat.authz.hasAtLeastOnePermission('post-readonly'));
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/client/lib/roomTypes.js]: `hasAtLeastOnePermission` is missing the `scope` param, because of this _moderators_ cannot talk on a read-only room even with the permission

File: packages/rocketchat-lib/server/lib/processDirectEmail.js [hunk 2]
```diff
@@ -81,10 +81,27 @@ RocketChat.processDirectEmail = function(email) {
 		}
 
 		if ((room.muted || []).includes(user.username)) {
-			// room is muted
+			// user is muted
 			return false;
 		}
 
+		if (room.ro === true) {
+			const userOwner = RocketChat.models.Roles.findOne({
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/lib/processDirectEmail.js]: I don't think we should test room's owner. Since `post-readonly` is given by default to _owners_ and _moderators_ I think we can test only the permission.

File: packages/rocketchat-lib/server/methods/sendMessage.js [hunk 3]
```diff
@@ -62,13 +62,37 @@ Meteor.methods({
 			throw new Meteor.Error('You can\'t send messages because you are blocked');
 		}
 
+		if (room.ro === true) {
+			const userOwner = RocketChat.models.Roles.findOne({
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/methods/sendMessage.js]: same as above. I don't think we should test room's owner. Since `post-readonly` is given by default to _owners_ and _moderators_ I think we can test only the permission.

File: packages/rocketchat-lib/server/methods/sendMessage.js [hunk 4]
```diff
@@ -62,13 +62,37 @@ Meteor.methods({
...
+				rid: room._id,
+				'u._id': user._id,
+				roles: 'owner',
+			}, {
+				fields: {
+					_id: 1,
+				},
+			});
+
+			if (!userOwner && !RocketChat.authz.hasPermission(Meteor.userId(), 'post-readonly')) {
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/methods/sendMessage.js]: `hasPermission` needs the scope parameter as well

File: app/authorization/client/hasPermission.js [hunk 5]
```diff
@@ -3,7 +3,9 @@ import { Template } from 'meteor/templating';
 import * as Models from '../../models';
 import { ChatPermissions } from './lib/ChatPermissions';
 
-function atLeastOne(permissions = [], scope) {
+function atLeastOne(permissions = [], scope, userId = undefined) {
```
Comment (MarcosSpessatto) [inline app/authorization/client/hasPermission.js]: I think we don't need this default parameter as `undefined`, because if the user does not provide the value, anyway it will be undefined. :thinking:

File: app/authorization/client/hasPermission.js [hunk 6]
```diff
@@ -28,13 +32,13 @@ function all(permissions = [], scope) {
...
 
-			return model && model.isUserInRole && model.isUserInRole(Meteor.userId(), roleName, scope);
+			return model && model.isUserInRole && model.isUserInRole(userId, roleName, scope);
 		});
 	});
 }
 
-function _hasPermission(permissions, scope, strategy) {
-	const userId = Meteor.userId();
+function _hasPermission(permissions, scope, strategy, userId = undefined) {
```
Comment (MarcosSpessatto) [inline app/authorization/client/hasPermission.js]: Same as above. :top:

File: app/authorization/client/hasPermission.js [hunk 7]
```diff
@@ -13,12 +15,14 @@ function atLeastOne(permissions = [], scope) {
...
 			const model = Models[roleScope];
 
-			return model && model.isUserInRole && model.isUserInRole(Meteor.userId(), roleName, scope);
+			return model && model.isUserInRole && model.isUserInRole(userId, roleName, scope);
 		});
 	});
 }
 
-function all(permissions = [], scope) {
+function all(permissions = [], scope, userId = undefined) {
```
Comment (MarcosSpessatto) [inline app/authorization/client/hasPermission.js]: Same as above. :top:

**Comment by MarcosSpessatto** [comment]
@Hudell can you please take a look on tests?

**Comment by rodrigok** [comment]
@Hudell can you fix the tests?
