### PR TITLE
Show discussion avatar

### LINKED ISSUE #14110: [REGRESSION] Avatar on autocomplete seems wrong
### Description:

Screen Shot 2019-04-11 at 18 23 58

### PR DESCRIPTION
**Pull request by sampaiodiego**
Along with the changes below, this PR also removes the suggestion of the channel as name of the discussion.

Closes #14110 

# Before

Shows the discussion icon instead of an avatar.

image

image

# After

Shows the avatar of the room where the discussion started and shows the icon in same place as other icons.

image

image

### CODE REVIEW

File: app/utils/lib/getAvatarUrlFromUsername.js [hunk 1]
```diff
@@ -1,21 +1,17 @@
...
-	const pathPrefix = (__meteor_runtime_config__.ROOT_URL_PATH_PREFIX || '').trim().replace(/\/$/, '');
-	let path = pathPrefix;
-	if (cdnPrefix) {
-		path = cdnPrefix + pathPrefix;
-	}
-	return `${ path }/avatar/${ encodeURIComponent(username) }?_dc=${ random }`;
+	const key = `avatar_random_${ username }`;
+	const random = typeof Session !== 'undefined' && typeof Session.keys[key] !== 'undefined' ? Session.keys[key] : 0;
+
+	return getAvatarURL(`${ encodeURIComponent(username) }?_dc=${ random }`);
```
Comment (tassoevan) [inline app/utils/lib/getAvatarUrlFromUsername.js]: I've a few suggestions for the `getAvatarURL()` helper:

- use `encodeURIComponent()` inside the helper;
- add a parameter to optionally disable cache busting (appending `?_dc=${ randomKey }`).

**Comment by rodrigok** [comment]
@sampaiodiego will this fix the issue https://github.com/RocketChat/Rocket.Chat/issues/14110 ?

**Comment by sampaiodiego** [comment]
@rodrigok I don't think so.. but I'll check

File: server/routes/avatar/utils.js [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+import { getAvatarColor } from '../../../app/utils';
+import { settings } from '../../../app/settings/server';
+
+const FALLBACK_LAST_MODIFIED = 'Thu, 01 Jan 2015 00:00:00 GMT';
+
+const cookie = new Cookies();
+
+export const getCacheTime = (req) => req.query.cacheTime || settings.get('Accounts_AvatarCacheTime');
+
+export const serveAvatar = (avatar, req, res) => {
```
Comment (MarcosSpessatto) [inline server/routes/avatar/utils.js]: I don't think these functions should receive the express objects (`req`, `res`), I think that the express objects, should only be at the level they are received, and not be passed to levels below. :thinking:

File: server/routes/avatar/utils.js [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+	const query = req.query || {};
+
+	let { rc_uid, rc_token } = query;
+
+	if (!rc_uid && headers.cookie) {
+		rc_uid = cookie.get('rc_uid', headers.cookie) ;
+		rc_token = cookie.get('rc_token', headers.cookie);
+	}
+
+	if (!rc_uid || !rc_token || !Users.findOneByIdAndLoginToken(rc_uid, rc_token)) {
```
Comment (MarcosSpessatto) [inline server/routes/avatar/utils.js]: Here we can simply return because the result is already Boolean, don't need this `if else`.

File: server/routes/avatar/utils.js [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+	let color = '';
+	let initials = '';
+
+	if (username === '?') {
+		color = '#000';
+		initials = username;
+	} else {
+		color = getAvatarColor(username);
+
+		initials = username.replace(/[^A-Za-z0-9]/g, '').substr(0, 1).toUpperCase();
```
Comment (MarcosSpessatto) [inline server/routes/avatar/utils.js]: I think we can move this regex to a function, to be easier to know what it recognizes.

File: server/routes/avatar/utils.js (hunk 2 above)
Comment (d-gubert) [reply server/routes/avatar/utils.js]: Maybe the function should only be moved to another place instead? Because by the name `serverAvatar` I guess it is *theoretically* in the same layer as the route handlers 🤔

Comment (sampaiodiego) [reply server/routes/avatar/utils.js]: yep, I guess so.. fixed all other comments btw =)
