### PR TITLE
[FIX] Do not allow passwords on private channels

### LINKED ISSUE #13750: password for private group
### Description:

Not correct view/use options for rooms and second way to access the room. (first is invite)

### Steps to reproduce:

1. make private room
2. set password then edit room
3. send url in some way to not invited user
4. user see only that private room was not found
изображение

but of couse private room exists
изображение

### Expected behavior:

even user not invited then they provide password from field user would access to private room or password option must be absent/hide than channel make as private.  

### Actual behavior:

Then first user have permission to edit room and he create room as "private group", option password was meaningless. the first of whole - no url have provided to access(only direct invite), the second even some users somehow gets url(for example from user-owner), they cant access to private-room. but if owner set private room as channel(public) then password option is Great! some users offered to enter password to proceed to public room

### Server Setup Information:

- Version of Rocket.Chat Server: 0743
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

if ths is not bug plase be patient and point me to correct..

### PR DESCRIPTION
**Pull request by MartinSchoeler**
Closes #13750

### CODE REVIEW

File: app/channel-settings/client/views/channelSettings.js [hunk 1]
```diff
@@ -493,7 +493,7 @@ Template.channelSettingsEditing.onCreated(function() {
 			showingValue: new ReactiveVar(false),
 			realValue: null,
 			canView() {
-				return roomTypes.roomTypes[room.t].allowRoomSettingChange(room, RoomSettingsEnum.JOIN_CODE) && hasAllPermission('edit-room', room._id);
+				return room.t !== 'p' && roomTypes.roomTypes[room.t].allowRoomSettingChange(room, RoomSettingsEnum.JOIN_CODE) && hasAllPermission('edit-room', room._id);
```
Comment (ggazzo) [inline app/channel-settings/client/views/channelSettings.js]: please update  allowRoomSettingChange for private channels

**Comment by engelgabriel** [comment]
@ggazzo can please you reprioritize this?
