### PR TITLE
[FIX] SAML wasn't working correctly when running multiple instances

### LINKED ISSUE #10436: SAML Sessions seems not to be shared between loadbalanced RC instances
### Description:

I setup SAML authentication for our demo system, all worked fine to the point there I hit an issue that sometimes the SAML authentication seems not to work.

Could debug this to the point there it seems that the loadbalancing without stickyness is an issue. 

So if SAML-RequestA is created on BackendServer1, but BackendServer2 receives the answer, it doesnt know something about this and prohibits the user from login.

image

This could be easily reproduced - if I enable session stickyness on the loadbalancer the SAML authentication works - because the requests going to one backend system only.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu Server 16.04 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 3
* DB Replicaset Oplog: Yes
* Node Version: v8.9.3
* mongoDB Version: 3.6.3

### Steps to Reproduce:

1. Enable SAML on your system
2. Try to login without session stickyness through a loadbalancer
3. - maybe it works - maybe not, depends on the loadbalancing ;). If the requests are balanced between multiple backend servers the logon is not possible

### Expected behavior:

SAML sessions should be shared between all backend-instances

### Actual behavior:

Seems that SAML sessions / login requests are not shared in the backend.

### Relevant logs:

2018-04-12T15:35:57.654136892Z SAMLProvidername
2018-04-12T15:35:58.662647819Z { actionName: 'validate',
2018-04-12T15:35:58.662686890Z   serviceName: 'samlprovidername',
2018-04-12T15:35:58.662695098Z   credentialToken: undefined }
....
2018-04-12T15:36:05.667566925Z RESULT :undefined

### PR DESCRIPTION
**Pull request by Hudell**
Closes #10436 

SAML login result data was previously stored in memory, which caused the login to sometimes fail when using multiple instances of Rocket.Chat. This PR moves this data to mongo to solve this problem.

### CODE REVIEW

File: packages/meteor-accounts-saml/saml_server.js [hunk 1]
```diff
@@ -170,17 +170,21 @@ Accounts.registerLoginHandler(function(loginRequest) {
 	}
 });
 
-Accounts.saml._loginResultForCredentialToken = {};
-
 Accounts.saml.hasCredential = function(credentialToken) {
-	return _.has(Accounts.saml._loginResultForCredentialToken, credentialToken);
+	const data = RocketChat.models.CredentialTokens.findOneById(credentialToken);
+	return Boolean(data);
```
Comment (geekgonecrazy) [inline packages/meteor-accounts-saml/saml_server.js]: Forgive my momentary ignorance.  :) findOneById will return null or undefined here right?  No chance of {} or any other result?
