### PR TITLE
Trim leading & trailing spaces on username or email at the login form

### LINKED ISSUE #2862: Username is not trimmed on login page
Your Rocket.Chat version: 0.25

If I try to login with "lunitic@example.com " with a space in the end ..
RC will give wrong username password.

If i remove the space it works. The space needs to be trimmed away.

Very annoying since most phones have auto add space.

### PR DESCRIPTION
**Pull request by netdevfighter**
@RocketChat/core 

Closes #2862 

Trim leading & trailing spaces on username or email at the login form

### CODE REVIEW

File: packages/rocketchat-ui-login/login/form.coffee [hunk 1]
```diff
@@ -114,10 +114,11 @@ Template.loginForm.events
 
 			else
 				loginMethod = 'loginWithPassword'
+				emailOrUsername = formData.emailOrUsername.replace /^\s+|\s+$/g, ""
```
Comment (engelgabriel) [inline packages/rocketchat-ui-login/login/form.coffee]: Maybe we could use the `trim()` from http://epeli.github.io/underscore.string/#in-meteor ?

**Comment by netdevfighter** [comment]
@engelgabriel  Thanks for your hint. Have you some documentation about this project for me?
