### PR TITLE
[FIX] Discussions created from inside DMs were not working

### LINKED ISSUE #17253: TypeError: Cannot read property 'filter' of undefined
### Description:

The instance runs well, but there is a same error in the log.

```
 I20200411-03:19:31.260(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: 2tsCvq9r2AZPHnLSPTZaGDMJWcdau8uwPj 
I20200411-03:19:31.263(0) Exception in defer callback: TypeError: Cannot read property 'filter' of undefined     at RocketChatIntegrationHandler.getTriggersToExecute (app/integrations/server/lib/triggerHandler.js:505:16)     at RocketChatIntegrationHandler.executeTriggers (app/integrations/server/lib/triggerHandler.js:576:34)     at _wrapperFunction (app/integrations/server/triggers.js:6:38)     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at app/callbacks/lib/callbacks.js:45:45     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at app/lib/server/functions/sendMessage.js:243:32     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)  
```

### Steps to reproduce:

I am not sure what step make this error. it seems related with some broken room which i don't know. When there is many users login, it happened frequently.

### Expected behavior:

No error log.

### Actual behavior:

https://i.imgur.com/66N7nks.png

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.0
- Operating System: ubuntu 16.04
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: 1
- NodeJS Version: v12.16.1
- MongoDB Version:4.0.17

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Windows

### Additional context

I run a test instance using the same database dump, but only me was logged in. it didn't show error.

This instance run years, it keep updating begin from very old version.

### Relevant logs:

Above showed

### LINKED ISSUE #17260: All other users are offline when login
### Description:

After I upgrade to 3.1.0, All other users show offline. There is two way I can show online back:

1. click the others name to check user info, the status will turn from offline to online
2. click members list in a channel, then all the online users will turn from offline to online

Then If I refresh website from browser, all the users become offline again.

**This GIF show the problem:** https://imgur.com/2T7Egor

### Steps to reproduce:

1. login
2. all others is offline
3. click member in any channel
4. the online users come out

### Expected behavior:

After login, all the users show the correct status.

### Actual behavior:
After login, all others is offline

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: ubuntu 16.04
- Deployment Method: Docker
- Number of Running Instances: 1 or 2
- DB Replicaset Oplog: true
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome, Firefox, Windows APP all the same
- Operating System:Windows

### Additional context
This instance was updated from a very old version.

### Relevant logs:
no Error logs shows.

### PR DESCRIPTION
**Pull request by rodrigok**
Closes #17260
Closes #17253

### CODE REVIEW

File: app/discussion/server/methods/createDiscussion.js [hunk 1]
```diff
@@ -86,7 +86,8 @@ const create = ({ prid, pmid, t_name, reply, users }) => {
 	// auto invite the replied message owner
 	const invitedUsers = message ? [message.u.username, ...users] : users;
 
-	const discussion = createRoom(p_room.t, name, user.username, [...new Set(invitedUsers)], false, {
+	const type = p_room.t === 'c' ? 'c' : 'p';
```
Comment (ggazzo) [inline app/discussion/server/methods/createDiscussion.js:89]: should this value be decided by a roomtypes method?
