### PR TITLE
[FIX] Remove invalid settings at startup

### LINKED ISSUE #26516: Upgrade to 5.0.2 - settings-omnichannel only gives me an empty grey screen
Omnichannel feature cannot be activated or configured as the according settings cannot be opened. When I try to open the Omnichannel setting page RC just gives me blank grey screen. The remaining other setting items are working as expected.

### Steps to reproduce:

1. Go to Administration - Settings
2. Click on Omnichannel 

### Expected behavior:

Omnichannel Settings page will be opened

### Actual behavior:

RC only gives me blank grey screen

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.2
- Operating System: Debian 10.7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.6 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Both - Desktop App and Browser version
- Operating System: Windows 11

### Relevant logs:

rc Docker container:
[_rocketchat_rocketchat_1_logs.txt](https://github.com/RocketChat/Rocket.Chat/files/9287320/_rocketchat_rocketchat_1_logs.txt)

### PR DESCRIPTION
**Pull request by KevLehman**
## Further comments

Fixes #26516

### CODE REVIEW

**Review by murtaza98 — APPROVED** [review]

**Review by aleksandernsilva — DISMISSED** [review]

File: apps/meteor/app/livechat/server/settingsRegenerator.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+			{ blocked: { $exists: false } },
+			{ sorter: { $exists: false } },
+			{ i18nLabel: { $exists: false } },
+		],
+	}).toArray();
+
+	if (invalidSettings.length > 0) {
+		logger.warn(`Found ${invalidSettings.length} invalid settings on DB. Deleting them...`);
+		logger.warn(invalidSettings.map(({ _id }) => _id));
+		await Settings.deleteMany({ _id: { $in: invalidSettings.map(({ _id }) => _id) } });
```
Comment (sampaiodiego) [inline apps/meteor/app/livechat/server/settingsRegenerator.ts:26]: a warn with only ids would be weird.. it is better to add them to the same log with a msg:
```suggestion
		const ids = invalidSettings.map(({ _id }) => _id);
		logger.warn({ msg: `Found ${invalidSettings.length} invalid settings on DB. Deleting them...`, ids });
		await Settings.deleteMany({ _id: { $in: ids } });
```

File: apps/meteor/app/livechat/server/settingsRegenerator.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+		$and: [
+			{ value: { $exists: false } },
+			{ type: { $exists: false } },
+			{ public: { $exists: false } },
+			{ packageValue: { $exists: false } },
+			{ blocked: { $exists: false } },
+			{ sorter: { $exists: false } },
+			{ i18nLabel: { $exists: false } },
+		],
+	}).toArray();
```
Comment (sampaiodiego) [inline apps/meteor/app/livechat/server/settingsRegenerator.ts:21]:
```suggestion
	}, {
		projection: { _id: 1 }
	}).toArray();
```

Comment (sampaiodiego) [inline apps/meteor/app/livechat/server/settingsRegenerator.ts:21]: because
```suggestion
	}, {
		projection: { _id: 1 }
	}).toArray();
```

**Review by sampaiodiego — CHANGES_REQUESTED** [review]

File: apps/meteor/app/livechat/server/settingsRegenerator.ts [hunk 3]
```diff
@@ -0,0 +1,28 @@
+// Validates settings on DB are correct on structure
+// And deletes invalid ones
+import { Settings } from '@rocket.chat/models';
+
+import { Logger } from '../../../server/lib/logger/Logger';
+
+// Validates settings on DB are correct on structure by matching the ones missing all the required fields
+const logger = new Logger('SettingsRegenerator');
+export async function settingsRegenerator() {
```
Comment (sampaiodiego) [inline apps/meteor/app/livechat/server/settingsRegenerator.ts:9]: as previously discussed as well, it would be good to move this function to a "global" namespace

**Review by sampaiodiego — APPROVED** [review]

**Review by ggazzo — APPROVED** [review]
