### PR TITLE
[FIX] Google Cloud Storage storage type

### LINKED ISSUE #25948: 4.8.1: file uploads to Google Cloud stopped working
### Description:

File Uploads using Google Cloud Storage have broken somewhere between 4.7.4 and 4.8.1, all uploads return the following error:
```
Error: Unable to detect a Project Id in the current environment. To learn more about authentication and Google APIs, visit: https://cloud.google.com/docs/authentication/getting-started [ufs: cannot upload file]
```
We've tried to generate a new secret based on the instructions, but it ends up with the same error.

### Steps to reproduce:

1. Set up a Google Cloud Storage backend on the File Upload
2. Attempt to upload a screenshot/file/etc.

### Expected behavior:

The screenshot/file/etc is posted in a channel/DM.

### Actual behavior:

An error is returned.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.1
- Operating System: Linux (kubernetes)
- Deployment Method: Kubernetes
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.17 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: any
- Operating System: any

### Relevant logs:

```
{"level":50,"time":"2022-06-21T16:36:05.180Z","pid":1,"hostname":"chat-668cb48c4b-7thps","name":"System","err":{"type":"Error","message":"Unable to detect a Project Id in the current environment. \nTo learn more about authentication and Google APIs, visit: \nhttps://cloud.google.com/docs/authentication/getting-started","stack":"Error: Unable to detect a Project Id in the current environment. \nTo learn more about authentication and Google APIs, visit: \nhttps://cloud.google.com/docs/authentication/getting-started\n    at /app/bundle/programs/server/npm/node_modules/google-auth-library/build/src/auth/googleauth.js:96:31\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"Unable to detect a Project Id in the current environment. \nTo learn more about authentication and Google APIs, visit: \nhttps://cloud.google.com/docs/authentication/getting-started"}
```

https://pastebin.com/bLnV6gWc

### PR DESCRIPTION
**Pull request by carlosrodrigues94**
## Proposed changes (including videos or screenshots)

Google Cloud Storage now requires a "project ID" to be filled. 

Useful links:

https://googleapis.dev/nodejs/storage/latest/global.html#StorageOptions
https://support.google.com/googleapi/answer/7014113?hl=en

## Issue(s)

Fixes #25948

### CODE REVIEW

File: apps/meteor/app/file-upload/server/config/GoogleStorage.js [hunk 1]
```diff
@@ -77,6 +78,8 @@ const configure = _.debounce(function () {
 		return;
 	}
 
+	process.env.GCLOUD_PROJECT = projectId;
```
Comment (debdutdeb) [inline apps/meteor/app/file-upload/server/config/GoogleStorage.js:81]: curious, why is this needed here?

Comment (carlosrodrigues94) [reply apps/meteor/app/file-upload/server/config/GoogleStorage.js:81]: this is necessary according with the issues of github about gcloud on 4.8.0

**Review by LucianoPierdona — DISMISSED** [review]

**Review by sampaiodiego — APPROVED** [review]
