### PR TITLE
[FIX] Uploading files from WebDAV

### LINKED ISSUE #20939: RocketChat shows "undefined" when sharing pictures from Nextcloud/Webdav
### Description:

Files from Webdav/Nextcloud can't be shared in the chat.

### Steps to reproduce:

After connecting a Nextcloud-Server to Rocket.chat and clicking the (+) button the file list of the Webdav folder appears.
Then i select a file. In the next dialog i enter a description and press "send". 
The file does not appear in the chat - it only displays a error on top "undefinded".

2021-02-28 18_18_00-Window
2021-02-28 18_18_15-Window
2021-02-28 18_18_27-Window

### Expected behavior:

The file should appear in the chat.

### Actual behavior:

A error message on the top.

2021-02-28 18_18_45-Window

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1 / 3.12.0-rc.0
- Operating System: Debian Buster
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.23 / mmapv1 (oplog Aktiviert)

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 88.0.4324.190 
- Operating System: Win10

### Relevant logs:
In the logs i can see that the file is successfully send from the webdav server to rocketchat.

2021-02-28 18_24_03-Rocket Chat - Brave

Then there is a message with following error:

Exception while invoking method ufsCreate TypeError: Cannot read property 'rid' of undefined     at Filter.validateFileUpload [as onCheck] (app/file-upload/server/lib/FileUpload.js:62:24)     at Filter.check (packages/jalik:ufs/ufs-filter.js:107:51)     at MethodInvocation.ufsCreate (packages/jalik:ufs/ufs-methods.js:155:12)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 

2021-02-28 18_24_45-Window

### LINKED ISSUE #21045: WebDav [undefined] Error on Upload from NextCloud
### Description:

[undefined] - Error on Upload from Nextcloud 

### Steps to reproduce:

Enable webdav
Config Webdav
Check config, username password and URL 
Choose File and try Upload to chat

### Expected behavior:

Upload File from Nextcloud-WebDav Location

### Actual behavior:

Mar 09 15:52:02  rocketchat[471]: Exception while invoking method ufsCreate TypeError: Cannot read property 'rid' of undefined
Mar 09 15:52:02 rocketchat[471]:     at Filter.validateFileUpload [as onCheck] (app/file-upload/server/lib/FileUpload.js:62:24)
Mar 09 15:52:02 rocketchat[471]:     at Filter.check (packages/jalik:ufs/ufs-filter.js:107:51)
Mar 09 15:52:02 rocketchat[471]:     at MethodInvocation.ufsCreate (packages/jalik:ufs/ufs-methods.js:155:12)
Mar 09 15:52:02 rocketchat[471]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Mar 09 15:52:02 rocketchat[471]:     at packages/ddp-server/livedata_server.js:1689:15
Mar 09 15:52:02 rocketchat[471]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Mar 09 15:52:02 rocketchat[471]:     at packages/ddp-server/livedata_server.js:1687:36
Mar 09 15:52:02 rocketchat[471]:     at new Promise (<anonymous>)
Mar 09 15:52:02 rocketchat[471]:     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Mar 09 15:52:02 rocketchat[471]:     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Mar 09 15:52:02 rocketchat[471]:     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Mar 09 15:52:02 rocketchat[471]:     at Object.post (app/api/server/v1/misc.js:263:26)
Mar 09 15:52:02 rocketchat[471]:     at app/api/server/api.js:394:82
Mar 09 15:52:02 rocketchat[471]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Mar 09 15:52:02 rocketchat[471]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Mar 09 15:52:02 rocketchat[471]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Mar 09 15:52:02 rocketchat[471]:     at packages/nimble_restivus/lib/route.coffee:59:33
Mar 09 15:52:02 rocketchat[471]:     at packages/simple_json-routes.js:98:9
Mar 09 15:52:02 rocketchat[471]:  => awaited here:
Mar 09 15:52:02 rocketchat[471]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Mar 09 15:52:02 rocketchat[471]:     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Mar 09 15:52:02 rocketchat[471]:     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Mar 09 15:52:02 rocketchat[471]:     at Object.post (app/api/server/v1/misc.js:263:26)
Mar 09 15:52:02 rocketchat[471]:     at app/api/server/api.js:394:82
Mar 09 15:52:02 rocketchat[471]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Mar 09 15:52:02 rocketchat[471]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Mar 09 15:52:02 rocketchat[471]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Mar 09 15:52:02 rocketchat[471]:     at packages/nimble_restivus/lib/route.coffee:59:33
Mar 09 15:52:02 rocketchat[471]:     at packages/simple_json-routes.js:98:9

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Debian 10 64bit
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4  - x64
- MongoDB Version: 4.4.4
- NextCloud 20.0.5.2

### Client Setup Information

- Desktop App or Browser Version: appears in Firefox and Chrome
- Operating System: Debian 10

Thank You!

### PR DESCRIPTION
**Pull request by KevLehman**
## Issue(s)

Fixes #20939 
Fixes #21045

### CODE REVIEW

**Review by milton-rucks — APPROVED** [review]

File: app/webdav/server/lib/webdavClientAdapter.ts [hunk 1]
```diff
@@ -40,6 +40,7 @@ export class WebdavClientAdapter {
 		try {
 			return await this._client.createDirectory(path);
 		} catch (error) {
+			console.error(error);
```
Comment (sampaiodiego) [inline app/webdav/server/lib/webdavClientAdapter.ts:43]: if this is important to keep, can you please use `Logger` instead? we should try not use `console` since we cannot control its output.

File: app/webdav/server/lib/webdavClientAdapter.ts [hunk 2]
```diff
@@ -64,6 +65,7 @@ export class WebdavClientAdapter {
 		try {
 			return await this._client.getDirectoryContents(path);
 		} catch (error) {
+			console.error(error);
```
Comment (sampaiodiego) [inline app/webdav/server/lib/webdavClientAdapter.ts:68]: same as above

**Review by sampaiodiego — CHANGES_REQUESTED** [review]

File: app/webdav/server/lib/webdavClientAdapter.ts (hunk 1 above)
Comment (KevLehman) [reply app/webdav/server/lib/webdavClientAdapter.ts:43]: Nope, this were debug logs. Let me modify

**Review by sampaiodiego — APPROVED** [review]
