### PR TITLE
[FIX] Go command duplicating subfolder path on iframes.

### LINKED ISSUE #22737: double sub-path when using iframe API
### Description:

Running RC 3.15.4 or 3.16.3 on a subpath like https://example.org/rocketchat iframe API "go" commands via postMessage fail:
```
frame.contentWindow.postMessage({externalCommand: "go", path: "/admin"}, "*")
``` 
adds sub-path twice, same for path ```"/account"```

Browser shows the RC 404 page and using the JS console you get the iframe url with the doubled sub-path
```
document.location.href
"https://pole.egroupware.org/rocketchat/rocketchat/admin"
```

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Admin page will be opened for an admin.

### Actual behavior:

RC 404 page is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.4 and 3.16.3 tested
- Operating System: Linux
- Deployment Method: official docker container
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.13 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: recent Chrome Browser, probably with every browser
- Operating System: Windows, Mac or Linux

### Relevant logs:

via browser JS console you get for the RC iframe:
```
document.location.href
"https://pole.egroupware.org/rocketchat/rocketchat/admin"
```

Nothing in the Docker logs.

### PR DESCRIPTION
**Pull request by gabriellsh**
## Issue(s)

closes #22737
## Steps to test or reproduce

- Run Rocket.Chat in a subfolder (the following steps apply to running `ROOT_URL=http://localhost:3000/test meteor`)
- Create a .html file with the following code 
```
<!DOCTYPE html>
<html lang="en" style="width: 100%;height: 100%;">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="width: 100%;height: 100%;">
    <iframe style="width: 100%;height: 100%;" src="http://localhost:3000/test"></iframe>
</body>
</html>
```
- in the rocket.chat instance, go to admin > general and disable "Restrict Access inside any iframe"
- still in general, go to Iframe Integration and enable both "Send" and "Receive"
- Now open the html file in your browser.
- Open the console, and set your context to be the iframe, like this
image

- Still in the console, run: `window.postMessage({externalCommand: "go", path: "/admin"}, "*")`
- Should redirect to admin. To check the url, just type in the console: `window.location` and hit enter. Should display a variable like this:
image

PS: Every time you refresh the page, the console context has to be set to the ifram again

### CODE REVIEW

File: app/ui/client/lib/iframeCommands.js [hunk 1]
```diff
@@ -14,14 +14,14 @@ const commands = {
...
-		const newUrl = new URL(baseURI + data.path);
+		const newUrl = new URL(`${ s.rtrim(baseURI, '/') }/${ s.ltrim(data.path, '/') }`);
 
 		const newParams = Array.from(newUrl.searchParams.entries()).reduce((ret, [key, value]) => {
 			ret[key] = value;
 			return ret;
 		}, {});
 
-		FlowRouter.go(newUrl.pathname, null, { ...FlowRouter.current().queryParams, ...newParams });
+		FlowRouter.go(s.ltrim(newUrl.pathname, __meteor_runtime_config__.ROOT_URL_PATH_PREFIX), null, { ...FlowRouter.current().queryParams, ...newParams });
```
Comment (ostjen) [inline app/ui/client/lib/iframeCommands.js:24]: I think it would be better to use `newUrl.pathname.replace()` w/ regex instead of ltrim, since the 2nd argument of those trim methods is an array of chars instead of a string

**Review by ostjen — CHANGES_REQUESTED** [review]

**Review by ostjen — APPROVED** [review]
LGTM

**Review by ostjen — APPROVED** [review]
