### PR TITLE
[FIX] Color reset when default value editor is different

### LINKED ISSUE #8523: [Release Candidate Bug] Reset the layout colors make it transparent
### Description:
Colors in the layout menu reset to "transparent" not to the default rocket.chat colors.
Found this after I upgraded my demo system to RC15.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0.rc15
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances:  3
* DB Replicaset Oplog: yes

### Steps to Reproduce:

1. upgrade to 0.59.0.rc15
2. try to reset my custom set colors in the layout admin interface
3. it resets it to #FFFFFF but it is displayed transparent

### Expected behavior:

The colors should reset to the default rocketchat colors.

### Actual behavior:

It reset the color to transparent

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

Closes #8523

### CODE REVIEW

File: packages/rocketchat-ui-admin/client/admin.js [hunk 1]
```diff
@@ -566,14 +568,16 @@ Template.admin.onRendered(function() {
 		SideNav.openFlex();
 	});
 	Tracker.autorun(function() {
-		const hasColor = TempSettings.findOne({
+		const hasColor = TempSettings.find({
 			group: FlowRouter.getParam('group'),
 			type: 'color'
-		}, { fields: { _id: 1 }});
+		}, { fields: { _id: 1, editor: 1 }}).fetch().length;
```
Comment (sampaiodiego) [inline packages/rocketchat-ui-admin/client/admin.js]: if you only want to check if there is a record matching the filter, you can remove the `fields` and just `.count()` instead of `.fetch().length`

Comment (rodrigok) [reply packages/rocketchat-ui-admin/client/admin.js]: I don't, I want to rerun the code to active the `jscolors` when missin

**Comment by GENSUSAN** [comment]
I am Gen Susan by name and am from united state America I will like you to contact me through my email okay I have an important issue to shear with you and I will like you to pay attention to me is very very urgent okay kindly contact me at gensusan0@gmail.com for more details okay love you
