### PR TITLE
fix(integrations): Ensure retryCount is sent as a number

### LINKED ISSUE #373: Disable e-mail verification
Setting exists, should use it now.

### LINKED ISSUE #37346: Outgoing webhook, retry count change results in bad API call
When trying to create an outbound webhook, if I modify the retry count, the integration cannot be saved any more as it sends the retry count as string, not as int:

Image

Image

### PR DESCRIPTION
**Pull request by MrKalyanKing**
- [X] I have read the Contributing Guide
- [X] I have signed the CLA
- [X] Lint and unit tests pass locally with my changes
- [X] I have tested my fix locally and it is effective
- [X] I have added necessary documentation (if applicable)

## Proposed changes

This PR fixes a bug where the "Retry Count" field on the Outgoing Webhook form was sending its value as a **string** instead of a **number**. This caused the API to reject the save/update with a `[invalid-params]` error.

I have updated the `outgoingwebhookform.tsx` component. The `TextInput` for `retryCount` now uses an `onChange` handler to capture the event and set the form's state using `e.currentTarget.valueAsNumber`. This ensures the value is always a **number** (or `undefined` if the field is empty), which the API expects.

I was able to reproduce the bug and confirm the fix on my local dev server, which now saves the integration successfully.

## Issue(s)

Closes #373

## Steps to test or reproduce

1.  Go to `Administration` > `Integrations`.
2.  Click `New` and select `Outgoing`.
3.  Fill in the required fields (Name, Channel, URL).
4.  Scroll down to the **Retry Count** field and change the value (e.g., from `6` to `5`).
5.  Click `Save`.
6.  **Before this fix:** An error "must be number" would appear.
7.  **After this fix:** The integration saves successfully with a "Integration has been added" message.

## Issue(s)

Closes #37346
Related to #37356

## Further comments

This is my first contribution. I'm happy to make any changes if needed!

[COMM-77](https://rocketchat.atlassian.net/browse/COMM-77)

## Summary by CodeRabbit

* **Refactor**
  * Outgoing webhook retry-count input updated to a numeric input control with non‑negative step increments, improving input constraints while preserving labels, hints, and accessibility.
* **Bug Fixes**
  * Retry count is now reliably treated and submitted as a numeric value, preventing invalid/non‑numeric entries.
* **Chores**
  * Added release metadata for a patch update.

[COMM-77]: https://rocketchat.atlassian.net/browse/COMM-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx [hunk 1]
```diff
@@ -476,7 +476,27 @@ const OutgoingWebhookForm = () => {
 								<Controller
 									name='retryCount'
 									control={control}
-									render={({ field }) => <TextInput id={retryCountField} {...field} aria-describedby={`${retryCountField}-hint`} />}
+									render={({ field }) => (
+										<TextInput
```
Comment (MartinSchoeler) [inline apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx]: Please use our NumberInput component instead

https://rocketchat.github.io/fuselage/fuselage/main/?path=/docs/inputs-numberinput--docs

File: .changeset/good-singers-kiss.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+'@rocket.chat/meteor': patch
+---
+
+fix(integrations):Ensure RetryCount is sent as a number
```
Comment (MartinSchoeler) [inline .changeset/good-singers-kiss.md]:
```suggestion
Fixes issue that caused Outgoing Webhook Retry Count to not be a number
```

File: apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx [hunk 3]
```diff
@@ -476,7 +476,27 @@ const OutgoingWebhookForm = () => {
...
+											{...field}
+											id={retryCountField}
+											type='number'
+											min='0'
+											step='1'
+											// This 'onChange' is the new magic
```
Comment (MartinSchoeler) [inline apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx]: Please don't leave comments on the component, usually we only use comments to explain code that might be counter intuitive or confusing

File: apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx [hunk 4]
```diff
@@ -476,7 +476,27 @@ const OutgoingWebhookForm = () => {
...
+											onChange={(e) => {
```
Comment (MartinSchoeler) [inline apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx]: Use [RHF](https://react-hook-form.com/) validations instead of creating a custom onChange

File: apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx [hunk 5]
```diff
@@ -476,7 +476,27 @@ const OutgoingWebhookForm = () => {
...
+												// e.currentTarget.valueAsNumber gives us a real number (or NaN)
+												const value = e.currentTarget.valueAsNumber;
+
+												// If the field is empty (value=NaN), send 'undefined'
+												// Otherwise, send the number
+												field.onChange(isNaN(value) ? undefined : value);
+											}}
+											// This 'value' prop ensures the input is blank when the value is undefined
+											value={field.value ?? ''}
```
Comment (MartinSchoeler) [inline apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx]: No need to manually add the value here

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]

**Comment by MrKalyanKing** [comment]
Hi @MartinSchoeler, thank you for the detailed feedback! This was very helpful.

I've made all the changes you requested:

Switched from TextInput to NumberInput.

Removed the custom onChange and value props to use the RHF defaults correctly.

Removed the extra comments.

Updated the changeset file description.

I've pushed the amended commit. This should be ready for another look. Thanks!

**Comment by MrKalyanKing** [comment]
Hi @MartinSchoeler, I have synced my branch with the latest develop branch to fix the outdated status.
Could you please approve the workflows so the tests can run? Once they pass, this should be ready to merge. Thanks!
