### PR TITLE
fix: `UserAutoCompleteMultiple` not removing selected items

### LINKED ISSUE #37809: Create Channel: selected members are not visually distinguishable
### Reproduction Steps
	1.	Open the Create Channel modal.
	2.	Click on Add Members.
	3.	The members dropdown opens.
	4.	Select one or more members from the list.

### Actual Behavior

Image

        •	Selected members are neither visually highlighted nor removed from the dropdown list.
        •	There is no clear indication of which members have already been added.
        •	With a long list of users, this becomes confusing and error-prone.
        

### Expected Behavior

One of the following behaviors would improve the UX:
	•	Option A: Highlight selected members in the dropdown list.
	•	Option B: Remove already selected members from the dropdown list.
	•	Option C: Disable selected members to prevent re-selection.

Any of the above would make the selection state clear and improve usability.

### Debug Info
	•	Version: 7.13.0-develop
	•	Deployment ID: d678315d-d5a0-47b6-9d71-df1137ba3c98
	•	Apps Engine Version: 1.57.0
	•	Node Version: v22.18.0
	•	Database Migration: 318 (December 15, 2025 3:21 PM)
	•	MongoDB: 7.0.16 / wiredTiger (oplog enabled)
	•	Branch: develop
	•	HEAD Commit: e1c634a
	•	PID: 37215

I’m open to discussion on the expected behaviour.
Once this issue is approved, I would like to work on implementing a fix.

### PR DESCRIPTION
**Pull request by juliajforesti**
[CORE-1559](https://rocketchat.atlassian.net/browse/CORE-1559)

## Proposed changes (including videos or screenshots)

- unify `UserAutoCompleteMultipleFederated` and `UserAutoCompleteMultiple` 
- add `federated` flag to change behavior
- remove `hasExternalMembers` validation on `CreateChannelModal` since it's not necessary anymore: the field will only show external users when `federated` flag is true

## Issue(s)

closes #37809

## Further comments

[CORE-1559]: https://rocketchat.atlassian.net/browse/CORE-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed members tab "add members" to properly remove deselected items.

* **New Features / UX**
  * Unified user picker across the app into a single component with federated support.
  * Selection inputs now surface actual error messages (not just presence).

* **Validation**
  * Prevents adding external users to non‑federated rooms.

* **Tests**
  * E2E tests updated to more reliable role‑based typing/selection interactions.

* **Chore**
  * Added a changeset entry for a patch release.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx [hunk 1]
```diff
@@ -1,55 +1,125 @@
...
+				setFilter={setFilter}
+				renderSelected={({ value: username, onMouseDown }: { value: string; onMouseDown: () => void }) => {
+					const currentCachedOption = selectedCache[username] || {};
+
+					return (
+						<UserAvatarChip
+							mie={4}
+							mb={2}
+							key={username}
+							federated={currentCachedOption._federated}
```
Comment (MartinSchoeler) [inline apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx:111]: The rabbit might be onto something here, if the `currentCachedOption` is `{}`, wouldn't the chip throw an error when trying to access it's properties?

File: apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx [hunk 2]
```diff
@@ -1,55 +1,125 @@
...
-						{label} <OptionDescription>({value})</OptionDescription>
-					</OptionContent>
-				</Option>
-			)}
-			options={options}
-		/>
+		<OptionsContext.Provider value={{ options }}>
+			<MultiSelectFiltered
+				{...props}
+				data-qa='create-channel-users-autocomplete'
```
Comment (MartinSchoeler) [inline apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx]: Are these qa properties needed? If so this component is used on places other than create channel.

Comment (juliajforesti) [reply apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx]: I'll remove `data-qa` - indeed it was not necessary. The other qa properties unfortunately are being used and it would require a wider refactor on tests locators - out of scope for this pr.
thanks

File: apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx (hunk 1 above)
Comment (juliajforesti) [reply apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx:111]: I understand the motivation, but I don't want to refactor this component, since it's a fix and I just renamed and unified the components... It's a very tricky component, maybe those improvements can be worked on separately, wdyt?
