### PR TITLE
Fix chat.postMessage not behaving like the web client

### LINKED ISSUE #5477: REST API : inconsistencies in rights management
Your Rocket.Chat version: 0.49.0-develop

I cannot post a message into a channel via the rest API if I'm logged-in as a user that does not have the `view-c-room` permission. The error message is "Not allowed [error-not-allowed]"
However, the same user with the same permissions can post to the same channel via the web app interface.

### PR DESCRIPTION
**Pull request by graywolf336**
@RocketChat/core Right now the web client lets you send messages to any channels you have joined (aka have a subscription to) whether or not you have permission to view that channel type. This fixes the issue where the rest api `chat.postMessage` wasn't behaving that way as well by checking for a Subscription before we try to join the user to a room.

Closes #5477

### CODE REVIEW

File: packages/rocketchat-integrations/server/processWebhookMessage.js [hunk 1]
```diff
@@ -4,7 +4,15 @@ function retrieveRoomInfo({ currentUserId, channel, ignoreEmpty=false }) {
...
 	}
 
-	if (room && room.t === 'c') {
+	//Since the room object can be empty, return out now since we depend on it to be an object below
+	if (!room) {
+		return room;
+	}
+
+	//Check if the user already has a Subscription or not, this avoids this issue: https://github.com/RocketChat/Rocket.Chat/issues/5477
+	const sub = RocketChat.models.Subscriptions.findOneByRoomIdAndUserId(room._id, currentUserId);
```
Comment (rodrigok) [inline packages/rocketchat-integrations/server/processWebhookMessage.js]: It's better to test by `room.t` before to prevent do the find for all type of rooms
