### PR TITLE
[FIX] status message won't show up for other users

### LINKED ISSUE #22089: [Regression] User status bubble tooltip no longer functions correctly
### Description:

I created the PR here (https://github.com/RocketChat/Rocket.Chat/pull/14892) that added a hoverable user status description to messages. It looks like this functionality is now broken. 😢 

### Steps to reproduce:

1. Set a status
2. Go to a DM or a room
3. Hover over the status bubble next to a person's name

### Expected behavior:

image

### Actual behavior:

ZxyDtXNeut

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0-develop
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.1.1
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by g-thome**
## Proposed changes (including videos or screenshots)

replace the current blaze block that queries the local session store by a react component that fetches memoized user data

## Issue(s)

Fixes #22089

### CODE REVIEW

**Comment by wreiske** [comment]
Resolves: #22089

**Comment by geekgonecrazy** [comment]
Added to PR body.

Any reason for us not to merge this one for this release?  @RocketChat/frontend  ?

File: client/components/Message/StatusMessage.tsx [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+const StatusMessage: FC<{ uid: string }> = ({ uid }) => {
+	const data = useUserData(uid);
+
+	if (!data || !data.statusText) {
+		return null;
+	}
+
+	return (
+		<button className='message-custom-status' title={data.statusText}>
```
Comment (gabriellsh) [inline client/components/Message/StatusMessage.tsx:13]: I don't think this should be a button if it does nothing when clicked. I'd also prefer the use of the Icon component istead of an ASCII character.

Another thing is, I believe we should deprecate the use of old classnames. Perhaps style a box component to do this work?

**Review by gabriellsh — CHANGES_REQUESTED** [review]

**Review by gabriellsh — DISMISSED** [review]

**Review by dougfabris — APPROVED** [review]
