### PR TITLE
[FIX] Integration history breaking when there's more than 49 records

### LINKED ISSUE #19442: [Bug] Integration History is broken in Admin UI
### Description:

Integration History is broken in Admin UI

### Steps to reproduce:

1. Go to Admin UI - Integration
2. Choose any Outgoing integration
3. Click History button
4. Get blank screen

### Expected behavior:

Integration History is opened and I can clear it.

### Actual behavior:

integr

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.17wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chrome 86 and desktop 3.0.5
- Operating System: Windows 10

### Relevant logs:

No errors in DevTools console or in RC server

### LINKED ISSUE #24099: Incoming integrations broken after upgrade 3.18.0 to 4.3.0
### Description:

Incoming integrations no longer work after upgrading from 3.18.0 to 4.3.0.

All integrations return the following message from the server:

`{"success":false,"error":"Invalid href value provided"}`

This behaviour is the same with old and newly recreated integrations, when using the sample curl command the behaviour is the same.

### Steps to reproduce:

1. Go to Administration -> Integrations
2. Click New and fill in the form, make sure the bot user is in the room where you want to send messages
3. Enable integration, save it, run the sample `curl` command provided in the form, e.g.:

`curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' https://[REDACTED/hooks/[REDACTED]`

### Expected behavior:

Sample message sent correctly to the room.

### Actual behavior:

No message appears in the room, curl command receives reponse:

`{"success":false,"error":"Invalid href value provided"}`

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.0
- Operating System: Ubuntu Server 
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.27

### Client Setup Information

- Desktop App or Browser Version: all
- Operating System: all

### Relevant logs:
```

{"level":30,"time":"2022-01-04T06:44:19.114Z","pid":24320,"hostname":"[REDACTED]","name":"Integrations","section":"Incoming WebHook","msg":"Post integration:","name":"test2"} 
{"level":20,"time":"2022-01-04T06:44:19.115Z","pid":24320,"hostname":"[REDACTED]","name":"Integrations","section":"Incoming WebHook","urlParams":{"integrationId":"[REDACTED]","token":"[REDACTED]"},"bodyParams":{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}} 
{"level":35,"time":"2022-01-04T06:44:19.122Z","pid":24320,"hostname":"[REDACTED]","name":"API","method":"POST","url":"/hooks/[REDACTED]/[REDACTED]","userAgent":"curl/7.68.0","length":"224","host":"[REDACTED]","remoteIP":"[REDACTED]","status":400,"responseTime":8}
```

### PR DESCRIPTION
**Pull request by gabriellsh**
## Proposed changes (including videos or screenshots)

Aditionally, fixed example data for incoming webhooks and converted some files to TS.

## Issue(s)

Fixes #19442
Fixes #24099

### CODE REVIEW

File: apps/meteor/client/views/admin/integrations/edit/HistoryContent.tsx [hunk 1]
```diff
@@ -1,16 +1,16 @@
...
 import { Skeleton, Box, Accordion } from '@rocket.chat/fuselage';
 import { useTranslation } from '@rocket.chat/ui-contexts';
-import React from 'react';
+import React, { ReactElement } from 'react';
 
-import { AsyncStatePhase } from '../../../../hooks/useAsyncState';
 import HistoryItem from './HistoryItem';
 
-function HistoryContent({ data, state, onChange, ...props }) {
+function HistoryContent({ data, isLoading }: { data: Serialized<IIntegrationHistory>[]; isLoading: boolean }): ReactElement {
```
Comment (tiagoevanp) [inline apps/meteor/client/views/admin/integrations/edit/HistoryContent.tsx:8]: why not es6+ ?

**Review by tiagoevanp — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/admin/integrations/edit/HistoryContent.tsx (hunk 1 above)
Comment (gabriellsh) [reply apps/meteor/client/views/admin/integrations/edit/HistoryContent.tsx:8]: IMO wouldn't change much. Also, using `function` makes sure the component is named, so in theory this should make it easier to debug.

**Review by ggazzo — APPROVED** [review]
