### PR TITLE
[FIX] Auto Translate not working on new message template

### LINKED ISSUE #27567: Bold font in the description
### Description:

In the description of the file, words marked with ** are displayed not in bold but in italics.

### Steps to reproduce:

Mark the word in bold in the description of the file.

### Expected behavior:

Bold markup in the description is rendered in bold.

### Actual behavior:

Bold markup in the description is shown in italics.
image

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.5
- Operating System:  Oracle Linux 8.5
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 107.0.5304.88 
- Operating System: Windows 10

### Additional context

On open.rocket.chat it is also reproduced.
Strikethrough and italics display correctly.

### PR DESCRIPTION
**Pull request by filipemarins**
## Proposed changes (including videos or screenshots)

- Fix auto translate not working on new message template; 
- Fix a bug that the auto-translate icon was showing for users who didn't have enabled. 
- Show translated quote messages;
- Remove translation provider for end users.
- Translate the ThreadMessagePreview component

## Issue(s)

closes #27567

## Further comments

I had to move `useAutoTranslate` and `useKatex` to a separate hook cause on `MessageList` component the context isn't fulfilled yet.

Quote attachment
Screenshot 2022-11-22 at 11 07 34

Multilevel quote attachments get translated as well:
Screenshot 2022-11-22 at 11 13 21

But if you try to translate a message that wasn't translated yet and has multiple levels of quote message it will only translate the first quote message...

ThreadMessagePreview component translated

Screenshot 2022-11-23 at 14 32 32

### CODE REVIEW

File: apps/meteor/client/views/room/MessageList/hooks/useMessages.ts [hunk 1]
```diff
@@ -29,16 +32,24 @@ export const useMessages = ({ rid }: { rid: IRoom['_id'] }): MessageWithMdEnforc
...
+					dollarSyntax: katexDollarSyntaxEnabled,
+					parenthesisSyntax: katexParenthesisSyntaxEnabled,
 				},
 			}),
 		};
 		return (message: IMessage): MessageWithMdEnforced =>
-			parseMessageTextToAstMarkdown(removePossibleNullMessageValues(message), parseOptions, autoTranslateLanguage, useShowTranslated);
-	}, [autoTranslateLanguage, katex, showColors, useShowTranslated]);
+			parseMessageTextToAstMarkdown(removePossibleNullMessageValues(message), parseOptions, autoTranslateOptions);
+		// eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (gabriellsh) [inline apps/meteor/client/views/room/MessageList/hooks/useMessages.ts:44]: Can you pass the properties without infringing the eslint rule? Thanks

File: apps/meteor/app/autotranslate/client/lib/autotranslate.ts [hunk 2]
```diff
@@ -177,7 +177,8 @@ export const createAutoTranslateMessageStreamHandler = (): ((message: ITranslate
 				subscription &&
 				subscription.autoTranslate === true &&
 				message.msg &&
-				(!message.translations || !message.translations[language])
+				(!message.translations ||
+					(!message.translations[language] && !message.attachments?.some((attachment) => attachment?.translations?.[language])))
```
Comment (gabriellsh) [inline apps/meteor/app/autotranslate/client/lib/autotranslate.ts:181]: I see this `message.attachments.some` pattern appear a lot of times throughout the code. I added a comment about the `ITranslatedMessageAttachment` and I think a helper function should be made to test this cases.

File: apps/meteor/app/autotranslate/client/lib/actionButton.ts [hunk 3]
```diff
@@ -22,21 +22,32 @@ Meteor.startup(() => {
 				action(_, props) {
 					const { message = messageArgs(this).msg } = props;
 					const language = AutoTranslate.getLanguage(message.rid);
-					if (!isTranslatedMessage(message) || !message.translations[language]) {
-						// } && !_.find(message.attachments, attachment => { return attachment.translations && attachment.translations[language]; })) {
+					if (
+						!isTranslatedMessage(message) ||
+						(!message.translations?.[language] && !message.attachments?.some((attachment) => attachment?.translations?.[language]))
```
Comment (gabriellsh) [inline apps/meteor/app/autotranslate/client/lib/actionButton.ts:27]: Same here, the helper would substitute this `message.attachments.some`

File: apps/meteor/app/autotranslate/client/lib/actionButton.ts [hunk 4]
```diff
@@ -22,21 +22,32 @@ Meteor.startup(() => {
...
 						Meteor.call('autoTranslate.translateMessage', message, language);
 					}
 					const action = 'autoTranslateShowInverse' in message ? '$unset' : '$set';
 					Messages.update({ _id: message._id }, { [action]: { autoTranslateShowInverse: true } });
 				},
-				condition({ message, user }) {
+				condition({ message, subscription, user }) {
+					const language = subscription?.autoTranslateLanguage || '';
+					const hasTranslationLanguage = isTranslatedMessage(message) && Boolean(message.translations?.[language]);
+					const hasAttachmentTranslationLanguage = Boolean(message.attachments?.some((attachment) => attachment?.translations?.[language]));
```
Comment (gabriellsh) [inline apps/meteor/app/autotranslate/client/lib/actionButton.ts:39]: Same here, the helper would substitute this `message.attachments.some`

File: apps/meteor/app/autotranslate/client/lib/actionButton.ts [hunk 5]
```diff
@@ -48,21 +59,33 @@ Meteor.startup(() => {
 				action(_, props) {
 					const { message = messageArgs(this).msg } = props;
 					const language = AutoTranslate.getLanguage(message.rid);
-					if (!isTranslatedMessage(message) || !message.translations[language]) {
-						// } && !_.find(message.attachments, attachment => { return attachment.translations && attachment.translations[language]; })) {
+					if (
+						!isTranslatedMessage(message) ||
+						(!message.translations?.[language] && !message.attachments?.some((attachment) => attachment?.translations?.[language]))
```
Comment (gabriellsh) [inline apps/meteor/app/autotranslate/client/lib/actionButton.ts:64]: Same here, the helper would substitute this `message.attachments.some`

File: apps/meteor/app/autotranslate/client/lib/actionButton.ts [hunk 6]
```diff
@@ -48,21 +59,33 @@ Meteor.startup(() => {
...
 						Meteor.call('autoTranslate.translateMessage', message, language);
 					}
 					const action = 'autoTranslateShowInverse' in message ? '$unset' : '$set';
 					Messages.update({ _id: message._id }, { [action]: { autoTranslateShowInverse: true } });
 				},
-				condition({ message, user }) {
+				condition({ message, subscription, user }) {
+					const language = subscription?.autoTranslateLanguage || '';
+					const hasMessageTranslated = isTranslatedMessage(message) && Boolean(message.translations?.[language]);
+					const hasAttachmentTranslated = message.attachments?.some((attachment) => attachment?.translations?.[language]);
```
Comment (gabriellsh) [inline apps/meteor/app/autotranslate/client/lib/actionButton.ts:76]: Same here, the helper would substitute this `message.attachments.some`

File: apps/meteor/app/autotranslate/server/autotranslate.ts [hunk 7]
```diff
@@ -305,10 +305,13 @@ export abstract class AutoTranslate {
 			Meteor.defer(() => {
 				for (const [index, attachment] of message.attachments?.entries() ?? []) {
 					if (attachment.description || attachment.text) {
-						const translations = this._translateAttachmentDescriptions(attachment, targetLanguages);
+						// Removes the initial link `[ ](quoterl)` from quote message before translation
+						const translatedText = attachment?.text?.split(') ')[1] || attachment?.text;
```
Comment (gabriellsh) [inline apps/meteor/app/autotranslate/server/autotranslate.ts:309]: Nice improvement! But if I have more parenthesis `) ` like this it breaks the translation.
image

**Review by gabriellsh — CHANGES_REQUESTED** [review]
When sending an attachment, the description was not translated in the main room, but was in the thread.
image

File: apps/meteor/client/views/room/MessageList/hooks/useMessages.ts (hunk 1 above)
Comment (filipemarins) [reply apps/meteor/client/views/room/MessageList/hooks/useMessages.ts:44]: This will cause an infinite loop because the `showTranslate` property is a function.

**Comment by filipemarins** [comment]
> When sending an attachment, the description was not translated in the main room, but was in the thread. image

Inside the thread, we are having the wrong behavior, we should not translate our own message. I was only focused on the main message list but nice catch, I will fix it on the thread.

**Review by gabriellsh — DISMISSED** [review]
Since this is a very large PR on an important feature, I'll ask for an additional review.

**Review by hugocostadev — APPROVED** [review]

**Review by hugocostadev — APPROVED** [review]

File: apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx [hunk 8]
```diff
@@ -62,7 +70,13 @@ const ThreadMessagePreview = ({ message, sequential, ...props }: ThreadMessagePr
 									{(parentMessage.data as { ignored?: boolean })?.ignored ? (
 										t('Message_Ignored')
 									) : (
-										<ThreadMessagePreviewBody message={{ ...parentMessage.data, msg: body }} />
+										<ThreadMessagePreviewBody message={{ ...parentMessage.data, ...previewMessage }} />
+									)}
+									{translated && (
+										<>
+											{' '}
+											<MessageStatusIndicatorItem name='language' color={colors.p500} title={t('Translated')} />
```
Comment (gabriellsh) [inline apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx:78]:
```suggestion
											<MessageStatusIndicatorItem name='language' color='font-on-info' title={t('Translated')} />
```

File: apps/meteor/client/views/room/MessageList/MessageList.tsx [hunk 9]
```diff
@@ -25,7 +25,8 @@ type MessageListProps = {
 
 export const MessageList = ({ rid }: MessageListProps): ReactElement => {
 	const t = useTranslation();
-	const messages = useMessages({ rid });
+	const userSubscription = useUserSubscription(rid);
+	const messages = useMessages({ rid, subscription: userSubscription });
 	const subscription = useRoomSubscription();
```
Comment (gabriellsh) [inline apps/meteor/client/views/room/MessageList/MessageList.tsx:30]: What is the difference between `userSubscription` and `subscription` here? I think they should be the same thing.

File: apps/meteor/client/views/room/MessageList/MessageList.tsx [hunk 10]
```diff
@@ -72,7 +73,8 @@ export const MessageList = ({ rid }: MessageListProps): ReactElement => {
 										data-unread={firstUnread}
 										data-sequential={sequential}
 										sequential={shouldShowAsSequential}
-										message={message}
+										message={message as IThreadMessage}
+										_subscription={userSubscription}
```
Comment (gabriellsh) [inline apps/meteor/client/views/room/MessageList/MessageList.tsx:77]: Any reason to add the underscore to this prop?

File: apps/meteor/client/views/room/MessageList/hooks/useMessages.ts [hunk 11]
```diff
@@ -26,16 +29,24 @@ export const useMessages = ({ rid }: { rid: IRoom['_id'] }): MessageWithMdEnforc
...
```
Comment (gabriellsh) [inline apps/meteor/client/views/room/MessageList/hooks/useMessages.ts:41]: I'll add this again, but is there a reason why we need to disable this eslint rule?

**Review by gabriellsh — CHANGES_REQUESTED** [review]

File: apps/meteor/client/views/room/MessageList/MessageList.tsx (hunk 9 above)
Comment (hugocostadev) [reply apps/meteor/client/views/room/MessageList/MessageList.tsx:30]: The Room subscription does not has the translation preference for EACH user, that why I had to use the user subscription

File: apps/meteor/client/views/room/MessageList/MessageList.tsx (hunk 10 above)
Comment (hugocostadev) [reply apps/meteor/client/views/room/MessageList/MessageList.tsx:77]: no, I'll change it here

File: apps/meteor/client/views/room/MessageList/hooks/useMessages.ts (hunk 11 above)
Comment (hugocostadev) [reply apps/meteor/client/views/room/MessageList/hooks/useMessages.ts:41]: Not apparently, removing it here

File: apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx (hunk 8 above)
Comment (hugocostadev) [reply apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx:78]: done

File: apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx [hunk 12]
```diff
@@ -22,13 +23,15 @@ export const AudioAttachment: FC<AudioAttachmentProps> = ({
...
 	title_link: link,
 	title_link_download: hasDownload,
+	md,
 }) => {
 	const [collapsed, collapse] = useCollapse(collapsedDefault);
 	const getURL = useMediaUrl();
 	return (
 		<Attachment>
 			<AttachmentDescription>
 				<MarkdownText parseEmoji variant='inline' content={description} />
```
[the remark this answers is not in the document]
Comment (hugocostadev) [reply apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx:33]: done

File: apps/meteor/client/components/message/variants/ThreadMessage.tsx [hunk 13]
```diff
@@ -21,20 +22,22 @@ import ThreadMessageContent from './thread/ThreadMessageContent';
 
 type ThreadMessageProps = {
 	message: IThreadMessage | IThreadMainMessage;
-	subscription?: ISubscription;
+	subscription: ISubscription | undefined;
```
[the remark this answers is not in the document]
Comment (hugocostadev) [reply apps/meteor/client/components/message/variants/ThreadMessage.tsx:25]: Yes, it is.... changing it here

File: apps/meteor/client/views/room/MessageList/hooks/useMessageBody.tsx [hunk 14]
```diff
@@ -1,14 +1,39 @@
...
 
-export const useMessageBody = ({ attachments, msg }: Partial<Pick<IMessage, 'msg' | 'attachments'>> = {}): string =>
-	useMemo(() => {
-		if (msg) {
-			return msg;
+import { parseMessageTextToAstMarkdown } from '../lib/parseMessageTextToAstMarkdown';
+import { useAutoTranslate } from './useAutoTranslate';
+
+export const useMessageBody = (
+	parentMessage: UseQueryResult<IMessage, unknown>,
```
Comment (tassoevan) [inline apps/meteor/client/views/room/MessageList/hooks/useMessageBody.tsx:10]: `nitpick` I don't think we need to couple the data fetching logic in this hook. I would type `parentMessage` as `IMessage | undefined` and let the hook caller handle the loading and error states.

File: apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx [hunk 15]
```diff
@@ -24,21 +26,24 @@ import {
...
 };
 
-const ThreadMessagePreview = ({ message, sequential, ...props }: ThreadMessagePreviewProps): ReactElement => {
+const ThreadMessagePreview = ({ message, sequential, subscription, ...props }: ThreadMessagePreviewProps): ReactElement => {
 	const {
 		actions: { openThread },
 	} = useMessageActions();
 	const parentMessage = useParentMessage(message.tmid);
-	const body = useMessageBody(parentMessage.data);
+	const messageBody = useMessageBody(parentMessage, subscription);
```
Comment (tassoevan) [inline apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx:45]: Look at remarks made on `useMessageBody`.

**Review by tassoevan — CHANGES_REQUESTED** [review]

**Review by tassoevan — APPROVED** [review]
