### PR TITLE
[FIX] Actions from User Info panel

### LINKED ISSUE #20058: Can't remove users from channels
### Description:

Since one of the last updates (3.9.3 / 3.10.0) we cannot remove users from channels / private groups anymore.
We use LDAP and sync accounts from ldap-groups to Channels but we can reproduce this error even on manually created private groups.

### Steps to reproduce:

1. Create new private group with another person
2. Open "Members"
3. Click on other person
4. 3-Dot -> Remove from room

### Expected behavior:

User gets removed

### Actual behavior:

User doesn't get removed and:
image

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Everywhere
- Operating System: All

### LINKED ISSUE #20095: [BUG] Ignore button in User info returns undefined when clicked
### Description:
When we click ignore button in full profile mode of a user , it doesn't work and returns  an undefined instead.

### Steps to reproduce:

1.  Go to any room and click on any user.
2.  Click on show full profile.
3.  Click on ignore button.

### Expected behavior:
A success message or notification should popup.

### Actual behavior:
Undefined is returned

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

https://user-images.githubusercontent.com/65273718/103894311-c4548000-5114-11eb-93ab-256d74a29a39.mp4

### PR DESCRIPTION
**Pull request by Darshilp326**
## Proposed changes (including videos or screenshots)

Users can be removed from channels without any error message.

https://user-images.githubusercontent.com/55157259/103759202-5b4c0a00-5039-11eb-82c9-a3d37726160a.mp4

## Issue(s)

Closes #20058 
Closes #20095

### CODE REVIEW

**Comment by Darshilp326** [comment]
Please review:)

File: client/views/room/hooks/useUserInfoActions.js [hunk 1]
```diff
@@ -310,7 +310,7 @@ export const useUserInfoActions = (user = {}, rid) => {
 			text={t('The_user_will_be_removed_from_s', roomName)}
 			close={closeModal}
 			confirmText={t('Yes_remove_user')}
-			confirm={() => { removeUserAction({ roomId: rid, userId: uid }); closeModal(); }}
+			confirm={() => { removeUserAction({ roomId: rid, username: user.username }); closeModal(); }}
```
Comment (gabriellsh) [inline client/views/room/hooks/useUserInfoActions.js:313]: Although this works for the user removal, it's not the ideal fix, since `uid` is used in other places that should be broken too. Try to see where this user object is coming from and why the `_id` property is not coming along with it.

This issue looks pretty bad, so I'll give you another couple of hours to figure it out, otherwise I'll fix it.

**Review by gabriellsh — CHANGES_REQUESTED** [review]

File: client/views/room/hooks/useUserInfoActions.js (hunk 1 above)
Comment (Darshilp326) [reply client/views/room/hooks/useUserInfoActions.js:313]: Working on it!

**Comment by Darshilp326** [comment]
@gabriellsh Please review!

**Comment by gabriellsh** [comment]
> @gabriellsh Please review!

Nice man! Did you test it again to see if the new fix is working?

**Comment by Darshilp326** [comment]
https://user-images.githubusercontent.com/55157259/103856335-77ec4e80-50da-11eb-8536-984360d28963.mp4

**Review by gabriellsh — APPROVED** [review]

**Comment by chetas411** [comment]
@Darshilp326  I think your changes would also solve this #20095 , So should I close it ?
