### PR TITLE
fix: Correct module path resolution for apps-engine in Deno runtime

### LINKED ISSUE #39621: Path resolution: local RocketChat Server fails to import local rc-apps or timeouts `rc-apps deploy`
### Description:
While running a local rocket chat server, when we try to import or deploy an app, the import fails due to deno runtime path resolution bug.

### Steps to reproduce:

1. Run the RocketChat server locally
2. Create a basic Rocket Chat app outside the rocket chat directory
3. Upload the app or deploy into the local running rocket chat server

### Expected behavior:

The app fails to import as the file path is resolved due a bug in how the require.ts in deno runtime was written.

### Actual behavior:

The app should successfully get uploaded and works.

### Server Setup Information:

- Version of Rocket.Chat Server: 8.3.0-develop
- License Type: MIT
- Number of Users: 1
- Operating System: MacOS 26.3.1
- Deployment Method: Local
- Number of Running Instances: 1
- DB Replicaset Oplog: wiredTiger
- NodeJS Version: 22.18.0 - arm64
- MongoDB Version: 7.0.16

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 145.0.7632.162
- Operating System: MacOS 26.3.1

### Relevant logs:

Logs can be found in this video.

https://github.com/user-attachments/assets/5ddb0e1a-aa4a-4d98-b232-f2194b671c10

### PR DESCRIPTION
**Pull request by durgeshbg**
## Proposed changes (including videos or screenshots)

Fixed the path resolution in custom runtime.ts written for deno-runtime. The previous solution involves replacing src in the entire path to solve the runtime imports.

Eg. `/Users/user/src/RocketChat/Rocket.Chat/packages/apps-engine/src/definition/App.js` -> `/Users/user/RocketChat/Rocket.Chat/packages/apps-engine/src/definition/App.js`
This replaces the wrong src resolving in a non existent path which results in `PermissionDenied` error.

The new approach replaces only the `src` only inside the app-engine directory.
`/Users/user/src/RocketChat/Rocket.Chat/packages/apps-engine/src/definition/App.js` -> `/Users/user/src/RocketChat/Rocket.Chat/packages/apps-engine/definition/App.js`

This fixes the issue which can be observed in the video.

https://github.com/user-attachments/assets/922ab4e2-1db1-4fc6-b911-9e2fa08fe7e9

## Issue(s)
fixes #39621

## Steps to test or reproduce

The steps are mentioned the above issue to reproduce

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed incorrect module path rewrites for compiled modules: only the targeted internal path segment is adjusted, preserving other paths. Added a clarifying comment; public behavior and interfaces remain unchanged.
 

 Task: [ARCH-2075]

[ARCH-2075]: https://rocketchat.atlassian.net/browse/ARCH-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: packages/apps-engine/deno-runtime/lib/require.ts [hunk 1]
```diff
@@ -7,7 +7,9 @@ export const require = (mod: string) => {
 	// However, the import maps are configured to look at the source folder for typescript files, but during
 	// runtime those files are not available
 	if (mod.startsWith('@rocket.chat/apps-engine')) {
-		mod = import.meta.resolve(mod).replace('file://', '').replace('src/', '');
+		mod = import.meta.resolve(mod).replace('file://', '');
+		// Only replace the apps-engine package's "src/" segment (to load compiled JS), not e.g. /Users/foo/src/ in the path
+		mod = mod.replace(/\/apps-engine\/src\//, '/apps-engine/');
```
Comment (d-gubert) [inline packages/apps-engine/deno-runtime/lib/require.ts]:
```suggestion
		// Only remove "src/" substring when it comes after "apps-engine/"
		mod = import.meta.resolve(mod).replace('file://', '').replace('apps-engine/src/, 'apps-engine/');
```

File: packages/apps-engine/deno-runtime/lib/require.ts [hunk 2]
```diff
@@ -7,7 +7,8 @@ export const require = (mod: string) => {
 	// However, the import maps are configured to look at the source folder for typescript files, but during
 	// runtime those files are not available
 	if (mod.startsWith('@rocket.chat/apps-engine')) {
-		mod = import.meta.resolve(mod).replace('file://', '').replace('src/', '');
+		// Only remove "src/" substring when it comes after "apps-engine/"
+		mod = import.meta.resolve(mod).replace('file://', '').replace('apps-engine/src/, 'apps-engine/');
```
Comment (d-gubert) [inline packages/apps-engine/deno-runtime/lib/require.ts]:
```suggestion
		mod = import.meta.resolve(mod).replace('file://', '').replace('apps-engine/src/', 'apps-engine/');
```

File: packages/apps-engine/deno-runtime/lib/require.ts [hunk 3]
```diff
@@ -7,7 +7,8 @@ export const require = (mod: string) => {
 	// However, the import maps are configured to look at the source folder for typescript files, but during
 	// runtime those files are not available
 	if (mod.startsWith('@rocket.chat/apps-engine')) {
-		mod = import.meta.resolve(mod).replace('file://', '').replace('src/', '');
+		// Only remove "src/" substring when it comes after "apps-engine/"
+		mod = import.meta.resolve(mod).replace('file://', '').replace('apps-engine/src/', 'apps-engine/');
```
[the remark this answers is not in the document]
Comment (d-gubert) [reply packages/apps-engine/deno-runtime/lib/require.ts:11]: _Technically_ that's correct, but in reality I'm not even sure this solution would be valid in this situation. Having `apps-engine/src/` subdirectories _inside `apps-engine/src/`_ likely points to a bigger problem - let it fail if it happens

**Comment by durgeshbg** [comment]
Thanks for your time and help here mr. @d-gubert
