### PR TITLE
[FIX] Update Message: Does not show edited when message was not edited.

### LINKED ISSUE #12282: Message is recognized as edited even if there is no change in content
### Description:

A changed message that does not change its content (edit and hit `return` key only) is displayed as changed.

### Steps to reproduce:

1. post a message
2. select edit and don't change anything
3. hit `return` key only

### Expected behavior:

The message should not be marked as changed because the content has not changed.

### Actual behavior:

The message is marked as changed.

rc_edit

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2 (tar) and 0.70.3 (open.rocket.chat), 0.72.0-develop (open.rocket.chat)

### PR DESCRIPTION
**Pull request by Kailash0311**
Closes #12282

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Thanks for contributing!  This looks good in my opinion.

@sampaiodiego thoughts?

File: packages/rocketchat-lib/server/functions/updateMessage.js [hunk 1]
```diff
@@ -28,16 +28,21 @@ RocketChat.updateMessage = function(message, user, originalMessage) {
...
-	message.editedBy = {
-		_id: user._id,
-		username: user.username,
-	};
 
-	const urls = message.msg.match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]*)?\??([-\+=&!:;%@\/\.\,\w]+)?(?:#([^\s\)]+))?)?/g) || [];
-	message.urls = urls.map((url) => ({ url }));
 
-	message = RocketChat.callbacks.run('beforeSaveMessage', message);
+	if (originalMessage.msg !== message.msg) {
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/functions/updateMessage.js]: should we return before having the message [processed by Apps](https://github.com/RocketChat/Rocket.Chat/pull/13053/files#diff-03e4fa2f14f1ee1fbf0fd78345355273L18)?

Comment (Kailash0311) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: Do you mean message processing by Apps should  happen when the messages are not equal ?

Comment (Kailash0311) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: Also, I am not sure what `Apps` does here.

Comment (sampaiodiego) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: `Apps` can change the message content or prevent a message from being sent.

so my question was: should we skip everything if the edited message didn't change? or should `Apps` still process messages that were "edited" but still have the same content?

Comment (sampaiodiego) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: @rodrigok @d-gubert @graywolf336 what you guys think on above?

**Comment by Kailash0311** [comment]
Ohh thanks! 
Yeah, I think we should skip all message processing because that will process the already processed message, which is redundant, I guess.

File: packages/rocketchat-lib/server/functions/updateMessage.js (hunk 1 above)
Comment (d-gubert) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: I'd say that we could skip the whole `RocketChat.updateMessage` method when the message's content doesn't change,   not executing `Apps`, before/after hooks, or message history -> https://github.com/RocketChat/Rocket.Chat/blob/235d0dbb73a69f5498b2b982b3bcee519c66d99e/packages/rocketchat-lib/server/functions/updateMessage.js#L27

Comment (geekgonecrazy) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: cool then sounds like this is good?

Comment (Kailash0311) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: Yeah I'll change it to the skipping the whole ``` RocketChat.updateMessage ``` method.

**Comment by Kailash0311** [comment]
@geekgonecrazy I have updated the code according to what we discussed.

File: packages/rocketchat-lib/server/functions/updateMessage.js [hunk 2]
```diff
@@ -4,55 +4,53 @@ RocketChat.updateMessage = function(message, user, originalMessage) {
...
 	}
-
-	// For the Rocket.Chat Apps :)
-	if (message && Apps && Apps.isLoaded()) {
-		const appMessage = Object.assign({}, originalMessage, message);
-
-		const prevent = Promise.await(Apps.getBridges().getListenerBridge().messageEvent('IPreMessageUpdatedPrevent', appMessage));
-		if (prevent) {
-			throw new Meteor.Error('error-app-prevented-updating', 'A Rocket.Chat App prevented the message updating.');
+	if (originalMessage.msg !== message.msg) {
```
Comment (sampaiodiego) [inline packages/rocketchat-lib/server/functions/updateMessage.js]: instead of shifting everything to inside the `if`, can you please change it to something like:
```javascript
if (originalMessage.msg !== message.msg) {
	return;
}
/* rest of the code */
```
this way the code looks nicer and clean as so the diff :)

Comment (Kailash0311) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: Yeah true, I'll do that but shouldn't it be,
```javascript
if (originalMessage === message.msg) {
       return;
}
```
because we want to skip everything and return if both messages are equal ?

Comment (d-gubert) [reply packages/rocketchat-lib/server/functions/updateMessage.js]: Yes, that's right :)

File: client/methods/updateMessage.js [hunk 3]
```diff
@@ -64,10 +64,12 @@ Meteor.methods({
 					delete messageObject.$set.msg;
 				}
 			}
-			ChatMessage.update({
-				_id: message._id,
-				'u._id': Meteor.userId(),
-			}, { $set : messageObject });
+			if (originalMessage.msg !== message.msg) {
```
Comment (d-gubert) [inline client/methods/updateMessage.js]: It looks like you could move this if up to the start of the method and make an "early return", similarly to the other file :)
