### PR TITLE
[FIX] fix bug on livechat message webhook when sending a image

### LINKED ISSUE #15557: Livechat Webhooks no working version 2.1.0
Description:
Livechat Webhooks is not working when a file is sent by livechat and when you log out, it only works if you send messages

Server Setup Information:

Version of Rocket.Chat Server: 2.1.0
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.16.0
MongoDB Version: v3.6.12

### PR DESCRIPTION
**Pull request by tatosjb**
Closes #15557 

An exception was raised because of an attribute access on an undefined property who does not exists when coming from livechat message.

See how to simulate below:

ezgif com-video-to-gif

### CODE REVIEW

File: app/utils/server/functions/normalizeMessageFileUpload.js [hunk 1]
```diff
@@ -2,9 +2,13 @@ import { getURL } from '../../lib/getURL';
 import { FileUpload } from '../../../file-upload/server';
 import { Uploads } from '../../../models/server';
 
+function userId(message) {
+	return message.u ? message.u._id : message.agentId;
```
Comment (renatobecker) [inline app/utils/server/functions/normalizeMessageFileUpload.js]: Since the `normalizeMessageFileUpload` is a public method, I mean, it's not a specific Livechat method, I don't like the idea of testing a field which is only used by a specific feature, such as the Livechat. Did you get it?

My suggestion is, instead of providing the `agentId` field here, what about providing the `message.u.` property before calling the `normalizeMessageFileUpload` [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/hooks/sendToCRM.js#L64)?
It would look like this:
```
    const u = message;
    postData.messages.push(normalizeMessageFileUpload({ u, ...msg }));
```

What do you think? 
Thanks.

Comment (tatosjb) [reply app/utils/server/functions/normalizeMessageFileUpload.js]: You are right, seems a lot better that way. I'll do it
