### PR TITLE
[FIX] "User not found" for direct messages

### LINKED ISSUE #8113: [i18n] "User not found" rather than "Room not found"
@ggazzo today when I talked to you in RC I saw a message for your old username:
screenshot from 2017-09-13 10-25-31
Title message is: "Room not found" but I think it's better to use "User not found" for it.

### PR DESCRIPTION
**Pull request by gabriellsh**
Closes #8113

Changed the room header message when a User doesn't exist. Channel and Group messages persisted.
Screenshot 2019-12-23 at 10 33 20

### CODE REVIEW

File: app/ui/client/views/404/roomNotFound.js [hunk 1]
```diff
@@ -20,4 +20,13 @@ Template.roomNotFound.helpers({
 	customErrorMessage() {
 		return this.error.reason;
 	},
+	headerMessage() {
+		const { type } = Template.currentData();
+
+		if (type === 'd') {
+			return 'User_not_found';
```
Comment (MartinSchoeler) [inline app/ui/client/views/404/roomNotFound.js]: Instead of using a `if` here, you can use a ternary operator like:  `return type === 'd' ? 'User_not_found' : 'Room_not_found';
`
