### PR TITLE
[FIX] "Click to Join" button is not working if there are no muted users in the room

### LINKED ISSUE #22845: get error when click Video chat "click to join"
Hi!
I have set up a video chat via Jitsi.
When I click on the "call" button, a chat is created, but no one can join. When someone presses the "Click to join" there is a error:
Uncaught TypeError: Cannot read property 'includes' of undefined
    at Object.joinJitsiCall (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:971)
    at Object.run (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:971)
    at T.y (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:971)
    at 66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:971
    at Object.Ve (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568)
    at Ze (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568)
    at er (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568)
    at Kn (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568)
    at Jn (66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568)
    at 66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568

### PR DESCRIPTION
**Pull request by matheusbsilva137**
## Proposed changes (including videos or screenshots)

 - Add check to `room.muted` array so as to cover the case in which it is `undefined`;

## Issue(s)

[Task - ClickUp](https://app.clickup.com/t/1axcwpx)
Fixes #22845 

## Steps to test or reproduce

Start a call in a room and, logged in as another user, press the "Click to Join!" button (system message) which has been sent in the room. No errors should be thrown in the console.

### CODE REVIEW

File: app/videobridge/client/actionLink.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ actionLinks.register('joinJitsiCall', function(message, params, instance) {
 		const currentTime = new Date().getTime();
 		const jitsiTimeout = new Date((room && room.jitsiTimeout) || currentTime).getTime();
 
-		if (room && room.muted.includes(username)) {
+		if (room && (room.muted || []).includes(username)) {
```
Comment (tassoevan) [inline app/videobridge/client/actionLink.js:18]: We could try a shortcut with nullish coalescing and optional chaining:

```suggestion
		if (room?.muted?.includes(username)) {
```

Comment (matheusbsilva137) [reply app/videobridge/client/actionLink.js:18]: Good suggestion 🙂 . I see we have some more places using `(room.muted || [])`. I'll replace them all by `room?.muted?.`

Comment (matheusbsilva137) [reply app/videobridge/client/actionLink.js]: Fixed!

**Review by tassoevan — APPROVED** [review]
