### PR TITLE
[BUG] No new room created when conversation is closed

### LINKED ISSUE #13733: Bug Report: Livechat: New room created when send message to a closed room via LiveChat API
### Description:

Livechat: New room created when send message to a closed room via LiveChat API

### Steps to reproduce:

Create a new visitor:
```bash
curl -X POST -d '{ "visitor": { "name": "myname", "token": "mytoken" }}' 'http://rocketchat:3000/api/v1/livechat/visitor'
```

Get a new room id
```bash
curl -X GET 'http://rocketchat:3000/api/v1/livechat/room?token=mytoken'
```

Send messages to this new room
```bash
curl -X POST -d '{ "token": "mytoken", "rid": "myroom", "msg": "Hello" }' 'http://rocketchat:3000/api/v1/livechat/message'
```

Close room (via Web Interface or API)

Send repeatdly times a new message to closed room.

### Expected behavior:

Response with error or preferably reopen the closed room. If there are both options, it is best to choose via parameter.

### Actual behavior:

It creates a new room every sent message.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: CentOS 7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Deactivated
- NodeJS Version: v8.11.4
- MongoDB Version: db version v4.0.4

### Additional context

I'm developing an integration between Telegram and Rocketchat using a platform in the middle.
This bug occurs when I send curl to room's endpoint with predefined token and rid parameters, with a closed room. Creates a new emtpy room.

### Relevant logs:

No errors in log.

### PR DESCRIPTION
**Pull request by knrt10**
Closes #13733 

This PR solves the problem of creating a new room, again and again, once the conversation is closed. 

Also fixed little CSS for analytics page from

old

to 

new

cc @renatobecker would you please review.

### CODE REVIEW

File: app/livechat/server/methods/sendMessageLivechat.js [hunk 1]
```diff
@@ -24,10 +24,22 @@ Meteor.methods({
...
+			closedAt: 1,
+			open: 1,
+		};
+
 		if (!guest) {
 			throw new Meteor.Error('invalid-token');
 		}
 
+		// Check if conversation is closed or not.
+		const closed = Rooms.findOneLivechatById(rid, fields);
```
Comment (renatobecker) [inline app/livechat/server/methods/sendMessageLivechat.js]: We can't add this validation here because the current version of the Livechat client needs to create a new room when the current room is closed.
The point is that the issue #13733 is related to REST API endpoints, and our new Livechat client works over this approach, so I suggest you add validation on the Livechat message endpoint:

https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/api/v1/message.js#L33

Comment (knrt10) [reply app/livechat/server/methods/sendMessageLivechat.js]: ok, will do that.

**Comment by knrt10** [comment]
tested 


API test

File: app/models/server/models/Rooms.js [hunk 2]
```diff
@@ -94,6 +94,21 @@ export class Rooms extends Base {
 		return this.find(query, options);
 	}
 
+	findOneLivechatById(_id, fields) {
```
Comment (renatobecker) [inline app/models/server/models/Rooms.js]: You don't need this method.

File: app/livechat/server/api/v1/message.js [hunk 3]
```diff
@@ -34,6 +34,11 @@ API.v1.addRoute('livechat/message', {
 				throw new Meteor.Error('invalid-room');
 			}
 
+			const closed = findRoomClosed(rid);
+			if (closed && closed.closedAt) {
```
[the remark this answers is not in the document]
Comment (knrt10) [reply app/livechat/server/api/v1/message.js]: I think it should be `if (room && !room.open)`

**Comment by knrt10** [comment]
@renatobecker updated

File: app/livechat/server/api/v1/message.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (renatobecker) [reply app/livechat/server/api/v1/message.js]: Actually my suggestion was to check both `room` and `room.open` in only one validation, but if you want to check the `room.open` separately, yeah you just need to check:

```
if (!room.open) {
...
```

Below the existing validation:

```
if (!room) {
    throw new Meteor.Error('invalid-room');
}
```

[the remark this answers is not in the document]
Comment (knrt10) [reply app/livechat/server/api/v1/message.js]: So it's fine right?

File: app/livechat/server/api/v1/message.js [hunk 4]
```diff
@@ -34,6 +34,10 @@ API.v1.addRoute('livechat/message', {
 				throw new Meteor.Error('invalid-room');
 			}
 
+			if (room && !room.open) {
```
Comment (renatobecker) [inline app/livechat/server/api/v1/message.js]: You can just check:

```
if (!room.open) {
...
}
```

Because the `room` object is checked here:
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/api/v1/message.js#L33

Comment (knrt10) [reply app/livechat/server/api/v1/message.js]: cool, let me update it

Comment (knrt10) [reply app/livechat/server/api/v1/message.js]: Done

File: app/livechat/server/api/v1/message.js [hunk 5]
```diff
@@ -34,6 +34,10 @@ API.v1.addRoute('livechat/message', {
 				throw new Meteor.Error('invalid-room');
 			}
 
+			if (!room.open) {
+				throw new Meteor.Error('chat-closed');
```
Comment (renatobecker) [inline app/livechat/server/api/v1/message.js]: Please, replace the `chat-closed` to `room-closed`, according we do here:
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/api/v1/room.js#L56

Comment (knrt10) [reply app/livechat/server/api/v1/message.js]: Done 😄
