### PR TITLE
Join command

### LINKED ISSUE #5793: /join command gives you wrong message when channel exists
Rocket.Chat Version: Demo Server

image

image

/join command should act as /open when channel exists.

### PR DESCRIPTION
**Pull request by ggazzo**
@RocketChat/core 
Closes #5793

It will works just with public channels.
```javascript 
room = RocketChat.models.Rooms.findOneByNameAndType(channel, 'c') /// <-here
```

### CODE REVIEW

File: packages/rocketchat-slashcommands-join/server.coffee [hunk 1]
```diff
@@ -15,17 +15,19 @@ class Join
...
-				_id: Random.id()
-				rid: item.rid
-				ts: new Date
-				msg: TAPi18n.__('Channel_doesnt_exist', { postProcess: 'sprintf', sprintf: [ channel ] }, user.language)
-			}
-			return
-
+		room = RocketChat.models.Rooms.findOneByNameAndType(channel, 'c')
+		
+		RocketChat.Notifications.notifyUser Meteor.userId(), 'message', {
```
Comment (karlprieb) [inline packages/rocketchat-slashcommands-join/server.coffee]: you can omit braces in coffeescript :)

Comment (ggazzo) [inline packages/rocketchat-slashcommands-join/server.coffee]: I know, but it doesn't mean I like it :) . I'm goin to fix this now.
@engelgabriel said something about change this [solution](https://github.com/RocketChat/Rocket.Chat/pull/6268/commits/ef5795eddebfcfd5a23953a9c3bf7dfceb6d5924) to something more generic.

Comment (karlprieb) [inline packages/rocketchat-slashcommands-join/server.coffee]: Hehehe I told you about the that because we omit braces on RC codebase :)
