### PR TITLE
[FIX] Users can access public discussions inside private channels they are not members of

### LINKED ISSUE #26266: User can send message to a channel without joining it
### Description:
If we sign in through RC API, we get `rc_uid` and `rc_token`, and with the help of them, we can send a message. The thing is, when a user is authenticated, he/she can even message in channels in which they've not even joined.

### Steps to reproduce:

1. Login a user with the help of this [API Endp](https://developer.rocket.chat/reference/api/rest-api/endpoints/other-important-endpoints/authentication-endpoints/login)
2. Send a message to a channel in which you aren't even a part of yet using this [API endp](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/chat-endpoints/sendmessage)
3. The message will be sent successfully.

### Expected behavior:
User must be a part of that channel to send the message.

### Actual behavior:
The message is sent successfully.

image

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.4
- Operating System: Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.18.3 - x64
- MongoDB Version:4.4.15

### Client Setup Information

- Desktop App or Browser Version: Brave
- Operating System: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by LucianoPierdona**
Fix #26266

### CODE REVIEW

File: apps/meteor/app/lib/server/methods/getMessages.ts [hunk 1]
```diff
@@ -16,8 +16,16 @@ Meteor.methods({
 
 		const msgs = Messages.findVisibleByIds(messages).fetch() as IMessage[];
 		const rids = [...new Set(msgs.map((m) => m.rid))];
+		const prids = [
+			...new Set(
+				rids
+					.map((rid) => Rooms.findOneById(rid))
+					.filter((room) => room.prid)
+					.map((room) => room.prid),
```
Comment (matheusbsilva137) [inline apps/meteor/app/lib/server/methods/getMessages.ts:24]: This works fine, but I think it'd be better to use a `reduce` instead of mapping, filtering and mapping again. wdyt?

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: apps/meteor/app/lib/server/methods/getMessages.ts (hunk 1 above)
Comment (LucianoPierdona) [reply apps/meteor/app/lib/server/methods/getMessages.ts]: updated!

File: apps/meteor/app/lib/server/methods/getMessages.ts [hunk 2]
```diff
@@ -16,9 +16,22 @@ Meteor.methods({
 
 		const msgs = Messages.findVisibleByIds(messages).fetch() as IMessage[];
 		const rids = [...new Set(msgs.map((m) => m.rid))];
+		const prids = [
+			...new Set(
+				rids.reduce<string[]>((prids, rid) => {
+					return Rooms.findOneById(rid).then((room: IRoom) => {
```
Comment (matheusbsilva137) [inline apps/meteor/app/lib/server/methods/getMessages.ts:22]: `findOneById` can be used as a synchronous method here

**Review by matheusbsilva137 — CHANGES_REQUESTED** [review]

File: apps/meteor/app/lib/server/methods/getMessages.ts (hunk 2 above)
Comment (LucianoPierdona) [reply apps/meteor/app/lib/server/methods/getMessages.ts]: updated!

**Review by matheusbsilva137 — APPROVED** [review]

**Review by debdutdeb — CHANGES_REQUESTED** [review]

**Review by debdutdeb — APPROVED** [review]

File: apps/meteor/app/lib/server/methods/getMessages.ts [hunk 3]
```diff
@@ -16,9 +16,22 @@ Meteor.methods({
...
+						prids.push(room.prid);
+					}
+
+					return prids;
+				}, []),
+			),
+		];
+
+		if (!rids.every((_id) => canAccessRoomId(_id, uid)) || !prids.every((_id) => canAccessRoomId(_id, uid))) {
+			throw new Meteor.Error('error-not-allowed', 'Not allowed', 'getSingleMessage');
```
[the remark this answers is not in the document]
Comment (debdutdeb) [reply apps/meteor/app/lib/server/methods/getMessages.ts:34]: I don't want my review to block the merge. This PR **works** and is a critical fix. No need to delay delivery just for this. Can be addressed separately.

**Comment by debdutdeb** [comment]
Approving since I don't want my review to block the merge. This PR **works** (according to the qa-tested label) and is a critical fix. No need to delay delivery just for this. Can be addressed separately.
